### PR TITLE
TypeScript: Allow non-null and type assertions as lvalues. (Fixes #7638)

### LINKED ISSUE #7638: TypeScript: Invalid left-hand side in assignment expression (2:0)
Bug

### Input Code
```ts
let num: number | undefined
num! += 1
```
https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=usage&code_lz=DYUwLgBAdgrgtgLmvARiAThAPhGUAmIAZgJZQj4BQscAhBANQC8EAjEA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&lineWrap=false&presets=es2015%2Cstage-3%2Ctypescript&prettier=false&targets=Node-5&version=7.0.0-beta.42&envVersion=

### Expected Behavior
No Errors

### Current Behavior
`Invalid left-hand side in assignment expression (2:0)`

### Context
I discovered this while pulling in a piece of code we were compiling with tsc. If you copy this code into the TypeScript playground it works fine. http://www.typescriptlang.org/play/

My work-around for now was to change it to:

```ts
let num: number | undefined
num = num! + 1
```

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  7.0.0 beta 42
| node             | 8.5.0
| npm              | 5.3.0
| Operating System | OS X 10.12.2

### PR DESCRIPTION
**Pull request by mmantel**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #7638
| Patch: Bug Fix?          | Yes
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR         | 
| Any Dependency Changes?  | No
| License                  | MIT

TypeScript allows non-null assertions and type assertions to be lvalues in assignments, such as `x! += 1;` and `(<number> x) += 1;`. This patch makes babylon able to parse these valid TypeScript expressions.

Added relevant tests.

### CODE REVIEW

**Comment by hzoo** [comment]
cc @lukescott

**Comment by existentialism** [comment]
Agree with @andy-ms, @mmantel can we add some babylon tests as well?

**Comment by mmantel** [comment]
Added Babylon tests and simplified the plugin-transform-typescript tests per the comments.

**Comment by existentialism** [comment]
@mmantel thanks!

**Pull request merged**
