### PR TITLE
[babylon] Fix arguments & super in class properties

### PR DESCRIPTION
**Pull request by nicolo-ribaudo**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | 
| Patch: Bug Fix?          | y
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR         | 
| Any Dependency Changes?  |
| License                  | MIT

> 6d6d9cb Disallow super in functions in class properties
> d3ca51d Disallow arguments in class properties

### CODE REVIEW

**Comment by jridgewell** [comment]
> Disallow super in functions in class properties

The only thing disallowed is `super()`. Can we get a test for that?

**Comment by nicolo-ribaudo** [comment]
Isn't `foo = function () { super.x }` disallowed?

**Comment by jridgewell** [comment]
That's disallow because `super` (both call and member expression) is only allowed inside methods (class or object):

```js
const foo = function () {
  super.x // syntax error
}

function foo() {
  super.x // syntax error
}
```

But that's not a class properties restriction. The only class props ones are `arguments` (unless inside a function) and `super()` (unless in a nested class)

```js
class Outer extends Object {
  class Foo {
    x = arguments // syntax error
    x = () => arguments // syntax error
    x = super() // syntax error
    x = () => super() // syntax error
  }
}

**Comment by nicolo-ribaudo** [comment]
> But that's not a class properties restriction.

Yeah, that commit fixes leakage of the `inClassProperty` flag to nested functions.

I will check the `foo = super()` case in a few hours.

**Pull request merged**
