### PR TITLE
Really fix "--help"

### PR DESCRIPTION
**Pull request by zertosh**
cc: @sebmck

### CODE REVIEW

**Comment by sebmck** [comment]
:relaxed:

**Comment by zertosh** [comment]
nah, I should've checked before I made the 2nd change :stuck_out_tongue:

**Comment by zertosh** [comment]
Trust But Verify

**Comment by sebmck** [comment]
I prefer [YDD](https://github.com/gabrielecirulli/ydd).

**Comment by zertosh** [comment]
that's why they made [`npm shrinkwrap`](https://docs.npmjs.com/cli/shrinkwrap)

**Pull request merged**
