### PR TITLE
Remove remaining references to lerna

### PR DESCRIPTION
**Pull request by nicolo-ribaudo**
| Q                        | A 
| ------------------------ | ---
| License                  | MIT

Since we don't use lerna anymore, we should remove the `lerna.json` file to avoid creating confusion for new contributors.

We also don't need the `lerna-changelog` dependency, since that is handled by a GH action. If someone really needs to manually generate the changelog, they can still run `yarn dlx lerna-changelog`.

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/12592"></a>

### CODE REVIEW

**Review by existentialism — APPROVED** [review]

**Review by hzoo — APPROVED** [review]
dang rip

**Comment by KevinGhadyani-minted** [comment]
Is there a PR for when you transitions from Lerna to another technology?

I'm curious why this project isn't using Lerna anymore. I'm not partial either way, but I also saw the `facebook/react` repo is also no longer using Lerna either. What'd you replace it with?

**Comment by Sawtaytoes** [comment]
Is there a PR for when you transitions from Lerna to another technology?

I'm curious why this project isn't using Lerna anymore. I'm not partial either way, but I also saw the `facebook/react` repo is also no longer using Lerna either. What'd you replace it with?

**Comment by nicolo-ribaudo** [comment]
This is the PR removing lerna: https://github.com/babel/babel/pull/12138

**Pull request merged**
