### PR TITLE
Add `readonly` to TypeScript type modifier

### LINKED ISSUE #9503: TypeScript `readonly` type modifier
TypeScript 3.4 will support a new `readonly` type modifier:

```ts
let x: readonly number[] = [];
```

See https://github.com/Microsoft/TypeScript/pull/29435

### PR DESCRIPTION
**Pull request by tanhauhau**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #9503 
| Patch: Bug Fix?          |
| Major: Breaking Change?  |
| Minor: New Feature?      | 
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

### CODE REVIEW

**Comment by danez** [comment]
Thanks for all the amazing work 👍

**Comment by nicolo-ribaudo** [comment]
Maybe we should throw an error for https://github.com/Microsoft/TypeScript/pull/29435/files#diff-e119cc28df9582f9e1ca0d41720ea142R1026?

Unless this is valid, in which case we don't have enough info to know whether to throw or not.
```js
type A = number[];
type B = readonly A;
```

**Comment by danez** [comment]
//cc @DanielRosenwasser ^ Above comment

**Comment by tanhauhau** [comment]
is there a TypeScript Playground that supports `readonly`?

**Comment by nicolo-ribaudo** [comment]
No, it hasn't been released yet.

**Comment by existentialism** [comment]
> Maybe we should throw an error for [Microsoft/TypeScript/pull/29435/files#diff-e119cc28df9582f9e1ca0d41720ea142R1026](https://github.com/Microsoft/TypeScript/pull/29435/files#diff-e119cc28df9582f9e1ca0d41720ea142R1026)?

IMO yes, we should

**Comment by tanhauhau** [comment]
> IMO yes, we should

Does that mean we throw a syntax error whenever readonly does not proceed with array literal or tuple literal?

**Comment by nicolo-ribaudo** [comment]
It depends on
> Unless this is valid, in which case we don't have enough info to know whether to throw or not.
>
> ```js
> type A = number[];
> type B = readonly A;
> ```

**Comment by nicolo-ribaudo** [comment]
@tanhauhau
> Does that mean we throw a syntax error whenever readonly does not proceed with array literal or tuple literal?

Exactly, accordingly to https://github.com/Microsoft/TypeScript/blob/9d3707d671592d030386956c9ce39e539b8d0972/tests/baselines/reference/readonlyArraysAndTuples.errors.txt, we should throw.

**Comment by nicolo-ribaudo** [comment]
The circleci failure doesn't seem related to this PR :thinking:

**Comment by nicolo-ribaudo** [comment]
Thanks!

**Pull request merged**
