### PR TITLE
chore: enable eslint 9 recommended rule set

### PR DESCRIPTION
**Pull request by JLHwung**
| Q                        | A 
| ------------------------ | ---
| Any Dependency Changes?  | bump `@eslint/js` to 9.8.0
| License                  | MIT

### CODE REVIEW

**Comment by nicolo-ribaudo** [comment]
Is the PR title correct?

**Comment by JLHwung** [comment]
Yes I think so. Previously we were using eslint 9 with eslint 8 recommended rules set, because eslint/js was not bumped together.

**Review by nicolo-ribaudo — APPROVED** [review]

**Comment by liuxingbaoyu** [comment]
This PR seems to have been superseded by https://github.com/babel/babel/pull/16718?

**Review by liuxingbaoyu — APPROVED** [review]

**Comment by JLHwung** [comment]
> This PR seems to have been superseded by https://github.com/babel/babel/pull/16718?

#16718 was based on this PR. I am offline this week, could you help me rebase that PR? Thank you.🙏

**Pull request merged**
