### PR TITLE
Require debug module directly

### LINKED ISSUE #5024: babel-core should consume `debug/node` directly
https://github.com/visionmedia/debug/issues/389

^ When releasing 2.5.0, we noticed in introduced a breaking change in babel-core which was referencing `debug/node` rather than simply `debug`.  I added a hook + hotfix that should prevent issues, but I think it would be wise to consume `debug` directly rather than referencing it's internal source files.  Is there anyway this could be fixed for an uncoming release?  I can put in a PR if necessary

### PR DESCRIPTION
**Pull request by xtuc**
| Q                        | A 
| ------------------------ | ---
| Patch: Bug Fix?          | yes
| Major: Breaking Change?  | no
| Minor: New Feature?      | no
| Deprecations?            | no
| Spec Compliancy?         | no
| Tests Added/Pass?        | no
| Fixed Tickets            | Fixes #5024 
| License                  | MIT
| Doc PR                   | no 
| Dependency Changes       | no

I changed the import, from `debug/node` to `debug`.

Tests are currently failing.

`packages/babel-plugin-transform-react-jsx/test/fixtures/react/should-disallow-spread-children/actual.js`:
```js
<div>{...children}</div>;
```

Should throw an error but doesn't. How can this be related?

This PR reverts an old fix, changelog:
> Use debug/node instead of debug to avoid browserify using the browser version that references window.

If this is still the case we need to handle it somehow in the code.

**Edit**: tests aren't failing on the CI, could someone double check that?

### CODE REVIEW

**Comment by danharper** [comment]
Fyi: https://github.com/visionmedia/debug/commit/a31178c8d842c192261b70085b9da9ec1333c6a8 (may be related to some failing tests you may have seen?)

**Comment by existentialism** [comment]
@xtuc FWIW, running your PR locally, all tests pass for me on both debug@2.4.5 and debug@2.5.1

**Comment by xtuc** [comment]
@danharper This is actually the bug i'm trying to fix there. I will do further testing.

@existentialism Thanks.

Ok for merge? I don't know much about the Browserify thing.

**Comment by artemave** [comment]
Please merge this! It breaks `debug` module in electron. As in, it doesn't log in dev tools console.

**Comment by xtuc** [comment]
I agree with @loganfsmyth, will be safer to ship it with 7. I will rebase with 7 branch and launch CI.

**Pull request merged**
