### PR TITLE
Run Flow before Regenerator is run

### PR DESCRIPTION
**Pull request by splodingsocks**
Should resolve https://github.com/babel/babel/issues/2477

I've tested this change only on a small bit of my own code so far. Sorry, I didn't write any automated tests for this. I couldn't get the test suite to run (on Master, without my changes). It aborted with an out of memory error. At that point I stopped figuring out how to add a new test.

I'd love to write a test for it though, if someone wouldn't mind lending some direction.

### CODE REVIEW

**Comment by sebmck** [comment]
This is actually going to break a lot. It's going to cause all the `builtin-trailing` transformers to be ran before `builtin-advanced`.

**Comment by splodingsocks** [comment]
Any suggestions about what approach to take instead?

It'll be easier to see what kinds of things this will break once the tests are passing on master again, and I rebase this, I think.

I did run this change against our code, and everything seemed fine, though I'm sure we're missing cases the cases that would break for others.

**Comment by sebmck** [comment]
Probably wait until Babel 6 where regenerator is going to be a Babel plugin.

**Comment by splodingsocks** [comment]
Is that looking like days, or months? This bug is a pretty big immediate problem for us.

If it's not happening soon, I guess we could temporarily use a forked version of babel.

**Comment by sebmck** [comment]
A week or two hopefully. I don't want to promise any specific date.

**Comment by splodingsocks** [comment]
Okay, thanks.

**Pull request closed without merging**
