### PR TITLE
Adds strictMode option to strict-mode transform

### PR DESCRIPTION
**Pull request by thejameskyle**
This allows you to disable `"use strict";` when using the `commonjs` module transform.

### CODE REVIEW

**Comment by loganfsmyth** [comment]
Looks good.

**Comment by jmm** [comment]
What's the use case for this?

What does "turn `strict` off" mean -- pass `strict: false` to `transform-strict-mode`?

**Comment by loganfsmyth** [comment]
@jmm The issue is we have this plugin used inside `transform-es2015-modules-commonjs` via `inherit`, and that plugin _also_ has an option called `strict`, so you can't toggle one but not the other, unexpectedly.

**Comment by jmm** [comment]
Thanks @loganfsmyth. Sorry, what I meant is, what is the use case for disabling Use Strict when transforming modules at all? When is it a good idea?

I was also wondering what's the purpose of the undocumented `strict` option to `transform-es2015-modules-commonjs`. I took a look at the source and couldn't totally figure it out yet. It looks like it controls at least a couple of other things besides adding Use Strict, one of which I didn't grok right away. The other is adding an `__esModule` export and I'm not sure what that has to do with adding Use Strict, and I see that you get 3 different transformations for `strict` values of `true|false|undefined`.

It's still not clear to me what the docs mean by:

> turn `strict` off

**Comment by loganfsmyth** [comment]
It's not a good idea, but we supported it in Babel 5 and James was transitioning a project from Babel 5 to Babel 6 and was hitting this as an issue because he couldn't toggle one flag without the other.

The other `strict` isn't related to strict mode, it's related to strictly processing modules, e.g. not adding another magic export called `__esModule` to the file that isn't actually declared in the file. I don't know why it was added or if it is used by anyone though.

**Comment by jmm** [comment]
Thanks Logan.

I'm guessing that was discussed on Slack...in any case, in general, if things are discussed on Slack it would be super helpful if people could record the background information and reasoning for decisions from there in PRs / issues.

> It's not a good idea

We should make that clear in the README. I was [helping module author on the forum](https://discuss.babeljs.io/t/can-i-disable-omit-a-plugin-from-a-preset/90/4?u=jmm) who used a preset that disables the Use Strict directive in the module transform to accommodate a user who wanted to concatenate their module with other code. Well, actually that user's package contains a script not a module, so omitting the module transform would be the appropriate solution there -- but it just goes to show that there's a lot of misunderstanding around strict mode and modules and we shouldn't make it sound like a good idea.

> The other strict isn't related to `strict` mode, it's related to strictly processing modules, e.g. not adding another magic export called `__esModule` to the file that isn't actually declared in the file.

Thanks for that info. It *does* affect output of Use Strict directive though. You can get three different versions of output:

```
strict: true
=> Use Strict: yes, __esModule: no

strict: false
=> Use Strict: no, __esModule: yes

strict: undefined
=> Use Strict: yes, __esModule: yes
```

> I don't know why it was added or if it is used by anyone though.

We should document or deprecate it. The [preset](https://www.npmjs.com/package/babel-preset-es2015-without-strict) that I mentioned above that came up on the discussion forum is using it for the purpose of omitting the Use Strict directive.

**Pull request merged**
