### PR TITLE
validate: allow JSXText node in JSXElement children property 

### PR DESCRIPTION
**Pull request by hzoo**
…6876)

https://phabricator.babeljs.io/T6876

### CODE REVIEW

**Comment by jridgewell** [comment]
Should `StringLiteral` still be allowed with this change?

**Comment by amasad** [comment]
yeah, why do we need both? cc @spicyj

**Comment by spicyj** [comment]
Agree that StringLiteral seems wrong here.

**Comment by hzoo** [comment]
Oh ok I think I got it originally from https://github.com/facebook/jsx/blob/master/AST.md#jsx-element

```
  children: [ Literal | JSXExpressionContainer | JSXElement ],
```

so it was just changed to `StringLiteral` for babel 6

**Comment by amasad** [comment]
update me maybe

**Comment by hzoo** [comment]
updated

**Comment by ForbesLindesay** [comment]
This is a breaking change.  I was generating JSX with `StringLiteral` because that was what babel-types said it accepted.  My code has now broken with a minor change to babel.

**Comment by ForbesLindesay** [comment]
Also, I hate to point this out because I don't want another breaking change, but should the value in https://github.com/babel/babel/blob/master/packages/babel-types/src/definitions/jsx.js#L5-L17 be JSXText rather than StringLiteral as well?

**Comment by amasad** [comment]
@ForbesLindesay can you send a PR or open a task. We can batch it for the next major now that we know it's a breaking change

**Comment by ForbesLindesay** [comment]
Done: https://phabricator.babeljs.io/T6962.

**Pull request merged**
