### PR TITLE
Visit method/function parameter decorators

### PR DESCRIPTION
**Pull request by shuhei**
This MR makes visitors visit method/function parameter decorators.

It makes `Decorator` visitors visit more nodes but I don't think it will break existing plugins because `Decorator` AST node is already used for different types of decorators, such as class, property and method, and most of plugins don't directly visit `Decorator` nodes but parent nodes instead.

### CODE REVIEW

**Comment by hzoo** [comment]
Looks like there is 1 failing test regarding types

**Comment by hzoo** [comment]
Sounds like we would need to update babylon

```
class Foo extends Bar {
  bar = "foo";
}
```

**Comment by shuhei** [comment]
@hzoo Thanks for taking a look at it! So, it tries to validate `decorators` property even when it does not exist. I still don't have any idea why it's working like this. Why do you think we would need to update babylon?

**Comment by hzoo** [comment]
I thought it if it was because of the ast `Property decorators expected type of array but got null` but it says null rather than undefined but maybe not

**Comment by shuhei** [comment]
Thanks! I'll look further later.

**Comment by shuhei** [comment]
The error seems to be happening [here](https://github.com/shuhei/babel/blob/2f5df51e48f24018e6c424bddd418a796121a428/packages/babel-plugin-transform-class-properties/src/index.js#L78). So, the `t.restElement`.

**Comment by hzoo** [comment]
https://github.com/babel/proposals/issues/13, will close until we handle this in parsing/transform for regular decorators

**Pull request closed without merging**
