### PR TITLE
Set up Renovate for GitHub Actions 

### PR DESCRIPTION
**Pull request by mmorel-35**
Set up Dependabot for GitHub Actions so they can stay up-to-date.
I have defined a "weekly" frequency. 

My first thought was to also handle npm dependencies but because of "
yarn install --immutable --skip-builds" in the CI it's failing when dependabot is making a PR, saying that the lock file would be modified. 
But that's the whole point of the operation because it is here to update the dependencies. 
<a href="https://gitpod.io/#https://github.com/babel/babel/pull/13305"></a>

### CODE REVIEW

**Comment by merceyz** [comment]
Dependabot only supports Yarn 1 so this wont work unless you do some workarounds - https://github.com/dependabot/dependabot-core/issues/1297

**Comment by nicolo-ribaudo** [comment]
Not related, but I noticed Babel is on Renovate's home page (Renovate works with Yarn 2), in the "Annotated" section :stuck_out_tongue:

https://www.whitesourcesoftware.com/free-developer-tools/renovate

**Comment by mmorel-35** [comment]
I found this fix : https://github.com/foxglove/studio/blob/main/.github/workflows/dependabot-fix.yml

Shall we use it or stick to github actions?

**Comment by nicolo-ribaudo** [comment]
I'd prefer to just use Renovate for dependencies since it works without any hack, and Dependabot for GH actions.

We never used any of them because Dependabot used to be quite spammy, but if they can be configured to run weekly (or maybe also once every two weeks), I'd be in favor of it. Let's also wait to hear what the rest of the team thinks.

**Comment by mmorel-35** [comment]
It would be even better to use only renovate, if it can handle github action versions. Anyone is aware of such a thing?

**Comment by JLHwung** [comment]
While we could use a dedicated renovate github action, we can install the renovate GH app to Babel repo and configure [`schedule`](https://docs.renovatebot.com/configuration-options/#schedule), such as
```json
{
  "schedule": [
    "before 3am on the first day of the month"
  ]
}
```

**Comment by mmorel-35** [comment]
I have setup a new file because I couldn't find the actual one.
Any way to check it's working?

**Comment by fedeci** [comment]
We should add also a GHAction with [renovate](https://docs.renovatebot.com/install-github-app/) installed.

**Comment by fedeci** [comment]
We should add the gh app to Babel and then wait the first day of the next month😆

**Comment by mmorel-35** [comment]
I love this fast fail approach 😂

**Comment by nicolo-ribaudo** [comment]
@hzoo @existentialism If you agree I can enable Renovate with a monthly schedule. According to https://github.com/marketplace/renovate it should open a PR to configure itself.

However, I couldn't find any reference about using it for GH actions, so we might still need the monthly Dependabot PR for them.

**Comment by nicolo-ribaudo** [comment]
I tried enabling the renovate GitHub app and it opened this PR: https://github.com/babel/babel/pull/13337

**Comment by mmorel-35** [comment]
Shall this pr be closed in favor of #13337?

**Pull request closed without merging**
