### PR TITLE
Fix/regenerator fixtures

### PR DESCRIPTION
**Pull request by Andarist**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues             | This should close PR #6109
| Patch: Bug Fix?          | no
| Major: Breaking Change?  | no
| Minor: New Feature?      | no
| Tests Added/Pass?        | yes
| Spec Compliancy?         | no
| License                  | MIT
| Doc PR                   | 
| Any Dependency Changes?  | no 

Those are fixed fixtures for #6109 . When merged it should automatically close the other PR too.

### CODE REVIEW

**Comment by Andarist** [comment]
This failing test:
`babel-plugin-transform-es2015-parameters/parameters rest member expression optimisation`
 is not connected to this PR and Im unsure what should I do. Should a separate PR with updated fixture be filed? cc @hzoo

**Comment by existentialism** [comment]
@Andarist will land https://github.com/babel/babel/pull/6116 in a sec

**Comment by Andarist** [comment]
@existentialism had to rebase it so the #6109 wont get automatically closed anymore (please close it manually), checks are passing atm though so 🎉 

cc @benjamn

**Comment by benjamn** [comment]
🎉

**Pull request merged**
