### PR TITLE
`parameters/rest` rename identifier names

### PR DESCRIPTION
**Pull request by jmm**
I find these names easier to reason about. I'm especially not a fan of double-negative boolean param names. ~~This is currently based on #3264. Here is the [diff from there to here](https://github.com/jmm/babel/compare/parameters-rest-simplify...jmm:parameters-rest-rename-ids).~~

### CODE REVIEW

**Comment by thejameskyle** [comment]
Why are https://github.com/babel/babel/pull/3264 and this separate PRs?

**Comment by jmm** [comment]
@thejameskyle only because the changes there are less subjective and I'm guessing they'll be more readily accepted, and because I just got feedback on a different PR that it's preferred I split it up more: https://github.com/babel/babel/pull/3174#issuecomment-171123846

**Comment by thejameskyle** [comment]
Well it appears you have the same commits in both except for the last two here

**Comment by jmm** [comment]
@thejameskyle 
> Well it appears you have the same commits in both except for the last two here

Yes. I'm working on a bunch of changes and I'm trying to strike a balance between maintaining a state I can hack on effectively (simple linear history spread across several branches) and not cramming too much into a single PR. That's why I noted that this is based on the other PR and provided a link to a diff between it and this. If that were merged this one would just start showing that diff (maybe I'd have to rebase, not sure) and if this were merged the other one would just evaporate. If that PR is stalled or rejected but the changes added by this one are going to be accepted, I can rework this one. If it's too difficult to review even with the diff link I provided, I'll just close this and wait to see what happens with the other one and take it from there.

**Comment by amasad** [comment]
rebase please

**Comment by jmm** [comment]
@amasad Done :sparkles:

**Comment by hzoo** [comment]
I think this is good to merge then?

**Comment by forivall** [comment]
bikeshedding: optEligible -> optimizable / optimisable?

**Comment by hzoo** [comment]
`optimisable` sounds good

**Comment by jmm** [comment]
@hzoo It would've been fine if this was merged a while ago, but at this point it's probably better for https://github.com/babel/babel/pull/3375 to get the focus first because those are actual bugs and this is to make the code easier to understand. I'd rather see https://github.com/babel/babel/pull/3375 get in first and then rebase and get this one ready to go again.

I might also make this more specific with multiple flags, e.g whatever the base is (let's just say `optEligible` for now) have `optEligible.arguments` and `optEligible.loop`. There are at least 2 distinct optimizations and I think due to the naming (which I proposed changing here) and the presence of only a single flag indicating the eligibility for optimization the code is likely to be quite confusing for anyone not really familiar with it (including me before I got as familiar with it as I am now). And the test coverage isn't great which makes it easier to make a mistake. The two of those combined is pretty gnarly. For example, **vhf** started fixing some of the issues in https://github.com/babel/babel/pull/3375 and accidentally killed one of the optimizations because the `deopted` flag implies a global boolean state and there wasn't good enough test coverage to catch it. I'm not explaining this great, but the key thing is there's more than one optimization the function can be eligible for but only one flag.

I think there's also a bunch of unnecessary processing happening in this transform and having more specific flags for eligibility for optimization may help eliminate that. I'll see, it may not be necessary.

In the meantime before https://github.com/babel/babel/pull/3375 gets dealt with I guess we can bikeshed the name here (be careful though :smiley: -- I've seen a project [literally bikeshed to death](https://github.com/thlorenz/es6ify/pull/80#issuecomment-73551650) before over a parameter name [and someone else's preference for a double-negative name, ironically]).

The most important thing to me is I don't think it should be a double negative kind of thing. If multiple people who get the gist of how the transform works think something other than what I suggested (and that's not a double negative) is better I'm open (I mean, I proposed changing the name in the first place -- it's not entirely up to me). I wish it didn't have to be British English, but w/e `¯\_(ツ)_/¯`.

**Comment by hzoo** [comment]
Closing for inactivity, can reopen

**Pull request closed without merging**
