### PR TITLE
Update monorepo.md

### PR DESCRIPTION
**Pull request by stefanpenner**
for example:

the decomposition of things like esprima and the various tools does enable quick one-off hacks, without having to grok a single large code-base. This experiments can mature etc.etc.

I believe mono-repo has its upsides, but this downside is worth mentioning.

My proposed solution (and likely already considered) is when internal concepts reach a specific level of maturity, and the boundaries to them are clear externalizing actually has some nice benifits

### CODE REVIEW

**Comment by sebmck** [comment]
I see it the other way. To me it encourages exposing powerful APIs since it's what all the packages need to interoperate.

**Comment by stefanpenner** [comment]
*Please don't take this as an argument against mono-repo, rather assume it suggests a pleasant middle-ground.*

----

Some food for thought:

Ember does largely present as mono-repo and this cuts down on overhead. It also provides a curated experience (also one of babels strong suites). But as the system has evolved various compositional units have been externalized.

* backburner
* rsvp
* router.js
* route-recognizer
* dag-map
* HTMLBars (glimmer)
* SImpleDOM (glimmer)
* simple-html-tokenizer (glimmer)
* handlebars
* morph-range
* etc

```
https://github.com/emberjs/ember.js/blob/master/bower.json#L13-L17
https://github.com/emberjs/ember.js/blob/master/package.json#L36
https://github.com/tildeio/htmlbars/blob/master/bower.json#L4
https://github.com/tildeio/htmlbars/blob/master/package.json#L45
https://github.com/tildeio/htmlbars/blob/master/package.json#L46
```

#### cons

* when we cut the boundaries wrong, it sucked and cost us
* some confusion where a problem lives
* required some massaging to get right
* coordination between maintainers

#### pros

* when we cut the boundaries right (or as they evolved to be correct) the division of responsibility improved quality
* easier contributions / bug hunting
* additional maintainers (this seemed to enable others to feel ownership, which aided in contributions)
* further innovation (outside of ember)

some examples of innovations enabled:

* https://github.com/jayphelps/graffiti (using HTMLBars and friends directly)
* https://github.com/riot/riot using SimpleDOM + simple-html-tokenizer
* rsvp has 334 depedents and has been downloaded > 1.1m times
* angular-new-router is using (a branch) of route-recongizer

**Comment by thejameskyle** [comment]
@stefanpenner I guess the difference here is that all the babel packages become their own npm modules and can be consumed individually by others where ember bundles them all together

**Comment by sebmck** [comment]
I don't feel as though the cons are relevant to a project like Babel. There are very few maintainers (one) and a handful of awesome contributors so coordination and triage is easy.

**Comment by sebmck** [comment]
Yeah, these packages aren't internal, they all have public APIs. It's essentially just shoving a bunch of npm git repos into the same repo so they all have the same build/lint/test/release system.

**Comment by sebmck** [comment]
Also I've found that I tend to neglect other repos a lot which will eventually lead to excessive coderot whereas the current architecture allows for faster iteration and atomic commits across all the dependencies.

**Comment by stefanpenner** [comment]
> There are very few maintainers (one)

I suspect the ownership problem may be preventing this number from growing. I suspect it is a side-affect of babel assimilating what it touches.

I acknowledge coordinating with others has overhead, but it may be a way to improve the Buss Factor.

**Comment by stefanpenner** [comment]
> @stefanpenner I guess the difference here is that all the babel packages become their own npm modules and can be consumed individually by others where ember bundles them all together

That doesn't seem any different

**Comment by thejameskyle** [comment]
> - when we cut the boundaries right (or as they evolved to be correct) the division of responsibility improved quality

The responsibility is already really well defined here. I don't see how separate repos would help at all.

> - easier contributions / bug hunting
> - additional maintainers (this seemed to enable others to feel ownership, which aided in contributions)

We don't see many contributions, I guess we'll see

> - further innovation (outside of ember)

This is where every package being an npm module makes a difference. People can use packages like `babel-types` without the rest of Babel the same way they can use HTMLBars without Ember.

None of these small packages in Babel will be massively popular on their own like RSVP or Handlebars, but people who want to build tools on top of them now can very easily.

**Comment by zonak** [comment]
What about if you look at it from the opposite perspective of wanting to try something like RSVP2 instead of the original one.

**Pull request closed without merging**
