### PR TITLE
Remove babylon

### PR DESCRIPTION
**Pull request by kittens**
Moved into repo [`babel/babylon`](https://github.com/babel/babylon). It's the only project in this repo that is decoupled so it makes sense to move it into it's own repo where it can undergo independent development.

### CODE REVIEW

**Comment by kittens** [comment]
CI is green. Merging. I've bought this up on slack a few times and there didn't seem to be any objections. We can revert this if someone feels strongly about it.

**Comment by jmm** [comment]
> I've bought this up on slack a few times and there didn't seem to be any objections. 

I asked why one of the times you brought it up and didn't hear back. I think the repo is really sprawling right now though, so not opposed to it being separate, though losing history is too bad.

**Comment by jmm** [comment]
Is Babylon issue tracking going to be on GitHub?

**Comment by kittens** [comment]
@jmm 

> I asked why one of the times you brought it up and didn't hear back. 

Sorry, I'd explained it previously but mustn't have seen your message. I'll summarise here:

Babylon is basically an independent project. It's the only module in `babel/babel` that we could remove and have nothing go wrong (this PR is testament to that, I literally just ran `rm -rf packages/babylon`). There's little value to having it in the monorepo and it's advantageous to make it have a separate development process. Especially if we want to get external adoption of it in other projects, right now it's a parser for Babel but I'd like to make it more generic.

While I don't really work full time on Babel and maintain it I'm more than happy to work on Babylon and maintain it as it influences other projects that I'm pursuing.

> though losing history is too bad.

Yeah I agree. I'm not very good with git but if someone knows how to copy the history over I'm more than willing.

> Is Babylon issue tracking going to be on GitHub?

I don't see why not. The parser doesn't get nearly the amount of issues as Babel.

**Comment by hzoo** [comment]
(For anyone developing, we'll need to `npm i babylon` again in the 5 packages that depend on it individually or run `make bootstrap` again)

**Comment by jmm** [comment]
@kittens Thanks for the info. I think having it in a separate repo will be good, but I think we should see if we can retain the history. I haven't done it before, but a quick search gives me hope that it's doable. Of course now it depends on commits not being added to the new repo in the meantime.

**Comment by hzoo** [comment]
@loganfsmyth said he is looking into it (#development in slack)

**Comment by loganfsmyth** [comment]
@jmm Yeah I'll do some surgery tonight :)

**Comment by jmm** [comment]
@hzoo @loganfsmyth Awesome, thanks! I'm sure you don't need this, but for whomever, these are a few of the resources I was going to check out:

* http://ariya.ofilabs.com/2014/07/extracting-parts-of-git-repository-and-keeping-the-history.html

* http://stackoverflow.com/questions/359424/detach-subdirectory-into-separate-git-repository

* https://help.github.com/articles/splitting-a-subfolder-out-into-a-new-repository/

**Comment by divmain** [comment]
@loganfsmyth, I stitched together the histories of `babel/packages/babylon` and new `babylon` repo together [here](https://github.com/divmain/babylon/tree/babylon-history).  Includes the handful of commits since the move to the new repo.

**Comment by hzoo** [comment]
FYI, @loganfsmyth has merged the history of `acorn`, `acorn-babel`, and `babel` now

**Comment by loganfsmyth** [comment]
Sorry it took longer than expected, things never quite work like you expect :)

**Comment by jmm** [comment]
Wow, you got the history back to Acorn? That's awesome. Thanks @loganfsmyth!

**Pull request merged**
