### PR TITLE
Prevents exception on PnP

### LINKED ISSUE #8967: Yarn Plug'n'Play support for babel-node
## Bug Report / Feature request

**Current Behavior**
Running babel-node with this package.json installed with yarn gives runtime errors.

```
/Users/niklas/Library/Caches/Yarn/v3/npm-@babel-node-7.0.0-20e55bb0e015700a0f6ff281c712de7619ad56f4/node_modules/@babel/node/lib/babel-node.js:99
    if (err.code !== "MODULE_NOT_FOUND") throw err;
                                         ^

Error: Package "@babel/node@7.0.0" (via "/Users/niklas/Library/Caches/Yarn/v3/npm-@babel-node-7.0.0-20e55bb0e015700a0f6ff281c712de7619ad56f4/node_modules/@babel/node/lib/babel-node.js") is trying to require the package "kexec" (via "kexec") without it being listed in its dependencies (@babel/core, @babel/polyfill, @babel/register, commander, fs-readdir-recursive, lodash, output-file-sync, v8flags, @babel/node)
    at makeError (.../.pnp.js:54:17)
    at Object.resolveToUnqualified (.../.pnp.js:3860:17)
    at Object.resolveRequest (.../.pnp.js:3931:31)
    at Function.Module._resolveFilename (.../.pnp.js:4111:30)
    at Function.Module._load (.../.pnp.js:4029:31)
    at Module.require (internal/modules/cjs/loader.js:643:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at /Users/niklas/Library/Caches/Yarn/v3/npm-@babel-node-7.0.0-20e55bb0e015700a0f6ff281c712de7619ad56f4/node_modules/@babel/node/lib/babel-node.js:94:19
    at /Users/niklas/Library/Caches/Yarn/v3/npm-v8flags-3.1.1-42259a1461c08397e37fe1d4f1cfb59cad85a053/node_modules/v8flags/index.js:131:14
    at /Users/niklas/Library/Caches/Yarn/v3/npm-v8flags-3.1.1-42259a1461c08397e37fe1d4f1cfb59cad85a053/node_modules/v8flags/index.js:39:14
```

Fixing this line to also ignore the error code `UNDECLARED_DEPENDENCY`

https://github.com/babel/babel/blob/d35563ee1a7c3d8a69b5bc1b87fc8d6d883f00ea/packages/babel-node/src/babel-node.js#L91

leads to this error:

```
internal/modules/cjs/loader.js:589
    throw err;
    ^

Error: Cannot find module '@babel/polyfill'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:587:15)
    at Function.Module._load (internal/modules/cjs/loader.js:513:25)
    at Module.require (internal/modules/cjs/loader.js:643:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/niklas/Library/Caches/Yarn/v3/npm-@babel-node-7.0.0-20e55bb0e015700a0f6ff281c712de7619ad56f4/node_modules/@babel/node/lib/_babel-node.js:73:1)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
error Command failed with exit code 1.
```

**Expected behavior/code**
No errors

**Babel Configuration (.babelrc, package.json, cli command)**

```json
{
  "private": true,
  "devDependencies": {
    "@babel/core": "^7.0.0",
    "@babel/node": "^7.0.0",
    "@babel/preset-env": "^7.0.0",
    "@babel/preset-react": "^7.0.0"
  },
  "installConfig": {
    "pnp": true
  }
}
```
```json
{
	"presets": [["env", {"target": "current"}], "react"]
}
```

**Environment**
- Babel version(s): @babel/core: 7.1.2
- Node version: v11.0.0
- Yarn: 1.12.1
- OS: macOS 10.13.6
- Monorepo: no
- How you are using Babel: babel-node

@arcanis might be interested

### PR DESCRIPTION
**Pull request by arcanis**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #8967
| Patch: Bug Fix?          | Y
| Major: Breaking Change?  | N
| Minor: New Feature?      | N
| Tests Added + Pass?      | n/a
| Documentation PR Link    | n/a
| Any Dependency Changes?  | N
| License                  | MIT

PnP environments throw semantic errors when a dependency cannot be found (in this case, it's because `kexec` isn't listed in `@babel/node`'s dependency list, and thus it's not allowed to access it). This cause the error to be thrown instead of silently ignored.

The real fix would be to use [optional peer dependencies](https://yarnpkg.github.io/berry/configuration/manifest#optional) to list the `kexec` peer dependency, but at the moment I'm looking for an uncontroversial hotfix to ship asap.

### CODE REVIEW

**Comment by nicolo-ribaudo** [comment]
Could you run `make fix`?

**Comment by arcanis** [comment]
@nicolo-ribaudo Just pushed the result of this command, but it seems to include a lot of changes. Is that expected?

**Comment by arcanis** [comment]
Ping?

**Comment by nicolo-ribaudo** [comment]
It looks that something went wrong and some test files have been deleted. Could you revert the last commit and run `./node_modules/.bin/eslint packages '*.js' --format=codeframe --fix` instead?

**Comment by nicolo-ribaudo** [comment]
Merged as d7801c644cd3e441e2a898339c0b7654936f93a9. Thank you!

**Pull request closed without merging**
