### PR TITLE
Add jsxQuotes option for formatting output:

### PR DESCRIPTION
**Pull request by shumov**
Add ability to generate JSX code with single quotes.

``` javascript
class Map {
  render() {
    return <div className='awesome'>Single quotes :)</div>
  }
}
```

### CODE REVIEW

**Comment by shumov** [comment]
@amasad What do you think? :)

**Comment by amasad** [comment]
What's the rationale here? Also when are you printing JSX code as opposed to React.createElement?

**Comment by shumov** [comment]
When you have code style with JSX single quotes like here https://www.youtube.com/watch?v=xsSnOQynTHs and write test fixtures with expected jsx.

**Comment by shumov** [comment]
We have some babel-plugins for developement auto code review. It need ability to keep existing code style.

**Comment by amasad** [comment]
We haven't supported this feature yet, although we plan to at some point. At facebook we use jscodeshift and it does some transformations and retains as much of the original code style as possible. Check it out https://github.com/facebook/jscodeshift

I'd rather find a way for us to work towards automatic code style detection and reprinting the same original source than add more and more printer options

**Comment by shumov** [comment]
By the way — in my pull request jsxQuotes default value is the result of CodeGenerator.findCommonStringDelimiter(code, tokens).
https://github.com/babel/babel/pull/3416/commits/50a9ddb44cc2b0104e5ce319d77a7a047633d460

**Comment by loganfsmyth** [comment]
Do we want two options for this? Seems like it would be much easier to have the general quotes option to apply to both places and update autodetection to take both into account.

**Comment by shumov** [comment]
@loganfsmyth a lot of people are using single quotes for js strings and double quotes for jsx/html/xml attributes https://github.com/facebook/relay/blob/master/examples/star-wars/js/components/StarWarsApp.js
obviously either there is no need to have any options and determine the quotes automatically or we should have options for both cases

**Comment by hzoo** [comment]
Closing for inactivity + we want to avoid options if possible especially with babel-generator since we are talking about compiled code not source code (otherwise can use recast/prettier)

I would use recast (as the generator replacement) or prettier as the output

```js
{
  "generatorOps": {
    "generator": "recast"
  }
}
```

**Pull request closed without merging**
