### PR TITLE
babel-helpers: prevent object shape change in jsx

### PR DESCRIPTION
**Pull request by jorrit**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            |  none
| Patch: Bug Fix?          | no
| Major: Breaking Change?  | no
| Minor: New Feature?      | no
| Tests Added + Pass?      | no
| Documentation PR         | no
| Any Dependency Changes?  |no
| License                  | MIT

Keeping the shape of an object constant is a performance improvement for modern javascript engines. At the point of the code change it is certain that the `children` property will be set later, so the property can already be set to `undefined`.

### CODE REVIEW

**Comment by Andarist** [comment]
cc @bmeurer

**Comment by bmeurer** [comment]
Good catch! Do you see concrete performance improvements somewhere?

**Comment by sophiebits** [comment]
This means that the children property is added before defaultProps instead of after. Not sure how that affects things. It might be worse? I would love to figure out a better way to pull this off and share more hidden classes for React elements.

**Comment by jorrit** [comment]
I encountered this code while researching a different issue and thought this was an easy opportunity for a small performance improvement. I have not tested the performance gains but they will only be there when there are no defaultProps, as it will change the shape again.

I don't see a problem with the defaultProps. The prop is compared to `void 0` which is undefined. Undefined is strictly equal to itself. The loop should execute the same. If the defaultProps is only contains a children property there will be a performance improvement and otherwise the performance will be the same. If you want me to change undefined in my change to void 0 that's fine.

This change is intended to be a small and easy improvement. If you are looking for something more fundamental that should be a separate issue in my opinion. I can understand it when you don't want to apply small changes based on theoretical performancr gains.

**Comment by Andarist** [comment]
@jorrit you'd have to rebase this PR to get this merge - we've recently renamed our fixtures files, so edited `expected.js` should be named `output.js` now.

**Comment by jorrit** [comment]
@Andarist done. I have changed `undefined` to `void 0` because that seems more appropriate in the context of this piece of code.

**Comment by Andarist** [comment]
Merged. Thanks! 🎉

**Comment by jorrit** [comment]
Thank you for merging!

**Pull request merged**
