### PR TITLE
⚡️ switch to reduce for pipeline

### PR DESCRIPTION
**Pull request by samccone**

### CODE REVIEW

**Comment by sebmck** [comment]
Any specific reason? Seems like it'd be much slower.

**Comment by samccone** [comment]
hey @sebmck do you still want this or should I :skull: it?

**Comment by sebmck** [comment]
yo @samccone, on a second look it actually looks much nicer. can you rebase?

**Comment by samccone** [comment]
yay :kiss:

**Comment by samccone** [comment]
https://www.youtube.com/watch?v=PoMhMZZjbGg

**Comment by sebmck** [comment]
thanks @samccone! :tada:

**Pull request merged**
