### PR TITLE
enable typescript incremental builds

### PR DESCRIPTION
**Pull request by zxbodya**
this is to make running tsc locally faster
(for me it is almost 10x improvement - reducing it from 40 to around 4 seconds)

| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | 
| Patch: Bug Fix?          |
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/14790"></a>

### CODE REVIEW

**Comment by liuxingbaoyu** [comment]
May I ask what command are you using? We only seem to use `tsc` with `make prepublish-build`.

This PR looks good to me though.

**Comment by zxbodya** [comment]
> May I ask what command are you using? We only seem to use `tsc` with `make prepublish-build`.

`yarn tsc` (and `time yarn tsc` to measure the time it takes)

**Review by liuxingbaoyu — APPROVED** [review]

**Review by JLHwung — APPROVED** [review]
Thanks.

**Comment by nicolo-ribaudo** [comment]
@liuxingbaoyu You can also run it locally with `make tscheck`

**Pull request merged**
