### PR TITLE
Move `babel-plugin-transform-class-properties` to stage 2

### PR DESCRIPTION
**Pull request by kripod**

### CODE REVIEW

**Comment by hzoo** [comment]
It looks like your master has some other commits (not a big deal since I can squash but letting you know)

**Comment by kripod** [comment]
@hzoo That's a great advice, thank you!

**Comment by loganfsmyth** [comment]
This has one issue, you need to modify `index.js` too.

**Comment by kripod** [comment]
@loganfsmyth Fixed, thanks for the feedback!

**Comment by hzoo** [comment]
Thanks!!

**Pull request merged**
