### PR TITLE
[@babel/types] Moved generators related to babel-types into the babel-types package directory.

### LINKED ISSUE #9239: @babel/types wasn't released after being modified
## Bug Report

**Current Behavior**
https://github.com/babel/babel/pull/9110 modified the typescript generator for @babel/types. There have been several releases since this PR was merged (v7.2.3-v7.2.5). However, these versions were not released for @babel/types - [the most recent release is still v7.2.2](https://www.npmjs.com/package/@babel/types).

**Expected behavior/code**
I would expect a new version of @babel/types to be released after the typescript generator was modified.

### PR DESCRIPTION
**Pull request by cameron-martin**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #9239 
| Patch: Bug Fix?          | 👍
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | No - no idea how to automatically test this change.
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

### CODE REVIEW

**Comment by nicolo-ribaudo** [comment]
Can't we also move utils and docs?

**Comment by cameron-martin** [comment]
Ah I didn't notice that the docs generator pertains only to the types. I'll move that too then.

**Comment by nicolo-ribaudo** [comment]
It used to be called by `make build`, but I removed it (https://github.com/babel/babel/pull/8142). Now it needs to be manually called.

**Comment by cameron-martin** [comment]
Does anything else need to happen before this is merged?

**Comment by nicolo-ribaudo** [comment]
I'm waiting for another

**Comment by nicolo-ribaudo** [comment]
Thank you!

**Pull request merged**
