### PR TITLE
chore: asserts that all comments are printed

### PR DESCRIPTION
**Pull request by liuxingbaoyu**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | `Fixes #1, Fixes #2` 
| Patch: Bug Fix?          |
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/15158"></a>

### CODE REVIEW

**Comment by liuxingbaoyu** [comment]
I forgot to ignore etc.

**Comment by liuxingbaoyu** [comment]
I want to add a test, but can't figure out how to do it.

**Comment by nicolo-ribaudo** [comment]
@liuxingbaoyu https://github.com/babel/babel/pull/15160 adds a test for a comment that could never be printed, you could use that and check that we report an error.

**Comment by liuxingbaoyu** [comment]
This assertion seems overly restrictive, as `file.comments` is not modified when we convert, which results in reporting comments that the compiler expected or accidentally discarded, and we only want to catch problems with the printer. I will try other methods.

**Comment by liuxingbaoyu** [comment]
I think in https://github.com/babel/babel/pull/15144 this becomes unnecessary.

**Pull request closed without merging**
