### PR TITLE
Use rollup to bundle @babel/polyfill

### PR DESCRIPTION
**Pull request by jridgewell**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | 
| Patch: Bug Fix?          |
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      |
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

This results in several kb file savings when compressed:

| `polyfill.js` |   Before |    After |
|---------------|---------:|---------:|
| Size          | 239,724b | 208,909b |
| Size (Brotli) |  49,258b |  45,159b |

| `polyfill.min.js` |  Before |   After |
|-------------------|--------:|--------:|
| Size              | 99,310b | 78,250b |
| Size (Brotli)     | 29,243b | 25,380b |

### CODE REVIEW

**Comment by nicolo-ribaudo** [comment]
Before merging this PR, we should check that the bundled polyfill passes the `core-js` test suite.

Rollup does many optimizations that are mostly not observable according to the standard, but often cause problems with feature detection.

**Comment by hzoo** [comment]
Maybe could also inject this version of the polyfill into our own test runner, but would need to build that before any other tests are run

**Comment by nicolo-ribaudo** [comment]
Also, please note that `@babel/polyfill` has been deprecated since 3303b079c596e56909adff4b834f098f5f1d8e2a (more than one year ago).

**Comment by jridgewell** [comment]
I'll close since this is deprecated.

**Pull request closed without merging**
