### PR TITLE
Optimize block-hoist transformer

### PR DESCRIPTION
**Pull request by jmm**
Some small optimizations to block-hoist transformer.

Re: e915e6b can there ever be a situation where `node.body[i] == null`? I think that's the only case where these changes would fall down.

### CODE REVIEW

**Comment by sebmck** [comment]
> can there ever be a situation where `node.body[i] == null`?

Not sure but it's better to be safe than sorry.

**Comment by jmm** [comment]
> Not sure but it's better to be safe than sorry.

Yeah, if it can't be ruled out, I suppose so. It seemed implausible to me that that can happen (I don't see anything in ESTree about a node being allowed to be `null|undefined` for example), but I don't have enough experience with it to say it can't. Those changes are segregated in their own commit, so if you like the other changes you can cherry pick 83854db, or I can create a new PR or whatever you need.

**Comment by sebmck** [comment]
Closing this as from my benchmarks this doesn't make any (noticeable) difference which was the intended goal of this PR. Sorry for the delay @jmm, thank you so much though! :blush:

**Comment by jmm** [comment]
Ok, no problem. When I noticed this, while looking at the file for something else, I asked you on slack about how to benchmark optimizations and you said it's hard to do for small things. So I wasn't going to bother with this, but I think you ended with something like "every little bit helps", so I did it after all. (And it seems silly to just keep iterating for no reason.) Needless to say I won't bother with anything else this small though.

**Comment by sebmck** [comment]
Oh shit, I missed the `break` part, you're right about that. Can you submit a separate PR for that please?

**Comment by jmm** [comment]
Sure, will do.

**Comment by jmm** [comment]
See #2136 -- it's just the `break` part from 83854db.

**Pull request closed without merging**
