### PR TITLE
drop `helpers/clone`

### PR DESCRIPTION
**Pull request by sindresorhus**
It's misleading as it doesn't actually do a deepClone, not even a clone. And `_.assign()` does the same only faster.

### CODE REVIEW

**Comment by sebmck** [comment]
`_.assign` only copies over own properties.

**Comment by sebmck** [comment]
See #583

**Comment by sindresorhus** [comment]
I don't get it, why would you want to support anything other than a plain object for options. That is so weird. He should just use Object.assign too.

**Comment by sebmck** [comment]
*shurg* Seemed like a good idea at the time.

**Comment by sebmck** [comment]
Oh well, thanks!

**Comment by thejameskyle** [comment]
lodash's `_.create` method can do this even faster if you don't need a deep clone.

**Pull request merged**
