### PR TITLE
Add `duplicate-named-capturing-groups-regex` to `preset-env`

### PR DESCRIPTION
**Pull request by JLHwung**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Add `duplicate-named-capturing-groups-regex` to preset-env as the language will be included in ES2025
| Patch: Bug Fix?          |
| Major: Breaking Change?  |
| Minor: New Feature?      | Yes
| Tests Added + Pass?      | Yes
| Documentation PR Link    | https://github.com/babel/website/pull/2893
| Any Dependency Changes?  |
| License                  | MIT

- [x] Renmae plugin to `transform-*`
- [x] Add it to preset-env

### CODE REVIEW

**Comment by JLHwung** [comment]
The CI error is related. As `duplicate-named-capturing-groups-regex` requires babel-core 7.19, preset-env will also indirectly require babel-core 7.19+. This case is similar to the `class-static-block` transform which requires babel-core 7.12 and was added to preset-env in 7.16.

I tend to revise the regression test so that it works for Babel <7.13.

**Comment by nicolo-ribaudo** [comment]
Isn't adding it to `minVersions` enough (https://github.com/babel/babel/blob/8911810f6006ebb720c837f585f482507a39349d/packages/babel-preset-env/src/available-plugins.ts#L145-L152)?

**Review by liuxingbaoyu — APPROVED** [review]

**Review by nicolo-ribaudo — APPROVED** [review]
Can you see if rebasing fixes the CI error?

**Comment by nicolo-ribaudo** [comment]
Could you change https://github.com/babel/babel/blob/3e4723fd07a0ef22039b508ec4da71ce73be1e6e/.github/workflows/reminders.yml to remind us to deprecate the old one?

**Pull request merged**
