### PR TITLE
Update babel-plugin-proposal-unicode-property-regex for Unicode v12

### PR DESCRIPTION
**Pull request by mathiasbynens**
https://github.com/tc39/ecma262/issues/1467
https://github.com/tc39/ecma262/pull/1468

### CODE REVIEW

**Comment by mathiasbynens** [comment]
Where does the `babel.js` increase of 912.83 KB come from? Any ideas?

The new Unicode data takes less than a KB (and that's uncompressed). Compare https://bundlephobia.com/result?p=regenerate-unicode-properties@7.0.0 vs. https://bundlephobia.com/result?p=regenerate-unicode-properties@8.0.0.

**Comment by nicolo-ribaudo** [comment]
I'm investigating the size regression

**Comment by nicolo-ribaudo** [comment]
The packahe which contains `addRange(0x0, 0x7F)` is included three times in the bundle

**Comment by nicolo-ribaudo** [comment]
Before:
schermata da 2019-03-05 17-24-37


After:
schermata da 2019-03-05 17-28-36

**Comment by nicolo-ribaudo** [comment]
schermata da 2019-03-05 17-39-36

For some reason, the `npm` registry doesn't show `regexpu-core@4.5`: for this reason, the top-level version will be 4.4 and lerna can't hoist the dependency used by the monorepo packages.

**Comment by nicolo-ribaudo** [comment]
Fixed
schermata da 2019-03-05 18-00-00

**Comment by danez** [comment]
Should we also update unicode in the parser and regenerate the identifier regexes?

**Comment by danez** [comment]
This makes babel-standalone fail on node 6

```
WARNING in ./node_modules/regenerate-unicode-properties/Binary_Property/Grapheme_Base.js
Module build failed: RangeError: Maximum call stack size exceeded
    at Object.needsParens (/home/travis/build/babel/babel/node_modules/@babel/generator/lib/node/index.js:112:10)
    at Generator.print (/home/travis/build/babel/babel/node_modules/@babel/generator/lib/printer.js:287:25)
    at Generator.MemberExpression (/home/travis/build/babel/babel/node_modules/@babel/generator/lib/generators/expressions.js:261:8)
    at withSource (/home/travis/build/babel/babel/node_modules/@babel/generator/lib/printer.js:299:22)
    at Buffer.withSource (/home/travis/build/babel/babel/node_modules/@babel/generator/lib/buffer.js:185:28)
    at Generator.withSource (/home/travis/build/babel/babel/node_modules/@babel/generator/lib/printer.js:178:15)
    at Generator.print (/home/travis/build/babel/babel/node_modules/@babel/generator/lib/printer.js:298:10)
    at Generator.CallExpression (/home/travis/build/babel/babel/node_modules/@babel/generator/lib/generators/expressions.js:177:8)
    at withSource (/home/travis/build/babel/babel/node_modules/@babel/generator/lib/printer.js:299:22)
    at Buffer.withSource (/home/travis/build/babel/babel/node_modules/@babel/generator/lib/buffer.js:185:28)
 @ ./node_modules/regenerate-unicode-properties ^\.\/.*\.js$
 @ ./node_modules/regexpu-core/rewrite-pattern.js
 @ ./packages/babel-plugin-proposal-unicode-property-regex/lib/index.js
 @ ./packages/babel-standalone/src/index.js
```

**Comment by nicolo-ribaudo** [comment]
This looks like a bug with Babel itself? :thinking:

**Comment by mathiasbynens** [comment]
Was about to reference https://github.com/babel/babel/issues/8278 here myself.

**Comment by mathiasbynens** [comment]
I just published `regenerate-unicode-properties@8.0.1` which changes the generated output to avoid deeply-nested ASTs. `regexpu-core@4.5.3` has the updated dependency.

**Pull request merged**
