### PR TITLE
fix onlyRegex no effect

### PR DESCRIPTION
**Pull request by fundon**

### CODE REVIEW

**Comment by sebmck** [comment]
It totally has an effect. It will return `true` if there's an ignore regex and the path matches it or if there's an only regex and it doesn't match it.

**Comment by fundon** [comment]
In this case https://github.com/trekjs/trek-cli/blob/master/templates/app/esnext.js

If I want add some `node_modules/{moduel}` also will be ignored.

**Comment by sebmck** [comment]
Having an only **and** an ignore filter doesn't make any sense since they're both to shadow each other. It's like using both the whitelist and the blacklist.

**Comment by fundon** [comment]
Yep, it has `whitelist` and `blacklist` options will be better.

**Comment by sebmck** [comment]
I was using the blacklist and whitelist example as a comparison about how the two shadow each other and using them both doesn't make any sense.

**Comment by fundon** [comment]
Something likes this in `.babelrc`:
```js
{
  "experimental": true,
  "playground": true,
  "loose": true,
   "node_modules": [
     "trek", // will be transformed
     "!does_not_transform"
   ]
}
```

**Comment by sebmck** [comment]
I'm confused by what you're requesting, you can just add an `only` regex that matches `trek`. Closing this since the current behaviour is correct and this is an unnecessary change.

**Comment by fundon** [comment]
If just add an `only` regex that `node_modules/trek` also will be ignored, because `node_modules/trek` path has `node_modules`, see https://github.com/babel/babel/blob/master/src/babel/api/register/node.js#L34.

So the `only` option no effect.

**Comment by sebmck** [comment]
Set `ignore` to `false`.

**Comment by fundon** [comment]
@sebmck 

https://github.com/babel/babel/blob/master/src/babel/util.js#L44

* If set `ignore` to false and set `only`, I also need add all file paths to `only` regexp.
* If just only set `ignore` to false, all files will be transformed.

So I need a simpler way to solve it.

**Comment by sebmck** [comment]
You really shouldn't under any circumstance be using the require hook in a node module that you're distributing over npm anyway. I'm not willing to support this use, you should be compiling your files before distribution.

**Comment by fundon** [comment]
Thanks for your suggestions.

**Pull request closed without merging**
