### PR TITLE
More es6

### PR DESCRIPTION
**Pull request by hzoo**
It was failing a few tests with other some other default param / destructuring changes or maybe I was using it wrong?

http://goo.gl/o6dShC

### CODE REVIEW

**Comment by neVERberleRfellerER** [comment]
@hzoo 
Default params are implemented by testing agains `undefined`, while `||=` is testing for falsy value. For example, `addImport(source, name)` will act differently (before/after change) when name is empty string.

**Comment by hzoo** [comment]
Ah that makes sense.

**Comment by sebmck** [comment]
Remove the `||=` changes and this should be good to merge. I'm a bit confused about the failing tests though?

**Comment by neVERberleRfellerER** [comment]
@hzoo And this
```
print.list = function (items, opts = {}) {
  opts.separator ||= ", ";
```
will set separator if it is not set in opts object. While this
```
print.list = function (items, opts = { separator: ", " }) {
  print.join(items, opts);
};
```
will set object ```{ separator: ", " }``` only if no options are passed. By passing something as options, *separator* property will not be set (independently of its prior existence).

**Comment by hzoo** [comment]
@sebmck The failing tests were because of changing `||=` since I didn't understand it was checking `truthy` instead of `undefined`. I'l remove that and it should be good.

**Comment by hzoo** [comment]
@sebmck ok removed `||=` changes. Oh and I think the `No ES6 syntax features or methods, exclusively ES5.` under `Code Standards` in `CONTRIBUTING.md` can be changed now?

**Comment by sebmck** [comment]
Ah, yep it can.

**Pull request merged**
