### PR TITLE
Removed guy ascii art

### PR DESCRIPTION
**Pull request by yupferris**
Also removed accompanying "test".

I love the [original joke](https://medium.com/friendship-dot-js/i-peeked-into-my-node-modules-directory-and-you-wont-believe-what-happened-next-b89f63d21558#.yd0dqq7iu) as much as the next guy, and I'll admit [this followup](https://github.com/babel/babel/pull/3646) gave me a chuckle, but I don't think these kind of jokes are necessary and I don't think I'm crossing any lines by calling them "borderline unprofessional".

### CODE REVIEW

**Comment by hzoo** [comment]
Thanks! I was just making another PR for this https://github.com/babel/babel/pull/3657

**Comment by yupferris** [comment]
@hzoo Does that `comments: false` config option strip comments when packaging the npm module? Are there any other comments that would be good to preserve? Does that fix have side effects like these? If so, I'd rather see the whole thing removed, but if it's sufficient I can't really complain.

**Comment by hzoo** [comment]
`comments: false` removes all comments when compiling babel itself into a string which goes from `src` -> `lib` folder which eventually gets published yeah.

**Comment by yupferris** [comment]
Sounds good to me. Feel free to close mine in favor of the other one (although I'd prefer to see it removed entirely, I have less objections as long as it doesn't end up in packaged code).

**Comment by hzoo** [comment]
Ok I just merged the followup. Thanks for the PR and help

**Comment by yupferris** [comment]
Thank you!

**Pull request closed without merging**
