### PR TITLE
Fix UpdateExpression handling in es2015-modules-commonjs, resolve #4462

### LINKED ISSUE #4462: Use of undefined-returning-function result in ES2015 CommonJS module transform (T7565)
> Issue originally made by Justin Johansson (justinjohansson)

### Bug information

* **Babel version:** 6.11.4 (babel-core 6.13.2)
* **Node version:** v6.4.0
* **npm version:** v6.4.0

### Input code

Bug shows up when transpiling following input code with ES2015 CommonJS module transform plugin.

```
/* file: bar.js */

export { yy, zz };

var yy = 0;
var zz = yy++;

```

### Description

Bug is apparent by visual inspection of code in babel-plugin-transform-es2015-modules-commonjs/src/index.js line 122 in UpdateExpression:

```
let newPaths = path.replaceWithMultiple(t.sequenceExpression(nodes));
for (const newPath of newPaths) this.requeueInParent(newPath);

```
replaceWithMultiple is a method which always returns undefined.  The following for/in statement will therefore always throw an exception as follows:

```
babel -d dist src
TypeError: src/bar.js: Cannot read property 'Symbol(Symbol.iterator)' of undefined
    at Object.UpdateExpression
```

### PR DESCRIPTION
**Pull request by motiz88**
| Q                 | A
| ----------------- | ---
| Bug fix?          | yes
| Breaking change?  | no
| New feature?      | no
| Deprecations?     | no
| Spec compliancy?  | no
| Tests added/pass? | yes
| Fixed tickets     | #4462
| License           | MIT

The `requeueInParent` call is apparently redundant (all tests pass without it). Also, whatever it was meant to do, I don't believe it has ever worked - since `replaceWithMultiple` returns `undefined` and has done so since basically forever (so the `for` would always have caused an error).

Possibly some other requeue calls in this file can be omitted with no adverse effects, but I kept changes to a minimum.

### CODE REVIEW

**Comment by hzoo** [comment]
cc @loganfsmyth

**Comment by hzoo** [comment]
original PR was done in https://github.com/babel/babel/pull/3368

**Comment by danez** [comment]
Also saw this and was wondering. Send to not do anything right now. But maybe it was meant that the function should actually return something.

**Comment by loganfsmyth** [comment]
Looks good. Obviously that `requeueInParent` hasn't been important up to now, if it's causing issues someone can always report it, but given how long this bug has been around, I just don't think people are using update expressions on exports much anways :P

**Pull request merged**
