### PR TITLE
Add ArrayExpression.elements.default

### PR DESCRIPTION
**Pull request by jmm**
I'd like to add a test for this, but #3174 isn't merged yet :(

### CODE REVIEW

**Comment by amasad** [comment]
why is the test dependent on #3174?

**Comment by jmm** [comment]
@amasad `babel-types` has no test infrastructure currently. I suppose I could test it indirectly via some other package, but to me it seems better to get tests up and running for `babel-types`.

**Comment by amasad** [comment]
ah, cool. In what cases does `ArrayExpression` need a default?

**Comment by hzoo** [comment]
I suppose if you want to do `t.arrayExpression()` instead of `t.arrayExpression([])`

**Comment by jmm** [comment]
@amasad Yes, just what @hzoo said: when you have reason to insert an empty array literal into the AST.

**Pull request merged**
