### PR TITLE
Use Yarn 2.4.0

### PR DESCRIPTION
**Pull request by nicolo-ribaudo**
| Q                        | A 
| ------------------------ | ---
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  | Yes, Yarn
| License                  | MIT

The new Yarn version lets us remove some code from the publish plugin: https://github.com/nicolo-ribaudo/yarn-plugin-babel-release-tool/commit/e56bcefc78df9c6b92fb89aa6aa53ed6423a6fcc

If the CRA e2e test fails, that's fixed by https://github.com/babel/babel/pull/12450.

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/12453"></a>

### CODE REVIEW

**Review by JLHwung — APPROVED** [review]
We can also remove https://github.com/babel/babel/blob/2ba92651982658d0d78e15bdddee6b725e4c30ea/Makefile#L239-L244 now.

**Comment by merceyz** [comment]
We haven't merged https://github.com/yarnpkg/berry/pull/2005 yet so you need to keep it for now

**Comment by nicolo-ribaudo** [comment]
Wait, I didn't run that `sed` command: why it isn't failing? 🤔

**Comment by nicolo-ribaudo** [comment]
Before the `Makefile` update:
```
➜ make check-yarn-bug-1882
echo "Your version of yarn is affected by https://github.com/yarnpkg/berry/issues/1882"
Your version of yarn is affected by https://github.com/yarnpkg/berry/issues/1882
echo "Please run `sed -i -e "s/3155328e5/4567890e5/g" .yarn/releases/yarn-*.cjs`"
Please run 
exit 1
```

After the `Makefile` update:
```
➜ make check-yarn-bug-1882
Your version of yarn is affected by https://github.com/yarnpkg/berry/issues/1882
Please run `sed -i -e s/3155328e5/4567890e5/g .yarn/releases/yarn-*.cjs`
```

(both are still exiting with `1`)

**Review by JLHwung — APPROVED** [review]

**Review by existentialism — APPROVED** [review]

**Pull request merged**
