### PR TITLE
Get React.Element#$$typeof from an element instead of inlining it.

### LINKED ISSUE #2517: react.inlineElements breaks on older browsers when ignoring node_modules
Generally, when using babel / `babel-loader` it is common to ignore `node_modules` for faster compilation speed.

The definition of the `$$typeof` attribute we're looking for is:

```js
var REACT_ELEMENT_TYPE = typeof Symbol === 'function' && Symbol['for'] && 
                         Symbol['for']('react.element') || 0xeac7;
```

And this is pushed into a shared module that exports it when using the `react.inlineElements` transform.

Here's the problem:

On older browsers that don't support `Symbol`, like Safari 7 / Chromium 30, `Symbol` is polyfilled by the core-js runtime. But the same definition of `REACT_ELEMENT_TYPE` is present inside `node_modules/react/lib/ReactElement.js`, and this is *not* polyfilled by oore-js and therefore equals `0xeac7`.

This causes the element test to fail on render (comparing a shimmed Symbol to `0xeac7`) and breaks the render on those browsers.

I propose, rather than redefining `REACT_ELEMENT_TYPE` directly so it can be used in the inline elements (and thus having it break if upstream ever changes it), let's just instantiate an element and export its `$$typeof`.

### PR DESCRIPTION
**Pull request by STRML**
Fixes #2517; Symbol polyfill could break the element check.

### CODE REVIEW

**Comment by sebmck** [comment]
Not everyone uses CommonJS.

**Comment by STRML** [comment]
Alright, what would you suggest to fix the problem?

**Comment by sebmck** [comment]
You should be using the global polyfill.

**Comment by STRML** [comment]
I think this optimisation is really going to bite users if we simply require them to use the global polyfill - that would need to be a big bold caveat in the docs when using it. And worse, it'll look like it's working in development but will break in production.

Since it only works on JSX elements which assume the presence of React anyway, it almost seems safe to do `React.createElement('div').$$typeof`, except that this would break when using the optional helpers build. Not sure how to proceed.

**Comment by sebmck** [comment]
The current behaviour is pretty expected. The entire point of the runtime transformer is to make a separate isolated environment. Thus it should not be expected to work with another separate environment/context.

**Comment by STRML** [comment]
This seems extremely error-prone. So, in the future, when bundling for browsers, we should be expected to run babel on all our dependencies (very slow) as well to ensure the environment is consistent, OR use the global polyfill. Otherwise, unexpected conflicts will happen with browsers that don't or partially implement ES6.

In that case, Babel should require using the global polyfill (or come with a gigantic warning).

**Comment by loganfsmyth** [comment]
Maybe I'm just missing something, but is anything gained by having this in a helper anyway? It's so short that it's almost in par with the number of characters in the helper function name, and it'll be way less if you're using `runtime`.

As a side question, wouldn't it make sense for React to just expose a `React.fromObject` function to hide these implementation details? The fact that Babel needs to know anything about this symbol seems weird to me.

**Comment by STRML** [comment]
Agreed @loganfsmyth , this would be a significant improvement.

**Comment by sebmck** [comment]
Let's keep the discussion to #5138 please. It's hard to keep track of discussion across multiple issues.

**Comment by STRML** [comment]
Sure - I'm going to close this and keep #2517 open to track implementation of whatever happens in #5138.

**Pull request closed without merging**
