### PR TITLE
Add LICENSE file to the published npm packages (upgrade lerna to v3.0.3)

### PR DESCRIPTION
**Pull request by opichals**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            |  Licensing
| Patch: Bug Fix?          | No
| Major: Breaking Change?  | No
| Minor: New Feature?      | No
| Tests Added + Pass?      | No
| Documentation PR Link    | No
| Any Dependency Changes?  | `lerna 3.0.3`
| License                  | MIT

This fixes the 'missing LICENSE file in the published npm packages' issue being discussed in the pending https://github.com/babel/babel/pull/8409 but in a way which was suggested in the PR https://github.com/babel/babel/pull/8409#issuecomment-409255743

### CODE REVIEW

**Comment by opichals** [comment]
@xtuc Sure, done.

**Comment by opichals** [comment]
Updated to the up0-to-date `lerna v3.0.3`.

**Comment by hzoo** [comment]
Done in https://github.com/babel/babel/pull/8409

**Comment by char0n** [comment]
Thanks @hzoo

**Pull request closed without merging**
