### PR TITLE
Allow --inspect-brk option to be used with babel-node [6.x backport]

### PR DESCRIPTION
**Pull request by noinkling**
Backport of #5785

### CODE REVIEW

**Comment by jridgewell** [comment]
This should be the `master` branch, right?

**Comment by existentialism** [comment]
Derp, yep... good catch, let's retarget.

**Comment by existentialism** [comment]
@noinkling didn't want to force push on to your 6.x branch, mind retargeting?

**Comment by noinkling** [comment]
Sorry my git fu isn't great, how would I go about that?

I don't care what happens to that 6.x branch if it matters.

**Comment by noinkling** [comment]
I'll try again :D

**Pull request closed without merging**
