### PR TITLE
Proper arity for asyncToGenerator calls.

### LINKED ISSUE #1618: asyncToGenerator transformer always returns function with 0 length.
some frameworks (such as mocha) checks function length (parameters count), but if i used asyncToGenerator it transforms my code to
```javascript
before(_asyncToGenerator(function* (done) {
}));
```
where result of _asyncToGenerator will be babel's helper function:
```javascript
function () { var gen = fn.apply(this, arguments); 
```
it's length always 0.
need to transpile code to something like this:
```javascript
before(function(done) {
    _asyncToGenerator(function* (done) {
    }).apply(this, arguments);
});
```
then will be work fine.

### PR DESCRIPTION
**Pull request by cb1kenobi**
asyncToGenerator() returns a function has no explicit arguments and thus it has a length of zero. This is problematic since you should be able to get the length of a async function. Regenerator works correctly.

Fixes #1618

### CODE REVIEW

**Comment by cb1kenobi** [comment]
@sebmck Can you give me some guidance on this PR please? My changes fix my use case, but I'm not sure I went about it correctly or completely. Any feedback appreciated! Thanks!

**Comment by loganfsmyth** [comment]
Two downsides that I can see with this:

1. You recreate the generator function on each call, so it won't optimize well. Seems like we'd want to split it out into a separate scope.
2. `.bind` is very slow compared to a normal function call. What is the motivation for the `.bind` call in this case?

**Comment by cb1kenobi** [comment]
@loganfsmyth Hmm, doesn't it always create a generator function on each call?

I've got 2 test cases. The first one is pretty simple:

```javascript
function baz(expected, fn) {
	if (expected === fn.length) {
		console.log('worked');
	} else {
		console.log('expected ' + expected + ', got ' + fn.length);
	}
}

baz(1, async (a) => {});
baz(2, async (a, b) => {});
baz(3, async (a, b, c) => {});
baz(4, async (a, b, c, d) => {});
```

```bash
$ babel-node test.js
worked
worked
worked
worked
$ babel-node --optional asyncToGenerator test.js
expected 1, got 0
expected 2, got 0
expected 3, got 0
expected 4, got 0
```

If we look at the generated code, we see the Regenerator version wraps the `regeneratorRuntime.async()` call in a function with the correct params:

```javascript
baz(1, function callee$0$0(a) {
	return regeneratorRuntime.async(function callee$0$0$(context$1$0) {
		while (1) switch (context$1$0.prev = context$1$0.next) {
			case 0:
			case 'end':
				return context$1$0.stop();
		}
	}, null, _this);
});
baz(2, function callee$0$0(a, b) {
	return regeneratorRuntime.async(function callee$0$0$(context$1$0) {
		while (1) switch (context$1$0.prev = context$1$0.next) {
			case 0:
			case 'end':
				return context$1$0.stop();
		}
	}, null, _this);
});
```

The asyncToGenerator version does not:

```javascript
baz(1, _asyncToGenerator(function* (a) {}));
baz(2, _asyncToGenerator(function* (a, b) {}));
baz(3, _asyncToGenerator(function* (a, b, c) {}));
baz(4, _asyncToGenerator(function* (a, b, c, d) {}));
```

My changes wrap the `_asyncToGenerator()` call just like the Regenerator version:

```javascript
baz(1, (function (a) {
    return _asyncToGenerator(function* (a) {}).apply(this, arguments);
}).bind(this));
baz(2, (function (a, b) {
    return _asyncToGenerator(function* (a, b) {}).apply(this, arguments);
}).bind(this));
```

And when run, it see:

```bash
$ node dist/src/test.js
worked
worked
worked
worked
```

Then I found another problem. Turns out you can't simply wrap `_asyncToGenerator()`. I found a use case in which I had a class `Foo` with a method `bar` returning an async function that used an arrow function and the spread operator. The `this` scope wasn't properly applied.

```javascript
class Foo {
	constructor() {
		this.name = 'baz';
	}

	bar() {
		return async (...args) => {
			return this.name;
		};
	}
}

let foo = new Foo();
let wiz = foo.bar();

wiz().then((name) => {
	if (name === 'baz') {
		console.log('worked');
	} else {
		console.log('expected baz, got', name);
	}
});
```

With regenerator and async-to-generator before my changes it worked. I looked the generated wrapper code and I saw:

```javascript
<snip>
	_createClass(Foo, [{
		key: 'bar',
		value: function bar() {
			return function () {
				var _this = this;

				for (var _len = arguments.length, args = Array(_len), _key = 0; _key < _len; _key++) {
					args[_key] = arguments[_key];
				}

				return _asyncToGenerator(function* () {
					return _this.name;
				}).apply(this, arguments);
			};
		}
	}]);
<snip>
```

The spread operator was creating `var _this = this;` in the wrong scope. Once I added a `bind()` to the wrapper, it worked:

```javascript
<snip>
	_createClass(Foo, [{
		key: 'bar',
		value: function bar() {
			return (function () {
				var _this = this;

				for (var _len = arguments.length, args = Array(_len), _key = 0; _key < _len; _key++) {
					args[_key] = arguments[_key];
				}

				return _asyncToGenerator(function* () {
					return _this.name;
				}).apply(this, arguments);
			}).bind(this);
		}
	}]);
<snip>
```

I agree that the bind is not great. I'm not sure of a better way to handle this. I suppose detect if the function being wrapped by `_asyncToGenerator()` is an arrow function and if so, use an arrow function instead of a normal function? Would Babel then move the `var _this = this;` to the correct scope? If so, then I could remove the `bind()`.

Maybe I should look at how the Regenerator version is constructed and copy that? I don't like that my generated version doesn't have named functions and that it wraps it with parenthesis.

And what about the use case when the async function is being assigned to a variable? (https://github.com/cb1kenobi/babel/blob/asyncToGenerator_fix/packages/babel/src/transformation/helpers/remap-async-to-generator.js#L67-L73) Maybe I should move the wrapper outside the if block.

What do you think? Any guidance is greatly appreciated, thank you!

**Comment by sebmck** [comment]
I merged the 6.0 branch into `master` and it messed up all pull requests. This PR isn't applicable to 6.0 anyway since this is actually the behaviour of it now.

**Pull request closed without merging**
