### PR TITLE
Add a general JSX transform package

### PR DESCRIPTION
**Pull request by calebmer**
Currently, Babel only supports the special React flavor of JSX. This flavor deviates a couple of ways from the [JSX](https://facebook.github.io/jsx/) spec. First, the React version accepts pascal-cased variable names for element identifiers (think `<App/>`). Second, the React version requires a function to construct JSX objects. The JSX spec is a wonderful specification and a general implementation which does not do these things would be amazing.

This pull request aims to provide just that general JSX transformation. Instead of requiring a function, this package will generate plain objects which can be processed later.

For example, the following JSX (from the [spec](https://facebook.github.io/jsx/)):

```jsx
var dropdown = (
  <Dropdown>
    A dropdown list
    <Menu>
      <MenuItem>Do Something</MenuItem>
      <MenuItem>Do Something Fun!</MenuItem>
      <MenuItem>Do Something Else</MenuItem>
    </Menu>
  </Dropdown>
);
```

Will roughly be transformed to the following:

```js
var dropdown = {
  element: 'Dropdown',
  attributes: {},
  children: [
    'A dropdown list',
    {
      element: 'Menu',
      attributes: {},
      children: [
        {
          element: 'MenuItem',
          attributes: {},
          children: ['Do Something']
        },
        {
          element: 'MenuItem',
          attributes: {},
          children: ['Do Something Fun!']
        },
        {
          element: 'MenuItem',
          attributes: {},
          children: ['Do Something Else']
        }
      ]
    }
  ]
};
```

#### Implementation
I haven‘t looked at a lot of the babel package‘s source code, however I get the feeling that this package is written in a much different style then the rest. I hope that‘s not an issue. The style is basically a pseudo-functional JavaScript one. I found that was the easiest for myself and others to understand. When implementing. I stuck very close to [the spec](https://facebook.github.io/jsx/) (why wouldn't I?) so most of the functions assume that contract (as any implementation would).

* * *

I would prefer this not be a user land module as it seems a general implementation is needed to balance the React implementation, and I really don't want to implement a build/test framework 😊. If for some political reason it may not be merged, I will probably publish this code independently.

JSX has a lot of possibilities outside the React ecosystem. Therefore I urge the babel team to consider supporting a general implementation of JSX.

### CODE REVIEW

**Comment by calebmer** [comment]
I‘m not entirely sure why the tests are failing with a message of: `Error: Cannot find module 'babel-runtime/helpers/interop-require-default'`.

**Comment by loganfsmyth** [comment]
@calebmer Can't comment on this at the moment, but the tests are failing because all Babel plugins should depend on `babel-runtime@5.x`

**Comment by sebmck** [comment]
Is there a reason this needs to be in core instead of a third party package?

**Comment by sebmck** [comment]
Looks like `babel-plugin-transform-react-inline-elements` basically does what you want.

 - https://github.com/babel/babel/tree/master/packages/babel-plugin-transform-react-inline-elements
 - https://babeljs.io/docs/plugins/transform-react-inline-elements/

**Comment by sebmck** [comment]
There's also the third party/community [babel-plugin-jsx](https://github.com/OpenJSX/babel-plugin-jsx) which compiles to [JSX-IR](https://github.com/OpenJSX/spec) by @NekR.

**Comment by thejameskyle** [comment]
I don't really have a "political" objection to this, but I reject the idea that this is a "general JSX transformation". This is just _another_ way of compiling JSX down. As such it does not make sense to have this in core, that's just putting the burden on Babel contribs instead.

**Comment by calebmer** [comment]
@sebmck
> Looks like `babel-plugin-transform-react-inline-elements` basically does what you want…There's also the third party/community babel-plugin-jsx which compiles to JSX-IR by @NekR.

Thanks for referencing the implementations, and indeed both capture the basic idea of this package. However there are a couple of things which make them non-ideal.

With the react implementation, it is still designed around the react contract. It transforms JSX in a couple of non-intuitive ways optimized for that library. First it moves the children nodes into props, second it moves `key` and `ref` properties to weird places, and third it adds the `$$typeof` property which explicitly implies react is a dependency.

As for @NekR's plugin, it has not yet been updated for babel 6. However, on principle either @NekR's implementation or mine, this concept should really be included in babel core.

> Is there a reason this needs to be in core instead of a third party package?

The main benefits I see is for, babel as a tool, JSX as a standard, the JavaScript community, and myself as a package author. Here's a further explanation:

- Firstly, it would balance the react implementation in babel. JSX is an open standard and if there is going to be a library specific implementation, there should also be another general implementation. To me this seems fair, correct me if I'm missing something.
- Helps build a develop JSX as an open standard. With a high quality implementation maintained by babel contributors, JSX has the ability to grow and mature as an open standard for the entire JavaScript community.
- Create a definitive transformation for the entire JavaScript community. Currently there is division (as you have seen) on the JSX implementation. Do you use a pragma, do you 
- Kind of silly, but building/testing framework (so nice to not have to write my own for once 😊).

* * *

@thejameskyle

> I reject the idea that this is a "general JSX transformation". This is just another way of compiling JSX down.

I agree that this is another way to compile JSX down. However, it is the most idiomatic, open, and dare I say general transformation out there. If you look at the [JSX](https://facebook.github.io/jsx) spec you will see that a `JSXElement` is (roughly) composed of `JSXElementName`, `JSXAttributes`, and `JSXChildren`. That translates *exactly* to the three keys of this transformation `elementName`, `attributes`, and `children`.

This is why I consider this implementation to be general, idiomatic, and more open then any other on the market.

> As such it does not make sense to have this in core, that's just putting the burden on Babel contribs instead.

I hope my justification above makes the (hopefully) small amount of time contributors spend maintaining this package worth the benefits, however I also don't plan on leaving this package alone. If this gets merged and a bug is found, I'd be happy to be notified and I would fix it, taking as much burden as possible off of core contributors. While the rest of babel code is a little hard for me to penetrate, I would be honored to take responsibility for all problems arising if this package gets into core.

**Comment by thejameskyle** [comment]
> I hope my justification above makes the (hopefully) small amount of time contributors spend maintaining this package worth the benefits, however I also don't plan on leaving this package alone. If this gets merged and a bug is found, I'd be happy to be notified and I would fix it, taking as much burden as possible off of core contributors. While the rest of babel code is a little hard for me to penetrate, I would be honored to take responsibility for all problems arising if this package gets into core.

The problem here is that to end users there is no benefit of having this in core, it gets consumed in exactly the same way. The only difference is the burden of maintenance that is placed on the core team. 

If you pull it into your own repo, we don't need to notify you, and if you don't maintain it then it goes away.

**Comment by calebmer** [comment]
@thejameskyle Well my honest question is are there any benefits to having the react modules in core? Or stage 0 proposals, or minification plugins? If so why don't those benefits apply to having this module in core?

I completely understand the reasoning, but from an outsiders perspective it is very hard to see the filter process for deciding which modules go to core.

Basically the only thing I (as an outsider) see is that the babel core package is the definitive implementation. And that's something frameworks wanting to use JSX (like [cycle](http://cycle.js.org), [mercury](https://www.npmjs.com/package/mercury), or [yolk](https://www.npmjs.com/package/yolk)) without the react contract really need.

**Comment by thejameskyle** [comment]
They were starting to get moved out of the repo initially, but they are only in the repo today because it simplifies the build process of managing many plugins.

But we don't want to maintain every Babel Plugin out there (that would be absurd), certainly not ones that don't have an active users like this one.

**Comment by calebmer** [comment]
Is there anyone who agrees this should be in babel core or thinks that it at least warrants more discussion? I strongly believe it has a place here, but if no one agrees I'll just go and publish it to NPM.

**Comment by TrejGun** [comment]
:+1:

**Comment by kittens** [comment]
There's already [babel-plugin-jsx](https://github.com/OpenJSX/babel-plugin-jsx) which doesn't really get a lot of use. There doesn't seem to be much demand for this that justifies bringing it into core.

**Comment by NekR** [comment]
Please put everyone module into core. Sure you should!

**Comment by amasad** [comment]
@calebmer this is really cool and well-written, I encourage you to publish it to npm and on your github page. We're trying to make core as small as possible (it's already a big hassle maintaining and releasing all these plugins) -- to your point about the minifier plugin we actually removed them from core and will be releasing them as a separate project.

**Comment by calebmer** [comment]
Alright, wish this could have gotten merged into core. It's been published [here](https://www.npmjs.com/package/babel-plugin-transform-jsx) for anyone with an interest in using it.

**Pull request closed without merging**
