### PR TITLE
Fix the issue #6331

### LINKED ISSUE #6331: do-expression support for catch
Choose one: is this a bug report or feature request? bug

I expect this to work:
```js
const foo = () => do { throw new Error('foo'); };
const bar = () => 3;
const res = do {
  try { foo(); } catch (e) { bar(); }
}
console.log(res); // 3;
```

But I get `undefined`;

babel transpiles to:
```js
const foo = () => function () {
  throw new Error('foo');
}();
const bar = () => 3;
const res = function () {
  try {
    return foo();
  } catch (e) {
    bar();
  }
}();
console.log(res); // 3;
```

but I expected:

```js
const foo = () => function () {
  throw new Error('foo');
}();
const bar = () => 3;
const res = function () {
  try {
    return foo();
  } catch (e) {
    return bar();
  }
}();
console.log(res); // 3;
```

an alternative that works is:
```js
const foo = () => do { throw new Error('foo'); };
const bar = () => 3;
const res = do { try { foo(); } catch (e) {} } || bar();
console.log(res); // 3;
```

see https://github.com/tc39/proposal-do-expressions/issues/6

### PR DESCRIPTION
**Pull request by wcastand**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues              | Fixes #6331 
| Patch: Bug Fix?          | y
| Major: Breaking Change?  | n
| Minor: New Feature?      | n
| Tests Added/Pass?        | y
| Spec Compliancy?         | y/n
| License                  | MIT
| Doc PR                   | 
| Any Dependency Changes?  | 

Maybe we need more tests if there is other cases, i'm not sure what are the possibilities about a catch in a do expression.
I'm not sure if i need to make a PR to the test branch or to do thing differently.

### CODE REVIEW

**Comment by existentialism** [comment]
@wcastand awesome! thanks for the PR!

Mind adding the test from https://github.com/babel/babel/pull/6361 and rebasing so https://github.com/babel/babel/pull/6372/commits/9cd4716cb45d90730025d954539bb9a970c10c65 isn't included?

**Comment by hzoo** [comment]
Yeah `git rebase master` and push that (I see you aren't on a branch either, can do that next time if you have multiple PRs)

**Comment by wcastand** [comment]
I still need to do something or we just review now ? :)
( not rushing, just want to be sure i didn't forget something :) )

**Comment by hzoo** [comment]
@nicolo-ribaudo probably not then? Either way we should have a traverse test for the code.

We can make some new issues for each function, could possibly be beginner friendly

**Comment by hzoo** [comment]
Ok we should make a test case for `finally` then. How would that work? Does it only return the finally?

**Comment by nicolo-ribaudo** [comment]
@hzoo I've made https://github.com/babel/babel/issues/6385 to track `finally` behavior

**Comment by wcastand** [comment]
Si we'll add the tests for finally on the PR for issue #6385 ?

**Comment by nicolo-ribaudo** [comment]
Actually I think the current behavior with finally is wrong

**Pull request merged**
