### PR TITLE
Fix: Add parens for unary arrow function

### PR DESCRIPTION
**Pull request by hzoo**
Fixes T7157

http://phabricator.babeljs.io/T7157

Not sure where to change so just doing this as a start (could modify `UnaryLike`, etc)

Feel free to commit to fix @amasad

### CODE REVIEW

**Comment by loganfsmyth** [comment]
Looks good to me.

**Comment by hzoo** [comment]
What about how we do ` UnaryLike(node, parent)` right below my change?

**Comment by loganfsmyth** [comment]
To me at least, your approach seems more consistent with the rest of the file.

**Comment by hzoo** [comment]
Oh I should probably look at what UnaryLike actually is lol - (rest/spread)

**Comment by amasad** [comment]
:+1:

**Pull request merged**
