### PR TITLE
Fix parens detection for object&function in `as`/`satisfies`

### PR DESCRIPTION
**Pull request by nicolo-ribaudo**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes https://github.com/babel/babel/pull/16617#issuecomment-2229847992
| Patch: Bug Fix?          |
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

I will also open a PR to avoid having to manually list all the case in `isFirstInContext`, but for now lets fix the regression the simple way.

### CODE REVIEW

**Review by liuxingbaoyu — APPROVED** [review]

**Comment by nicolo-ribaudo** [comment]
@cpojer I'll release this soon :)

**Comment by cpojer** [comment]
Thank you!

**Comment by zachbwh** [comment]
Legendary! Thanks folks :)

**Comment by ArnaudBarre** [comment]
@nicolo-ribaudo I'm not sure if this normal but I think the v7.24.10 was no published to npm? A entry was added to the changelog and a git tag was added but nothing on npm or GH releases

**Comment by JLHwung** [comment]
> @nicolo-ribaudo I'm not sure if this normal but I think the v7.24.10 was no published to npm? A entry was added to the changelog and a git tag was added but nothing on npm or GH releases

`@babel/generator@7.24.10` was published, see https://www.npmjs.com/package/@babel/generator.

If you are using a lock file, you can try to remove `@babel/generator` from the lock file and run install again, your package manager should pick up the latest update.

**Comment by ArnaudBarre** [comment]
Oh sorry I looked at the core version that's why. Thanks!

**Pull request merged**
