### PR TITLE
Add tests for util.booleanify

### PR DESCRIPTION
**Pull request by arthurvr**
Ref https://github.com/babel/babel/pull/1724

### CODE REVIEW

**Comment by arthurvr** [comment]
Any update on this one?

**Comment by sebmck** [comment]
Sorry, been taking a break from things. Thanks!

**Comment by arthurvr** [comment]
@sebmck No problem! Thanks for the awesome work! PR welcome with tests for some other functions?

**Comment by sebmck** [comment]
That’d be great!

**Pull request merged**
