### PR TITLE
Make plugin instantiation unobservable

### PR DESCRIPTION
**Pull request by kittens**
Not to be merged unless it becomes problematic/common. Dunno if this will work, haven't tested it.

### CODE REVIEW

**Comment by amasad** [comment]
context?

**Comment by kittens** [comment]
https://github.com/developit/modify-babel-preset

**Comment by loganfsmyth** [comment]
I don't think we should do this. It's fighting a losing battle and it doesn't seem like we actually gain anything. Modules are cached and that's just how it is. Presets are executable code, so for all we know, there's a preset out there that relies on caching.

This is still trivially work-aroundable by having your `main` just do `module.exports = require('./lib/index');` so the module having its cache cleared will still be identical.

**Comment by loganfsmyth** [comment]
@kittens I'm going to close this so it doesn't just sit here, but we'll have it if we need to refer to it.

**Pull request closed without merging**
