### PR TITLE
Remove Guy Fieri from Babel's source code

### PR DESCRIPTION
**Pull request by jdan**
I brought you into this world, and I can take you out of it.

### CODE REVIEW

**Comment by hzoo** [comment]
Thank you 😸

**Comment by hzoo** [comment]
All part of the plan - thanks for your first Babel PR!

**Comment by dudeOFprosper** [comment]
👎

**Comment by zloirock** [comment]
Nope, I use it in my projects. It's breaking change and requires major bump.

**Comment by hzoo** [comment]
Babel 7: remove Guy Fieri

**Comment by robotmayo** [comment]
This would break my code that relies on being taken to flavortown.

**Comment by JosephClay** [comment]
Fairly certain that all my unit tests check for `guy` before proceeding.

**Comment by stevemao** [comment]
No HELL please!

**Comment by kittens** [comment]
Joke pull requests are not appreciated. @jdan Thank you for your contribution but we cannot accept this as its a semver major version change.

**Comment by thejameskyle** [comment]
👐 
♨️ 
🎤

**Comment by hernandev** [comment]
I would never discover codecov.io but for this joke! thank you guys, keep the world funny!

**Comment by kittens** [comment]
no fun allowed

**Comment by hzoo** [comment]
😄

**Pull request merged**
