### PR TITLE
Enable optional chaining and nullish coalescing plugins

### PR DESCRIPTION
**Pull request by nicolo-ribaudo**
| Q                        | A 
| ------------------------ | ---
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

They are both stage 3, and they are used in a few PRs (e.g. https://github.com/babel/babel/pull/10491, https://github.com/babel/babel/pull/10357)

### CODE REVIEW

**Comment by nicolo-ribaudo** [comment]
Well, they aren't shipped anywhere yet :stuck_out_tongue: 

https://kangax.github.io/compat-table/esnext/#test-optional_chaining_operator_(?.)

**Comment by mrtnzlml** [comment]
@nicolo-ribaudo It's also a good idea to enable this lint rule to make sure it's used correctly: [unnecessary-optional-chain](https://flow.org/en/docs/linting/rule-reference/#toc-unnecessary-optional-chain)

Just a small tip 🍻 :)

**Comment by jsg2021** [comment]
> Nice! Should we add these to preset-env shippedProposals eventually? Not sure how many people are using that anyway though

I use `shippedProposals` 😉

**Comment by nicolo-ribaudo** [comment]
Spoiler: given that we release a new minor about every 2 months, probably `shippedProposals` won't be the correct place for at least one of them 😉

**Pull request merged**
