### PR TITLE
chore: bump minimist from 1.2.5 to 1.2.6

### PR DESCRIPTION
**Pull request by fargito**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            |
| Patch: Bug Fix?          |
| Major: Breaking Change?  | No
| Minor: New Feature?      | No
| Tests Added + Pass?      | No
| Documentation PR Link    | No
| Any Dependency Changes?  | Yes
| License                  | MIT

Hello and thanks for your time! 

A [security issue](https://security.snyk.io/vuln/SNYK-JS-MINIMIST-2429795) has been created for minimist@1.2.5, I believe that 1.2.6 fixes it, so I bumped the depenedency.

Also check out the documentation in minimist: https://github.com/substack/minimist#security

Also json5 [removed its minimist dependency](https://github.com/json5/json5/releases/tag/v2.2.1), so I also updated the dependency

Thanks a lot!

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/14382"></a>

### CODE REVIEW

**Review by JLHwung — APPROVED** [review]
Thanks!

**Comment by fargito** [comment]
@JLHwung I also bumped json5 which removed its dependency to minimist

**Review by existentialism — APPROVED** [review]

**Comment by fargito** [comment]
@existentialism @JLHwung the tests fail on Windows, but it is already the same on main, is it an issue that I need to fix?

**Comment by existentialism** [comment]
@fargito reran it, you're good!

**Pull request merged**
