### PR TITLE
install polyfill & runtime to dependency instead of devDependency [skip ci]

### PR DESCRIPTION
**Pull request by spondbob**
as per doc:
- https://babeljs.io/docs/en/next/babel-polyfill.html#installation
- https://babeljs.io/docs/en/next/babel-runtime.html#usage

| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | No
| Patch: Bug Fix?          | No
| Major: Breaking Change?  | No
| Minor: New Feature?      | No
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  | No
| License                  | MIT

### CODE REVIEW

**Comment by nicolo-ribaudo** [comment]
Oh right, it needs to be special-cased in that script

**Comment by spondbob** [comment]
Thanks for mentioning the script, sorry did not realize one exists!

I'll try to play around with the script see what I can come up with. It's just got a long weekend down here.

**Comment by spondbob** [comment]
Managed to update the script so that it will print `npm install --save package` and `yarn add package` for `@babel/polyfill` and `@babel/runtime`.

Also found `@babel/helper-create-class-features-plugin` was written as `@babel/plugin-class-features` think that might be a typo?

**Comment by nicolo-ribaudo** [comment]
> Also found @babel/helper-create-class-features-plugin was written as @babel/plugin-class-features think that might be a typo?

Yeah, it was the old name.

**Comment by existentialism** [comment]
@spondbob thanks!

**Pull request merged**
