### PR TITLE
Remove duplicate keys from alias-keys.json

### LINKED ISSUE #1734: Duplicate Object Key in alias-keys
The key `JSXEmptyExpression` is duplicated in `alias-keys.json`. This file is converted to JavaScript in browserification, and evaluating _that_ source in strict mode causes an exception to be thrown. 

https://github.com/babel/babel/blob/8055ce29f7dbbc8564087f01fa11a34d9d258a33/src/babel/types/alias-keys.json#L79

https://github.com/babel/babel/blob/8055ce29f7dbbc8564087f01fa11a34d9d258a33/src/babel/types/alias-keys.json#L119

### PR DESCRIPTION
**Pull request by grncdr**
Fixes #1734

### CODE REVIEW

**Comment by hzoo** [comment]
Would you want to put "Expression" back in?

`"JSXMemberExpression":    ["JSX", "Expression"],` and same for `JSXEmptyExpression`

**Comment by grncdr** [comment]
No, that would be a change in behaviour. Most (all?) implementations of `JSON.parse` follow a "last write wins" policy for duplicate keys, I just want the babel code to parse in strict mode.

**Comment by sebmck** [comment]
@grncdr No, he's saying to put back in the previous values.

**Comment by grncdr** [comment]
I feel extra dense, but as far as I can tell the previous values are still there?

[These lines](https://github.com/grncdr/babel/blob/patch-1/src/babel/types/alias-keys.json#L117-L120) are untouched from [these ones](https://github.com/grncdr/babel/blob/26924d59443992a736eeaad2f3c8407513209959/src/babel/types/alias-keys.json#L119-L122). Being that the later lines _redefine_ the values in the object, this change does not alter the result of JSON.parse'ing the file.

**Comment by sebmck** [comment]
Even though the `Expression` value was having no effect because it was being shadowed, it should still be included in the subsequent arrays.

**Comment by grncdr** [comment]
> Even though the Expression value was having no effect because it was being shadowed, it should still be included in the subsequent arrays.

I don't understand what this file is even doing (other than causing the parsing issue in #1734), so I'm not seeing any reason to change the data it contains. If it's important that `"Expression"` ends up in the resulting array, then I'd rather do that as a separate PR.

**Comment by sebmck** [comment]
It is important that it ends up in the resulting array and it's an oversight that it's not. It'd be much quicker and easier for everyone involved to just do it in the same PR.

**Comment by grncdr** [comment]
> It is important that it ends up in the resulting array and it's an oversight that it's not. It'd be much quicker and easier for everyone involved to just do it in the same PR.

Fair enough. I hope I'm not being too picky, I'm just not comfortable making changes in a project as widely used as babel without having any idea *why* I'm making them. :wink:

**Comment by sebmck** [comment]
All good, thanks! To give more context which I should have done to begin with, the `alias-keys` file lists all the "subtypes" of a certain node type. In this case, the node `JSXMemberExpression` should be of the type `Expression` as they're treated differently when you try and do transformations on them.

**Comment by grncdr** [comment]
Ah cool, thanks for explaining it to me. (and thanks for babel! It's really great!)

**Pull request merged**
