### PR TITLE
API docs for babel-traverse/types

### PR DESCRIPTION
**Pull request by thejameskyle**
Just opening this up with what I have right now. I'm going to change this in the future to convert to JSON and then format it exactly the way we want it. At which point we can clean up a lot of weird things in this PR like `@name` and how class members are documented.

### CODE REVIEW

**Comment by thejameskyle** [comment]
Also, I intentionally left jsdoc comments for every method in these two packages in order to make sure that the correct methods are always documented. ie. It could be easy to add a `/** */` comment above a private function and suddenly it shows up in the docs (trying to address this over here: https://github.com/documentationjs/documentation/issues/262)

**Comment by sebmck** [comment]
I'm vehemently against having description placeholders. Nobody actually filled in the previous descriptions and it added a ton of clutter. Just them not existing should be reminder enough to fill them in later.

**Comment by thejameskyle** [comment]
I plan on getting rid of the private placeholders once documentation js supports hiding unmarked docs by default. But I do want to mark all the methods we intend on being public.

**Comment by thejameskyle** [comment]
Also, the `@name`-ing was temporary until I switch to generating JSON to HTML for the website where I can programmatically set the name. I wanted some markdown I could link to in the meantime

**Comment by sebmck** [comment]
Any update? Want to clear the PR queue.

**Comment by thejameskyle** [comment]
I was waiting for them to publish a new release of documentation js, but I'll work on this today

**Comment by amasad** [comment]
ping

**Comment by schmod** [comment]
If I can add my $0.02, I'd love to see this merged soon.

If documentationjs is holding things up, we could start by merging the js annotations (where we have them) for now.  Having some inline documentation is still vastly superior to having no documentation at all, and gets the ball rolling for others to make contributions.

**Comment by tmcw** [comment]
there's a beta of documentation.js 4.x out, which I think fixes the issue that was blocking this. It still isn't updated to babel 6 - I'm trying to squirrel enough time to make the upgrade but it's proving to be extremely difficult, and free time is pretty scarce.

**Comment by charltonaustin** [comment]
@tmcw Hey I don't mind helping out. What can I do to get this moving along?

**Comment by tmcw** [comment]
documentation.js is updated to babel 6.x, and I'm happy to pick up this task. Babel's a great testcase for making sure documentation.js performs well with sophisticated code.

**Comment by hzoo** [comment]
Closing for now

**Pull request closed without merging**
