### PR TITLE
Add `proposal-unicode-sets-regex` to `@babel/standalone`

### PR DESCRIPTION
**Pull request by nicolo-ribaudo**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            |
| Patch: Bug Fix?          |
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

We forgot to add this when we added the plugin, it's stage 3 and it would be nice to have it in the repl (cc @mathiasbynens)

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/14697"></a>

### CODE REVIEW

**Comment by nicolo-ribaudo** [comment]
It looks like it doesn't transform :thinking: 
https://babeljs.io/repl/build/52380/#?browsers=chrome%2090&build=&builtIns=false&corejs=3.6&spec=false&loose=false&code_lz=DYUwLgBATiDmIA8AOEC8ED0BtLBDAtAGYC6AZKVgMb4AWxGA3EA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=stage-3&prettier=false&targets=&version=7.18.5%2Bpr.14697&externalPlugins=&assumptions=%7B%7D

**Comment by nicolo-ribaudo** [comment]
It works, I just had a wrong input :slightly_smiling_face: 

https://babeljs.io/repl/build/52380/#?code_lz=DYUwLgBATiDmIA8AOEC8ED0BtLBDAtAGYC6AZKVgMb4AWxxGAbgNxA&presets=stage-3&version=7.18.5%2Bpr.14697

Also, I found a bug in the transform: it fails with `/\p{RGI_Emoji}/v`.

**Comment by nicolo-ribaudo** [comment]
Same time :smile:

**Comment by nicolo-ribaudo** [comment]
@mathiasbynens Why `/x|*️⃣|0️⃣/u` isn't valid? :thinking:

**Comment by nicolo-ribaudo** [comment]
Oh damn, I got it.

Magic :magic_wand: 
`/^x*️⃣?$/u.test("xxxx\uFE0F")` -> `true`

**Comment by macchiati** [comment]
Yup, the keycaps are a pain, because they have 0-9 and * and #

**Review by JLHwung — APPROVED** [review]

**Pull request merged**
