### PR TITLE
fix(helper): update spelling of _assertThisInitialized helper

### PR DESCRIPTION
**Pull request by Haroenv**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | 
| Patch: Bug Fix?          | Yes
| Major: Breaking Change?  | No
| Minor: New Feature?      | No
| Tests Added + Pass?      | No
| Any Dependency Changes?  | No
| License                  | MIT

~~I have not updated the tests yet, since I'm not sure if this is something worth changing. Let me know if it's worth it and I'll clone the repository and update all the tests (28 instances)~~, EDIT: done.

The spelling in the name of the helper is "initialized" (American English), but the text of the error itself said "initialised" (International English). I suggest making both American English, since that's more common in JS

### CODE REVIEW

**Comment by nicolo-ribaudo** [comment]
cc @hzoo @existentialism Native speakers :stuck_out_tongue:

**Comment by JLHwung** [comment]
@Haroenv Could you update the test fixtures?

**Comment by Haroenv** [comment]
Yep, I'll update the tests!

**Comment by Haroenv** [comment]
This is my first time contributing on these things, so I might have replaced too much @JLHwung

**Comment by JLHwung** [comment]
The CI error is not related, I will fix it in a separate PR.

@Haroenv Thank you! It looks good to me.

**Pull request closed without merging**
