### PR TITLE
Transform labeled `for-of` inside braceless `if` statement

### LINKED ISSUE #12610: Labeled for/of loop as brace-less sub-statement crashes
## Bug Report

- [ ] I would like to work on a fix!

**Current behavior**

Code with a labeled `for/of` loop as direct substatement of an `if` crashes Babel.

- [REPL](https://babeljs.io/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&spec=false&loose=false&code_lz=JYMwBAFALgTgrgUwJQCgxgIYGMrAPYB2AzgFxgh4yQA2CUYAHmHuAJ5JgDea6YWhuAokw58xHgF8UQA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Ces2015%2Cstage-2&prettier=false&targets=&version=7.12.12&externalPlugins=),

**Input Code**

```javascript
if (true)
  actions: for (let x of y) {
    continue actions
  }
```

**Expected behavior**

Compilation works.

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**

See the repl link. Only happens when `es2015` is checked.

### PR DESCRIPTION
**Pull request by nicolo-ribaudo**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #12610
| Patch: Bug Fix?          | Yes
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/12611"></a>

### CODE REVIEW

**Review by JLHwung — APPROVED** [review]

**Review by existentialism — APPROVED** [review]

**Comment by NagRock** [comment]
@existentialism 👍 that was really fast! Thanks.

Any info when it will be released on npm repository?

**Comment by nicolo-ribaudo** [comment]
We'll have a minor release before the end of January, but we might release a patch sooner.

**Comment by NagRock** [comment]
Thanks for the info

**Comment by NagRock** [comment]
We still cannot build angular application because of this bug.
@nicolo-ribaudo any update about release?

**Comment by nicolo-ribaudo** [comment]
Released as 7.12.13

**Comment by NagRock** [comment]
@nicolo-ribaudo :yay: !!!

**Pull request merged**
