### PR TITLE
Bring back isPluginRequired

### PR DESCRIPTION
**Pull request by nicolo-ribaudo**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes https://github.com/babel/babel/issues/9707
| Patch: Bug Fix?          | Yes
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

### CODE REVIEW

**Comment by Turbo87** [comment]
@nicolo-ribaudo thanks for reacting on this so quickly! if the Ember CLI can help you test this or get it out quickly please let us know :)

**Comment by nicolo-ribaudo** [comment]
@Turbo87 Since the method hasn't been changed (but only accidentally removed), I don't think that we need anything else :slightly_smiling_face: 
I'll release a new version in ~12 hours, to give people time to report other possible regressions.

**Comment by Turbo87** [comment]
> I'll release a new version in ~12 hours, to give people time to report other possible regressions.

would it be possible to get this out a little quicker? right now, it looks like `ember-cli` and `vue-cli` are not working at all when generating new projects that don't have lockfiles with older `preset-env` versions yet 😢

**Comment by nicolo-ribaudo** [comment]
Done

**Comment by Turbo87** [comment]
awesome, thanks a lot! 😍

**Pull request merged**
