### PR TITLE
Fix printing of comments before `=>`

### LINKED ISSUE #15161: [Bug]: With `comments: false`, babel inserts an extra newline before the `=>` of an arrow function
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@babel/cli

### Input code

```js
var test = (/* placeholder */) => {
  /* Unused */
}
```

### Configuration file name

babel.config.json

### Configuration

```json
{
  "sourceType": "script",
  "presets": ["@babel/preset-env"],
  "comments": false
}
```
Browserslist is set to `["defaults"]`.

### Current and expected behavior

With `comments: false`, the following output is produced:
```js
var test = (
)
=> {
};
```
which is not valid code. With `comments: true`, the following output is produced:
```js
var test = ( /* placeholder */
) => {
  /* Unused */
};
```
which is valid. With `@babel/generator` version `7.20.2` and `comments: false`, the following output is produced:
```js
var test = (
) => {
};
```
which is valid, so this looks like a regression in version `7.20.3` (from https://github.com/babel/babel/pull/15135?).

### Environment

```
System:
    OS: Windows 10 10.0.19044
  Binaries:
    Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
    npm: 8.19.3 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    @babel/cli: ^7.19.3 => 7.19.3
    @babel/core: ^7.20.2 => 7.20.2
    @babel/generator: ^7.20.3 => 7.20.3
    @babel/parser: ^7.20.3 => 7.20.3
    @babel/preset-env: ^7.20.2 => 7.20.2
```

### Possible solution

_No response_

### Additional context

Maybe https://github.com/babel/babel/pull/15160 will also fix this, but there seems to be a gap in testing with `comments: false`.

### PR DESCRIPTION
**Pull request by nicolo-ribaudo**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #15161 
| Patch: Bug Fix?          |
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

This fix conflicts with the fix proposed in https://github.com/babel/babel/pull/15159, however I believe that it solves the problem in a better way: we must keep the correct `_noLineTerminator` to make sure to disallow _any_ multiline comment right before `=>`.

All these cases with multi-line comments before `=>` cannot happen just by parsing+printing the source code, but can happen if plugins modify the AST. It's better to miss printing the comment (or to report an error, as in #15158), but we should never generate invalid code.

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/15160"></a>

### CODE REVIEW

**Comment by liuxingbaoyu** [comment]
This PR looks good to me, can we keep https://github.com/babel/babel/pull/15159/files#diff-6c32c344bfe1f4e77de24cdd3e427e84c4ac0a871380ff3720a7351cac63cb74R197-R198?
In my opinion this is better than being trailing Commens.

**Comment by liuxingbaoyu** [comment]
Oops, these seem to be two different fixes.

**Comment by nicolo-ribaudo** [comment]
Well, we could still keep the new `this.printInnerComments();` call

**Comment by liuxingbaoyu** [comment]
The current `this._noLineTerminator` is automatically set to `false`, which I fear does not completely prevent all line breaks.

Also the output in https://github.com/babel/babel/issues/15161 is weird, it seems like we are wrapping comments for non-existent, it might be worth me to open a PR to optimize.

**Comment by nicolo-ribaudo** [comment]
> The current `this._noLineTerminator` is automatically set to false, which I fear does not completely prevent all line breaks.

It's automatically set to false _after printing a token/word_. [no LineTerminator here] is only between two tokens, so after printing the second one is always safe to set `_noLineTerminator` to false.

**Review by liuxingbaoyu — APPROVED** [review]

**Review by JLHwung — APPROVED** [review]

**Pull request merged**
