### PR TITLE
Update regenerator-transform to version 0.10.0.

### PR DESCRIPTION
**Pull request by benjamn**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues             | none
| Patch: Bug Fix?          | no
| Major: Breaking Change?  | no
| Minor: New Feature?      | no
| Tests Added/Pass?        | no
| Spec Compliancy?         | no
| License                  | MIT
| Doc PR                   | no
| Any Dependency Changes?  | yes

The most notable improvement is that Regenerator now generates code that is easier for tools like Webpack to tree-shake, thanks to work by @modosc and @Andarist: https://github.com/facebook/regenerator/pull/309

### CODE REVIEW

**Comment by benjamn** [comment]
Circle CI is [pretty hosed right now](https://status.circleci.com/), so these tests might have to be restarted later.

**Comment by modosc** [comment]
any chance of getting this backported to the 6.x branch as well? i'd be happy to make the pr

**Comment by hzoo** [comment]
@modosc since got pinged multiple times about another 6.x release that I'm doing now sure 😛 . Not that we don't do backports but the more backports and releases the less focus on 7.x.

**Comment by Andarist** [comment]
@hzoo aint sure how ur git flow works now, but it could be accommodate somehow to ease the pain with backports? especially when in the transition process between latest stable and development alpha/beta/candidates?

maybe adding `backport` labels would help with releasing the newest non breaking changes for the stable version?

**Comment by modosc** [comment]
@hzoo thanks, opened #6111

**Comment by hzoo** [comment]
Will need to fix the fixtures in both

**Comment by hzoo** [comment]
https://github.com/babel/babel/pull/6113 adds the test changes

**Pull request closed without merging**
