### PR TITLE
fixes invalid line offsets in merged sourcemaps

### PR DESCRIPTION
**Pull request by peterm0x**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| Breaking change? | no |
| New feature? | no |
| Deprecations? | no |
| Spec compliancy? | yes |
| Tests added/pass? | yes |
| Fixed tickets | possibly #4788 and others |
| License | MIT |
| Doc PR |  |

Sourcemaps generated from multiple input files have invalid line offsets.

Problem is obvious when one considers 

`> "one line here\n".split("\n").length`
`< 2`

Original tests were comparing results against invalid sourcemaps, which can be readily demonstrated by inspecting them for example by source-map-visualization. Also fixed.

### CODE REVIEW

**Comment by hzoo** [comment]
Didn't know about https://sokra.github.io/source-map-visualization/#custom

screen shot 2016-11-15 at 12 13 37 pm

check line 10/11

**Comment by kangax** [comment]
@hzoo did you test it by uploading a file to this service?

**Comment by hzoo** [comment]
I pasted the test output but I didn't check the op

> Sourcemaps generated from multiple input files have invalid line offsets.

**Comment by hzoo** [comment]
Released in https://github.com/babel/babel/releases/tag/v6.22.0

**Pull request merged**
