### PR TITLE
Add missing semicolons for exports

### PR DESCRIPTION
**Pull request by mathiasbynens**
Since the current style doesn’t rely on ASI, let’s be consistent and always end statements of the form `export [default] foo` with a semicolon.

The CI build fails because [eslint’s no-extra-semi rule incorrectly thinks such semicolons are redundant in some cases](https://github.com/eslint/eslint/issues/4915). This has been patched in eslint, so I guess it’s a matter of bumping the package.

### CODE REVIEW

**Comment by hzoo** [comment]
Thanks for style changes @mathiasbynens - it looks like in that thread that they only added some tests to cover that case. From that it's probably something in babel-eslint that has to be fixed. I'd be ok with turning off the rule in the meantime https://github.com/babel/babel/blob/master/package.json#L67 and then merging?

**Comment by jmm** [comment]
Hello @mathiasbynens, thanks for contributing! However, from skimming this, many (most?) of these cases are not missing a semicolon, according to my understanding.

```js
function x () {};

// Semicolon here is no more necessary than above.
export function y () {};
export default function z () {};
```

The semicolons are redundant in these examples.

If I'm mistaken, please describe how the grammar calls for a semicolon there with spec citations.

Ones like this are missing it, so thank you for correcting those!:

```js
let buildForXStatement = function (op) {}
```

**Comment by mathiasbynens** [comment]
@jmm Where did I add a semicolon to a statement of the form `function x () {}`?

> The semicolons are redundant in these examples.

Depends on your definition of redundant, I guess — the semicolon in this example is “redundant” as well:

```js
const x = 42;
```

…yet, using a semicolon to avoid having to rely on ASI seems to be the coding style for the Babel project, so it should be applied consistently.

As it stands, the source contains things like: 

```js
export let canCompile = util.canCompile;
```

So why would there be no semicolon here?

```js
export function foo () {};
```

Both are `ExportNamedDeclaration`s so why do you think there should be a difference?

**Comment by mathiasbynens** [comment]
@hzoo I’m not sure where the bug is, actually. Babel is currently using eslint v1.8.0 which doesn’t have this bug. So perhaps the issue lies with babel-eslint.

**Comment by jmm** [comment]
@mathiasbynens
> Where did I add a semicolon to a statement of the form `function x () {}`?

You did not. I apologize if it was unclear that that was only to provide comparison to a more familiar production. Are we on the same page that in that case a semicolon would be totally unnecessary?

> Depends on your definition of redundant…yet, using a semicolon to avoid having to rely on ASI seems to be the coding style for the Babel project, so it should be applied consistently.

My definition of redundant is: not required by the grammar, and therefore not subject to ASI, but included in the source.

> As it stands, the source contains things like:

  ```js
  export let canCompile = util.canCompile;
  ```

Which the grammar requires to end in a semicolon, which may be inserted via ASI.


> So why would there be no semicolon here?

  ```js
  export function foo () {};
  ```

Because the grammar doesn't call for it.

Again, if I'm mistaken, please map out how the spec requires a semicolon there.

> Both are `ExportNamedDeclarations` so why do you think there should be a difference?

Because they're different syntactic constructs with different grammar. Please refer to the spec, not the AST types. For that matter, if you're correct, it's not just a linting issue -- Babylon's parsing is broken. Note how [this](http://astexplorer.net/#/TG7JaeQQhb/1) ends with an `EmptyStatement` while [this](http://astexplorer.net/#/TG7JaeQQhb) does not.

**Comment by mathiasbynens** [comment]
@jmm Interesting — all the existing parsers generate `EmptyStatement`s for `export function foo () {};`. However, https://tc39.github.io/ecma262/#sec-automatic-semicolon-insertion explicitly mentions `export` statements:

> Certain ECMAScript statements ([…] `export` declarations […]) must be terminated with semicolons. Such semicolons may always appear explicitly in the source text. For convenience, however, such semicolons may be omitted from the source text in certain situations. These situations are described by saying that semicolons are automatically inserted into the source code token stream in those situations.

**Comment by jmm** [comment]
@mathiasbynens

https://tc39.github.io/ecma262/ is a draft. For the general case it's better to refer to http://www.ecma-international.org/ecma-262/6.0/.

> https://tc39.github.io/ecma262/#sec-automatic-semicolon-insertion explicitly mentions export statements:

That list is merely a hint. If it's omitted the remaining text + grammar productions fully describe the ASI rules (https://github.com/jeffmo/es-class-fields-and-static-properties/issues/25#issuecomment-170081700). Some `export` forms are required to end in a semicolon. These are not:

```js
export function x () {}
export default function x () {}
export default function () {}
```

> Furthermore, table 43 (although purely illustrative) includes the semicolons in its examples: https://tc39.github.io/ecma262/#table-42
>
> (I realize these are not references to the actual grammar, but it’s enough to make me doubt ; is optional there.)

I'll submit a PR for that since it's confusing people. Why look at the spec only to cite a non-normative example though when you could look at the actual grammar and we can clear this up one way or the other? (I have no problem being wrong on this -- I just need to see it.)

**Comment by mathiasbynens** [comment]
> That list is merely a hint. 

Are you saying it’s an incorrect (as in, overgeneralizing) hint?

Reading the grammar I have to agree with you :) I guess those two other entries in the spec (although non-normative) confused me.

I was filing https://github.com/tc39/ecma262/issues/284 while you wrote your reply.

**Comment by jmm** [comment]
@mathiasbynens
> Are you saying it’s an incorrect (as in, overgeneralizing) hint?

Within the past week I've been thinking of PR'ing an update to that to clarify that the list items are just examples and the rules would be fully described with the list omitted. It overgeneralizes a bit by, for example, including `export` in the list, since not all forms of `export` have that requirement. On the other hand, there's not necessarily any guarantee that the list is exhaustive.

The bottom line is that the list is just a hint and you have to look at the grammar for whatever production and the rules to see if it's applicable, but I don't think that's as clear as it could be (within the past week I asked @allenwb for confirmation of that, which he provided). It becomes especially important when considering spec proposals and how semicolons in their grammar need to be interpreted by the reader.

> Reading the grammar I have to agree with you :) I guess those two other entries in the spec (although non-normative) confused me.

I don't blame you :) There's been plenty of confusion about semicolons just recently in https://github.com/babel/babel/pull/3225 and the linked issues.

> I was filing tc39/ecma262#284 while you wrote your reply.

:thumbsup: Thanks for doing that. I'll give that a thorough read later. I agree the examples should be updated, including this one (which really throws people for a loop):

```js
// Before
export default function(){};

// After
export default function(){}
```

Rather than exclude `export` entirely, perhaps it'd be better to update it to something like:

> some forms of `export`

**Comment by yordis** [comment]
Am I the only that actually push for remove the semicolon from JS? I prefer to delegate that responsibility to babel :smile: or any transpiler. Right now the spec of properties in class have a required semicolon :sob:

**Comment by mathiasbynens** [comment]
Closing as per https://github.com/tc39/ecma262/issues/284. Thanks for your patience, @jmm!

**Comment by jmm** [comment]
Thanks @mathiasbynens. I appreciate the intent and effort on this :smiley:

**Pull request closed without merging**
