### PR TITLE
Always print strings for consistency

### PR DESCRIPTION
**Pull request by amasad**
It's weird to mix single and double quotes (and really bad for gzip)

### CODE REVIEW

**Comment by jmm** [comment]
I haven't looked at this in depth, but I think this might be related to https://phabricator.babeljs.io/T1852. This changes output of something like:

```js
"what\x20ever";
```

In this case it escapes it to:

```js
"what\\x20ever";
```

I tried dropping a couple of fixtures in to demonstrate this, but for some reason they're not being picked up -- I'll have to figure that out.

Also, like the CI I'm getting other failing tests.

**Comment by jmm** [comment]
Ok, here's a fixture that passes on [`master`](https://github.com/babel/babel/compare/master...jmm:generate-directive-literal) and fails on [this branch](https://github.com/babel/babel/compare/master...jmm:jmm/always-print). (I don't know if it's in the best place in the dir structure or if `DirectiveLiteral` is the most appropriate type.)

**Comment by amasad** [comment]
@jmm thanks for the feedback. I'm going to leave it as is but always reprint in compact mode. I think that's a reasonable tradeoff.

**Comment by jmm** [comment]
@amasad Thanks. I'm not too familiar with compact mode, so I defer. I do think the docs on `compact` need to be updated, as the effects go above and beyond what's described. Also, FWIW, this can transform an innocuous string literal like `"use\x20strict";` into a directive, `"use strict";`.

**Comment by amasad** [comment]
Good point. I'm not sure if I should add yet another mode to avoid
confusion, say minified. We briefly touched in that in the past.
@sebmck any thoughts?

**Comment by thejameskyle** [comment]
Why are we changing it at all in compact mode?

**Comment by hzoo** [comment]
I think @amasad mentioned for gzip?

**Comment by thejameskyle** [comment]
That almost seems like the different mode itself. I feel like `compact` should only be the safe stuff to change, and a separate mode could do slightly more dangerous changes

**Comment by amasad** [comment]
Yeah, I'll add a new mode that is a superset of compact

**Comment by jmm** [comment]
Do we want to add some [fixtures like these](https://github.com/babel/babel/compare/master...jmm:jmm/always-print)? I think they would've flagged a couple of things to consider here (first double escaping, then unescaping, which can create a directive that means something from a string that doesn't.)

**Comment by amasad** [comment]
@jmm this is now behind a `minified` flag so I'm not too worried about edge cases like this.

**Comment by jmm** [comment]
@amasad Ok. (FWIW I've been trying to get fixtures like that in since before this (https://github.com/babel/babel/pull/1852, https://github.com/babel/babel/compare/master...jmm:use-strict-raw3), but those commits were never actually merged.)

**Pull request merged**
