### PR TITLE
Use a functionExpression with class decorators. Fixes #1161.

### LINKED ISSUE #1161: React Component is not working with class decorators
I was very excited for the new decorator syntax and was trying to get a simple example of class decorators with react working. Unfortunately I'm running into the following issue:

Using this simple component
```js
@Enhance
export class Simple extends Component {

  render() {
    return (
      <span>I am a {this.props.enhanced ? 'enhanced' : 'simple'} component.</span>
    )
  }
}
```

and this `Enhance` decorator

```js
import React from 'react'
const { Component } = React

const Enhance = Target => class extends Component {

  render() {
    return <Target {...this.props} enhanced={true} />
  }
}
```
If I try to render this component it throws with

```
Uncaught TypeError: Cannot call a class as a function  bundle.js:58 
_classCallCheck                                        bundle.js:101
```

The generated `bundle.js` can be found [here](https://gist.github.com/Dignifiedquire/e5244904712f94f9c05c)

It seems that the check for the constructor of the `Simple` component is referencing the constructor where `Enhance` has already been applied to.

I might be just doing  something wrong, if so a pointer to what I need to fix would be great. 

Thanks for a great tool!

---

Libraries used:
```bash
➜  react  npm ls react
/Users/dignifiedquire/play/react
└── react@0.13.1

➜  react  npm ls babel-loader
/Users/dignifiedquire/play/react
└── babel-loader@5.0.0

➜  react  npm ls babel-core
/Users/dignifiedquire/play/react
├── babel-core@5.0.8
└─┬ babel-loader@5.0.0
  └── babel-core@5.0.8
```

### PR DESCRIPTION
**Pull request by Dignifiedquire**
This is an implementation of the fix I suggested in #1161. Class decorators work as expected in my test project now. 

It's my first time around this code base, so please be merciful with me.

### CODE REVIEW

**Comment by sebmck** [comment]
I'll need to verify that this wont break anything as I'm not sure if:

```javascript
class Foo {
  foobar() {
    return Foo;
  }
}
```

is supposed to return the decorated class or the original undecorated class.

**Comment by sebmck** [comment]
:+1: It's the decorated one. Thanks!

**Comment by sebmck** [comment]
Actually no, this will cause references to the class inside the decorated class constructor be incorrect.

**Comment by Dignifiedquire** [comment]
@sebmck yes, this makes the reference inside the constructor to be the non decorated version. I could change it, to this, which would ensure `Foo` is the decorated version:

```js

var _Foo = function Foo() {
  _classCheck(this, _Foo); 
}

Foo = Bar(Foo) || Foo;
return Foo
```

**Comment by sebmck** [comment]
`Foo` isn't in scope then.

**Comment by Dignifiedquire** [comment]
@sebmck maybe I'm thick, but why not? (updated the example to show the wrapper)

**Comment by sebmck** [comment]
Classes have a lexical binding inside so:

```javascript
class Foo {
  bar() {
    return Foo; // this will always be the class
  }
}

var bar = new Foo;
Foo = 5;
bar.bar(); // this wont be 5
```

**Comment by Dignifiedquire** [comment]
Okay, sorry got the issue now..

What about this then: 

```js
var Bar = (function () {
    var _Bar;
    function Bar() {
        _classCallCheck(this, _Bar);
    }

    _createClass(Bar, [{
        key: "bar",
        value: function bar() {
            return Bar; // this will always be the class
        }
    }]);

    _Bar = Bar;
    Bar = Enhance(Bar) || Bar;
    return Bar;
})();

var bar = new Bar();
Bar = 5;
console.log(bar.target.bar().toString());
// Prints
// function () {
//    this.target = new Target();
// }
```

**Pull request merged**
