### PR TITLE
[babel 8] Remove the `Noop` node type

### LINKED ISSUE #12355: Remove `Noop` node from `@babel/types`
We should have [removed it in Babel 7](https://github.com/babel/babel/pull/5970), but it's still there:
https://github.com/babel/babel/blob/3e0fa927c09183b0ef9a280b4258f8db673085fc/packages/babel-types/src/definitions/misc.js#L9-L11

It's not used anywhere in our code.

### PR DESCRIPTION
**Pull request by sidntrivedi012**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #12355  
| Patch: Bug Fix?          |
| Major: Breaking Change?  | Yes, behind `BABEL_8_BREAKING`
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/12361"></a>

### CODE REVIEW

**Comment by sidntrivedi012** [comment]
@nicolo-ribaudo Please review if the changes look good. I am not sure why the CI is failing though.

**Comment by JLHwung** [comment]
@sidntrivedi012 Please run `make build` and commit the changes in `@babel/types`.

**Review by xtuc — APPROVED** [review]

**Comment by xtuc** [comment]
@sidntrivedi012 could you please resolve the merge conflict? Debasing and Regenerating the file should do it

**Comment by nicolo-ribaudo** [comment]
Actually, https://github.com/babel/babel/pull/12431 will introduced other conflicts. Since this PR has lower priority (because we have time for Babel 8), maybe it's worth waiting for #12431 to be merged before rebasing this one.

**Review by nicolo-ribaudo — APPROVED** [review]

**Pull request merged**
