### PR TITLE
Flow opaque type aliases

### PR DESCRIPTION
**Pull request by jbrown215**
| Q                        | A 
| ------------------------ | ---
| Patch: Bug Fix?          | No
| Major: Breaking Change?  | No
| Minor: New Feature?      | Yes
| Deprecations?            |  No
| Spec Compliancy?         | Yes
| Tests Added/Pass?        |  Yes
| Fixed Tickets            |  None
| License                  | MIT
| Doc PR                   | ?
| Dependency Changes       | N/A

Adds support for Flow's opaque type aliases. Babylon support was added in this PR: https://github.com/babel/babylon/pull/643

Tests pass when using the current state of babylon's master branch. Backport for 6.x will come after this lands.

I tried to split my commits in a way that would make it easier to review. The first two are the only code changes I made, the rest are tests.

Q: I assume I probably should update the babel-types README to include declareOpaqueType and opaqueType, but I noticed all of the docs refer to `to.is__` and `t.assert__` which only look like they are declared in an autogenerated file. Should I run that script myself?

### CODE REVIEW

**Comment by samwgoldman** [comment]
👍

Flow 0.51 is released with Flow-side support for opaque types. Excited for this to land!

**Comment by existentialism** [comment]
@jbrown215 yep, run that script!

**Comment by jbrown215** [comment]
Ran generate-interfaces and generate-babel-types-docs! :D 

excited!

**Comment by jbrown215** [comment]
@existentialism should I not have run one of those scripts? travis build failed from one of the files changed by the script

**Comment by existentialism** [comment]
@jbrown215 just fyi, I pushed https://github.com/babel/babel/pull/6031 to fix the CI error! :)

**Comment by jbrown215** [comment]
@existentialism thanks for the help! looks like tests are passing now :D

**Pull request merged**
