### PR TITLE
Revert "Improve output when wrapping functions"

### PR DESCRIPTION
**Pull request by jjonescz**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes https://github.com/babel/babel/issues/15978
| Patch: Bug Fix?          | Yes
| Major: Breaking Change?  | No
| Minor: New Feature?      | No
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  | No
| License                  | MIT

This adds a new test to reproduce the bug and reverts https://github.com/babel/babel/issues/15978 (without removing new tests added there). That's the simplest fix I could think of for now.
cc @liuxingbaoyu

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/15979"></a>

### CODE REVIEW

**Comment by nicolo-ribaudo** [comment]
Could we revert just the changes relative to function expressions and not to function declarations?

**Comment by jjonescz** [comment]
> Could we revert just the changes relative to function expressions and not to function declarations?

Do you mean that the optimization would apply to expressions but not declarations? Could that be done in a follow up PR - now only quickly fixing the regression by a safe revert of all changes?

**Comment by lightmare** [comment]
I think the problem affects function declarations as well. If you replace the function expression in the example with a declaration, i.e. replace:
```js
  for (const item of items) {
    await f(async (x) => {
      console.log(item);
    });
  }
```
with
```js
  for (const item of items) {
    async function g(x) {
      console.log(item);
    }
    await f(g);
  }
```
the wrapper returned from `_asyncToGenerator` still cannot be cached in a function-scoped variable, because the wrapped function references a lexical.

**Comment by nicolo-ribaudo** [comment]
Ok let's revert this for now, we will related with a proper fix later.

**Review by nicolo-ribaudo — APPROVED** [review]

**Comment by nicolo-ribaudo** [comment]
Releasing, it will take 15 minute

**Comment by liuxingbaoyu** [comment]
Thank you for your PR! I have a complete refactor locally and I will reopen a PR later.

**Comment by overlookmotel** [comment]
@liuxingbaoyu Just to flag that, depending on how you're refactoring, #15945 may also be similar - problem with temporary vars being function-scoped rather than block-scoped.

**Pull request merged**
