### PR TITLE
[@babel/parser] Add "allowUndeclaredExports" option

### PR DESCRIPTION
**Pull request by nicolo-ribaudo**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | https://github.com/babel/babel/issues/9720#issuecomment-481030523
| Patch: Bug Fix?          |
| Major: Breaking Change?  |
| Minor: New Feature?      | Yes
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

Ref: https://github.com/babel/notes/blob/master/2019/04/09.md#export-changes-in-scope-pr-break-meteor-issue

cc @benjamn Would this work for meteor?

### CODE REVIEW

**Comment by mlrawlings** [comment]
We ([Marko]()) are working on integrating babel to parse the JavaScript sections of our templates. 
 In many cases we are parsing statements and expressions in isolation, where they may not be valid on their own.  We were also broken by #9589 and were a bit surprised by that coming in a minor release.  This PR fixes the immediate issue, but something like [loose mode](https://github.com/babel/notes/blob/master/2019/04/09.md#export-changes-in-scope-pr-break-meteor-issue) would be useful so we wouldn't have to worry about early errors in the future.

**Comment by benjamn** [comment]
Anything I can do to move this along? Happy to write the docs if I can get a quick checklist of places to look. 🙏

**Comment by nicolo-ribaudo** [comment]
I'm writing the release blog post, hopefully I will release this PR in the following days.

> Happy to write the docs if I can get a quick checklist of places to look. 

:heart: :heart: :heart: 
It should be documented at https://github.com/babel/website/blob/master/docs/parser.md

**Comment by benjamn** [comment]
@nicolo-ribaudo done!

**Comment by benjamn** [comment]
If you need any additional motivation to get this shipped, check out the unholy workaround I came up with in https://github.com/benjamn/reify/pull/230. 😉

**Pull request merged**
