### PR TITLE
chore: use `c8` for coverage testing

### PR DESCRIPTION
**Pull request by liuxingbaoyu**
| Q                        | A 
| ------------------------ | ---
| License                  | MIT

Closes: #14916 

`c8` supports child processes, which increases our coverage to 93-95%.
Also I renamed some `.ts` to `.d.ts`.

```
File                                   | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
---------------------------------------|---------|----------|---------|---------|-------------------
All files                              |   94.51 |    92.76 |   95.02 |   94.51 |        
```
https://app.codecov.io/github/babel/babel/commit/84cd0c65be9f471a039f193457a130a766b4f706

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/14961"></a>

### CODE REVIEW

**Comment by nicolo-ribaudo** [comment]
> which increases our coverage to 93-95%.

Can we bump the minimum target to 93?
https://github.com/babel/babel/blob/0cc190c128c646e217de121a549e97beaefe1206/codecov.yml#L8

**Comment by liuxingbaoyu** [comment]
I'm concerned that this might cause trouble in the future, but I'm fine with changes.
Because the coverage rate may drop again for some reasons later (such as adding a lot of automatically generated code), and different calculation methods will produce different coverage rates (92%, 93%, 94%, 95%).

**Comment by nicolo-ribaudo** [comment]
Ok let's keep it at 90%, we can bump it to something higher when we consistently good higher results.

**Review by nicolo-ribaudo — APPROVED** [review]

**Review by JLHwung — APPROVED** [review]
Great work!

**Pull request merged**
