### PR TITLE
Add main file for babel-node

### PR DESCRIPTION
**Pull request by dword-design**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | 
| Patch: Bug Fix?          | Yes
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    |
| Any Dependency Changes?  |
| License                  | MIT

It sometimes makes sense to `require.resolve` a package in order to look for certain information/files. E.g. [https://www.npmjs.com/package/depcheck](depcheck) parses the binaries from packages in order to find out if it's an unused dependency. However, this requires the packages to have a main file. This PR simply adds `lib/babel-node.js` as the main fine.

### CODE REVIEW

**Comment by JLHwung** [comment]
I'm conservative on this change as adding a `main` entry will enable people to use `require("@babel/node")`, which we are not meant for.

Could [`Special` options](https://www.npmjs.com/package/depcheck#special) help `depcheck` to detech `@babel/node`?

**Comment by dword-design** [comment]
Hey @JLHwung, bin special is in fact the special I'm using. This uses resolveFrom, which in turn uses require.resolve. Other options like resolve-bin also use require.resolve, so it always seems to come down to that :P.

**Comment by JLHwung** [comment]
Closing this PR as I think it should be fixed on `resolve-bin`'s side: https://github.com/thlorenz/resolve-bin/issues/7

**Comment by dword-design** [comment]
Yeah you're right

**Pull request closed without merging**
