### PR TITLE
Document `babel-helper-plugin-test-runner` usage

### PR DESCRIPTION
**Pull request by rattrayalex**
| Q                        | A 
| ------------------------ | ---
| Patch: Bug Fix?          |  no
| Major: Breaking Change?  | no
| Minor: New Feature?      | no
| Deprecations?            | no
| Spec Compliancy?         | N/A
| Tests Added/Pass?        | N/A
| Fixed Tickets            | discussed in Slack
| License                  | MIT
| Doc PR                   | yes
| Dependency Changes       | no

Docs change, discussed in Slack at https://babeljs.slack.com/archives/C062LH50D/p1496953147883088

I don't know the internals of this library well and it may not be exactly accurate. Feel free to reject if it won't be helpful, I just slapped this together and don't feel strongly about its inclusion.

### CODE REVIEW

**Comment by hzoo** [comment]
Oh you targeted master 😛?

**Comment by rattrayalex** [comment]
Whoops – should it have been 6?

**Comment by rattrayalex** [comment]
(I look for docs online, personally, which usually points to master)

**Comment by hzoo** [comment]
default is 7.x, not a big deal just since merging to 6.x/master is annoying. We really just need to switch 7.x to be master but then all the prs need to change (necessary at some point though)

**Pull request merged**
