### PR TITLE
Fix logic to insert parens in return statements with comments

### LINKED ISSUE #11304: // comments in anonymous functions break React code
**I'm submitting a bug report**

**Webpack Version:**
4.42.0

**Babel Core Version**:
7.9.0

**Babel Loader Version**:
8.1.0

**Please tell us about your environment:**
OSX 10.14

**Current behavior:**
After running yarn build in create-react-app following code transpiles to wrong JS code:
```js
import React from "react";

function App() {
  return (
    <div className="App">
      <A
        render={() => (
          //test
          <B />
        )}
      />
    </div>
  );
}

const A = ({ render }) => {
  return <>{render()}</>;
};

const B = () => {
  return <p>bbbbbbb</p>;
};

export default App;
```

Transpiled and packed:
```
function App(){return/*#__PURE__*/react_default.a.createElement("div",{className:"App"},/*#__PURE__*/react_default.a.createElement(App_A,{render:function render(){return/*#__PURE__*/ //test <-----------------------
react_default.a.createElement(App_B,null);}}));}var App_A=function A(_ref){var render=_ref.render;return/*#__PURE__*/react_default.a.createElement(react_default.a.Fragment,null,render());};var App_B=function B(){return/*#__PURE__*/react_default.a.createElement("p",null,"bbbbbbb");};/* harmony default export */ var src_App = (App);
```
(arrow added)
`render()` has dangling `return` (line break after comment), so JS adds semicolon there - function returns undefined.

When setting `compact: false` in loader options this behavior isn't observed

**Expected/desired behavior:**

babel-loader should keep parens in arrow functions, following code is valid JS
```js
x = () => (
// TEST
5
);
```

* Minimal demo
Here's ejected react-create-app with reproduction
https://github.com/jakub-gonet/babel-loader-comment-bug

Run `yarn build && serve -s build` (assuming serve is installed)

When changing compact to false in `webpack.config.js#351` it works correctly

EDIT:

```js
function App() {
  return (
    <div className="App">
      {(() => (
        //test
        <span>test</span>
      ))()}
    </div>
  );
}
```
also reproduces this issue.

### PR DESCRIPTION
**Pull request by nicolo-ribaudo**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #11304
| Patch: Bug Fix?          | Yes
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

Wow, this was super hard to debug :grimacing:

### CODE REVIEW

**Comment by redonkulus** [comment]
@nicolo-ribaudo when do you think this will be published?

**Comment by nicolo-ribaudo** [comment]
As soon as https://github.com/babel/babel/pull/11307 is merged (I need another review).

It might get delayed at most to tomorrow morning in my timezone (central europe).

**Comment by zombieJ** [comment]
Seems #11307 merged. Is that possible to patch? : )

**Comment by nicolo-ribaudo** [comment]
Published

**Pull request merged**
