### PR TITLE
creating a cache to config content

### PR DESCRIPTION
**Pull request by jeanp**
Hi, this tries to resolve this issue:
https://phabricator.babeljs.io/T7391

My scenario and what've done is also described there.

### CODE REVIEW

**Comment by leyendecker** [comment]
+1

**Comment by takanorh** [comment]
Up

**Comment by xtuc** [comment]
You can configure the amout of open files at the system level.

Do you still have this issue? If not, do you mind if I close it?

**Comment by jeanp** [comment]
@xtuc sure. we've managed it in other ways! ty

**Pull request closed without merging**
