### PR TITLE
Update to stable chokidar.

### PR DESCRIPTION
**Pull request by paulmillr**
That's it. Brings LOTS of stability & improvements.

### CODE REVIEW

**Comment by sebmck** [comment]
Great, thanks!

**Comment by sebmck** [comment]
Erm, this was submitted to the `experimental` branch.

**Comment by paulmillr** [comment]
Correct. You don't seem to have `chokidar` in `master`.

**Comment by sebmck** [comment]
It's only used in the [CLI](https://github.com/babel/babel/blob/master/packages/babel-cli/package.json)

**Comment by paulmillr** [comment]
Ohh, got confused. Sorry for that! gh-1212

**Pull request merged**
