### PR TITLE
@babel/preset-typescript: fix tsx assigment issue

### LINKED ISSUE #12587: @babel/preset-typescript   Error: Assert fail  @babel/parser/src/plugins/typescript/index.js:53:11
### Input Code

```jsx
let a = 2

a == 3 ? (a = <h1>123</h1>) : (a = <h1>abc</h1>)
```

### error message
```
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Assert fail
    at assert (/project/node_modules/@babel/core/node_modules/@babel/parser/src/plugins/typescript/index.js:53:11)
    at Object.parseMaybeAssign (/project/node_modules/@babel/core/node_modules/@babel/parser/src/plugins/typescript/index.js:2504:9)
    at callback (/project/node_modules/@babel/core/node_modules/@babel/parser/src/parser/expression.js:224:12)
    at Object.allowInAnd (/project/node_modules/@babel/core/node_modules/@babel/parser/src/parser/expression.js:2561:12)
    at Object.parseMaybeAssignAllowIn (/project/node_modules/@babel/core/node_modules/@babel/parser/src/parser/expression.js:223:17)
    at Object.parseMaybeDefault (/project/node_modules/@babel/core/node_modules/@babel/parser/src/parser/lval.js:375:23)
    at Object.parseMaybeDefault (/project/node_modules/@babel/core/node_modules/@babel/parser/src/plugins/typescript/index.js:2676:26)
    at Object.parseAssignableListItem (/project/node_modules/@babel/core/node_modules/@babel/parser/src/plugins/typescript/index.js:1738:25)
    at Object.parseBindingList (/project/node_modules/@babel/core/node_modules/@babel/parser/src/parser/lval.js:336:24)
    at Object.tsParseBindingListForSignature (/project/node_modules/@babel/core/node_modules/@babel/parser/src/plugins/typescript/index.js:448:19)
    at Object.tsFillSignature (/project/node_modules/@babel/core/node_modules/@babel/parser/src/plugins/typescript/index.js:433:35)
    at Object.tsParseFunctionOrConstructorType (/project/node_modules/@babel/core/node_modules/@babel/parser/src/plugins/typescript/index.js:753:12)
    at Object.tsParseNonConditionalType (/project/node_modules/@babel/core/node_modules/@babel/parser/src/plugins/typescript/index.js:1170:21)
    at Object.tsParseType (/project/node_modules/@babel/core/node_modules/@babel/parser/src/plugins/typescript/index.js:1154:25)
    at cb (/project/node_modules/@babel/core/node_modules/@babel/parser/src/plugins/typescript/index.js:1145:33)
    at Object.tsInType (/project/node_modules/@babel/core/node_modules/@babel/parser/src/plugins/typescript/index.js:1281:16)
```

## babel-code

image

https://github.com/babel/babel/blob/0d6063f1b9c837838ddefc2c623ac9fd594fa7f0/packages/babel-parser/src/plugins/typescript/index.js#L2504

## babel gif【 try it out 】

Jan-05-2021 19-04-53

## link 【 try it out 】

https://babeljs.io/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&spec=false&loose=false&code_lz=DYUwLgBAhhC8ECYDcAoFNaYgZggfggAoMIAeACwEYA-BUgeiuoEoIAuIqWCha7bBuV7NUaevWhwsuAsThkmdRjVYc58SsyA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-2&prettier=false&targets=&version=7.12.12&externalPlugins=

### PR DESCRIPTION
**Pull request by Zzzen**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            |  Fixes #12587 
| Patch: Bug Fix?          |  Yes
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

This is actually copied from flowjs plugin https://github.com/babel/babel/blob/fce3e7124a2d6bef323a3982ded9c752054992ef/packages/babel-parser/src/plugins/flow.js#L2671-L2673 

Someone might forget ts when fixing it in flowjs plugin.

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/12599"></a>

### CODE REVIEW

**Comment by Zzzen** [comment]
Does it mean that I should remove `jsxIntrinsicElementsExtendsRecord.tsx` from the allowlist file?

```
yarn node scripts/parser-tests/typescript
Now running tests...
.........................................................................................................
Testing complete (5291 tests).
Summary:
 ✔ 4452 valid programs parsed without error
 ✔ 401 invalid programs produced a parsing error
 ✔ 5 invalid programs did not produce a parsing error (and allowed by the allowlist file)
 ✔ 432 valid programs produced a parsing error (and allowed by the allowlist file)

 ✘ 1 valid programs parsed without error (in violation of the allowlist file)

Details:
   1 valid programs parsed without error (in violation of the allowlist file):
     jsxIntrinsicElementsExtendsRecord.tsx
```

**Comment by nicolo-ribaudo** [comment]
Yes :+1: Or better, you can run `make test-typescript-update-allowlist`

**Review by nicolo-ribaudo — APPROVED** [review]

**Comment by existentialism** [comment]
@Zzzen thanks!

**Comment by Topthinking** [comment]
@existentialism  When will the new version of this change be released

**Pull request merged**
