### PR TITLE
Fix import with wrong extension

### PR DESCRIPTION
**Pull request by nicolo-ribaudo**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | `Fixes #1, Fixes #2` 
| Patch: Bug Fix?          |
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

This is a .js file. It's unfortunate that neither ESLint's `import` plugin neither TS complain.

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/15952"></a>

### CODE REVIEW

**Review by JLHwung — APPROVED** [review]
The `import/no-unresolved` rule is disabled by default, since it requires a custom import resolver, so the `eslint-plugin-import` can't do much here. We can create own own rule just to disable `vendor/**/*.ts` imports. I think `tsc` should have warned though, at least for non-type imports.

**Review by liuxingbaoyu — APPROVED** [review]

**Comment by nicolo-ribaudo** [comment]
@JLHwung Now that we use paths with the full extension, `import/no-unresolved` works without a custom resolver :)

**Comment by JLHwung** [comment]
Well it seems that it can't resolve relative path without further config.

**Comment by nicolo-ribaudo** [comment]
The problem is that file is auto-generated by `make build`, but CI artifacts do not contain auto-generated files from the `src` folder. It's just a special case, and the rule is working everywhere else 😬

**Comment by JLHwung** [comment]
> The problem is that file is auto-generated by `make build`, but CI artifacts do not contain auto-generated files from the `src` folder. It's just a special case, and the rule is working everywhere else 😬

👍 In that case we should add it to the artifacts:

https://github.com/babel/babel/blob/56713333bea8eae3ed022aba93a6b0541dab4c0c/scripts/get-artifact-files.sh

**Review by JLHwung — APPROVED** [review]

**Pull request merged**
