### PR TITLE
feat(react-jsx-source): add columnNumber property

### PR DESCRIPTION
**Pull request by motiz88**
This will be useful to tools that consume the injected `__source` prop, allowing precise source locations to be displayed.

cc @rickhanlonii

| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            |
| Patch: Bug Fix?          |
| Major: Breaking Change?  |
| Minor: New Feature?      | 👍
| Tests Added + Pass?      | 👍
| Documentation PR Link    | https://github.com/babel/website/pull/2178
| Any Dependency Changes?  |
| License                  | MIT

### CODE REVIEW

**Comment by nicolo-ribaudo** [comment]
Should we call it `columnNumber`?

**Comment by motiz88** [comment]
Yeah, probably. We _could_ make up a convention that `...Number` is for 1-based values and thus leave it as `column` (or change to `columnIndex`) to signify that it's 0-based... But that's just me having been bitten by too many off-by-one bugs involving source locations :) I'll change it to whatever you prefer.

**Comment by motiz88** [comment]
Fixed tests and corrected the information in the PR description (I had a  👍 under Breaking Change, which this isn't)

**Comment by kaicataldo** [comment]
`columnNumber` makes sense to me.

**Comment by motiz88** [comment]
I'll change to `columnNumber`. Actually, how do you feel about making it 1-based as well?

**Comment by nicolo-ribaudo** [comment]
I slightly prefer 0-based column numbers, but it seems that other user-facing tools start counting from 1:

| **tool** | **line start** | **column start** |
|:--------:|:--------------:|:----------------:|
| VS Code  | 1 | 1 |
| Chrome stack traces | 1 | 1 |
| `@babel/parser` | 1 | 0 |
| acorn | 1 | 0 |
| ESLint | 1 | 1 |

**Comment by nicolo-ribaudo** [comment]
@motiz88 Out of curiosity, what tool would use this information?

**Comment by motiz88** [comment]
The specific thing we have in mind is showing better code frames for component errors in React Native.

**Pull request merged**
