### PR TITLE
chore: update jest 29

### PR DESCRIPTION
**Pull request by liuxingbaoyu**
| Q                        | A 
| ------------------------ | ---
| Any Dependency Changes?  |jest
| License                  | MIT

pending https://github.com/nicolo-ribaudo/jest-light-runner/pull/56

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/14885"></a>

### CODE REVIEW

**Comment by liuxingbaoyu** [comment]
They are referenced by `jest-light-runner` and should disappear after the https://github.com/nicolo-ribaudo/jest-light-runner/pull/56 merge.

**Review by nicolo-ribaudo — COMMENTED** [review]
Since Jest 29 dropped support for Node.js 12, we need to do something like https://github.com/babel/babel/blob/ae5182a2c52ca3e87c70f1cd53fb74e9f683a316/.github/workflows/ci.yml#L197-L204 (downgrading to Jest 28 and jest-light-runner 0.3.0) to test Babel on it.

**Comment by nicolo-ribaudo** [comment]
Is it normal that Jest doesn't escape quotes in strings in snapshots anymore? (see the failures)

**Comment by liuxingbaoyu** [comment]
Yes, this is the new default in jest 29.0. I define it explicitly for older versions because the new behavior is better looking.
But strangely, in my local tests only inline snapshots are affected by this option, I'm still investigating.

**Comment by liuxingbaoyu** [comment]
Ah, just now my git branch seems to be wrong. 😅
Also you may want to modify https://github.com/nicolo-ribaudo/jest-light-runner/blob/main/src/worker-runner.js#L80 to align with jest behavior, otherwise default inline snapshot vs external snapshot format will be different.🙂

**Comment by nicolo-ribaudo** [comment]
Isn't `snapshotFormat: test.context.config.snapshotFormat` already "do whatever Jest tells you to do"? :sweat_smile:

**Comment by liuxingbaoyu** [comment]
There is a default in jest 29.0 and `light-jest-runner` doesn't support this, it doesn't matter to us, but will it affect other users?

**Comment by liuxingbaoyu** [comment]
Sorry, I made a mistake, that was the result yesterday when `jest-linght-runner` was not updated.😅

**Comment by liuxingbaoyu** [comment]
I kept the original format due to not working on older versions of jest.
Also I found out that BABEL8 tested on windows with two exceptions, our CI didn't show this.

**Review by nicolo-ribaudo — APPROVED** [review]
We can change the snapshot format after the Babel 8 release.

**Review by JLHwung — APPROVED** [review]

**Comment by liuxingbaoyu** [comment]
I merged using github app, but the commit message is not the title.😰

**Comment by nicolo-ribaudo** [comment]
When there is a single commit it uses its title; don't worry but be careful in the future 🤷

**Comment by merceyz** [comment]
@nicolo-ribaudo You can actually configure that now
https://github.blog/changelog/2022-05-11-default-to-pr-titles-for-squash-merge-commit-messages/
https://github.blog/changelog/2022-08-23-new-options-for-controlling-the-default-commit-message-when-merging-a-pull-request/

**Comment by liuxingbaoyu** [comment]
This might be a problem with the github app, it's normal for me to merge on my computer.😕

**Comment by nicolo-ribaudo** [comment]
@merceyz Thank you!

**Pull request merged**
