### PR TITLE
Flow typings: update for babel-types and add for more packages

### PR DESCRIPTION
**Pull request by mischnic**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | 
| Patch: Bug Fix?          | Yes?
| Major: Breaking Change?  | No?
| Minor: New Feature?      | No?
| Tests Added + Pass?      |  Not needed?
| Documentation PR Link    |
| Any Dependency Changes?  | No
| License                  | MIT

- `@babel/types` didn't export the individual types
- The visitor in `@babel/traverse` is now properly typed as well (see example)
- `@babel/template`
- in `@babel/core`, I intentionally left out the deprecated behaviour.

With this change, this has 100% type coverage:
```js
// @flow
import type {
  ArrayExpression, ClassExpression, CallExpression, FunctionExpression, Identifier, NullLiteral,
  NumericLiteral, ObjectExpression, Statement, StringLiteral
} from "@babel/types";
import type { NodePath } from "@babel/traverse";

import * as t from "@babel/types";
import { isIdentifier } from "@babel/types";
import traverse from "@babel/traverse";
import * as parser from "@babel/parser";
import * as template from "@babel/template";

const ast = parser.parse("console.log('a');");
traverse(ast, {
  Program(path) {
    // path is a Program
    let { body } = path.node;

    // you have to help flow with .get(), is unchecked though (obviously)
    let body2 = path.get<NodePath<Statement>>("body.0");
    let body3 = path.get<Array<NodePath<Statement>>>("body");
  }
});

// refinement
let x: mixed = t.identifier("x");
if (isIdentifier(x)) {
  (x: Identifier);
  (x: string); // should fail
}

(t.valueToNode({ a: 2 }): ObjectExpression);
(t.valueToNode(1): NumericLiteral);
(t.valueToNode([1, 2, 3]): ArrayExpression);
(t.valueToNode(null): NullLiteral);
(t.valueToNode(undefined): Identifier);

let c = template.expression<{| X: StringLiteral |}, CallExpression>("call(X)");
c(); // fails
c({ X: "" }); // fails
c({ X: t.stringLiteral("abc") }); // passes

(t.toExpression(
  t.classDeclaration(t.identifier("X"), null, t.classBody([]))
): ClassExpression);
(t.toExpression(
  t.functionDeclaration(t.identifier("X"), [], t.blockStatement([]))
): FunctionExpression);
```

### TODO/Questions:
- Fix the Makefile?
- I'm not quite sure about the types for `@babel/core`, this documentation doesn't seem to cover everything regarding e.g. `loadPartialConfig`
- `@babel/types`: These should not be `any` (caused by `stringifyValidator`) and also remove the patches in `flow.js`:
```
BabelNodeFile.comments
BabelNodeFile.tokens
BabelNodeObjectMethod.key
BabelNodeTryStatement.block
BabelNodeClassExpression.mixins
BabelNodeClassDeclaration.superClass
BabelNodeClassDeclaration.body
BabelNodeClassDeclaration.decorators
BabelNodeClassDeclaration.mixins
BabelNodeClassDeclaration.superTypeParameters
BabelNodeClassDeclaration.typeParameters
BabelNodeMetaProperty.meta
BabelNodeJSXElement.selfClosing
BabelNodeBindExpression.object
BabelNodeBindExpression.callee
BabelNodeOptionalMemberExpression.property
BabelNodeClassPrivateMethod.returnType
BabelNodeClassPrivateMethod.typeParameters
```

### CODE REVIEW

**Comment by nicolo-ribaudo** [comment]
Thanks for this PR!

The `BabelNode` prefix to flow nodes was initially added to avoid conflicts, since we declared those types in the global scope.

Would it be possible to maintain the `BabelNodeArrayExpression`-style with global types and remove the prefix for exported types, like [we do with TypeScript](https://unpkg.com/browse/@babel/types@7.8.6/lib/index.d.ts)?

> `@babel/types`: These should not be `any` (caused by `stringifyValidator`)

Related: https://github.com/babel/babel/issues/11100#issue-561035030

**Comment by mischnic** [comment]
> remove the prefix for exported types,

`Class` and `Function` are both already predefined Flow types...

**Comment by nicolo-ribaudo** [comment]
It doesn't seem to be a problem :thinking: 

https://flow.org/try/#0CYUwxgNghgTiAEBbA9sArhBAiAAgIyjxAgHoAXATwAcQBnLeAbwCh55RJYEQAPK5GGXiUa8AGJoAdmDIBLZJPgBeJqzbDqIAFzwsE6XIVY1AX2ZnmQA

**Comment by mischnic** [comment]
The issue is that they don't shadow the predefined ones:

Bildschirmfoto 2020-03-03 um 16 50 17

Bildschirmfoto 2020-03-03 um 16 51 14

**Comment by mischnic** [comment]
Furthermore:

```js
declare class BabelNode {}
declare type BabelNodeExpression = BabelNode

declare module "@babel/types" {
  declare export {
    BabelNode as Node,

	// Cannot reference type `BabelNodeExpression` [1] from a value position
    BabelNodeExpression as Expression
  };
}
```

https://flow.org/try/#0CYUwxgNghgTiAEkoGdnwEJQEYggOQHtR4BvAXwChQk54AXATwAcFMd8iQBRADyblQBLAgDt4AXgzZchUBSrhotALZEArhAQAiAAJZpEAPSMWyLaQrx41JQhB8CMOhatW2MzvBTxZIADSWru4coLz8IEKiXmhhAsjCIoFkANwUlBRAA

**Comment by mischnic** [comment]
Somehow, you can't shadow `Class`:

```js
type Class = string | number;

function x(): Class { // Cannot use type without exactly 1 type argument.
  
}
```

https://flow.org/try/#0C4TwDgpgBAwgNgQwM5KgXik4AnAlgOwHMoAfKfAVwFsAjCbAbgCgmAzC-AY2FwHt8oADwAUASgBcsRCigBvJlChMAvkA

**Comment by mischnic** [comment]
Sorry for the noise, 

> Would it be possible to maintain the BabelNodeArrayExpression-style with global types and remove the prefix for exported types

I've removed the Prefix from the exported types (if you want to import `Function` or `Class`, `Class as BabelClass` is needed).

**Comment by nicolo-ribaudo** [comment]
Thanks!
Even if it's 5 years old, please :+1: https://github.com/facebook/flow/issues/942 :stuck_out_tongue:

**Comment by nicolo-ribaudo** [comment]
Is it possible to automatically check that the `.js.flow` types match the inferred types in the source code?

**Comment by liuxingbaoyu** [comment]
Thank you for your PR! Since it is now obsolete, I will close it.

**Pull request closed without merging**
