### PR TITLE
Bump `@babel/preset-typescript` to 7.2.0

### PR DESCRIPTION
**Pull request by kevinmarrec**
| Q                        | A
| ------------------------ | ---
| Fixed Issues?            | No
| Patch: Bug Fix?          | No
| Major: Breaking Change?  | No
| Minor: New Feature?      | No
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  | Yes
| License                  | MIT

Bumps the `@babel/preset-typescript` to **7.2.0**
=> Upgraded `@babel/plugin-transform-typescript` dependency to **^7.2.0**
=> Upgraded `@babel/core` devDependency to **^7.2.0**

I'm not sure how to test this version bump locally, so I let the CI pipeline decide.
EDIT : Tests passed

I'm submitting this PR as the preset doesn't seem to be kept up to date. (Maybe there is a reason ?)

### CODE REVIEW

**Comment by existentialism** [comment]
> I'm submitting this PR as the preset doesn't seem to be kept up to date.

FWIW, our versioning is handled via `lerna`.

It is a _little_ strange that `@babel/plugin-transform-typescript` didn't get bumped when we release 7.2, but the current setup doesn't prevent the latest from being installed due to semver?

```sh
> npm i @babel/preset-typescript
> npm ls @babel/plugin-transform-typescript
└─┬ @babel/preset-typescript@7.1.0
  └── @babel/plugin-transform-typescript@7.2.0
```

**Comment by kevinmarrec** [comment]
Alright, then what should we do ? Wait for `7.3.0` and see if everything is updated ?
It felt weeird having everything in 7.2.0 but only this package in 7.1.0 within my app, so I created this PR.

**Comment by nicolo-ribaudo** [comment]
We only publish packages which have changes: 7.2.0 contained a lot of new packages because of a PR which touched almost every plugin, but usually we only release 5-10 packages (e.g. 7.2.1 [only contains three packages](https://github.com/babel/babel/commit/8b132c0889c4d0a91f983d2fcb353d94c1515603))

**Comment by kevinmarrec** [comment]
Well alright, I close my PR has anyway the changes are not really relevan, as there is a behavior used to automatically bump and release the packages.

**Pull request closed without merging**
