### PR TITLE
[babel-template][T7046]: Add optional babylon options argument.

### PR DESCRIPTION
**Pull request by jamestalmage**
Reference [#T7046](https://phabricator.babeljs.io/T7046)

I would love to add a test, but there do not appear to be any for `babel-template`. I will happily add one if pointed in the right direction.

### CODE REVIEW

**Comment by hzoo** [comment]
Yeah your right there aren't any tests yet. I would look at the `babel-traverse` or `babel-core` tests and use something there.
You can assert the AST output or in this case assert that there is or isn't an error

**Comment by jamestalmage** [comment]
@hzoo - test added.

**Comment by hzoo** [comment]
Thanks @jamestalmage!

**Comment by jamestalmage** [comment]
:tada: 
Awesome, thanks!

**Comment by hzoo** [comment]
@jamestalmage for docs, do you want to make a PR for the README for this addition?

**Pull request merged**
