### PR TITLE
Bootstrap Babel on npm install

### LINKED ISSUE #5299: Better setup
If a new contributor does `npm run test` or `make test` and expects it to work you are greeted with `Error: Cannot find module '../lib'` because they didn't run `make bootstrap`. @montogeek

Of course we could be like "You should read the contributing.md, etc" but why not just do it automatically then?

- Basic idea is that these commands should figure out whether the folder in `packages/*/lib` are empty or not and then run `make build`. If it's not bootstrapped properly it should run `make bootstrap`.

If we do this right they may not have to do anything other than git clone + npm install?

### PR DESCRIPTION
**Pull request by chicoxyzzy**
| Q                        | A 
| ------------------------ | ---
| Patch: Bug Fix?          | no
| Major: Breaking Change?  |no 
| Minor: New Feature?      | no
| Deprecations?            | no
| Spec Compliancy?         | no
| Tests Added/Pass?        | no
| Fixed Tickets            | Fixes #5299
| License                  | MIT
| Doc PR                   | 
| Dependency Changes       |

### CODE REVIEW

**Comment by hzoo** [comment]
If we do this we can change the contributing.md https://github.com/babel/babel/blob/master/CONTRIBUTING.md#setup to say `npm install` instead of `make bootstrap`

**Comment by danez** [comment]
This would run npm install twice for the root I think, but probably is not a big issue.

**Comment by hzoo** [comment]
Oh right - hmm I wonder what happens for yarn for 7.0

**Comment by chicoxyzzy** [comment]
> This would run npm install twice for the root

That's true but preinstall will be called once

**Comment by chicoxyzzy** [comment]
`yarn` commands seems to work properly

**Comment by chicoxyzzy** [comment]
hmmm... that's weird but I see `npm install` call only once in my console using either npm or yarn

**Comment by hzoo** [comment]
Maybe it won't run again if it's currently being run 😄 ?

**Comment by chitchu** [comment]
One caveat of the `--ignore-scripts` switch is it also prevents dependency scripts to run.

And also upgrading/adding a new dependency will run `make bootstrap` every time.

Also maybe you could split `bootstrap` by adding both `preinstall` and `postinstall` script where `preinstall` cleans up all `node_modules` folder and `postinstall` does the bootstrap? So the lifecycle is much cleaner as such:

1. `preinstall` will `clean-all`
1. `install`
1. `postinstall` will `bootstrap`

**Comment by chicoxyzzy** [comment]
I've tried this but `npm install` fails when I run it for second time (when there are `node_modules` already). It doesn't actually run `install` script before `postinstall` for some reason and I get following error:
```bash
make: ./node_modules/.bin/lerna: No such file or directory
```

related npm issue: https://github.com/npm/npm/issues/10379

**Comment by chitchu** [comment]
I think you might need to remove `make clean-all` from `bootstrap`.

**Comment by chicoxyzzy** [comment]
That's exactly what I did:
```
bootstrap:
	./node_modules/.bin/lerna bootstrap
	make build
	cd packages/babel-runtime; \
	npm install; \
	node scripts/build-dist.js
```

```
    "preinstall": "make clean-all",
    "postinstall": "make bootstrap"
```

There is an issue in npm `preinstall` script logic (described in issue I mentioned)

**Comment by chitchu** [comment]
Maybe make a conditional `npm install` in bootstrap?

**Comment by chicoxyzzy** [comment]
Just realized that if we'll make Babel run tests via `npm install && npm test`, than we'll be able to propose Babel for inclusion in Node.js [CITGM](https://github.com/nodejs/citgm) runs. If Babel will be included in CITGM than each new version of Node.js will be smoke-tested using Babel among other npm modules.

**Comment by hzoo** [comment]
That would cool! cc @MylesBorins

**Comment by MylesBorins** [comment]
As long as releases continue to use a consistent tagging as I'm seeing in https://github.com/babel/babel/tags we could definitely get babel on CITGM!

Does someone want a good first contrib to www.github.com/nodejs/citgm ??

**Comment by hzoo** [comment]
Might be a good beginner-friendly issue? 

> The test process must be executable with only the commands npm install && npm test using the tarball downloaded from the Github tag mentioned above

So it should be ok if we use `preinstall` then?

**Comment by chicoxyzzy** [comment]
I'll contrib to CITGM when we'll get this PR sorted 👍

**Comment by MylesBorins** [comment]
@hzoo `preinstall` should be fine as long as you are not modifying the env

**Comment by chicoxyzzy** [comment]
I'm getting following error when running CITGM

```bash
➜  citgm git:(master) ✗ ./bin/citgm.js -v verbose babel
info:    starting            | babel
verbose: babel using-uid     | 501
verbose: babel using-gid     | 20
verbose: babel using-node    | /Users/Chico/.nvm/versions/node/v7.5.0/bin/node
verbose: babel using-npm     | /Users/Chico/.nvm/versions/node/v7.5.0/bin/npm
verbose: babel mk.tempdir    | /var/folders/rt/rl8_2jsn67l24mvmfwdkgqzm0000gn/T/6c4015d7-060b-43c4-93db-97509d257119
info:    lookup              | babel
info:    lookup-found        | babel
info:    babel lookup-replace| https://github.com/babel/babel/tree/master/packages/babel/archive/v6.23.0.tar.gz
info:    babel npm:          | Downloading project: https://github.com/babel/babel/tree/master/packages/babel/archive/v6.23.0.tar.gz
error:   failure             | Failure getting project from npm
error:   failing module(s)   |
error:   module name:        | babel
error:   version:            | 6.23.0
error:   error:              | Failure getting project from npm
error:   error:              |
error:   done                | The smoke test has failed.
info:    duration            | test duration: 73385ms
```

lookup.json
```js
  "babel": {
    "prefix": "v"
  }
```

**Comment by hzoo** [comment]
Is it because Babel is a monorepo?

**Comment by chicoxyzzy** [comment]
Adding `repo` field makes "Project link" correct (omits `/tree/master/packages/babel` part of "Downloading project" url, now it's downloadable) but I'm still getting same error

**Comment by MylesBorins** [comment]
So we have run into this edge case before and it is caused by `npm pack` blowing up on the tarball.

we can repro with citgm via ```npm pack https://github.com/babel/babel/archive/v6.23.0.tar.gz```

The first time we ran into it was with lerna usage on `pug`

--> https://github.com/npm/npm/issues/15563

I'm digging into the errors from npm to see what's up, this is a slightly different edge case. Will update inline

**Comment by xtuc** [comment]
I think this should only run the first time you clone Babel. Each time we add a new dependecy and run `npm i` it will cause to compile Babel.

**Comment by chicoxyzzy** [comment]
As far as I understand this is possible only using [post-checkout](https://git-scm.com/docs/githooks#_post_checkout) GIT hook. But CITGM will ignore any GIT hooks

**Comment by hzoo** [comment]
> edit: it is because the package.json inside the babel tarball does not have a name. Is there a reason you publish with a stripped down package.json?

No reason it's just a monorepo and the top level package.json isn't a package, but holds our devDeps so probably didn't think it was necessary to have a name (and we have a `babel` package at `packages/babel`)

but https://github.com/babel/babel/issues/5311 should fix!

**Comment by chicoxyzzy** [comment]
Now `npm pack http://github.com/babel/babel/archive/master.tar.gz` fails with `npm ERR! No version provided` so we should have a `version` in package.json

**Comment by chicoxyzzy** [comment]
can we solve this using lerna and use version from `babel-core`?

**Comment by chicoxyzzy** [comment]
I have a  of questions:
- I'm not familiar with lerna but I've found that `lerna.json` has [`version`](https://github.com/babel/babel/blob/master/lerna.json#L3) field. Is it number of version we need to copy to `package.json`?
- Is it possible to do this using lerna?
- If not, should I contribute to lerna by adding an option to update `version` field in `package.json`?
- If I should contribute to lerna, **does that blocks this PR**?
- Should I do something else in **this** PR?

**Comment by hzoo** [comment]
If we just need a version in the top level package.json we can just add it with like 0.0.0 or something

**Comment by chicoxyzzy** [comment]
`npm pack` works with `"version": "0.0.0"` but something goes wrong after `make bootstrap`, it fails with 
```
fatal: Not a git repository (or any of the parent directories): .git
```

**Comment by chicoxyzzy** [comment]
Just found that pug is in lookup list in CITGM but [it's skipped](https://github.com/nodejs/citgm/blob/master/lib/lookup.json#L43). It seems that lerna has more blockers for including in CITGM than just https://github.com/npm/npm/issues/15563

**Comment by MylesBorins** [comment]
if you are going to add a version I do humbly request you don't just opt for 0.0.0. We use those version number when investigating

**Comment by nicolo-ribaudo** [comment]
I'm working on upgrading to yarn 2 + workspaces, which make `lerna bootstrap` obsolete.

**Pull request closed without merging**
