### PR TITLE
[helper-create-class-features-plugin] fix feature in isLoose

### PR DESCRIPTION
**Pull request by pnowak**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | #9424 
| Patch: Bug Fix?          |
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

`isLoose` is call with `FEATURES.fields`, but it's true only for the `class-properties`. In `private-methods` `feature` has `FEATURES.privateMethods`, so it's fails. 
I used `feature` which is passed in the call `createClassFeaturePlugin`.

### CODE REVIEW

**Comment by pnowak** [comment]
Should I create a new PR without unnecessary commits?

**Comment by nicolo-ribaudo** [comment]
Yes please. I suggest using a new branch instead of `master`.

**Comment by nicolo-ribaudo** [comment]
@pnowak https://github.com/babel/babel/pull/9708/commits/f524311c466d8a2b083d740ccbd2994d268c0aed looks good, let me know when you can clean up the PR fro mthe unnecessary commits.

**Comment by nicolo-ribaudo** [comment]
Some commits are unrelated. I will merge this locally.

**Comment by nicolo-ribaudo** [comment]
Merged as 3aaafae053fa75febb3aa45d45b6f00646e30ba4. Thanks!

**Comment by pnowak** [comment]
Sorry that I didn't respond, yesterday I was off the internet.
Thanks for review and merge.

**Comment by jridgewell** [comment]
@nicolo-ribaudo that’s exactly what a [squash merge](https://help.github.com/en/articles/about-pull-request-merges#squash-and-merge-your-pull-request-commits) does.

**Comment by nicolo-ribaudo** [comment]
My bad, I didn't notice that commits from 3c0d103 to 800c452 where, overall, empty. :sweat_smile: 	
I cherry-picked `f524311`.

**Pull request closed without merging**
