### PR TITLE
fix: enable transform-block-scoping with generators feature (#12806)

### PR DESCRIPTION
**Pull request by IlyaSemenov**
| Q                        | A
| ------------------------ | ---
| Fixed Issues?            | Workaround for #12806
| Patch: Bug Fix?          | 👍
| Major: Breaking Change?  | -
| Minor: New Feature?      | -
| Tests Added + Pass?      | 👍
| Documentation PR Link    | -
| Any Dependency Changes?  | -
| License                  | MIT

This adds `generators` to `transform-block-scoping` features:

https://github.com/babel/babel/blob/29426297d64315661b6407f331c304bba598d271/packages/babel-compat-data/scripts/data/plugin-features.js#L104-L106

as asked by @nicolo-ribaudo in #12806, and adds a regression test for Chrome 49 preset.

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/15606"></a>

### CODE REVIEW

**Comment by IlyaSemenov** [comment]
I am not sure why the tests wouldn't pass. It's like it's ignoring the new compat-data. 🤷

**Comment by JLHwung** [comment]
Can you also update `packages/babel-compat-data/data/plugin-bugfixes.json`? I believe that is why CI is failing.

**Comment by IlyaSemenov** [comment]
Updated. It passes all tests locally with `make test-only` and `yarn jest --ci`, but still fails some CI checks.

**Comment by nicolo-ribaudo** [comment]
I updated the Babel 8 tests, hopefully CI will be green now :)

**Review by JLHwung — APPROVED** [review]

**Review by nicolo-ribaudo — APPROVED** [review]

**Pull request merged**
