### PR TITLE
Update to Jest 28

### PR DESCRIPTION
**Pull request by JLHwung**
| Q                        | A 
| ------------------------ | ---
| Any Dependency Changes?  | Bump Jest to v28
| License                  | MIT

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/14490"></a>

### CODE REVIEW

**Comment by JLHwung** [comment]
CI error is due to https://github.com/facebook/jest/issues/12745.

**Comment by nicolo-ribaudo** [comment]
This should be rebased after merging https://github.com/babel/babel/pull/14488.

**Comment by nicolo-ribaudo** [comment]
@JLHwung Are you sure `jest.getVersion` is supposed to exist? It's not documented at https://jestjs.io/docs/jest-object :thinking:

**Comment by nicolo-ribaudo** [comment]
@JLHwung Are you sure `jest.getVersion` is supposed to exist? It's not documented at https://jestjs.io/docs/jest-object :thinking:

**Comment by SimenB** [comment]
It's not a thing - to get the version you'll need to parse `jest/package.json`

**Comment by nicolo-ribaudo** [comment]
Thanks!

**Comment by JLHwung** [comment]
> @JLHwung Are you sure `jest.getVersion` is supposed to exist? It's not documented at https://jestjs.io/docs/jest-object 🤔

Ah `jest.getVersion` does not exist in Jest 24.

It does exist in Jest 28:

https://github.com/facebook/jest/blob/8f9b812faf8e4d241d560a8574f0c6ed20a89365/packages/jest/src/index.ts#L11

**Comment by SimenB** [comment]
Ah!

That's `import {getVersion} from 'jest`, not the `jest` "global" (module scoped)

**Comment by nicolo-ribaudo** [comment]
The flaky failing e2e test is because `receiveMessageOnPort` sometimes returns `undefined`, even if we only ever wake the main thread after posting an object on the port. This looks like a Node.js bug :confused:

**Review by nicolo-ribaudo — APPROVED** [review]

**Comment by SimenB** [comment]
🎉

**Pull request merged**
