### PR TITLE
add failing test for infinite recursion

### PR DESCRIPTION
**Pull request by calvinmetcalf**

### CODE REVIEW

**Comment by sebmck** [comment]
Can I get some context?

**Comment by calvinmetcalf** [comment]
yes sorry 

```
class Foo{
  [Symbol.iterator](){
    return this;
  }
}
```

causes an infinite recursion error in 4.7.x

**Comment by sebmck** [comment]
When doing what? It compiles and executes fine.

**Comment by sebmck** [comment]
The output in `test/fixtures/bin/babel/infinite recursion error/stdout.txt` is pre-4.7.0 too.

**Comment by eventualbuddha** [comment]
@sebmck I had the same result, thought I might be doing something wrong.

@calvinmetcalf, can you give very explicit instructions on how to reproduce? Include npm or git commands required to get the failing build of babel.

**Comment by calvinmetcalf** [comment]
@sebmck yes the output is probably wrong there but when I run the test suite locally I get

```
 1) bin/babel infinite recursion error:
     Error: /Users/cmetcalf/projects/babel/bin/babel: stderr: "/Users/cmetcalf/projects/babel/lib/babel/helpers/parse.js:54\n    throw err;\n          ^\nRangeError: stdin: Maximum call stack size exceeded\n    at new Number (native)\n    at t.cloneDeep (/Users/cmetcalf/projects/babel/lib/babel/types/index.js:473:19)\n    at Array.map (native)\n    at Object.t.cloneDeep (/Users/cmetcalf/projects/babel/lib/babel/types/index.js:480:19)\n    at Object.t.cloneDeep (/Users/cmetcalf/projects/babel/lib/babel/types/index.js:478:17)\n    at t.cloneDeep (/Users/cmetcalf/projects/babel/lib/babel/types/index.js:478:17)\n    at Array.map (native)\n    at Object.t.cloneDeep (/Users/cmetcalf/projects/babel/lib/babel/types/index.js:480:19)\n    at t.cloneDeep (/Users/cmetcalf/projects/babel/lib/babel/types/index.js:478:17)\n    at Array.map (native)"
      at assertTest (/Users/cmetcalf/projects/babel/test/bin.js:45:11)
      at ChildProcess.<anonymous> (/Users/cmetcalf/projects/babel/test/bin.js:93:9)
      at emitTwo (events.js:87:13)
      at ChildProcess.emit (events.js:169:7)
      at maybeClose (child_process.js:984:16)
      at Socket.<anonymous> (child_process.js:1153:11)
      at emitOne (events.js:77:13)
      at Socket.emit (events.js:166:7)
      at Pipe.close (net.js:464:12)
```

**Comment by calvinmetcalf** [comment]
and the test does not fail here so wtf is wrong with my install

**Comment by calvinmetcalf** [comment]
adding these 2 files to a folder and then running npm install && npm test does it for me in iojs 1.4.2

https://gist.github.com/calvinmetcalf/8f2a4b14711e3fb59351

**Comment by calvinmetcalf** [comment]
make test_travis doesn't actually cause the error locally for me but make test-simple (or make test) does...

**Comment by neVERberleRfellerER** [comment]
@sebmck Infinite recursion is triggered by computed property usage. For some reason, it works in REPL and not locally.
In example provided by @calvinmetcalf , MemberExpression node is being cloned, but it contains `_paths` array, which contains objects with parent references and those references are creating cycles in object graph (`node._paths[0].parent` is `node` again).

**Comment by sebmck** [comment]
Works locally for me. I'm abstracting node metadata into a "path" that's
retained across replacements.

On Saturday, 7 March 2015, neVERberleRfellerER <notifications@github.com>
wrote:

> @sebmck <https://github.com/sebmck> Infinite recursion is triggered by
> computed property usage. For some reason, it works in REPL and not locally.
> In example provided by @calvinmetcalf <https://github.com/calvinmetcalf>
> , MemberExpression node is being cloned, but it contains _paths array,
> which contains objects with parent references and those references are
> creating cycles in object graph (node._paths[0].parent is node again).
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/babel/babel/pull/962#issuecomment-77686502>.
>


-- 
Sebastian McKenzie

**Comment by neVERberleRfellerER** [comment]
@sebmck Then I dare to say, that it does not work for you and that problem is on your side - infinite recursion is expected behavior.

When elements of `_paths` property of `MemberExpression` are being cloned (and they are, since every element of array is deeply cloned), it will eventually get to `container` property of first path. This `container` is `MemberExpression` itself and is being deeply cloned (it contains `type` property). Cycle begins.

Check this chain
```
node._paths[0].container._paths[0].container._paths[0].container
```
`node` is original `MemberExpression` from beginning.
`type` is present in `node` and in `node._paths[0].container`. That is enough to trigger infinite depth cloning.

**Comment by calvinmetcalf** [comment]
The fact that make travis didn't catch this is also worrying.

**Comment by sebmck** [comment]
@neVERberleRfellerER Can you replicate this? Because I can't. The code for `t.cloneDeep` is as follows:

```javascript
t.cloneDeep = function (node) {
  var newNode = {};

  for (var key in node) {
    var val = node[key];

    if (val) {
      if (val.type) {
        val = t.cloneDeep(val);
      } else if (Array.isArray(val)) {
        val = val.map(t.cloneDeep);
      }
    }

    newNode[key] = val;
  }

  return newNode;
};
```

There's no way `_paths` will ever be recursively cloned since if it's on an object it will be copied verbatim (this probably shouldn't happen but it's not a big deal since nothing is relying on paths yet) and if it's on an array it'll be ignored since `map` wont include it.

**Comment by neVERberleRfellerER** [comment]
@sebmck From the beginning to the end:
`MemberExpression` is passed to cloneDeep. Properties are enumerated and at some point `_paths` (name) is stored in `key`. Then `val = node[key]` exists and is an array. Since `val` is an array, following path is taken
```javascript
      } else if (Array.isArray(val)) {
        val = val.map(t.cloneDeep);
      }
```
So, every element in `_paths` array is deeply cloned. During this process, properties of first element are enumerated and at some time `container` property is *active* one (the one whose name is in `key`). At this point `val = node[key]` exists, is same as original `MemberExpression` and as such contains `type` property and thus following path is taken
```javascript
      if (val.type) {
        val = t.cloneDeep(val);
      }
```
Cycle begins by repeating whole process infinitely.

**Comment by sebmck** [comment]
Weird, wonder why I can't replicate it locally.

**Comment by calvinmetcalf** [comment]
Sweet! Thanks

**Comment by sebmck** [comment]
Fixed as of 4.7.2, thanks!

**Pull request closed without merging**
