### PR TITLE
Add test of import hoisting that fails when the runtime transform is used.

### PR DESCRIPTION
**Pull request by benjamn**
I believe the root of the problem is that the `._blockHoist` value of 3 assigned to import statements by `state.file.addImport` in the template literals transform is lost when the runtime transform turns that import statement into a `require` call, so that 3 never has the chance to be compared to the 1.9 value that we get when we call `addTemplateObject`.

If that theory is correct, then one possible approach to fixing the problem might be to copy the `._blockHoist` values from import statements over to the corresponding required variable declarations.

### CODE REVIEW

**Comment by benjamn** [comment]
I'm aware my second commit causes more problems than it fixes, but at least it fixes the failing test I introduced in the first commit.

**Comment by benjamn** [comment]
Created a Phabricator task for this: https://phabricator.babeljs.io/T6738

Should I close this PR?

**Comment by hzoo** [comment]
I don't think you need to close it if it can be a valid solution?

**Comment by benjamn** [comment]
Looking at this patch with new eyes, I realized the test failures were due to a small mistake, namely neglecting to check `blockHoist > 0` [here](https://github.com/babel/babel/pull/3118/files#diff-d14797ce7c2385d5701ea1ef6b4da702R172). Everything passes now!

**Comment by mathieumg** [comment]
I just got bit by this, would welcome this change very much as well! Thank you.

**Comment by amasad** [comment]
I'm not familiar with the module transform. cc @hzoo @loganfsmyth for review

**Comment by hzoo** [comment]
I wonder if we have other underscored properties that we add to the AST nodes? Those would also get removed in a similar way. Code looks fine if we want to do it this way but it would be nice if we didn't have specific handle it like that

**Comment by benjamn** [comment]
I can look into transferring other properties, but this fix seems important for more than one project that's trying to upgrade to Babel 6 (not just Meteor), so perhaps investigating other properties can be split into a follow-up task?

One thing to keep in mind is that one `import` statement can turn into multiple `require` declarations, which is why I'm computing that `.maxBlockHoist` property. While I don't know about any other underscored properties that might need to be transferred, I also don't know if it would make sense to duplicate those hypothetical properties across multiple declaration nodes. In other words, the logic for transferring each property might end up being specific to that property, which argues (in my mind) for handling them in separate commits/issues/tasks.

**Comment by hzoo** [comment]
@benjamn Yeah making that a follow-up sounds good to me and right it depends on the property (if there are any more)

**Comment by kittens** [comment]
Extremely sorry for the turnaround in getting this in @benjamn.

**Comment by benjamn** [comment]
All good! Thanks much

**Pull request merged**
