### PR TITLE
Update polyfill plugins

### PR DESCRIPTION
**Pull request by nicolo-ribaudo**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | 
| Patch: Bug Fix?          |
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

The breaking change is just that I added `exports` to `package.json` of those plugins, so internal files aren't accessible anymore. We can safely update them, since this breaking change isn't reflected to our users.

Changelog: https://github.com/babel/babel-polyfills/compare/babel-plugin-polyfill-corejs2%400.1.10...babel-plugin-polyfill-corejs2%400.2.0

### CODE REVIEW

**Comment by nicolo-ribaudo** [comment]
This also changes how `@babel/standalone` is bundled, since Rollup will probably use the ESM version of these plugins instead of the CJS one.

**Comment by hzoo** [comment]
The changes in import order in tests are from https://github.com/babel/babel-polyfills/pull/78?

**Comment by nicolo-ribaudo** [comment]
Yes!

**Review by hzoo — APPROVED** [review]

**Review by JLHwung — APPROVED** [review]

**Comment by nicolo-ribaudo** [comment]
> I'll make sure that it works before merging this one.

There are some problems when updating the rollup plugin, but it's not related to these updates.

**Pull request merged**
