### PR TITLE
Fix generator missing parens on Flow union types

### LINKED ISSUE #6333: [babel-generator] Missing parens around some flow types
Choose one: bug report

Babel generates `?any | any` instead of `?(any | any)`.

### Input Code

```js
const gen = require('babel-generator').default;
const t = require('babel-types');

function exportType(name, type) {
  return t.exportNamedDeclaration(
    t.typeAlias(t.identifier(name), null, type),
    [],
    null,
  );
}

const ast = t.program([
  exportType(
    'test',
    t.nullableTypeAnnotation(
      t.unionTypeAnnotation([
        t.anyTypeAnnotation(),
        t.anyTypeAnnotation()
      ]),
    ),
  ),
]);

const code = gen(ast).code;
console.log(code);
```

### Babel Configuration (.babelrc, package.json, cli command)

babel 6.26

### Expected Behavior
`?(any | any)`

### Current Behavior
`?any | any`

### Possible Solution
fix up logic parenthesis.js of babel-generator?

### Context
This is a bit of a contrieved example, but it makes a difference for other cases like `?A & B` is always a `B`, while `?(A & B)` means either `null` or both `A` and `B`.

### Your Environment
| software         | version(s)
| ---------------- | -------
| Babel            |  6.x
| node             |  8.6.0
| yarn              |  1.0
| Operating System | 
osx

### PR DESCRIPTION
**Pull request by existentialism**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues             | Fixes #6333
| Patch: Bug Fix?          | 
| Major: Breaking Change?  | 
| Minor: New Feature?      | 
| Tests Added/Pass?        | 
| Spec Compliancy?         | 
| License                  | MIT
| Doc PR                   | 
| Any Dependency Changes?  |

### CODE REVIEW

**Comment by kassens** [comment]
Not clear to me from the code if this also covers `?(A & B)`.

**Comment by existentialism** [comment]
@kassens yep, I just added intersections too.

**Comment by kassens** [comment]
It's getting more edge casey, but I think you might want to account for this too while you're at it:
```
type foo = a & (b | c);
type foo = (a | b) & c;
```
& seems to have higher precedence, at least according to the flow parser at astexplorer.net

**Comment by existentialism** [comment]
@kassens yep, updated!

**Pull request merged**
