### PR TITLE
Merge env options with base ones

### LINKED ISSUE #4539: env is being ignored in preset
### Babel Configuration (.bablerc, package.json, cli command)

this is my preset config: https://github.com/foray1010/babel-preset-foray1010/blob/d86899e005cde00541251d193c1dce70df316217/react.js

``` js
{
  presets: [
    require('babel-preset-es2015'),
    require('babel-preset-stage-2')
  ],
  plugins: [
    require('babel-plugin-transform-decorators-legacy').default,
    [require('babel-plugin-transform-react-jsx'), {
      pragma: 'createElement'
    }]
  ],
  env: {
    production: {
      plugins: [
        require('babel-plugin-transform-react-constant-elements'),
        require('babel-plugin-transform-react-inline-elements'),
        require('babel-plugin-transform-react-remove-prop-types').default
      ]
    },
    test: {
      plugins: [
        require('babel-plugin-istanbul')
      ]
    }
  }
}
```

this is how I require this preset it in another repo

``` json
{
  "presets": [
    "babel-preset-foray1010/react"
  ]
}
```

I am sure I set correct NODE_ENV to production, I can see process.env.NODE_ENV => production when I console.log in the preset file
### Expected Behavior

`babel-plugin-transform-react-constant-elements`, `babel-plugin-transform-react-inline-elements`, `babel-plugin-transform-react-remove-prop-types` should be used
### Current Behavior

None of them are being used, but when I put env config into the project .babelrc directly, it works
### Context

I want to share my react babel config to all my react project, and there are some plugins that I will only run in production, so I don't want to repeat myself every time in the babelrc on how to handle different env
### Your Environment

| software | version |
| --- | --- |
| Babel-core | 6.14.0 |
| node | 4.5.0 |
| npm | 3.10.7 |
| Operating System | Ubuntu 16.04 |

### LINKED ISSUE #5275: Unexpected env option behaviour
### Babel Configuration (.babelrc, package.json, cli command)
This config does not work.
```js
{
    "presets": [
      "react"
     ],
     "plugins": [
          "transform-class-properties"
     ],
    "env": {
      "es6": {
        "presets": [
          "es2016"
        ]
      },
      "es5": {
        "presets": [
          "es2015"
        ]
      }
    }
  }
```

But, this config works.
```js
{
    "presets": [
      "react"
    ],
    "env": {
      "es6": {
        "presets": [
            "es2016"
          ],
        "plugins": [
          "transform-class-properties"
        ]
      },
      "es5": {
        "presets": [
          "es2015"
        ],
        "plugins": [
          "transform-class-properties"
        ]
      }
    }
  }
```
Code in action:

Failing build:
https://travis-ci.org/vkbansal/react-contextmenu/builds/199246315

Working build:
https://travis-ci.org/vkbansal/react-contextmenu/builds/199253625

### PR DESCRIPTION
**Pull request by mdarse**
| Q                        | A 
| ------------------------ | ---
| Patch: Bug Fix?          | yes
| Major: Breaking Change?  | no?
| Minor: New Feature?      | no
| Deprecations?            | no
| Spec Compliancy?         | 
| Tests Added/Pass?        | yes
| Fixed Tickets            | Fixes #5275, Fixes #4539
| License                  | MIT
| Doc PR                   | no
| Dependency Changes       | no

Hi everyone,

Right now, using the `env` option overrides the base config. This PR makes environment specific options inherit from base options.

Current strategy is to do a *shallow merge* of options. No merge of plugins of presets is done here. Deep merging is error-prone (they may have options to merge too), and would only allow additive changes in environment specific config. We would not be able to remove a plugin from config by example.

I'm not sure what the current behaviour of `extends` is but we may want to have the same here.

### CODE REVIEW

**Comment by mdarse** [comment]
Well, we may be able to not have additive config only if we add some specific syntax like:
```
{
  plugins: ["foo"]
  env: {
    production: {
      plugins: ["!foo"]
    }
  }
}
```

**Comment by mdarse** [comment]
@hzoo Can I make something to help getting this merged?

**Comment by loganfsmyth** [comment]
I think the team as a whole things `env` is confusing and probably not something that is going to behave for everyone's usecase. The plan at the moment is to land https://github.com/babel/babel/pull/4892 and let people do their own merging based on their needs.

Your proposed change would definitely be breaking, since many people rely on the current behavior of having env-specific behavior merged with the base config rather than overriding it, so I don't think we could safely land this.

**Comment by hzoo** [comment]
Hey @mdarse, thanks for the PR and the work you put into fixing this issue! Unfortunately, we think it's best if we eventually drop support for this option and ask users to go with a .babelrc.js file.

We're going to go with deprecating "env" as an option in 7.0 and asking for users to use a `.babelrc.js` file to support this use case (https://github.com/babel/babel/pull/4892). Basically the workaround is the new suggestion since it's not too much of a pain to do. We can think about writing some utils or just recommending what's done for webpack like https://github.com/kentcdodds/webpack-config-utils.

Let us know your thoughts

**Comment by mdarse** [comment]
I understand your approach, and landing #4892 would allow a more powerful configuration.
I was hoping to fix `env` behavior because it's the only tool to have environment specific configuration from `package.json#babel`.

**Pull request closed without merging**
