### PR TITLE
Add __moduleName support to System.register

### PR DESCRIPTION
**Pull request by guybedford**
See https://github.com/systemjs/builder/issues/416 for the discussion here.

Ideally this would only add the argument to modules that explicitly use a `__moduleName` reference. My Babel plugin knowledge is still pretty limited, so any suggestions how to quickly check if `__moduleName` is a bound to the outer scope and omit it in this case would be very welcome.

### CODE REVIEW

**Comment by guybedford** [comment]
*nudge*

Just let me know if you have any questions here at all.

**Comment by sebmck** [comment]
Seems weird to expose this magic variable when none of the other module formatters do.

**Comment by guybedford** [comment]
CommonJS has the exact same feature via `module.id`. We could use a contextual object that has a `key` or `id` property similarly too.

**Comment by sebmck** [comment]
`module` isn't exposed via the CommonJS module formatter though, it's just consequent of the loader.

**Comment by guybedford** [comment]
Yes it's an environment variable assumed by the format. ES modules will have contextual data via a special contextual import syntax to avoid the scope assumptions that CommonJS does. Support for that will be via this argument in System.register. I agree an object may be a more extensible approach though.

The build problem currently is that `__moduleName` needs to be provided somehow. When building CommonJS we have a transport wrapper of `System.registerDynamic` but because `System.register` already is a transport wrapper, adding another wrapper on top of that with `__moduleName` is not ideal.

**Comment by guybedford** [comment]
Ok I've updated the PR to rather use a `_context` argument that can be extended in future to accommodate the full context specification. Let me know your thoughts!

I know `__moduleName` is pretty hideous on review, but this is by design - it's just a placeholder for the module name until the contextual spec comes along eventually, so the syntax should reflect this impermanence.

To reiterate on the use case, the point is that `System.register` is a transport format (unlike CommonJS), so it should provide all the features needed to run the module in context with no further wrapping. The reason for this was CSP use cases, otherwise `System.register` could have just been a binary format.

Hoping to get a jspm 0.17 alpha out pretty soon, just let me know if you have any further questions at all.

**Comment by kittens** [comment]
Sorry for the delay @guybedford, looks good!

**Comment by guybedford** [comment]
Thanks so much!

**Pull request merged**
