### PR TITLE
Add modulus operator

### LINKED ISSUE #3068: Error with generator function with modulus operator
Input:

```
const ops = {
  *["%"] (a, b) { return (yield toPrimitive(a)) % (yield toPrimitive(b)); }
}
```

Error:

```
Property operator expected value to be one of ["+","-","/","*","**","&","|",">>",">>>","<<","^","==","===","!=","!==","in","instanceof",">","<",">=","<="] but got "%""
```

### PR DESCRIPTION
**Pull request by jrsearles**
Fixes #3068

### CODE REVIEW

**Comment by thejameskyle** [comment]
@jrsearles mind adding a regression test to catch this?

**Comment by jrsearles** [comment]
Sure, i'll try. I'm having trouble getting the tests to run in Windows.

**Comment by thejameskyle** [comment]
@jrsearles If you need help you can join our slack channel: http://slack.babeljs.io/

**Comment by jrsearles** [comment]
After looking at this quite a bit it doesn't look like the tests in "babel-plugin-transform-regenerator" are running as part of the test suite, because the they are in the directory ".test" instead of "test". I'm assuming this is deliberate because renaming the dir causes the suite to fail. These tests don't appear to follow the conventions of the other tests i am seeing in other modules. What's the state of these tests?

**Comment by sebmck** [comment]
The entire module was pulled in when Babel 6 was released. The default regenerator tests haven't been converted to the Babel test runner though. I don't think this needs any tests (it'd literally just be an `indexOf` which IMO those tests are useless and catch 0 bugs) so I'll merge as-is. Thanks!

**Pull request merged**
