### PR TITLE
Add babel.analyze

### PR DESCRIPTION
**Pull request by kittens**
Simple API sugar. Usage is in the tests.

### CODE REVIEW

**Comment by kittens** [comment]
Maybe this should be `analyse`. What convention do we follow with other public APIs? Pretty sure it'd be British s rather than American z because I named them.

**Comment by hzoo** [comment]
Probably - would an alias for both be bad?

**Comment by kittens** [comment]
Probably a good idea we keep the API light. Supporting this API at all is a bit of a stretch since it's just an alias to make life easier for consumers.

**Comment by kittens** [comment]
Updated to `analyse`.

**Comment by hzoo** [comment]
looks good

**Pull request merged**
