### PR TITLE
Add ??= to Logical Assignment Operators

### PR DESCRIPTION
**Pull request by jridgewell**
`??=` is being merged into the Logical Assignment Operator proposal, and the overall proposal will wait until nullish coalescing is finalized.

### CODE REVIEW

**Comment by loganfsmyth** [comment]
@jridgewell This PR seems to be causing Flow errors. 

```
Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ packages/babylon/src/tokenizer/index.js:610:12

Cannot call this.expectPlugin because property expectPlugin is missing in Tokenizer [1].

 [1] 125│ export default class Tokenizer extends LocationParser {
        :
     607│     const next = this.input.charCodeAt(this.state.pos + 1);
     608│     const next2 = this.input.charCodeAt(this.state.pos + 2);
     609│     if (next === charCodes.questionMark) {
     610│       this.expectPlugin("nullishCoalescingOperator");
     611│
     612│       if (next2 === charCodes.equalsTo) {
     613│         // '??='


Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ packages/babylon/src/tokenizer/index.js:614:14

Cannot call this.expectPlugin because property expectPlugin is missing in Tokenizer [1].

 [1] 125│ export default class Tokenizer extends LocationParser {
        :
     611│
     612│       if (next2 === charCodes.equalsTo) {
     613│         // '??='
     614│         this.expectPlugin("logicalAssignment");
     615│         this.finishOp(tt.assign, 3);
     616│       } else {
     617│         // '??'



Found 2 errors
```

**Comment by jridgewell** [comment]
Does this need `$FlowFixMe`s? Also, why the hell do we need `$FlowFixMe`?

**Comment by loganfsmyth** [comment]
No, it's a legit error. You moved the calls into the `Tokenizer` class, but those helpers are defined in a subclass, so from a type standpoint it is possible that there'd be an instance of `Tokenizer` where `expectPlugin` doesn't exist.

**Comment by loganfsmyth** [comment]
I think generally I'd expect checks like this to live in the parser, with the tokenizer being fine to tokenize it, even if it isn't allowed. Then the parser can just throw on the unexpected token.

**Comment by jridgewell** [comment]
Ohhh, I'll get this fixed.

**Pull request merged**
