### PR TITLE
Replace node7 to node8 in .travis.yml for 7.0 branch

### LINKED ISSUE #5804: Add node 8 to travis config
We currently only test babel with node 7,6 and 4. 

We should also test against node 8: 
- [ ] edit `.travis.yml` and add node 8 there. 
- [ ] use node 8 locally and run tests to see if it works (see [CONTRIBUTING.md](https://github.com/babel/babel/blob/master/CONTRIBUTING.md) )
- [ ] if tests fail try to figure out why and fix
- [ ] if not clear why tests fail, ask here or create PR and ask in PR.

We also want to check babel 6.x works with node 8 so this changes can be done for the following branches:
- [ ] master
- [ ] 7.0

---
- [ ] Comment below you are going to do this (for others to know): `"I'd like to work on this for branch <BRANCHNAME>"`
- [ ] Check you are on the correct branch with `git checkout 7.0` or `git checkout master` and then make a branch off of that to PR

### PR DESCRIPTION
**Pull request by egoroof**
| Q                        | A 
| ------------------------ | ---
| Patch: Bug Fix?          |  yes
| Major: Breaking Change?  | no
| Minor: New Feature?      | no
| Deprecations?            | 
| Spec Compliancy?         | 
| Tests Added/Pass?        | 
| Fixed Tickets            | Fixes #5804 
| License                  | MIT
| Doc PR                   | 
| Dependency Changes       | 

Replace node7 to node8 in travis

### CODE REVIEW

**Comment by egoroof** [comment]
2 tests has failed:

```
 1) bin/babel-node v8Flag-dashed-with-param:
     Error: "/home/travis/build/babel/babel/packages/babel-cli/lib/babel-node" "--presets" "/home/travis/build/babel/babel/packages/babel-preset-es2015,/home/travis/build/babel/babel/packages/babel-preset-react" "--plugins" "/home/travis/build/babel/babel/packages/babel-plugin-transform-strict-mode,/home/travis/build/babel/babel/packages/babel-plugin-transform-es2015-modules-commonjs" "--only" "../../../../packages/*/test" "--expose-debug-as=customDebug" "--eval" "console.log(customDebug.Debug.DebugEvent.Break)": stderr:
error: unknown option `--expose-debug-as'
      at assertTest (packages/babel-cli/test/index.js:56:11)
      at ChildProcess.<anonymous> (packages/babel-cli/test/index.js:131:9)
      at maybeClose (internal/child_process.js:887:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
  2) bin/babel-node v8Flag-underscored-with-param:
     Error: "/home/travis/build/babel/babel/packages/babel-cli/lib/babel-node" "--presets" "/home/travis/build/babel/babel/packages/babel-preset-es2015,/home/travis/build/babel/babel/packages/babel-preset-react" "--plugins" "/home/travis/build/babel/babel/packages/babel-plugin-transform-strict-mode,/home/travis/build/babel/babel/packages/babel-plugin-transform-es2015-modules-commonjs" "--only" "../../../../packages/*/test" "--expose_debug_as=customDebug" "--eval" "console.log(customDebug.Debug.DebugEvent.Break)": stderr:
error: unknown option `--expose_debug_as'
      at assertTest (packages/babel-cli/test/index.js:56:11)
      at ChildProcess.<anonymous> (packages/babel-cli/test/index.js:131:9)
      at maybeClose (internal/child_process.js:887:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
```

**Comment by egoroof** [comment]
The end :)

**Comment by xtuc** [comment]
I'm sorry to hear that, still thanks for your contribution :+1:

**Comment by egoroof** [comment]
I'm sorry for taking your time

**Pull request closed without merging**
