### PR TITLE
Now babel searches presets relative the script path (process.argv[1]).

### PR DESCRIPTION
**Pull request by mrtrizer**
I had a problem when tried compile files outside the project dir. When I did so, I have an error: "Couldn't find preset es2015"

### CODE REVIEW

**Comment by mrtrizer** [comment]
Possible, this commit is conflicts with some main ideas. May be there are some another way to solve my problem.

**Comment by jmm** [comment]
Hello @mrtrizer. Thank you for your interest in contributing to Babel. However, I'm afraid there isn't enough information here for this to be mergeable. If you want something like this merged please provide a more complete explanation of the before and after situation, like an example directory structure and how Babel would be invoked.

> Possible, this commit is conflicts with some main ideas.

I think there's a good chance of that, but if so it highlights the need for some more tests since this is passing.

How are you invoking Babel -- if you're using the API are you passing an absolute pathname as the value of the `filename` option?

> May be it is some another way to solve my problem.

In the future please see the support channels listed in the `README` before going to the trouble of PR'ing new behavior.

Thanks!

**Comment by mrtrizer** [comment]
Example
I have a script this path: /some/path/somescript.js
I am compiling sources from: /another/path/src/*.js
And here I need node_modules folder with installed preset so:
/build-script/path/somescript.js 
/sources/path/src/*.js
/sources/path/node_modules/babel-preset-es2015

So, it seems useful when I use different presets for sources in different directories. But I need a possibility to use presets from building script so:
/build-script/path/somescript.js
/build-script/path/node_modules/babel-preset-es2015
/sources/path/src/*.js

Finally, I want give sources path to my build-script, watch for them and build on changing. Of course, I can just copy modules I need, to to the sources path. May be it will be the right way.
I hope, I described my problem clearly enough.

**Comment by jmm** [comment]
@mrtrizer Please mark up code in comments. See these [tips](https://github.com/substack/node-browserify/wiki/How-to-report-issues-with-browserify#formatting) if you're unfamiliar with how to do it.

The explanation is a bit hard for me to follow, but I think I get the gist of it. Based on your explanation it sounds like you're using the Babel API and want to locate the presets in relation to your build script. In that case, you should be able to require them directly in your build script and pass them to the API, e.g.:

```js
babel.transform(input, {
  presets: [require("babel-preset-es2015")],
});
```

**Comment by mrtrizer** [comment]
Yes. Thank you. This helped. Sorry for my hurry.

**Pull request closed without merging**
