### PR TITLE
Permit %%placeholder%% in left-hand-side of a let declaration

### LINKED ISSUE #12717: Template parser can't handle let declaration with syntactic placeholder variable
## Bug Report

- [X] I would like to work on a fix!

**Current behavior**

When `template` is called with a `let` statement containing a syntactic placeholder for the variable (e.g. `let %%foo%% = 1`), the parser rejects it and mysteriously complains about `Unexpected reserved word 'let'`.

```js
Welcome to Node.js v15.6.0.
Type ".help" for more information.
> require("@babel/template/package.json").version
'7.12.7'
> template = require("@babel/template").default
> template("let %%foo%% = 1")()
Uncaught [SyntaxError: Unexpected reserved word 'let' (2:0)
  1 | /* @babel/template */;
> 2 | let %%foo%% = 1
    =============
] {
  loc: Position { line: 2, column: 0 },
  pos: 23,
  code: 'BABEL_TEMPLATE_PARSE_ERROR'
}
```

**Input Code**

```js
template("let %%foo%% = 1")({ foo: "x" });
```

These also give the same syntax error:

```js
template.statement("let %%foo%% = 1")({ foo: "x" });
template.statements("let %%foo%% = 1")({ foo: "x" });
template.program("let %%foo%% = 1")({ foo: "x" });
```

**Expected behavior**

The template invocation should return an AST for `let x = 1`.

These invocations return an AST as expected:

```js
// No placeholder
template("let x = 1")();

// Identifier placeholder
template("let FOO = 1;")({ FOO: "x" });

// const or var instead of let
template("const %%foo%% = 1")({ foo: "x" });
template("var %%foo%% = 1")({ foo: "x" });

// Ordinary identifier appears first
template("let a = 0, %%foo%% = 1")({ foo: "x" });

// Array destructuring
template("let [%%foo%%] = []")({ foo: "x" });
```

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**

- Importing `@babel/template` directly from the Node repl; no Babel config.

**Environment**

```
$ npx envinfo --preset babel

  System:
    OS: macOS High Sierra 10.13.6
  Binaries:
    Node: 15.6.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.4.0 - /usr/local/bin/npm
  npmPackages:
    @babel/template: ^7.12.7 => 7.12.7 
```

I can also reproduce this in AST Explorer and in RunKit, so it's unlikely to be environment-specific.

**Possible Solution**

**Additional context**

### PR DESCRIPTION
**Pull request by Zalathar**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #12717 
| Patch: Bug Fix?          | Yes
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

This change adds support for template syntactic placeholders in the left-hand-side of a `let` declaration (e.g. `let %%lhs%% = 7`).

This already works for `var` and `const`, but wasn't working for `let` because the special handling needed to disambiguate let-as-keyword vs let-as-identifier didn't know to treat a following placeholder as though it were a variable.

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/12725"></a>

### CODE REVIEW

**Comment by Zalathar** [comment]
There are a few different ways to implement this.

I didn't like the idea of overriding `isLet` in the placeholder plugin, because then I'd have to copy-paste a bunch of code from the base implementation, which seems needlessly messy.

So my choice was between adding adding a very narrow hook method that the plugin could override, or just adding ad-hoc code directly in the parser itself.

I went with the ad-hoc code because it's very straightforward and compact, and that seems worth the downside of having placeholder code that lives outside the placeholder plugin.

**Comment by Zalathar** [comment]
I'd like to add some explicit test cases for `let % x` and `let %%x%%` when the placeholders plugin is *not* being used, but I'm not quite sure where to put them.

**Review by nicolo-ribaudo — COMMENTED** [review]
I would really prefer to keep this code in `placeholders.js`, even if we would then have to duplicate `this.isContextual("let")`.

This isn't an hot code path (usually the placeholders plugin is not enabled), and even when perf matters the `isContextual` function is not expensive.

Btw, thanks for also adding tests for the `let %%LHS%%;` case!

**Comment by Zalathar** [comment]
> Btw, thanks for also adding tests for the `let %%LHS%%;` case!

Just to be clear, I have only added tests for `let %%LHS%% = %%RHS%%;` (with initializer), for the initializer forms with `var`/`const`, and for the *negative* case `let %RHS;` where the `%` should be parsed as modulo.

I had also written tests for `let %%LHS%%;` (without initializer), but I didn't add them in this PR because they fail, with or without this patch! That's a separate issue that will need a separate fix.

**Comment by nicolo-ribaudo** [comment]
>  and for the negative case let %LHS; where the % should be parsed as modulo

Sorry I was tired 🙃

**Comment by Zalathar** [comment]
I'm rather baffled by my new failure test (`let context 3`) producing a subtly different error under CI.

**Comment by nicolo-ribaudo** [comment]
I think it could be because GitHub runs CI not on your branch, but on the result of merging your branch in `main`.
We recently merged https://github.com/babel/babel/commit/8cf0a757d5534d07fb609d69aecbc1f21b31379b, which could cause the test failure.
Could you try rebasing on `main`?

**Review by nicolo-ribaudo — APPROVED** [review]
Thanks!

**Review by JLHwung — APPROVED** [review]

**Pull request merged**
