### PR TITLE
[transform-typescript] Fix import elision for type exports

### LINKED ISSUE #12121: [PR included!] [transform-typescript] Imports which used only in type exports is not elided
## Bug Report

- [X] I would like to work on a fix!

**Input Code**

```js
import A, { T } from './mod';
A;
export type { T };
```

**Current behavior**
Imports which used only in type exports is not elided.
```js
import A, { T } from './mod';
A;
```

**Expected behavior**
Import should be removed since is used in types only.
```js
import A from './mod';
A;
```

**Possible Solution**
PR are ready, just added type exports checking.

### PR DESCRIPTION
**Pull request by Amareis**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #12121 
| Patch: Bug Fix?          | Yes
| Major: Breaking Change?  | No
| Minor: New Feature?      | No
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  | No
| License                  | MIT

Pretty small change.

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/12122"></a>

### CODE REVIEW

**Review by nicolo-ribaudo — APPROVED** [review]
Thanks!

**Review by existentialism — APPROVED** [review]

**Comment by Amareis** [comment]
Looks like it's not my code error, but some unrelated infrastructure fail.

**Comment by JLHwung** [comment]
@Amareis The e2e error has been fixed on upstream. Please rebase.

**Review by JLHwung — APPROVED** [review]

**Comment by Amareis** [comment]
> @Amareis The e2e error has been fixed on upstream. Please rebase.

Done.

**Pull request merged**
