### PR TITLE
Revert "Differentiate object spread and non-spread properties (#9341)"

### LINKED ISSUE #9376: Cannot convert undefined or null to object
## Bug Report

image

bug version: `@babel/runtime 7.3.0`,  #9334

### PR DESCRIPTION
**Pull request by danez**
This reverts commit 3ae5e79ec8ab1e6d1c6927f35d4a1eeac04faf9a.

| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #9376
| Patch: Bug Fix?          | y
| Major: Breaking Change?  | reverse breaking change
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

Not sure what the actual issue is yet, but it seems to throw in some cases.

### CODE REVIEW

**Comment by saschanaz** [comment]
It seems it's because some environments doesn't support `Object.getOwnPropertyDescriptors`.

**Comment by nicolo-ribaudo** [comment]
@saschanaz Do you want to open a PR moving these new changes to a new `objectSpread2` helper? That way old code won't be broken by the new helper.

**Comment by saschanaz** [comment]
Yep, I'll do in a minute.

**Comment by loganfsmyth** [comment]
@saschanaz I wouldn't rush, we can review a second pass on this in a future release.

**Comment by danez** [comment]
The problem is for example this (which seems unlikely someone would do that, but there are probably other cases):

```
var a = { ...null, ...undefined };
```

in babel 7.2 this gets generated:
```
var a = _objectSpread({}, null, undefined);
```

in babel 7.3 this gets generated:
```
var a = _objectSpread({}, null, {}, undefined);
```

**Comment by saschanaz** [comment]
I don't think adding `{}` there would cause any problem, though?

**Comment by danez** [comment]
the problem is, that the code generated in 7.2 without `{}` still needs to work with the new helper.
and as we do `i%2` the first `t` will be in the `if(i%2)` clause of the helper the other `t` will be in the `else` branch. and if t is null `Object. getOwnPropertyDescriptors(null)` will throw.

**Pull request merged**
