### PR TITLE
add some more flow types

### PR DESCRIPTION
**Pull request by hzoo**
Also revert https://github.com/babel/babel/pull/3275

### CODE REVIEW

**Comment by amasad** [comment]
failing

**Comment by hzoo** [comment]
This is only passing on node 5

```
packages/babel-code-frame/src/index.js:6
  6: import esutils from "esutils";
                         ^^^^^^^^^ esutils. Required module not found
```

so i'm assuming this is an issue with npm 2?

**Comment by amasad** [comment]
let me know when this is ready :nail_care:

**Comment by hzoo** [comment]
I suppose it is (since it finally passes)? I dono what is going on with ^ `esutils. Required module not found` - it sounds like it has to do with how flow does require statements and something with npm 2 since it works in node 5 / npm 3. I had to remove flowcheck from those 2 files

**Comment by amasad** [comment]
Is it hard to update the CI to node 5 / npm 3?

**Comment by hzoo** [comment]
What do you mean? https://github.com/babel/babel/blob/master/.travis.yml our travis has 0.10, etc which are all npm 2. Do you mean doing something like `npm install npm@3 -g` for the older versions?

**Comment by amasad** [comment]
That or maybe just run flow on node 5 environments:

```
node_v=`node -v`
if [ "$node_v" = "v5.5.0" ]; then flow; fi
```

or something like that

**Comment by hzoo** [comment]
Ooh something like that sounds good actually

**Comment by amasad** [comment]
Yeah needs a bit more bash fu than I have to parse the int but it's doable.

**Comment by hzoo** [comment]
time to google (or I just write it in js and call the script).

**Comment by amasad** [comment]
Lol why not

**Comment by hzoo** [comment]
Ok probably lazy/unnecessary but it works.

**Comment by amasad** [comment]
Cool, do you want to revert the noflow checks you had to add?

**Comment by hzoo** [comment]
Yeah I did already :sunglasses:

**Comment by hzoo** [comment]
Although I think I can remove some more

**Pull request merged**
