### PR TITLE
rename scope bindings during block scope transform

### PR DESCRIPTION
**Pull request by schmod**
See https://phabricator.babeljs.io/T7091

### CODE REVIEW

**Comment by hzoo** [comment]
I think this will need some tests - we can help you with this if you don't know how it's done.

Can check out https://github.com/babel/babel/blob/master/CONTRIBUTING.md#writing-tests although this one will be asserting the bindings

**Comment by schmod** [comment]
Thanks.  I somehow missed the `exec.js` kind of test when I skimmed through that document.  I'll go write something up.

**Comment by schmod** [comment]
Actually, I can't really seem to find any other plugin/transformation tests that examine the internals of the AST transformation.  

Would appreciate some guidance about how you think this should be tested.

**Comment by amasad** [comment]
`scope.rename` is inefficient because it does a traversal but obviously this is important for correctness. Thank you

**Pull request merged**
