### PR TITLE
Replace custom "fundSuggestion" function with "levenary"

### PR DESCRIPTION
**Pull request by nicolo-ribaudo**
| Q                        | A 
| ------------------------ | ---
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  | Yes
| License                  | MIT

This PR is extracted from https://github.com/babel/babel/pull/10899. In https://github.com/babel/babel/pull/10899 I needed to use the `findSuggestion` function in two different libraries, so I would have had to duplicate that code.
Instead of duplicating it, I decided to dig into the universe of fastest levenshtein distance functions on npm to find one with the interface that we actually need.
I initially used `didyoumean2`, but then switched to `levenary` because:
1) it's faster and because :wink:
2) it's created by @tanhauhau 
3) it provides flow typings out of the box.

I extracted this commit to a separate PR because @JLHwung is going to work on some content which touches similar lines/depends on this package, so we can merge this without waiting for https://github.com/babel/babel/pull/10899.

### CODE REVIEW

**Comment by tanhauhau** [comment]
Published [levenary@1.1.0](https://www.npmjs.com/package/levenary/v/1.1.0) with @JLHwung's PR https://github.com/tanhauhau/levenary/pull/1

**Comment by SimenB** [comment]
This is a breaking change - levenary depends on Node 8

**Comment by SimenB** [comment]
`leven` itself [is node 6](https://github.com/sindresorhus/leven/blob/252edb6e8c274b78fbc3a3bc4a01b4896a513354/package.json#L13), so it should just be a matter of downgrading the requirement in `levenary`: https://github.com/tanhauhau/levenary/pull/3. Hopefully that's all that's needed

**Comment by nicolo-ribaudo** [comment]
Thanks for catching this! cc @tanhauhau

**Pull request merged**
