### PR TITLE
Move `environment-visitor` helper into `@babel/traverse`

### PR DESCRIPTION
**Pull request by nicolo-ribaudo**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | `Fixes #1, Fixes #2` 
| Patch: Bug Fix?          |
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

I'm working on removing cycles between packages caused by type-only imports. My motivation is that, even if it's a type-only import, it's an actual conceptual cycle and those packages will always be used together anyway. For example:
- `@babel/traverse` depends on `@babel/helper-environment-visitor`
- `@babel/helper-environment-visitor` does not **explicitly** depend `@babel/traverse`, but it can only be used on `NodePath`s so it can only be used when `@babel/traverse`

This has two benefits:
- when publishing TS types we'll need to mark them as actual dependencies, and having cycles between packages causes problems
- we reduce the number of packages

### CODE REVIEW

**Review by JLHwung — COMMENTED** [review]
I recall previously we imported the `traverse` from their peer dependent `@babel/core` because of compatibility issues. Specifically we want the core, even if it is an old version, to explode any AST alias so that the traverser, imported from `core`, will not complain about any new AST types beyond its knowledge.

Now that `visitors.environmentVisitor` will explode the visitors via `merge` from the latest `traverse`, maybe we have to defer this change to Babel 8?

**Comment by nicolo-ribaudo** [comment]
@JLHwung Most of the plugins changed in this PR already _import_ their traverse (either from `@babel/core` or from `@babel/traverse`) rather than using the one passed as a parameter to the plugin function, so they are already potentially subject to this issue.

I will revert the change for the plugins that currently use the function parameter, so that we don't risk breaking something that is currently working.

**Comment by nicolo-ribaudo** [comment]
Actually, the only packages where we are potentially introducing the problem is `@babel/plugin-bugfix-firefox-class-in-computed-class-key`. The only problematic node type is `StaticBlock`, which is present in the environment visitor (since it is a `FunctionParent`) but was only introduced in Babel 7.12.0.

I'll add a little check for it.

**Review by JLHwung — APPROVED** [review]

**Review by liuxingbaoyu — APPROVED** [review]

**Comment by nicolo-ribaudo** [comment]
Whops, I meant to mark as ready and I merged 😅

I guess it's fine given that we are close to a release, but I'll revert if needed.

**Pull request merged**
