### PR TITLE
Remove stage presets from the monorepo

### PR DESCRIPTION
**Pull request by nicolo-ribaudo**
| Q                        | A 
| ------------------------ | ---
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

`babel/babel-archive` already includes the last working version of these presets (v7.0.0-beta.52), and they have been throwing since 7.0.0

### CODE REVIEW

**Comment by nicolo-ribaudo** [comment]
Probably yes, but now they are hardcoded in `@babel/standalone` (sigh).
Maybe we could remove them from `@babel/standalone` in Babel 8 and hard-code it in `babel/website`.

**Comment by hzoo** [comment]
Oh right! We'll we aren't expecting anyone to be using any stage presets anymore for a long time now so we could remove it there too. It's only for convenience in the repl and that we haven't made the UI change there?

**Comment by nicolo-ribaudo** [comment]
> It's only for convenience in the repl and that we haven't made the UI change there?

Yeah, exactly.

**Comment by nicolo-ribaudo** [comment]
(The build failure is unrelated)

**Pull request merged**
