### PR TITLE
Add `import type` and `export type` support to TypeScript

### LINKED ISSUE #8361: [Babel 7] [Typescript] Exported Interfaces from an import are kept in the generated JS code
## Bug Report

**Current Behavior**
If the Typescript code exports an interfaces that was imported from other module, that interface reference is kept in the Javascript code after transpilation.

**Input Code**

File A:
```typescript
export interface ExportedInterface {
  value: string
}
```

File B:
```typescript
import { ExportedInterface } from './file-a';
export { ExportedInterface }

export function test(): ExportedInterface {
  return { value: '1' };
}
```

**Expected behavior/code**
The result code should not keep reference of that interface because is a type.

```js
export function test() {
  return {
    value: '1'
  };
}
```

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  presets: [
    ['@babel/preset-env', { modules: false }],
     '@babel/preset-typescript',
  ],
}
```

**Environment**
- Babel version(s): v7.0.0-beta.54
- Node/npm version: Node 10.5.0/npm 6.2.0
- OS: OSX 10.13.5
- Monorepo no
- How you are using Babel: cli (but is the same with loader)

**Possible Solution**
Looks like the here is a comment in the code that could be related to this issue: https://github.com/babel/babel/blob/master/packages/babel-plugin-transform-typescript/src/index.js#L52

**Additional context/Screenshots**
The generated code currently is the following one:

File A:
```js
// No error, the file is generated empty
```

File B:
```js
import { IInterface } from './test-sub';
export { IInterface };
export function test() {
  return {
    value: '1'
  };
}
```

### LINKED ISSUE #10337: Convert exported TypeScript types to undefined
## Bug Report

**Current Behavior**

When the code below is compiled using webpack and `babel-loader`, this triggers the following warning:

```
WARNING in ./src/Bar/index.tsx 1:0-42
"export 'BarProps' was not found in './Bar'
 @ ./src/index.tsx
```

The original issue is here: babel/babel-loader#769

However, I believe it can be fixed upstream (in `@babel/plugin-transform-typescript`).

**Input Code**

`src/Bar/Bar.tsx`

```tsx
export interface BarProps {
  value: string;
}

export default function Bar(props?: BarProps) {}
```

`src/Bar/index.tsx`

```tsx
export { default, BarProps } from './Bar'
```

`src/index.tsx` (Webpack entry point)

```tsx
import Bar from './Bar';

console.log(Bar())
```

**Expected behavior/code**

There are no warnings

**Babel Configuration (.babelrc, package.json, cli command)**

```js
module.exports = {
  plugins: ['@babel/plugin-transform-typescript']
}
```

**Environment**
- Babel version(s): 7.5.5
- Node/npm version: Node 10/npm 6
- OS: Ubuntu 18.04
- Monorepo: no
- How you are using Babel: `loader`

**Possible Solution**

Convert exported types and interfaces to undefined constants. This way, Webpack will find the constants and stop complaining and their types are still undefined when using `typeof` checks. A minifier should strip the constant, as it is unused in the final bundle.

I believe this should be an opt in solution on the Babel part. I.e. an option `typeToConst: true` for both `@babel/plugin-transform-typescript` and `@babel/preset-typescript`

**Additional context/Screenshots**

This webpack config can be used to verify behaviour.

```js
module.exports = {
  devtool: 'source-map',
  resolve: {
    extensions: ['.tsx'],
  },
  module: {
    rules: [
      { 
        test: /\.tsx?$/, 
        use: 'babel-loader'
      }
    ]
  }
};
```

### LINKED ISSUE #10618: TS: re-exported types are not stripped properly
## Bug Report

**Current Behavior**
Imported types are not stripped for decorated method's params

**Input Code**

```js
import {Controller} from "@nestjs/common";
import {MessagePattern} from "@nestjs/microservices";
import {EventLog} from "web3/types";


@Controller()
export class EthereumController {

  @MessagePattern("EVENT")
  public contract(data: EventLog): any {
    return data;
  }
}
```

**Expected behavior/code**
EventLog (web3/types) should be stripped out

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "plugins": [
    "babel-plugin-transform-typescript-metadata",
    [
      "@babel/plugin-proposal-decorators",
      {
        "legacy": true
      }
    ],
    [
      "@babel/plugin-proposal-class-properties",
      {
        "loose": true
      }
    ],
    "babel-plugin-parameter-decorator"
  ],
  "presets": [
    [
      "@babel/env",
      {
        "targets": {
          "node": "current"
        }
      }
    ],
    "@babel/typescript"
  ]
}
```

It does not work even without `babel-plugin-parameter-decorator`

**Environment**
```
    "@babel/preset-typescript": "7.6.0",
    "@babel/preset-env": "7.6.3",
    "@babel/core": "7.6.4",
    "@babel/plugin-proposal-class-properties": "7.5.5",
    "@babel/plugin-proposal-decorators": "7.6.0",
    "babel-plugin-parameter-decorator": "1.0.10",
    "babel-plugin-transform-typescript-metadata": "0.2.2",
```
- Babel version(s): ^^^
- Node/npm version: v12.10.0
- OS: OSX 10.14.6
- Monorepo: Lerna
- How you are using Babel: babel-watch

**Possible Solution**
I was able to work arround by redeclaring type
```js
import {Controller} from "@nestjs/common";
import {MessagePattern} from "@nestjs/microservices";
import {EventLog} from "web3/types";


declare type IEventLog = EventLog;

@Controller()
export class EthereumController {

  @MessagePattern("EVENT")
  public contract(data: IEventLog): any {
    return data;
  }
}
```

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

### LINKED ISSUE #10981: `import type` in TypeScript
TypeScript 3.8 will support a new `import type` construct. While there's already some logic for similar stuff (Flow has its own `import type`), TypeScript's has a few extra restrictions.

* `import type` can only be used on imports with named imports or with a default import - but not both.

  ```ts
  import type FooDefault, { Bar, Baz } from "module"; // error!
  ```
* Even though `import type` creates no emit, an `import type` functionally shadows variables from the outer scope, and using these declarations in a value position that will be emitted causes an error.

  ```ts
  import type { RegExp } from "special-regexp-module";

  // Okay - RegExp won't be used at runtime here.
  declare class Foo extends RegExp { }

  // Okay - RegExp won't be used at runtime here.
  let r: typeof RegExp;

  // Error! RegExp is imported via import type and cannot be used as a value here.
  new RegExp()
  ```

See more at

* https://github.com/microsoft/TypeScript/pull/35200
* https://github.com/microsoft/TypeScript/pull/36092
* https://github.com/microsoft/TypeScript/issues/36138

### PR DESCRIPTION
**Pull request by nicolo-ribaudo**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #10981, closes #10618, closes #8361, closes #10337
| Patch: Bug Fix?          |
| Major: Breaking Change?  |
| Minor: New Feature?      | Yes
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

#11053, #11122, #11157, #11173, #11179

### CODE REVIEW

**Comment by nicolo-ribaudo** [comment]
The various parts of this PR have already been approved.

**Comment by nicolo-ribaudo** [comment]
I'm removing the "ready to be merged" label per https://github.com/babel/babel/pull/11173#issuecomment-591707329

**Comment by AlCalzone** [comment]
Just out of interest: When can we expect a version (7.9.0?) containing this change to be shipped?

**Comment by nicolo-ribaudo** [comment]
I hope to release it at the end of the next week.
I suggest checking https://github.com/babel/babel/milestone/33: we'll release when all those PRs have the "Ready to be Merged" label (i.e. 2 :heavy_check_mark: )

**Comment by Bogidon** [comment]
I compiled a babel from this PR that I'm using because I really needed the feature: 🙈
`"@babel/core": "git+https://github.com/spatialsys/spatialwebapp-gitpkg-registry.git#babel-core-v7.8.4-gitpkg"`

Working well!

**Comment by khanh-bes** [comment]
> I compiled a babel from this PR that I'm using because I really needed the feature: 🙈
> `"@babel/core": "git+https://github.com/spatialsys/spatialwebapp-gitpkg-registry.git#babel-core-v7.8.4-gitpkg"`
> 
> Working well!

This is ready to be merged already!

**Comment by tiagovtristao** [comment]
Hey @nicolo-ribaudo, good work on getting this PR up! I'm also wondering when v7.9.0 will be out?

**Comment by ecbrodie** [comment]
Is there any chance that this feature can be pushed out in a patch-level release? For example, for `@babel/preset-typescript`, this is released in 7.8.4 instead of being released in 7.9.0.

Regardless of this decision, I appreciate the hard work that was done in this PR.

**Comment by nicolo-ribaudo** [comment]
Why would this go in a patch release? It's clearly a new feature :thinking:

**Comment by nicolo-ribaudo** [comment]
:tada:

**Comment by nicolo-ribaudo** [comment]
Hey y'all, we had to delay the release by a few days.

However, we have a clearly defined ETA (March 20th) this time, so I can assure you that it will be released soon!

**Pull request merged**
