### PR TITLE
Flow opaque type 6.x backport

### PR DESCRIPTION
**Pull request by jbrown215**
| Q                        | A 
| ------------------------ | ---
| Patch: Bug Fix?          | No
| Major: Breaking Change?  | No 
| Minor: New Feature?      |  Yes
| Deprecations?            | No
| Spec Compliancy?         | Yes
| Tests Added/Pass?        | Yes
| Fixed Tickets            | N/A
| License                  | MIT
| Doc PR                   | No
| Dependency Changes       | None

Backport of #5990. Depends on https://github.com/babel/babylon/pull/644

I added all the same tests (with some slight changes) to babel-generator, babel-plugin-transform-flow-strip-types, and babel-plugin-transform-flow-comments.

Note: When using the current state of 6.x on both babel and babylon, there were two tests errors:
bin/babel-node v8Flag-dashed-with-param and bin/babel-node v8Flag-underscored-with-param

This diff will also have those errors

### CODE REVIEW

**Comment by bradennapier** [comment]
Looking forward to this!

**Comment by jbrown215** [comment]
@hzoo changed target to master and bumped babylon in babel-core, babel-generator, babel-traverse, and babel-types to 6.18.0

**Comment by jbrown215** [comment]
@hzoo: the build is broken for the same reason it was broken in the pr to 7.0. I'm going to backport @existentialism's fix (https://github.com/babel/babel/pull/6031) and put up another PR to master

**Comment by hzoo** [comment]
cool, thanks

**Comment by jbrown215** [comment]
problem repros locally, but with changes from #6031 everything is fine

**Pull request merged**
