### PR TITLE
fix(`@babel/parser`): fix tokenizer context update code

### PR DESCRIPTION
**Pull request by Eyoatam**
| Q                        | A 
| ------------------------ | ---
| Patch: Bug Fix?          | Yes
| Tests Added + Pass?      | Yes
| License                  | MIT

[this](https://github.com/babel/babel/blob/main/packages/babel-parser/src/tokenizer/context.js#L110) will always be false since `b_stat` does not exist on the `types` object. so instead of `types.b_stat` use `types.braceStatement` 

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/13422"></a>

### CODE REVIEW

**Review by JLHwung — DISMISSED** [review]
Good catch! We should add a test for this change.

**Review by existentialism — APPROVED** [review]

**Comment by Eyoatam** [comment]
> Good catch! We should add a test for this change.

Where should I add the tests?

**Review by JLHwung — APPROVED** [review]
This change is not visible to users. 

Before this PR, the first slash in `{ function x () {} /1/ }` is tokenized as a slash (incorrect!) but later we are saved from the `parser#parseExprAtom` where we re-read as a regex token:

https://github.com/babel/babel/blob/4eda1c860507e84b44a718a39ce58cf45f7ccc6e/packages/babel-parser/src/parser/expression.js#L993

After this PR, such token is handled as regexp token in the first place. So this PR does not introduce changing behaviours.

**Comment by JLHwung** [comment]
I marked this PR as internal because of no visible behaviour changes.

**Pull request merged**
