### PR TITLE
bump dependencies

### PR DESCRIPTION
**Pull request by sindresorhus**
The only breaking change is https://github.com/sindresorhus/globals/commit/599dd668fd045ab2b3f5979dcf8eb1fd94664b0c and it doesn't affect `babel` since it doesn't use that property.

### CODE REVIEW

**Comment by sindresorhus** [comment]
@sebmck Can you consider using `^` on the `devDependencies`?

**Comment by sebmck** [comment]
@sindresorhus Sure, previously I used `^` for all dependencies but then regenerator broke (babel/babel#475) and I got angry and made all the versions fixed.

**Comment by sindresorhus** [comment]
I'm talking about `devDependencies` here, not `dependencies`.

**Comment by sebmck** [comment]
Oh right. Thanks!

**Pull request merged**
