### PR TITLE
Add flow types to @babel/parser

### PR DESCRIPTION
**Pull request by goodmind**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            |  No
| Patch: Bug Fix?          | Yes
| Major: Breaking Change?  | No
| Minor: New Feature?      | No
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  | No
| License                  | MIT

### CODE REVIEW

**Comment by nicolo-ribaudo** [comment]
Is it possible to auto-generate them from the source code?

**Comment by goodmind** [comment]
@nicolo-ribaudo is typescript typings autogenerated?

**Comment by goodmind** [comment]
I checked now, they should be in lib folder to typecheck

**Comment by nicolo-ribaudo** [comment]
No, but since we are using flow in our codebase I tought that it would be possible

**Comment by goodmind** [comment]
@nicolo-ribaudo I think Flow team works on something like this, there was `gen-flow-files` but they removed it https://github.com/facebook/flow/issues/5871

**Comment by nicolo-ribaudo** [comment]
Oh ok :+1:

**Comment by goodmind** [comment]
@nicolo-ribaudo do you know where I can add build step to move this file to `lib` when publishing?

**Comment by nicolo-ribaudo** [comment]
Could you add a comment at the top of the new file like this? Also in the ts definitions.

```js
/*================================!!! NOTE !!!===============================*\
|  When updating this file, don't forget to update typings/babel-parser.d.ts  |
\*===========================================================================*/
```

> do you know where I can add build step to move this file to `lib` when publishing?

You can add it at the end of `prepublish-build` in `Makefile`

**Comment by nicolo-ribaudo** [comment]
I don't think that it should go in `typings`, since that folder is conventionally ued by typescript. Maybe in src?

**Comment by goodmind** [comment]
@nicolo-ribaudo wouldn't it break internal types in`.flowconfig`
```
module.name_mapper='^@babel\/\([a-zA-Z0-9_\-]+\)$' -> '<PROJECT_ROOT>/packages/babel-\1/src/index'
```

**Comment by nicolo-ribaudo** [comment]
I don't think so, since that type is trying to describe exactly `index.js`?

**Comment by liuxingbaoyu** [comment]
Thank you for your PR! Since it is now obsolete, I will close it.

**Pull request closed without merging**
