### PR TITLE
test: destructuring w/o declarations from a function w/ an object argument

### PR DESCRIPTION
**Pull request by jonathanong**
this is a failing test case for a bug i ran into. if this isn't valid, let me know.

```bash
     SyntaxError: /Users/jonathanong/Workspace/babel/packages/babel-core/test/fixtures/transformation/misc/destructuring-with-no-declaration-and-function-with-object/exec.js: Unexpected token (8:9)
    6 | let a, b
    7 | 
  > 8 | { a, b } = someFunction({})
      |          ^

```

### CODE REVIEW

**Comment by jmm** [comment]
Hello @jonathanong, thanks for your interest in contributing! This case is just a syntax error though. Combine the `let` and destructuring, or wrap the expression statement in parens.

**Comment by jonathanong** [comment]
do you have a source for this?

**Comment by hzoo** [comment]
@jonathanong should be in a lot of places - not the spec but

> The parentheses around the object patterns are necessary because statements must not begin with curly braces in JavaScript. http://www.2ality.com/2015/01/es6-destructuring.html

**Comment by jonathanong** [comment]
OH got it. thought the issue was with the right hand side.

**Comment by jmm** [comment]
@hzoo pretty sure the 2ality article is incorrect about being able to wrap the LHS. See http://ecma-international.org/ecma-262/6.0/#sec-destructuring-assignment. Noticed it when looking at the spec and it's also mentioned in the comments of the other article and reflected in the current text.

**Comment by hzoo** [comment]
@jmm yeah you're right it might be somewhat old. I remember the change in babel for that too (wrap the whole thing in parens) `You're trying to assign to a parenthesized expression, eg. instead of `({a}) = 0` use `({a} = 0)` (1:1)`

**Pull request closed without merging**
