### PR TITLE
Fix links in CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by abouthiroppy**
| Q                 | A 
| ----------------- | ---
| Bug fix?          | no
| Breaking change?  | no
| New feature?      | no
| Deprecations?     | no
| Spec compliancy?  | no
| Tests added/pass? | no
| Fixed tickets     |  none
| License           | MIT
| Doc PR            | yes
| Dependency Changes| no

### CODE REVIEW

**Comment by xtuc** [comment]
I think you should add an `internals` section to the CONTRIBUTING.md with the following links:
* AST spec ([https://github.com/babel/babylon/blob/master/ast/spec.md](babylon/ast/spec.md)) (will also avoid running into the moved page)
* Versionning ([/doc/design/versioning.md](/doc/design/versioning.md))
* Monorepo ([/doc/design/monorepo.md](/doc/design/monorepo.md))
* Compiler environment support ([/doc/design/compiler-environment-support.md](/doc/design/compiler-environment-support.md))
* Compiler assumptions ([/doc/design/compiler-assumptions.md](/doc/design/compiler-assumptions.md))

**Comment by abouthiroppy** [comment]
@xtuc Updated.

**Comment by xtuc** [comment]
LGTM :+1: 

/cc @hzoo @existentialism ok for you?

**Comment by hzoo** [comment]
Cool 👍

**Pull request merged**
