### PR TITLE
Fix the module plugin to properly requeue so the ES3 transforms can work

### PR DESCRIPTION
**Pull request by loganfsmyth**
Two separate fixes, but both are needed to get the ES3 transforms to function as expected.

### CODE REVIEW

**Comment by ljharb** [comment]
(ﾉ◕ヮ◕)ﾉ*:・ﾟ✧ so stoked on this, ty

**Comment by hzoo** [comment]
:santa: Nice definitely will try getting this in the next release

**Comment by hzoo** [comment]
:+1: Seems like we've being having trouble with transformers using the exit visitor

@amasad

**Comment by amasad** [comment]
@hzoo I don't have much context (is there a task for this?) -- but from the looks of it I don't understand why we have to queue things manually. Using the path APIs to replace, remove, or add should automatically schedule it to be visited. If not then that's something we need to fix for those APIs. (I might not understand the issue though :smile_cat:)

**Comment by hzoo** [comment]
>  I don't have much context

Haha that's what the issue is "about" - doing a `replaceWith` doesn't requeue if this this.contexts is empty `[]`.

Yeah this is the really old https://phabricator.babeljs.io/T6863. I talked to logan a bit about whether we would be able to automatically requeue or something after a replaceWith.

I think he tired doing so but was getting other issues since other transforms would end up being queued too early?

**Comment by amasad** [comment]
What leads it to not have context? cc @kittens

**Comment by loganfsmyth** [comment]
@amasad I can expand on this:

> What leads it to not have context?

The only paths that have traversal contexts are the paths currently being traversed, and any sibling paths of a node currently being traversed. The first commit in this PR expands `.replaceWith` to look at parent paths because once traversal has passed a given section of the tree, the paths no longer have a context. In the case of `Program#exit` for instance, only the root traversal context is active, and the paths deeper in the tree have no contexts. So now if you use `.replaceWith`, it will be queued up in the root context, rather than not being queued at all, which is what is happening currently. We already do this same `parentPath` lookup for `.contexts` for `unshiftContainer`, but we were not doing it for `.replaceWith`.

> I don't understand why we have to queue things manually.

Definitely not obvious, I was hoping I could get the API to do it automatically, but my attempts ended up causing problems elsewhere, so I opted to defer that for now and do it manually.

The core issue is that in the case of `requeueInParent`, we are calling `.replaceWith` inside a sub-traversal, not inside the primary traversal. With the API as it currently is, this will re-queue the replaces path, but only in the context of the sub-traversal. The paths are not queued in the overall outer traversal context.

**Comment by kittens** [comment]
LGTM. We should idealy fix the requeueing in the future though to check sibling paths as we crawl up, as suggested. (I think that'll fix it)

**Comment by ljharb** [comment]
Awesome! When will this be released?

**Comment by weslleyaraujo** [comment]
ah thats awesome! looking forward to the next release :)

**Comment by ljharb** [comment]
looks like it's out in v6.6.0 today, thanks!

**Comment by hzoo** [comment]
We'll need to revert if there's still issues though

**Pull request merged**
