### PR TITLE
ci: add ember e2e test

### PR DESCRIPTION
**Pull request by JLHwung**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Related: https://github.com/emberjs/ember.js/issues/20806
| Patch: Bug Fix?          |
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

Let's see if the e2e test can catch this bug.

### CODE REVIEW

**Comment by JLHwung** [comment]
Okay, the ember e2e test is failing and throw the expected error. This PR is ready to serve as a starting branch for the regression fix.

**Review by liuxingbaoyu — APPROVED** [review]
Thanks!

**Review by nicolo-ribaudo — APPROVED** [review]
Once CI is green on this, lets merge and release

**Comment by JLHwung** [comment]
Unfortunately CI is not green, so reverting https://github.com/babel/babel/pull/16923 is not sufficient to fix #16999, I will reopen that issue.

**Comment by patricklx** [comment]
> Unfortunately CI is not green, so reverting #16923 is not sufficient to fix #16999, I will reopen that issue.

can it be that the e2e ember test is not getting the babel from source and still installs released one from npm?

**Comment by JLHwung** [comment]
> > Unfortunately CI is not green, so reverting #16923 is not sufficient to fix #16999, I will reopen that issue.
> 
> can it be that the e2e ember test is not getting the babel from source and still installs released one from npm?

Negative. The e2e CI test is per PR, otherwise we won't observe that this test is passing for #17001: https://github.com/babel/babel/actions/runs/12174471428/job/33956764670?pr=17001

**Comment by liuxingbaoyu** [comment]
[`396f396` (#17001)](https://github.com/babel/babel/pull/17001/commits/396f396e93cc3778c8f6e8c31bd6c0187661d14a)
Just apply it. :)

**Comment by patricklx** [comment]
🎉

**Pull request merged**
