### PR TITLE
Add charset so tests work with convert-source-map@>1.4

### PR DESCRIPTION
**Pull request by loganfsmyth**
Fix a test broken by the introduction of a `charset` value in `convert-source-map@1.4`. See https://github.com/thlorenz/convert-source-map/commit/4b8aaf951e1bd7c6fe4b0d86fda6ae7e71934c7a

### CODE REVIEW

**Comment by hzoo** [comment]
cc @thlorenz as FYI

**Comment by loganfsmyth** [comment]
Definitely on the fence as to whether the constitutes breaking, not because I care that our test broke, but just because we have no way of knowing if downstream systems actually properly parse data URLs.

For now my vote is we fix the tests and hope for the best, and if we get reports of sourcemap issues, we can always pin `convert-source-map` to the old version.

**Comment by thlorenz** [comment]
The charset value is actually a fix, shouldn't break anything which is why we published as a minor.
I can understand your test failed, but you shouldn't get any sourcemap issues.

If you run into any problems please LMK.
However with the charset provided it will fix problems with Chines characters in the code for instance.

@Delagen actually provided that change, so he may be able to provide more background.

**Comment by loganfsmyth** [comment]
Yeah I'm not going to worry about it unless we actually hear of issues. I totally agree with you, and it's always hard to decide what constitutes "breaking" when a bugfix might cause issues for people who weren't parsing things properly to begin with.

**Pull request merged**
