### PR TITLE
Minor enhancements around spacing

### PR DESCRIPTION
**Pull request by sarupbanskota**
Just some consistent spacing, cuz it was annoying me ;)

### CODE REVIEW

**Comment by nicolo-ribaudo** [comment]
These docs are generated by [`/scripts/generate-babel-types-docs.js`.](https://github.com/babel/babel/blob/7.0/scripts/generate-babel-types-docs.js#L93-L97) -- you should edit that file instead.

**Comment by jridgewell** [comment]
Yup, you'll need to edit https://github.com/babel/babel/blob/7.0/scripts/generate-babel-types-docs.js#L94 specifically.

```diff
- fieldDescription.push(customTypes[key][field]);
+fieldDescription.push(": " + customTypes[key][field]);

**Comment by sarupbanskota** [comment]
sorry both; I was busy with my other PR, but I'll get this done shortly.

**Comment by jridgewell** [comment]
Merge conflict. 😦

**Comment by sarupbanskota** [comment]
@jridgewell haha check now

**Comment by jridgewell** [comment]
Merging minor doc update.

**Pull request merged**
