### PR TITLE
[Babel 8] Split `typeParameter` of `TSMappedType`

### PR DESCRIPTION
**Pull request by liuxingbaoyu**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | https://github.com/babel/babel/issues/16679 
| Patch: Bug Fix?          |
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | https://github.com/babel/website/pull/2939
| Any Dependency Changes?  |
| License                  | MIT

### CODE REVIEW

**Review by nicolo-ribaudo — APPROVED** [review]

**Review by JoshuaKGoldberg — APPROVED** [review]
🚀

**Comment by JoshuaKGoldberg** [comment]
Back-linking for reference: https://github.com/typescript-eslint/typescript-eslint/pull/7065

**Comment by liuxingbaoyu** [comment]
The PR failure seems a bit difficult to fix unless we also land it in Babel 7.

**Comment by nicolo-ribaudo** [comment]
Can we skip those prettier tests for now?

**Review by JLHwung — APPROVED** [review]

**Pull request merged**
