### PR TITLE
Fix --root-mode option in babel-node

### LINKED ISSUE #9137: root-mode for babel-node
I'm using Babel 7 and I have a monorepo with lerna and yarn workspaces, I could configure the script like this: `babel src --root-mode upward --out-dir dist --delete-dir-on-start` and it works really nice, however I want to use `nodemon` with `babel-node` but I noticed that I can't specify `--root-mode` for `babel-node`, what can I do to solve that?

`nodemon --legacy-watch --exec babel-node -- src/index`

### PR DESCRIPTION
**Pull request by nicolo-ribaudo**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #9137
| Patch: Bug Fix?          | Yes
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

### CODE REVIEW

**Comment by zefexdeveloper** [comment]
Amazing, thank you @nicolo-ribaudo, can't wait for this to get merged.

**Comment by nicolo-ribaudo** [comment]
Don't know lol :laughing:

**Comment by loganfsmyth** [comment]
Oh huh, wasn't there a test?

**Comment by nicolo-ribaudo** [comment]
Nope, many babel-node options aren't tested because they only forward a parameter to babel-core. Also, I'm not sure that we can test this option with the current `@babel/node` test infrastructure because it requires changing the cwd to a subpackage, right?
@wtgtybhertgeghgtwtg If it is possible, do you want to add a test for this option?

**Comment by loganfsmyth** [comment]
That'll teach me I guess :p Thanks for fixing.

**Comment by zefexdeveloper** [comment]
@nicolo-ribaudo @existentialism I still can't use it, am I missing something here?

**Comment by nicolo-ribaudo** [comment]
We didn't release it yet

**Comment by zefexdeveloper** [comment]
@nicolo-ribaudo Oh, got it, I thought it was released. I will wait then :smile:

**Comment by wtgtybhertgeghgtwtg** [comment]
Wow, how did I screw up that badly?
> If it is possible, do you want to add a test for this option?

I'm sorry, I can't figure out a good way to do that with the current setup.

**Comment by zefexdeveloper** [comment]
@wtgtybhertgeghgtwtg It happens, someone would find out eventually. :rofl:

**Comment by jibees** [comment]
Thanks a lot, this will certainly solve my issue 👍

**Comment by casesandberg** [comment]
Has this been released? Still having the same problem

**Comment by nicolo-ribaudo** [comment]
It seems to work for me :thinking: 	

```
  babel-test > @babel/node@^7.2.2


Documenti/dev/babel-test is 📦 v1.0.0 via ⬢ v10.14.2 took 5s 
➜ yarn run babel-node --root-mode upward
yarn run v1.12.3
$ /home/nicolo/Documenti/dev/babel-test/node_modules/.bin/babel-node --root-mode upward
> 

```

Can you share a precise example which shows the problem_

**Pull request merged**
