### PR TITLE
Add missing deps

### PR DESCRIPTION
**Pull request by siddharthkp**
| Q                        | A 
| ------------------------ | ---
| Patch: Bug Fix?          |  Y
| Major: Breaking Change?  |  N
| Minor: New Feature?      |  N
| Deprecations?            |  N
| Spec Compliancy?         |  ?
| Tests Added/Pass?        | No (tests are failing on 7.0)
| Fixed Tickets            | 1 step towards #5172
| License                  | MIT
| Doc PR                   | N
| Dependency Changes       | Y

`yarn test` crashes because of missing dependencies.

### CODE REVIEW

**Comment by hzoo** [comment]
cc @ChauTNguyen

Weird to have to do this when switching from npm 2/3 to yarn?

Just wondering if they have to be at the top level or in packages/*?

**Comment by siddharthkp** [comment]
Also happening when using just npm

node 6.9.4
npm 3.10.9

**Comment by ChauTNguyen** [comment]
I don't have to download any additional dependencies; The build and test works, and I'm also using node 6.9.4 & npm 3.10.9.

**Comment by hzoo** [comment]
Yeah it looks like I didn't need the deps either? Node 6.9.0, npm v3.10.10

**Comment by siddharthkp** [comment]
> Yeah it looks like I didn't need the deps either? Node 6.9.0, npm v3.10.10
 
Weird, i'll try on a few versions and get back to you.

**Comment by siddharthkp** [comment]
Update: works on node 6.9.4 and npm 3.10.10 🤔 

Closing this issue.

**Pull request closed without merging**
