### PR TITLE
Rename `-proposal-`s that became standard to `-transform-`

### PR DESCRIPTION
**Pull request by nicolo-ribaudo**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | 
| Patch: Bug Fix?          |
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | https://github.com/babel/website/pull/2787
| Any Dependency Changes?  |
| License                  | MIT

Ref https://github.com/babel/babel/pull/15473#pullrequestreview-1329335214.

This PR doesn't actually do the rename yet, but it introduces a script to do it easily:
```
node scripts/rename-proposal-to-transform.js ./packages/babel-plugin-proposal-async-generator-functions
```
or
```
node scripts/rename-proposal-to-transform.js ./packages/babel-plugin-proposal-async-generator-functions the-new-name
```

I'll do the actual rename once I know what to do about the old `-proposal-` packages. We have two options:
- [ ] Do nothing, just stop publishing them
- [ ] Publish one more version that just re-exports the new package

Additionally, we will have to choose if we want to deprecate the old packages or not.

My preference would be to do nothing, wait 2 months to give time to the community to migrate (preset-env will already depend on the new packages), and then npm-deprecate them.

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/15614"></a>

### CODE REVIEW

**Review by JLHwung — APPROVED** [review]
> do nothing, wait 2 months to give time to the community to migrate (preset-env will already depend on the new packages), and then npm-deprecate them.

This plan looks good to me. 👍

**Comment by nicolo-ribaudo** [comment]
Next week the RegExp v flag proposal might reach Stage 4: https://github.com/tc39/agendas/blob/main/2023/05.md

**Review by liuxingbaoyu — APPROVED** [review]
I'm fine with both options.

**Comment by nicolo-ribaudo** [comment]
CI is failing because GH actions are partially down: https://www.githubstatus.com/

**Pull request merged**
