### PR TITLE
[ts] Remove override modifier

### LINKED ISSUE #13380: [Bug]: "override" modifier of TypeScript 4.3.0 is not removed when transforming to JavaScript
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@babel/cli

### Input code

```ts
class A {
  test() {
  }
}

class B extends A {
  override test() {
  }
}
```

### Configuration file name

babel.config.js

### Configuration

```js
module.exports = {
  presets: [
    ["@babel/preset-typescript", { "allowDeclareFields": true }],
    ["@babel/preset-env", {
      "targets": {
        "node": true
      }
    }]
  ]
};
```

### Current and expected behavior

Current output:
```js
"use strict";

class A {
  test() {}

}

class B extends A {
  override test() {}

}
```

Expected output:
```js
"use strict";

class A {
  test() {}

}

class B extends A {
  test() {}

}
```

### Environment

  System:
    OS: Linux 5.4 Linux Mint 20 (Ulyana)
  Binaries:
    Node: 14.16.1 - ~/.nvm/versions/node/v14.16.1/bin/node
    Yarn: 1.22.5 - /usr/bin/yarn
    npm: 7.11.2 - ~/.nvm/versions/node/v14.16.1/bin/npm

### Possible solution

Remove the "override" modifier when transforming to JavaScript.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by sosukesuzuki**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            |  Fixes #13380
| Patch: Bug Fix?          | Y
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| License                  | MIT

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/13381"></a>

### CODE REVIEW

**Review by fedeci — APPROVED** [review]

**Review by nicolo-ribaudo — APPROVED** [review]
Thanks!

**Comment by jtbandes** [comment]
When will this be available in a patch release? Seems like it's not possible to run transpiled TS code with overrides until this is included :)

**Comment by nicolo-ribaudo** [comment]
We'll probably release a patch today.

**Comment by nicolo-ribaudo** [comment]
Released in v7.14.4 of the TS plugin

**Comment by lgarron** [comment]
> Released in v7.14.4 of the TS plugin

Hmm, there's a v7.14.4 release of [`@babel/preset-env`](https://www.npmjs.com/package/@babel/preset-env).

But picking up that version doesn't seem to be enough to prevent errors in my project. Should there be an accompanying [`@babel/preset-typescript`](https://www.npmjs.com/package/@babel/preset-typescript) release?

**Comment by nicolo-ribaudo** [comment]
No, the fix is in `@babel/plugin-transform-typescript` which is a dependency of `@babel/preset-typescript`. You can try running `npm --depth 9999 update @babel/plugin-transform-typescript` to update it.

**Pull request merged**
