### PR TITLE
Always transform for-await in async functions[rebase of #6953].

### PR DESCRIPTION
**Pull request by Gvozd**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | #4969
| Patch: Bug Fix?          | yes
| Major: Breaking Change?  | yes?
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR         |
| Any Dependency Changes?  |
| License                  | MIT

>> for-await was transformed in @babel/helper-remap-async-to-generator, which was called
>> by @babel/plugin-transform-async-to-generator and
>> @babel/plugin-proposal-async-generator-functions. This prevented for-await statements
>> in async functions to be transpiled if the transform-async-to-generator plugin was't
enabled.

> This might be considered a breaking change, in case someone used for-await in async functions using just the async functions transform.

This PR is rebase(and fix merge conflicts) of #6953 on actual master

### CODE REVIEW

**Comment by Gvozd** [comment]
@nicolo-ribaudo I've rebase your fix.
And I really need this fix)

**Comment by nicolo-ribaudo** [comment]
Thank you! :slightly_smiling_face:

**Comment by danez** [comment]
Do I understand this correctly: To get the same result as before you need to have `proposal-async-generator-functions` (which name does not seem to make sense after this change ?) and `transform-async-to-generator`?

**Comment by nicolo-ribaudo** [comment]
Before:
- `async function* () {}` was parsed and transformed by `proposal-async-generators`
- `async function () {}` was transformed by `transform-async-to-generator`
- `for await` inside `async function* () {}` was parsed and transformed by `proposal-async-generator`
- `for await` inside `async function () {}` was parsed by `proposal-async-generators` and transformed by `transform-async-to-generator`

After:
- `async function* () {}` is parsed and transformed by `proposal-async-generators`
- `async function () {}` is transformed by `transform-async-to-generator`
- `for await` is parsed and transformed by `proposal-async-generator`

So to fully transpile this code yes, you need both the plugins:
```js
async function fn() {
  for await (const x of gen()) {}
}
```
But it makes sense, because `for await` and `asunc function* fn() {}` are part of the same proposal and `for await` will almost always be used to iterate over `async function* fn() {}`

On the other hand, without this PR it is impossible to _only_ transpile the `for await` statement in that code.

**Comment by danez** [comment]
Thanks for the clarification.

**Comment by nicolo-ribaudo** [comment]
I don't know if I should label this PR as a bug fix or as a breaking change :thinking:

**Comment by Loilo** [comment]
Is there any hint when this will go into `@babel/preset-stage-3`?

**Pull request merged**
