### PR TITLE
Switch to individual lodash functions

### PR DESCRIPTION
**Pull request by bmeurant**
This PR proposes to remove all global ``lodash`` usages in favor of lodash individual functions. This should significantly reduce the number of dependency files.

note that lodash ``each`` is an alias of ``forEach`` and ``extend`` an alias of ``assignIn`` see [here](https://lodash.com/docs)

versions for individual lodash modules are corresponding to the current version of lodash in babel (``4.2.0``): see [4.2.0-npm-packages](https://github.com/lodash/lodash/tree/4.2.0-npm-packages).  

let me know if you think that anything is wrong or missing

### CODE REVIEW

**Comment by hzoo** [comment]
Thanks for this and all the work, we appreciate it 😄 ! 

I was wondering about @jdalton's thoughts - should we just use the babel lodash plugin or does that do something different

**Comment by bmeurant** [comment]
ah ... was not aware of babel-plugin-lodash. And now I'm curious :wink:

**Comment by jdalton** [comment]
I'm not  a fan of the individual method packages. I may cut them for v5 (Jan 2017). They have everything inlined, so they're zero-dependency packages, which is good for one off  usage, or to supplement older Lodash/Underscore versions, but when you start using more I dig the `lodash` package with [babel-plugin-lodash](https://github.com/lodash/babel-plugin-lodash). I was just thinking Babel could use it :P

**Comment by bmeurant** [comment]
@jdalton good to know, thx. 

Just to be sure to understand, using [babel-plugin-lodash](https://github.com/lodash/babel-plugin-lodash) still requires to declare all lodash as a prod dependency, right ?

**Comment by jdalton** [comment]
Yep, and lodash (being the most popular directly depended on package) is already in everyone's local npm cache (so seldom downloaded).

**Comment by bmeurant** [comment]
good point. But precisely because it is one of the most popular package, some versions conflicts may occur and users will have to dowload lodash multiple times, no? Not to mention npm2 ...

**Comment by hzoo** [comment]
Well for Babel 6 we don't recommend using npm 2 since we have all of these dependencies.

**Comment by jdalton** [comment]
Lodash is really intended to favor the `^` range so folks set it and forget it.

**Comment by bmeurant** [comment]
@hzoo I understand that :smirk: !

@jdalton I am curious, what would your recommend if I wanted to use and export a minimum lodash distribution, only for the functions I really use ? ``lodash-cli`` & custom builds ?

**Comment by jdalton** [comment]
@bmeurant 
> I am curious, what would your recommend if I wanted to use and export a minimum lodash distribution, only for the functions I really use ? lodash-cli & custom builds ?

You'd use `lodash` as a dev dep along with [babel-plugin-lodash](https://github.com/lodash/babel-plugin-lodash) and likely [lodash-webpack-plugin](https://github.com/lodash/lodash-webpack-plugin) to cherry-pick the methods needed similar to [redux](https://github.com/reactjs/redux).

**Comment by bmeurant** [comment]
@jdalton ok, thx, I shoud take a look at lodash-webpack-plugin, too :smile:

**Comment by bmeurant** [comment]
@hzoo @jdalton thank you for your answers and your time

**Comment by danez** [comment]
It seems we now agreed that it might be better to use babel-plugin-lodash in babel. 
@bmeurant Can you change this PR to do this or should we make a new PR?

**Comment by jdalton** [comment]
It'll make things prettier for sure.

**Comment by bmeurant** [comment]
@danez OK, I'll close this PR for now, then. 

I'll try to take some time to take a look to babel-plugin-lodash implementation but I'll open a new PR.

Just to be clear, babel-plugin-lodash will not reduce the deps size of babel (it still requires the full lodash package) but this doesn't seem to be a problem from your perspective, right ?

Thx

**Pull request closed without merging**
