### PR TITLE
Fix compatibility with Node.js 20.6

### PR DESCRIPTION
**Pull request by nicolo-ribaudo**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes https://github.com/babel/babel/issues/15927
| Patch: Bug Fix?          |
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

Node.js 20.6.0 introduces [a regression](https://github.com/nodejs/node/issues/49497) that is breaks importing `@babel/core` and `@babel/types` from ESM modules.

This is currently breaking all new installations of [Angular](https://github.com/angular/angular-cli/issues/25782), [Astro](https://github.com/withastro/astro/issues/8411), [Nuxt](https://github.com/nuxt/nuxt/issues/23020), [Vite](https://github.com/vitejs/vite/issues/14299). Unfortunately Node.js's process for releases is **_incredibly slow_**. This bug has been reported three days ago and while a release is being worked no there is no clear timeline yet.

We add a workaround for that bug so that Babel is not affected.

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/15947"></a>

### CODE REVIEW

**Review by liuxingbaoyu — APPROVED** [review]
The CI failure has nothing to do with this PR, it may be other changes in node v20.6, I also noticed this locally.

**Comment by nicolo-ribaudo** [comment]
Yes I'm fixing it

**Comment by nicolo-ribaudo** [comment]
The last commit is because Node.js 20.6.0 unflaggeg `import.meta.resolve`, but it removed support for the second "parent URL" parameter (https://github.com/nodejs/node/pull/49028). Given that we were using the built-in `import.meta.resolve` API when available (i.e. when users had the flag enabled), this completely breaks our module resolution.

Note that it's entirely our fault, for relying on experimental APIs 😅

**Comment by nicolo-ribaudo** [comment]
Releasing to get the various upstream projects unblocked -- if there is anything we can follow up in other PRs.

I will have to release locally to force release `@babel/traverse` and `@babel/types`.

**Comment by cpojer** [comment]
Thanks so much for spending time on this workaround @nicolo-ribaudo.

**Comment by nicolo-ribaudo** [comment]
Now that Node.js 20.6.1 has been released with the bugfix, we reverted the workaround (which was just temporary, since top-level return even in CommonJS files causes problem with many tools): https://github.com/babel/babel/pull/15965

**Pull request merged**
