### PR TITLE
Avoid terser workaround in firefox bugfix for computed keys

### PR DESCRIPTION
**Pull request by nicolo-ribaudo**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | `Fixes #1, Fixes #2` 
| Patch: Bug Fix?          |
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

https://github.com/terser/terser/commit/3f912af14dab4817867fbf5982efb183f34efdbf :)

### CODE REVIEW

**Review by liuxingbaoyu — APPROVED** [review]

**Comment by nicolo-ribaudo** [comment]
This needs to be merged before the next Babel release, and we must document that the bugfix is "undone" by older terser versions.

**Comment by JLHwung** [comment]
Let's wait till terser publish a new version.

**Comment by nicolo-ribaudo** [comment]
Note that for now there is a workaround for terser users: they can specify `compress.inline: false`.

**Comment by liuxingbaoyu** [comment]
https://github.com/terser/terser/commit/36214433fb7790bfeb9a9a7c9472505815059e98
Released. :)

**Comment by nicolo-ribaudo** [comment]
I mentioned in https://github.com/babel/website/pull/2885 that people need to use a recent Terser version (or disable function inlining)

**Review by existentialism — APPROVED** [review]

**Pull request merged**
