### PR TITLE
Move decorators to stage 2

### PR DESCRIPTION
**Pull request by doug-wade**
https://twitter.com/BrendanEich/status/758852228794822656

### CODE REVIEW

**Comment by jmeas** [comment]
Based on [this doc](https://github.com/tc39/proposals) it seems that class props are also stage2 now.

**Comment by hzoo** [comment]
That is fine too, can do 2 commits if you want. Either way will be noted in the changelog

**Comment by hzoo** [comment]
Thanks! Oh I merged the other pr first, oops (merge conflicts)

**Comment by doug-wade** [comment]
rebased

**Comment by kevinSuttle** [comment]
Will this be added here? http://babeljs.io/docs/plugins/preset-stage-2/

**Comment by hzoo** [comment]
@kevinSuttle yeah feel free to pr it if youd like

**Pull request merged**
