### PR TITLE
fix: throw expect jsx plugin error when an idStart or > is seen

### LINKED ISSUE #11769: Parser throws `undefined` when parsing HTML-Like comment
## Bug Report

- [ ] I would like to work on a fix!

Properly not

**Current behavior**

When parsing HTML-Like comment with `sourceType: 'module'`, the `@babel/parser` throws `undefined`.

**Input Code**

```js
require('@babel/parser').parse('alert(<!--comment\n)', {plugins: ['jsx'], sourceType: 'module'})
```

**Expected behavior**

Should throw an error.

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**

NaN

**Environment**

```
- Babel version(s): 7.10.4
- Node/npm version: [e.g. Node v14.4.0/npm v6.14.5]
- OS: Windows 10
- Monorepo: no
- How you are using Babel: api
```

**Possible Solution**

NaN

**Additional context**

PR on Prettier project https://github.com/prettier/prettier/pull/8688

CI Log https://github.com/prettier/prettier/runs/825234580?check_suite_focus=true#step:7:1200

> Expected error, Received: undefined

### PR DESCRIPTION
**Pull request by JLHwung**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #11769 
| Patch: Bug Fix?          | Yes
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

As a follow-up to #11722  , we throw expecting JSX errors when an IdentifierStart or `>` is seen after `<`. This should cover type parameters, JSX element name and JSX fragment shorthand.

This PR also moves `html-comment` test to `basic`, since it is _not_ an error test.

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/11774"></a>

### CODE REVIEW

**Comment by fisker** [comment]
What `<!--a-->` will be?

**Comment by existentialism** [comment]
> And if all "jsx", "flow", "typescript" not enabled, will it throw?

Yeah, it'll fall through: https://github.com/babel/babel/pull/11774/files#diff-56fea09eea2de51b8291db400d2f69beR1193

**Comment by JLHwung** [comment]
@fisker It is now covered in https://github.com/babel/babel/pull/11774/files#diff-c5056d45669fb19d12644f213c79e030

**Comment by fisker** [comment]
Thank you!

**Pull request merged**
