### PR TITLE
Added DCE tests for all the bugs I've reported so far.

### PR DESCRIPTION
**Pull request by Naddiseo**
Let me know if there's any code style changes or the like you want me to make.

### CODE REVIEW

**Comment by sebmck** [comment]
Awesome, thanks! Only nit is that the `minification.deadCodeElmination/bug` paths should be `minification.dead-code-elmination/issue-` to keep consistency with all the other tests.

**Comment by sebmck** [comment]
Rename the `bug` folders to `issue-` too please.

**Comment by Naddiseo** [comment]
@sebmck, any ideas on how to handle regenerator giving different output depending on how the tests are run?

**Comment by sebmck** [comment]
Probably easiest/nicest to just add `"regenerator"` to the `blacklist` in `options.json`.

**Comment by sebmck** [comment]
Squash the commits and this is good to merge.

**Comment by sebmck** [comment]
Thanks @Naddiseo!

**Pull request merged**
