### PR TITLE
Use OS-specific newlines

### PR DESCRIPTION
**Pull request by kellyselden**
This came about from babel/broccoli-babel-transpiler/issues/54.

These are the changes necessary to get the Windows tests to pass. I made minor changes to account for the 2 char newline.

cc @stefanpenner

### CODE REVIEW

**Comment by sebmck** [comment]
I'd rather not. Having the output be non-deterministic across multiple operating systems is asking for trouble.

**Comment by sindresorhus** [comment]
:-1: The above + All code editors on Windows can handle `\n`.

**Comment by stefanpenner** [comment]
@sebmck should babel warn/error if it encounters a line-ending it is not expecting?

**Comment by sebmck** [comment]
@stefanpenner I just don't see the point? It adds a lot of additional complexity for little gain.

**Comment by stefanpenner** [comment]
> Or is the issue more or less transparent, just causing grief for exact match based test helpers?

?

**Comment by loganfsmyth** [comment]
Just wanted to point out, this PR also appears to change the permissions of all the files it touched from `644` to `755`.

**Comment by stefanpenner** [comment]
> permissions of all the files it touched from 644 to 755.

hmm, this seems to be common from windows contributors.
@kellyselden any recommendation to windows users to prevent this ?

**Comment by forivall** [comment]
`git config core.fileMode false`

**Pull request closed without merging**
