### PR TITLE
Annotating taggedTemplateLiteral calls as #__PURE__

### LINKED ISSUE #5900: [taggedTemplateLiteral] not marked as pure
**INPUT**
```js
function whatever() {}
const value = 'value'
const smth = whatever`str(${value})
```
**ACTUAL OUTPUT**
```js
var _templateObject = _taggedTemplateLiteral(['str(', ')'], ['str(', ')']);

function _taggedTemplateLiteral(strings, raw) { return Object.freeze(Object.defineProperties(strings, { raw: { value: Object.freeze(raw) } })); }

function whatever() {}
var value = 'value';
var smth = whatever(_templateObject, value);
```
**EXPECTED OUTPUT**
```diff
- var _templateObject = _taggedTemplateLiteral(['str(', ')'], ['str(', ')']);
+ var _templateObject = /*#__PURE__*/_taggedTemplateLiteral(['str(', ')'], ['str(', ')']);

function _taggedTemplateLiteral(strings, raw) { return Object.freeze(Object.defineProperties(strings, { raw: { value: Object.freeze(raw) } })); }

function whatever() {}
var value = 'value';
var smth = whatever(_templateObject, value);
```
**PROBLEM**
Function call is treated as side effect risk by UglifyJS by default and it cannot be tree shaken even if its result is geting marked as unused. More can be read [here](https://iamakulov.com/notes/polished-webpack/).

**SOLUTION**
Just add `/*#__PURE__*/` comment before the calls. I'm happy to provide an implementation of this, the only thing I would greatly appreciate is pointing out all places where this should be changed - with babel helpers im always unsure in how many places and forms they appear ;)

Possibly also every other helper should be checked if it is not created by a function call and the same thing should be applied there if needed.

### LINKED ISSUE #6324: taggedTemplateLiterals prevent tree shaking
Choose one: is this a bug report or feature request?

I don't know if bug or feature (maybe both)

when using taggedTemplateLiteral with css fe. the generated code is not tree shakable anymore by webpack. When not imported, the transformed code is visible in source. With 1000's of css export it is a big problem.

### Input Code

```js
export const active = css`.active { color: red; }`;
```

### Babel Configuration (.babelrc, package.json, cli command)

```js
{
    "presets": ["env"]
}
```

### Possible Solution

If I replace my var export by a function, the shim should be within the function (and not on top). Not perferct solution but a workaround for now. 

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  6.26
| node             | 8.5
| npm              | 5.4.2
| Operating System | linux

### PR DESCRIPTION
**Pull request by Andarist**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues             | Fixes #6324, fixes #5900
| Patch: Bug Fix?          | no
| Major: Breaking Change?  | no
| Minor: New Feature?      | yes
| Tests Added/Pass?        | yes
| Spec Compliancy?         | n/a
| License                  | MIT
| Doc PR                   | no
| Any Dependency Changes?  | no

### CODE REVIEW

**Comment by brikou** [comment]
Great!

**Comment by Andarist** [comment]
@brikou keep in mind that this will make only `taggedTemplateLiteral` calls tree-shakeable, but you also need to mark as pure your `css` calls. You can do that with `pure_funcs` option of UglifyJS.

**Comment by brikou** [comment]
thank you very much for your insights :+1:

**Comment by Andarist** [comment]
@brikou You might be interested in the plugin I'm creating. 

When I add [this feature](Andarist/babel-plugin-annotate-pure-calls#9) it might help consumers of your component library (assuming you distribute one - if not its still advised to just use `pure_funcs` of the UglifyJS).

**Comment by jridgewell** [comment]
Feel free to merge, this is a simple enough change.

**Pull request merged**
