### PR TITLE
set options default to prevent destructuring from failing

### PR DESCRIPTION
**Pull request by RusinovAnton**
closes https://github.com/babel/babel/issues/6386

### CODE REVIEW

**Comment by RusinovAnton** [comment]
@hzoo

**Comment by hzoo** [comment]
Hmm some other tests failed

```
    if (descriptor.options) {
      throw new Error(
        "Passed options to an existing Plugin instance will not work.",
      );
    }
```

may need to wait for @loganfsmyth to get back

**Comment by loganfsmyth** [comment]
I think this isn't quite the place I'd add this. I'd prefer the change be at https://github.com/babel/babel/blob/36d8a13f4dd97ead0dd7c295fbadad2835b2056c/packages/babel-core/src/config/plugin.js#L40

As you've seen with the test failures, we've got Flow typechecking activated in `babel-core`, so we'll also want to update the datatypes to match, e.g.

https://github.com/babel/babel/blob/36d8a13f4dd97ead0dd7c295fbadad2835b2056c/packages/babel-core/src/config/plugin.js#L10

I _think_ those are the only two places that will need fixing?

**Comment by hzoo** [comment]
I merged https://github.com/babel/babel/pull/6383 and then rebased https://github.com/babel/babel/pull/6381 on top of it and there's no error anymore?

**Comment by loganfsmyth** [comment]
I revisited this, and I've unfortunately realized that my recommendation above was _also_ wrong. To get this the way I actually want it to be, I'm going to close this in favor of some refactoring in https://github.com/babel/babel/pull/6435 because it is kind of complicated.

**Pull request closed without merging**
