### PR TITLE
add nextjs-10 e2e-test

### PR DESCRIPTION
**Pull request by JLHwung**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | 
| Patch: Bug Fix?          |
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

Added a new e2e test for Next.js 10, which roughly equals to webpack 4.44 + Babel 7.12.

The new test should be failing due to #16689.

### CODE REVIEW

**Comment by JLHwung** [comment]
"Redy" for review now, it's finally red in an expected way!

**Review by nicolo-ribaudo — APPROVED** [review]
Lets rebase and see if it passes :)

**Comment by nicolo-ribaudo** [comment]
The CI failure is the same one I saw locally, but I believe it's not related to the breaking change we are working on fixing.

**Comment by JLHwung** [comment]
> The CI failure is the same one I saw locally, but I believe it's not related to the breaking change we are working on fixing.

If we revert the `package.json` change, the test will be green:

https://github.com/babel/babel/actions/runs/10168808112/job/28124367505

So this must somehow related to the Babel version change. For the time being lets ignore this error and fix it in later PRs.

**Comment by nicolo-ribaudo** [comment]
With the latest commit, a demo I have locally is passing.

**Comment by nicolo-ribaudo** [comment]
Come on

**Pull request merged**
