### PR TITLE
Increase the minimum node version for development

### PR DESCRIPTION
**Pull request by liuxingbaoyu**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | `Fixes #1, Fixes #2` 
| Patch: Bug Fix?          |
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

https://github.com/babel/babel/pull/16545#discussion_r1624472643

### CODE REVIEW

**Review by JLHwung — APPROVED** [review]

**Comment by liuxingbaoyu** [comment]
Although eslint I use `__dirname` because of vscode, but this feature is good, we can still merge it.

**Comment by nicolo-ribaudo** [comment]
I'm not 100% sure about this given the comments in https://github.com/babel/babel/pull/16545. Maybe we could wait until when vscode updates their Node version?

**Comment by liuxingbaoyu** [comment]
We won't actually use it in eslint configuration, just increase the requirement in the docs for possible future use. : )

**Comment by liuxingbaoyu** [comment]
This PR doesn't matter.

**Pull request closed without merging**
