### PR TITLE
Update File constructor

### PR DESCRIPTION
**Pull request by arash16**
| Q                        | A 
| ------------------------ | ---
| Patch: Bug Fix?          | yes
| Major: Breaking Change?  | no
| Minor: New Feature?      | no
| Deprecations?            | no
| Spec Compliancy?         | yes
| Tests Added/Pass?        | 
| Fixed Tickets            | 
| License                  | MIT
| Doc PR                   | no
| Dependency Changes       | no

Parser expects sourceFilename, not sourceFileName

### CODE REVIEW

**Comment by xtuc** [comment]
According to Babylon's documentation and [BabelParserOptions](https://github.com/babel/babel/blob/d33d02359474296402b1577ef53f20d94e9085c4/lib/parser.js) in Babel yes but for some reason tests are failing

**Comment by arash16** [comment]
Without this change, there's no filename property inside loc.

**Comment by arash16** [comment]
I did some grep search, looks like there are some other places where it's mis-cased.
```
./packages/babel-cli/src/babel/dir.js:      sourceFileName: slash(path.relative(dest + "/..", src)),
./packages/babel-cli/src/babel/file.js:        sourceFileName: "stdin",
./packages/babel-cli/src/babel/file.js:        sourceFileName: sourceFilename,
./packages/babel-core/README.md:| `sourceFileName`         | `(filenameRelative)` | Set `sources[0]` on returned source map. |
./packages/babel-core/src/transformation/file/index.js:      sourceFileName: this.opts.filename,
./packages/babel-core/src/transformation/file/index.js:      sourceFileName:   basenameRelative,
./packages/babel-core/src/transformation/file/options/config.js:  sourceFileName: {
./packages/babel-generator/README.md:sourceFileName         | string   |                 | The filename for the source code (i.e. the code in the `code` argument).  This will only be used if `code` is a string.
./packages/babel-generator/src/source-map.js:        map.setSourceContent(this._opts.sourceFileName, code);
./packages/babel-generator/src/source-map.js:        Object.keys(code).forEach((sourceFileName) => {
./packages/babel-generator/src/source-map.js:          map.setSourceContent(sourceFileName, code[sourceFileName]);
./packages/babel-generator/src/source-map.js:      source: line == null ? undefined : filename || this._opts.sourceFileName,
./packages/babel-generator/test/index.js:      sourceFileName: "inline",
./packages/babel-generator/test/index.js:      sourceFileName: "a.js",
./packages/babel-helper-transform-fixture-test-runner/src/index.js:            sourceFileName:   task.actual.filename,
```

**Comment by arash16** [comment]
I guess it was easier to fix babylon instead.

**Comment by xtuc** [comment]
This is actually a breaking change. `babel-core` and `babel-generator` will require `sourceFilename` instead of `sourceFileName`.

Should we add it to the Babel 7 release? I agree that this inconsistency between names is confusing but i'm not sure it's worth introducing a breaking change. What do you think?

We could add an alias in the configuration between `sourceFilename` and `sourceFileName`.

**Comment by loganfsmyth** [comment]
Since this never made it into 7.x and will likely just sit here, I'm going to close it. I agree that it's an unfortunate difference. I'd might be willing to accept a PR so that the code generator and parser accepted `sourceFileName` or `sourceFilename`?

**Pull request closed without merging**
