### PR TITLE
Added license files to packages

### PR DESCRIPTION
**Pull request by Bamieh**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | None
| Patch: Bug Fix?          | Yes
| Major: Breaking Change?  | No
| Minor: New Feature?      | No
| Tests Added + Pass?      | Yes
| Documentation PR         | No
| Any Dependency Changes?  | No
| License                  | MIT

Babel packages do not have a LICENSE file on them. It is a good practice to have one per package. I added a bash script to copy the main license file into the packages.

```
make clone-license
```

Dependency watchers like [versioneye](https://www.versioneye.com/) show UNKNOWN license to the new babel, this will probably solve such issues as well.

image

### CODE REVIEW

**Comment by lukescott** [comment]
I'm not sure a LICENSE file should be committed to each and every package. The root LICENSE is enough for the project repo.

However, you could copy each LICENSE file just before the publish step and then remove them afterward. That way each published npm package has one. You should probably also have `/packages/*/LICENSE` in the gitignore to make sure they aren't accidentally committed.

There is a lerna issue that mentions this problem https://github.com/lerna/lerna/issues/1213.

**Comment by hzoo** [comment]
Is it necessary to add the actual files? it's also in the package.json already

**Comment by Bamieh** [comment]
@lukescott no need to remove after adding them if they are not committed. However I'm not sure if we should not commit them to github, since some might have different things (some LICENSE files are already in some packages already).

@hzoo the `package.json` file does have the name of the license only. It's usually a better idea to include the LICENSE file for whatever code you download (via npm or github)

**Comment by lukescott** [comment]
I think it's going to depend on a companies legal team.

**Comment by Bamieh** [comment]
@lukescott legally, it is not satisfactory to have the license name alone in the package.

This is also explicitly required by some license in order for it to take effect, such as `ICS` or `Apache 2.0`, all `GNU` licenses and **`MIT`**.

> The MIT license requires that "the above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software." By including the license in the source file, you have met this obligation.

Not specifying the license text in each package restrictedly means that no one may reproduce, distribute, or create derivative works from your work. **The name of the license alone does not "apply" the license, hence it retains the default license instead.**

> without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work.

**Comment by hzoo** [comment]
Ok I think we should just do this at publish time then, this seems to be what other projects do like React https://github.com/facebook/react/tree/master/packages/react

> However, you could copy each LICENSE file just before the publish step and then remove them afterward. That way each published npm package has one. You should probably also have /packages/*/LICENSE in the gitignore to make sure they aren't accidentally committed.

This sounds good to me

**Comment by Bamieh** [comment]
@hzoo cool. i'll update the code then

**Comment by klimashkin** [comment]
Hi @Bamieh, any updates on that?
I would be really appreciate for that PR, since tools like license-checker still [can't pick up](https://github.com/davglass/license-checker/issues/134#issuecomment-358654097) packages licenses automatically until they are shipped

**Comment by Bamieh** [comment]
@klimashkin wow I completely forgot about this, I'll have it ready today

**Comment by opichals** [comment]
@Bamieh Gave the script-only solution a shot in https://github.com/babel/babel/pull/8409

**Comment by hzoo** [comment]
Done in https://github.com/babel/babel/pull/8409

**Pull request closed without merging**
