### PR TITLE
babel-parser: Add new internal ESLint rule to consistent error messages

### PR DESCRIPTION
**Pull request by sosukesuzuki**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            |  N/A
| Minor: New Feature?      | Y
| Tests Added + Pass?      | Yes
| License                  | MIT

I have been concerned about the inconsistent in the format of error messages. However, tools such as Prettier use error messages as their interface, and It wasn't able to fixed.
With the introduction of error codes in 7.14, it is now easier to fix error messages.
So I created an Internal ESLint rule to enforce the format of error messages.
What do you think about this?

### CODE REVIEW

**Comment by sosukesuzuki** [comment]
Oh, this PR includes huge diffs.. But almost diff are updating snapshots.

**Review by JLHwung — APPROVED** [review]
LGTM.

Note for reviewers: I suggest reviewing the first 3 commits, the others are snapshot changes.

**Review by existentialism — APPROVED** [review]
💯

**Review by kaicataldo — APPROVED** [review]
:tada:

**Comment by nicolo-ribaudo** [comment]
Could you rebase? It should make the tests pass.

**Comment by nicolo-ribaudo** [comment]
Thanks! I had to reword the commit message a bit so that it doesn't get cropped by GH's ui.

**Pull request merged**
