### PR TITLE
Fixes #6577

### LINKED ISSUE #6577: `sourcemaps: "inline"` ignored when "inputSourceMap" specified
This is a bug.  Using the Babel API, when specifying an `inputSourceMap`, the `sourcemaps` option is forced to `true`, ignoring if it was set to `"inline"` or `"both"`.

### Input Code

```js
import * as ts from 'typescript';
import * as babel from 'babel-core';

const input = `
    export default 0;
`;
// Create an input sourcemap (doesn't have to be via typescript)
const tsOutput = ts.transpileModule(input, {
    fileName: 'input.ts',
    compilerOptions: {sourceMap: true}
});

function transpile(withInputSourceMap) {
    const babelOutput = babel.transform(tsOutput.outputText, {
        sourceMaps: 'inline',
        inputSourceMap: withInputSourceMap ? JSON.parse(tsOutput.sourceMapText!) : undefined
    });
    console.log(babelOutput.code);
    console.log(babelOutput.map);
}

console.log('====Transpiling====');
transpile(false);
console.log('====Transpiling, passing an inputSourceMap====');
transpile(true);
```

### Expected Behavior

In both cases, babel returns an inlined, base64-encoded sourcemap.

### Current Behavior

In the second case, babel does not return an inlined sourcemap.

### Possible Solution

I believe this code is to blame: https://github.com/babel/babel/blob/6.x/packages/babel-core/src/transformation/file/index.js#L141-L143

### Context

I'm using a babel transformation to post-process compiled Typescript.

### Your Environment

| software         | version(s)
| ---------------- | -------
| babel-core            |  6.26.0
| typescript    | 2.5.3
| node             | 8.7.0
| npm              | 5.5.1
| Operating System | Windows 10

### PR DESCRIPTION
**Pull request by cspotcode**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | `Fixes #6577
| Patch: Bug Fix?          | Yes
| Major: Breaking Change?  | No
| Minor: New Feature?      |  No
| Tests Added + Pass?      | No
| Documentation PR         | No
| Any Dependency Changes?  | No

### CODE REVIEW

**Comment by Qantas94Heavy** [comment]
Hey there! Looks like the CircleCI build is failing because your branch isn't up to date with what's currently in master. You can update it by running the following:

```sh
git pull --rebase upstream master
git push --force
```
Also, the message for the commit could have a bit more detail about what it's doing. Something like this would be great:

```
Do not override specified source map option (#6577)

[an explanation here, if needed]
```

As for the actual fix, it looks good to me. 👍

**Comment by Qantas94Heavy** [comment]
Also, it seems this PR is targeting 6.x. Do you know if this affects 7.x as well?

**Comment by cspotcode** [comment]
I don't know if it affects 7.x.  The 7.x code looks very different (renamed / split / moved files) so it wasn't straightforward to find the equivalent code on master.

I'll rewrite the commit message shortly.

**Comment by cspotcode** [comment]
@Qantas94Heavy I rewrote the commit message, so we should be good to go.

**Pull request merged**
