### PR TITLE
Add failing test case for #4192

### PR DESCRIPTION
**Pull request by SimenB**
No idea how to fix it, but this may be a small start :smile: 
#4192

### CODE REVIEW

**Comment by SimenB** [comment]
@hzoo Any news here? I noticed a new release of the ES3 plugin, but after rebasing this test still fails

**Comment by hzoo** [comment]
All packages were updated to compile with Babel 6 so that's why that plugin is 6.8.0 - there weren't any other changes so it wasn't expected to fix this particular issue, sorry

**Comment by stevenjob** [comment]
Any updates on this?

**Comment by SimenB** [comment]
I just rebased on master, maybe by the power of half a year it'll pass now?

**Comment by danez** [comment]
I started looking into this, so far I only found the similar issue for classes here #4518.

**Comment by danez** [comment]
I integrated this test in #5497

**Pull request closed without merging**
