### PR TITLE
add ie8Safe option for very basic IE8 compatibility (fixes #1369)

### LINKED ISSUE #1369: Mangled class names brake in IE8
If you mangle the Babel output of a simple ES6 class using UglifyJS2, it won't work in IE8.

Let see the following ES6 code:

```javascript
class TestClass {
}
new TestClass();
```

The output will be:

```javascript
var TestClass = function TestClass() {
  _classCallCheck(this, TestClass);
};
new TestClass();
```

If you compress that using UglifyJS2:

```javascript
var TestClass = function X() {
  _classCallCheck(this, X);
};
new TestClass();
```

In IE8 the inner variable X and outer TestClass variables refer to two distinct function objects so the class call check fails. You can read more about it in the ``Example #3`` [of this nice article](https://kangax.github.io/nfe/#jscript-bugs).

There is a related ticket in UglifyJS2 repository (mishoo/UglifyJS2#248, especially [this comment](https://github.com/mishoo/UglifyJS2/issues/248#issuecomment-22758717)). In my opinion it is not easy to fix and can be circumvented if you change your code, so I don't expect a fix on the UglifyJS2 side for it soon (or at all...).

### PR DESCRIPTION
**Pull request by kondi**
I know that IE8 compatibility is not a goal of babel project, but currently #1369 is the only issue which blocks me to use it. This branch fixes that by introducing an optional ``ie8Safe`` option.

Since the fix is very simple and the option is disabled by default, I think it won't hurt the main code base and would be nice if one does not have to use a fork for it.

Furthermore this new option could be used by other miserable folks who has to fix something for IE8 compatibility.

### CODE REVIEW

**Comment by sebmck** [comment]
Closed via #1382.

**Comment by jamm** [comment]
How to use this option? "ie8Safe" is unrecognized...

**Comment by sebmck** [comment]
@jamm The option was incorrectly named and will not strictly make your code "IE8 safe", it only gets around a particular JScript bug to do with function expressions. See the linked issue #1382, where it's included in the optional transformer `jscript`.

**Comment by jamm** [comment]
thank you all, IE8 is happy now and no more ugly hacks in build scripts.

**Pull request closed without merging**
