### PR TITLE
Deprecate `ModuleDeclaration` alias

### PR DESCRIPTION
**Pull request by JLHwung**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Deprecate the `ModuleDeclaration` alias and rename to `ImportOrExportDeclaration`
| Patch: Bug Fix?          |
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

In this PR we deprecate the `ModuleDeclaration` alias for `ImportOrExportDeclaration`, due to the name conflict with the stage 2 [Module Declarations](https://github.com/tc39/proposal-module-declarations) proposal. The `ImportOrExportDeclaration` alias now covers the following AST types:

- ImportDeclaration
- ExportDefaultDeclaration
- ExportNamedDeclaration
- ExportAllDeclaration

We plan to deprecate the `ModuleDeclaration` alias usage starting from Babel 7.21. In the next major version, `ModuleDeclaration` will longer function as an alias, instead it will refer to the `ModuleDeclaration` node `module foo {}`, followed by the `is*` and `assert*` helpers.

### `@babel/types` usage:

```diff
import * as t from "@babel/types";
--- t.isModuleDeclaration(node)
+++ t.isImportOrExportDeclaration(node)

--- t.assertModuleDeclaration(node)
+++ t.assertImportOrExportDeclaration(node)
```

### Plugin or traverse usage
```diff
{
  visitor: {
---    ModuleDeclaration(path, state) {
+++    ImportOrExportDeclaration(path, state) {
    }
  }
}
```

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/15266"></a>

### CODE REVIEW

**Review by nicolo-ribaudo — COMMENTED** [review]
It seems like this PR removes `ModuleDeclaration` from `t.FLIPPED_ALIAS_KEYS`. Can we keep it until Babel 8?

**Review by nicolo-ribaudo — APPROVED** [review]

**Review by liuxingbaoyu — APPROVED** [review]

**Comment by amingRo** [comment]
in version 7.21.0,i get the mistake 
Trace: `isModuleDeclaration` has been deprecated, please migrate to `isImportOrExportDeclaration`.
what can i do to fix this？

**Comment by mannymu** [comment]
Trace: isModuleDeclaration has been deprecated, please migrate to isImportOrExportDeclaration.
what can i do to fix this？

**Comment by eleven-net-cn** [comment]
Many third-party packages will automatically use the v7.21.0 version, causing too many warnings in the terminal, and can only wait for the third-party package to change.

So sad!

**Comment by amingRo** [comment]
> in version 7.21.0,i get the mistake Trace: `isModuleDeclaration` has been deprecated, please migrate to `isImportOrExportDeclaration`. what can i do to fix this？
好了兄弟们，估计作者这会儿还在睡觉？他们那可能是晚上，我先给大家提供一个临时的解决方案，可以试试对你们是否有帮助。
ok,all brothers,there some problems need the author to answer,if somebodys work are blocked,there are some temporary resolutions for you.
1.change your packages manager to `Yarn`
2.edit your packages.json,add this
`
resolutions:{
"@babel/core":"7.20.12",
"@babel/types":"7.20.7",
"@babel/traverse":"7.20.13"
}
`
3. run `yarn` in your terminal
4. start or build your programs
it's useful for me,maybe can help you

**Comment by eleven-net-cn** [comment]
> 

only for yarn, can not with npm, so sad ...

**Comment by eleven-net-cn** [comment]
> 

only for yarn, can not with npm, so sad ...

**Comment by eleven-net-cn** [comment]
> > in version 7.21.0,i get the mistake Trace: `isModuleDeclaration` has been deprecated, please migrate to `isImportOrExportDeclaration`. what can i do to fix this？
> 
> 好了兄弟们，估计作者这会儿还在睡觉？他们那可能是晚上，我先给大家提供一个临时的解决方案，可以试试对你们是否有帮助。 ok,all brothers,there some problems need the author to answer,if somebodys work are blocked,there are some temporary resolutions for you. 1.change your packages manager to `Yarn` 2.edit your packages.json,add this `resolutions:{ "@babel/core":"7.20.12", "@babel/types":"7.20.7", "@babel/traverse":"7.20.13" }` 3. run `yarn` in your terminal 4. start or build your programs it's useful for me,maybe can help you

only for yarn, can not with npm, so sad ...

**Comment by lpbottle** [comment]
> > in version 7.21.0,i get the mistake Trace: `isModuleDeclaration` has been deprecated, please migrate to `isImportOrExportDeclaration`. what can i do to fix this？
> 
> 好了兄弟们，估计作者这会儿还在睡觉？他们那可能是晚上，我先给大家提供一个临时的解决方案，可以试试对你们是否有帮助。 ok,all brothers,there some problems need the author to answer,if somebodys work are blocked,there are some temporary resolutions for you. 1.change your packages manager to `Yarn` 2.edit your packages.json,add this `resolutions:{ "@babel/core":"7.20.12", "@babel/types":"7.20.7", "@babel/traverse":"7.20.13" }` 3. run `yarn` in your terminal 4. start or build your programs it's useful for me,maybe can help you

666，这个临时方案可用，强迫症表示实在无法忍受编译时出现这么一大堆编译错误，坐等插件作者更新

**Comment by nicolo-ribaudo** [comment]
I'm releasing #15448 now, which should greatly reduce the number of warnings (to 1 in most cases).

**Comment by dqm07** [comment]
> 

Soooooo nice of you, It works for me! Thanks again!

**Comment by dqm07** [comment]
> > in version 7.21.0,i get the mistake Trace: `isModuleDeclaration` has been deprecated, please migrate to `isImportOrExportDeclaration`. what can i do to fix this？
> 
> 好了兄弟们，估计作者这会儿还在睡觉？他们那可能是晚上，我先给大家提供一个临时的解决方案，可以试试对你们是否有帮助。 ok,all brothers,there some problems need the author to answer,if somebodys work are blocked,there are some temporary resolutions for you. 1.change your packages manager to `Yarn` 2.edit your packages.json,add this `resolutions:{ "@babel/core":"7.20.12", "@babel/types":"7.20.7", "@babel/traverse":"7.20.13" }` 3. run `yarn` in your terminal 4. start or build your programs it's useful for me,maybe can help you

Soooo Nice, It works for me. Thanks again!

**Pull request merged**
