### PR TITLE
[babel 8] Output minimal strings by default

### PR DESCRIPTION
**Pull request by JLHwung**
| Q                        | A 
| ------------------------ | ---
| Any Dependency Changes?  | `jsesc` bumped to v3 before a flag
| License                  | MIT

This PR backports #11384 to `main`, for more info see that PR.

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/12675"></a>

### CODE REVIEW

**Review by hzoo — APPROVED** [review]

**Review by nicolo-ribaudo — APPROVED** [review]

**Comment by paranoidjk** [comment]
This is a breaking change, why this PR is not being list in changelog ? https://github.com/babel/babel/releases/tag/v7.12.13

**Comment by nicolo-ribaudo** [comment]
It's not released yet, it will be released in Babel 8.

**Comment by paranoidjk** [comment]
image

https://github.com/babel/babel/commits/main/packages/babel-generator
@nicolo-ribaudo

**Comment by paranoidjk** [comment]
In my case,  a  demo code just like this:
```tsx
import generate from '@babel/generator'
// do something to generate a tsx file ast 
    const output = generate(file, {
      jsescOption: {
        minimal: true,
      },
    });
```

after v7.12.13 released, the react attribute value change to unicode
image

when i lock @bable/generator to 7.12.11, it goes back to normal.

**Comment by nicolo-ribaudo** [comment]
Ohh right, it's a bug introduced by this PR.
We tried not to change the default to `true` for Babel 7, and ended up always setting it to `false.

**Comment by nicolo-ribaudo** [comment]
@paranoidjk Fixed in 7.12.15

**Pull request merged**
