### PR TITLE
fix: Transform property mutators fails on computed property names

### LINKED ISSUE #12097: @babel/plugin-transform-property-mutators fails on computed property names
## Bug Report

- [ ] I would like to work on a fix!

**Current behavior**

- [REPL](https://babeljs.io/repl#?browsers=ie%2011&build=&builtIns=usage&spec=false&loose=false&code_lz=MYewdgzgLgBApgDwA4CcYF4YCIBmIRYDcAUMaJLCAEYBWGMA3sTDAOZywDaiqAugBQBKRsxYwUHAK4ow2KgEMURUQF8ANMRUky4CCAA2cAHT6QrftRpG8IQYRgB6B3MVYgA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Cenv&prettier=false&targets=&version=7.11.6&externalPlugins=%40babel%2Fplugin-transform-property-mutators%407.10.4)
It fails with the error:

```
{ RangeError: /home/markoski/Documents/babel-test/script.js: Maximum call stack size exceeded
    at Scope.get parent [as parent] (/home/markoski/Documents/babel-test/node_modules/@babel/traverse/lib/scope/index.js:192:13)
    at Scope.getBinding (/home/markoski/Documents/babel-test/node_modules/@babel/traverse/lib/scope/index.js:789:28)
    at Scope.getBindingIdentifier (/home/markoski/Documents/babel-test/node_modules/@babel/traverse/lib/scope/index.js:797:23)
    at PluginPass.ReferencedIdentifier (/home/markoski/Documents/babel-test/node_modules/@babel/preset-env/lib/polyfills/corejs3/usage-plugin.js:172:17)
    at PluginPass.newFn (/home/markoski/Documents/babel-test/node_modules/@babel/traverse/lib/visitors.js:220:17)
    at newFn (/home/markoski/Documents/babel-test/node_modules/@babel/traverse/lib/visitors.js:179:21)
    at NodePath._call (/home/markoski/Documents/babel-test/node_modules/@babel/traverse/lib/path/context.js:55:20)
    at NodePath.call (/home/markoski/Documents/babel-test/node_modules/@babel/traverse/lib/path/context.js:42:17)
    at NodePath.visit (/home/markoski/Documents/babel-test/node_modules/@babel/traverse/lib/path/context.js:90:31)
    at TraversalContext.visitQueue (/home/markoski/Documents/babel-test/node_modules/@babel/traverse/lib/context.js:112:16) code: 'BABEL_TRANSFORM_ERROR' }
```

**Input Code**

```js
const expr = "foo";

const obj = {
  get [expr]() {
    return "bar";
  },
};

console.log(obj.foo); // "bar"
```

**Expected behavior**
It should handle computed property names correctly, or at least give an error why that's not possible.

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `babel.config.js`

```js
{
  presets: [
    ["@babel/preset-env", { debug: true, useBuiltIns: "usage", corejs: 3 }],
  ],
  plugins: ["@babel/plugin-transform-property-mutators"],
};

```

**Environment**
```
System:
    OS: Linux 4.15 Ubuntu 18.04.4 LTS (Bionic Beaver)
  Binaries:
    Node: 10.19.0 - /usr/bin/node
    Yarn: 1.22.4 - /usr/bin/yarn
    npm: 6.13.4 - /usr/bin/npm
  npmPackages:
    @babel/cli: ^7.8.4 => 7.8.4 
    @babel/core: ^7.8.7 => 7.8.7 
    @babel/plugin-transform-modules-amd: ^7.8.3 => 7.8.3 
    @babel/plugin-transform-modules-commonjs: ^7.8.3 => 7.8.3 
    @babel/plugin-transform-property-mutators: ^7.10.4 => 7.10.4 
    @babel/plugin-transform-proto-to-assign: ^7.10.5 => 7.10.5 
    @babel/plugin-transform-runtime: ^7.9.0 => 7.9.0 
    @babel/preset-env: ^7.9.5 => 7.9.5 
    @babel/runtime-corejs3: ^7.9.2 => 7.9.2 
    babel-plugin-transform-inline-consecutive-adds: ^0.4.3 => 0.4.3 
```

### PR DESCRIPTION
**Pull request by liuxingbaoyu**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #12097 
| Patch: Bug Fix?          | √
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | √
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/15234"></a>

### CODE REVIEW

**Review by JLHwung — COMMENTED** [review]
Can you add a new test case for computed keys with side effect? In this case the key expression should be computed twice. I believe that's why the plugin ignored the computed key.

We could support those key expressions if `scope.isStatic(expressionPath)` is true.

**Review by nicolo-ribaudo — APPROVED** [review]
Could you rebase this now that https://github.com/babel/babel/pull/15232 has been merged? There are no git conflicts, but just to make sure that the fixtures don't need to be updated.

**Comment by nicolo-ribaudo** [comment]
I found a bug: with the property mutators plugin, this code:
```js
var obj = {
  get [(() => "x")()]() { return 1 },
  set [(() => "x")()](_) {}
};

console.log(obj.x);
```

logs `undefined` instead of `1`. However, on `main` babel crashes when compiling it, so it's not a regression introduced by this PR.

**Comment by liuxingbaoyu** [comment]
https://babeljs.io/repl/build/53642/#?browsers=&build=&builtIns=false&corejs=false&spec=false&loose=false&code_lz=G4QwTgBA9gRgVhAvBA3gKAhA5gUwC4QDaAFMQJRIB8EARAB41nkC65qEY-ArmAHYQBGCAF8ANBggBnfEVIVE1eoxbEA-hRTC0wgNxo0AYyi9JUADY4AdGahZisOJbpkdQA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=env&prettier=false&targets=&version=7.20.6%2Bpr.15234&externalPlugins=&assumptions=%7B%7D

Can this be reproduced in the repl? I tried and failed.

**Comment by liuxingbaoyu** [comment]
It seems that using merge would be more convenient in this case.

**Review by JLHwung — APPROVED** [review]

**Comment by nicolo-ribaudo** [comment]
I was thinking about this, and I'm not sure anymore that we should fix it. `main` is already an improvement over https://github.com/babel/babel/issues/12097: instead of crashing, it just leaves the computed property as-is. If users want to transform computed properties, they have to also enable `@babel/plugin-transform-computed-properties`.

**Comment by liuxingbaoyu** [comment]
I forget why I did this, but apparently the original problem has been fixed.

**Pull request closed without merging**
