### PR TITLE
fix: Class decorator correctly passes return value

### LINKED ISSUE #16198: [Bug]: decorators are broken and when applied, they override the preceding value.
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@babel/cli

### Input code

I've created a test repo with a basic example [here](https://github.com/amirmohsen/decorators-broken). You can also see it below:
```js
function decorateA(target) {
  return class extends target {
    a() {
      console.log("a");
    }
  };
}

function decorateB(target) {
  return class extends target {
    b() {
      console.log("b");
    }
  };
}

@decorateB
@decorateA
class Target {}

const target = new Target();

target.b();

target.a(); // This throws an error: TypeError: target.a is not a function
```
I only checked class decorators. This bug may exist for function decorators as well but I haven't checked.

### Configuration file name

_No response_

### Configuration

```js
module.exports = (api) => {
  api.cache(true);
  return {
    presets: [
      [
        "@babel/preset-env",
        {
          modules: false,
          targets: {
            node: 20,
          },
        },
      ],
    ],
    plugins: [["@babel/plugin-proposal-decorators", { version: "2023-05" }]],
  };
};
```

### Current and expected behavior

Instead of passing the result of one decorator to the next, the original value of the `Target` class gets passed to each decorator and as a result, the last applied decorator result overrides the preceding ones.

### Environment

Babel package versions:
```json
"@babel/cli": "^7.23.4",
"@babel/core": "^7.23.7",
"@babel/plugin-proposal-decorators": "^7.23.7",
"@babel/preset-env": "^7.23.7",
```
Node: `20.9.0`
NPM: `10.1.0`
Yarn: `1.22.19`
Environment: `Ubuntu 20.04.4 LTS (WSL2 on Windows)`

### Possible solution

_No response_

### Additional context

This is a recent bug because I have a project that is using Babel version `7.23.2` and it's working fine. However, the bug doesn't seem to originate in Babel itself because simply reverting to an older version of the packages, doesn't fix anything. I think the problem might originate in a sub-dependency. I haven't had time to investigate further though.

### PR DESCRIPTION
**Pull request by liuxingbaoyu**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #16198 
| Patch: Bug Fix?          | √
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | √
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

---
Edit by @JLHwung 

In this PR we fix a regression introduced in https://github.com/babel/babel/pull/16160. Currently when multiple class decorators are applied, they are provided with the unmodified classes, this is incorrect as per 15.7.7 [ApplyDecoratorsToClassDefinition](https://arai-a.github.io/ecma262-compare/?pr=2417&id=sec-applydecoratorstoclassdefinition) step 1.e, the next decorator should be applied on the modified class.

### CODE REVIEW

**Review by JLHwung — APPROVED** [review]
Can we rename the test case to `decorator-access-modified-classes`? We already have `decorator-access-modified-{fields,methods}` for the same purposes.

**Comment by JLHwung** [comment]
I updated the PR's description, I hope it can help reviewers pick up the PR's intention. Please do fill in the descriptions in the PR template, it will also help our future selves when trying to understand why changes are made.

**Comment by liuxingbaoyu** [comment]
Thanks!
In fact, the detailed description of the issue exists in https://github.com/babel/babel/issues/16198, and this PR only has small changes, and the added tests also help with review, so I did not add a detailed description. :)

**Review by nicolo-ribaudo — APPROVED** [review]
👍

**Comment by JLHwung** [comment]
CI error is not related.

**Pull request merged**
