### PR TITLE
Fix UpdateExpression generating wrong assignment

### LINKED ISSUE #7488: Unexpected change of Math operators: - to +
Choose one: is this a bug report or feature request? Bug

### Input Code

Repo where the bug can be reproduced: https://github.com/marvinhagemeister/babel-bug-export

```js
export let diffLevel = 0;

export function diff() {
  if (!--diffLevel) {
    console.log("hey");
  }
}

diff();
```

### Babel/Babylon Configuration (.babelrc, package.json, cli command)

```js
{
  "presets": [
    [
      "@babel/env",
      {
        "loose": true,
        "targets": {
          "browsers": ["last 2 versions", "IE >= 9"]
        }
      }
    ]
  ]
}
```

### Expected Behavior

```js
if (!(exports.diffLevel = diffLevel = diffLevel - 1)) {
```

### Current Behavior

```js
if (!(exports.diffLevel = diffLevel = diffLevel + 1)) { // note the `+ 1` instead of `- 1`
```

### Context

Currently trying to upgrade preact's toolchain to `babel 7` for jsx-fragment support: https://github.com/developit/preact/pull/879

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            | 7.0.0-beta.40 
| Babylon          | 
| node             | 9.4.0
| npm              | yarn 1.5.1
| Operating System | MacOS High Sierra

### PR DESCRIPTION
**Pull request by marvinhagemeister**
Fixes #7488

| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | #7488 
| Patch: Bug Fix?          | 👍 
| Major: Breaking Change?  | no
| Minor: New Feature?      | no
| Tests Added + Pass?      | yes
| Documentation PR         | 
| Any Dependency Changes?  |
| License                  | MIT

~~I'd love to add decent tests but I'm not sure how. `babel-helpers-*` packages don't seem to have a `test/` directory and whenever I add one I get a cyclic dependency warning from lerna.~~

**EDIT:** Added tests

### CODE REVIEW

**Comment by nicolo-ribaudo** [comment]
You can add the test to https://github.com/babel/babel/tree/master/packages/babel-plugin-transform-modules-commonjs/test/fixtures/regression, since the commonjs transformer is the "public interface" of the functions exposed by this helper.

**Comment by marvinhagemeister** [comment]
@nicolo-ribaudo Awesome, that was exactly what I was looking for 🎉  Thanks for your help 👍

**Comment by loganfsmyth** [comment]
Embarrassing mistake on my part, good find :)

**Comment by marvinhagemeister** [comment]
@loganfsmyth happens to all of us :)

**Comment by loganfsmyth** [comment]
FYI, had to tweak these tests a little, they weren't actually running because the directories were nested too deeply (our test fixture running is a pain :P)

https://github.com/babel/babel/commit/aa669ef9027cb8a350024b76f39ed652ade8b1aa

**Comment by marvinhagemeister** [comment]
Oh that's good to know :+1:

**Pull request merged**
