### PR TITLE
Run Babel asynchronously in fixtures

### PR DESCRIPTION
**Pull request by nicolo-ribaudo**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | `Fixes #1, Fixes #2` 
| Patch: Bug Fix?          |
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

This was extracted from #13414: by running our tests asynchronously, they can also run ESM plugins. The second commit verifies that it works by converting an existing test-only plugin from CJS to ESM.

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/14659"></a>

### CODE REVIEW

**Comment by nicolo-ribaudo** [comment]
The failure is related, it looks like our logic to detect if dynamic import is supported was broken 😬

**Comment by nicolo-ribaudo** [comment]
Yes, but import is in a different file that we require in a try/catch block, so if it was a parsing error would be suppressed and correctly handled 🤔

**Comment by liuxingbaoyu** [comment]
This is related to `jest-runner`, but not only a `jest-runner` problem, our `supportsESM` does not actually call to test whether `import()` is available, so it will throw an exception when used.

**Comment by nicolo-ribaudo** [comment]
I'm so annoyed that we have to hard-code the Node.js version, but there is no other synchronous way to know if dynamic import is supported in the current Node.js version. I used this code to test:

```js
// demo.js
console.log("syntax is ok");
import("./.eslintrc.cjs").then(console.log, console.error);
```

**Comment by liuxingbaoyu** [comment]
Maybe we can use child processes!
😉

**Comment by nicolo-ribaudo** [comment]
Probably it's not worth it for this simple check 😬

**Review by liuxingbaoyu — APPROVED** [review]

**Pull request merged**
