### PR TITLE
docs: add package-specific documentation links

### PR DESCRIPTION
**Pull request by DanArthurGallagher**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | n/a
| Patch          | This only adds links to the documentation so it would be a patch version at most
| Tests Added + Pass?      | n/a, only documentation links added
| Any Dependency Changes?  | No
| License                  | MIT

This extends babel/babel#10418 and adds package-specific homepage links to all of the packages which have one.
I ran a script checking the links, and removed any links which 404'd.
I also added `"bugs"` links to the packages which have a specific label mentioned in their README.

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/12531"></a>

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/12531"></a>

### CODE REVIEW

**Comment by merceyz** [comment]
Seems like a job that should be covered by https://yarnpkg.com/features/constraints to avoid it falling out of sync

**Comment by nicolo-ribaudo** [comment]
We didn't setup constraints yet, but it's in our list of things to do!

**Review by nicolo-ribaudo — COMMENTED** [review]
Thanks!

I think we'll wait to merge this until https://github.com/babel/babel/pull/12526 is merged, because this PR will probably cause every package to be published and I'd like to run https://github.com/babel/babel/pull/12526 for the first time with a small release.

**Review by nicolo-ribaudo — APPROVED** [review]

**Review by JLHwung — APPROVED** [review]
nit: could use `babel.dev`, too. One byte shorter.

**Review by existentialism — APPROVED** [review]

**Comment by nicolo-ribaudo** [comment]
Thanks!

**Pull request merged**
