### PR TITLE
[test runner] Restore `TEST_GREP` support (jest's `-t` parameter)

### PR DESCRIPTION
**Pull request by nicolo-ribaudo**
| Q                        | A 
| ------------------------ | ---
| License                  | MIT

Tested manually running `yarn jest babel-parser/test/index -t placeholders` and `TEST_GREP=placeholders TEST_ONLY=babel-parser make test-only`.

The logic is copied from https://github.com/facebook/jest/blob/3a85065fe5604655e1337ffc1631f9999722c821/packages/jest-circus/src/run.ts#L105 and https://github.com/facebook/jest/blob/e0b33b74b5afd738edc183858b5c34053cfc26dd/packages/jest-circus/src/eventHandler.ts#L237.

Thanks @pzuraq and @tolmasky for noticing that this stopped working! :sweat_smile: 

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/14170"></a>

### CODE REVIEW

**Comment by tolmasky** [comment]
Nice! Thanks @nicolo-ribaudo

**Review by JLHwung — APPROVED** [review]
Another feature request for jest-light-runner: run in main thread when `--runInBand` is provided, mostly used for debugging.

**Comment by nicolo-ribaudo** [comment]
Q: Do you still use `--runInBand`? With the lighter wrappers that we use know, I have never felt the need for it.

**Comment by JLHwung** [comment]
> Do you still wish you had --runInBand? With the lighter wrappers that we use know, I have never felt the need for it.

`--runInBand` is used for hooking debugger. Otherwise we have to pass `--inspect-brk` to each worker and figure out which worker is running the interested test. Currently I manually revise `jest.config.js` when I want to open a debugger.

**Comment by nicolo-ribaudo** [comment]
Oh ok, right. I didn't think about it because I take a different approach: using vscode (I don't remember which editor you use), I put a breakpoint in the test file (it works well because they are not compiled, but they are executed natively), and then I run that file with this `.vscode/launch.json`:
```json
{
	"version": "0.2.0",
	"configurations": [
		{
			"type": "pwa-node",
			"request": "launch",
			"name": "Test current file",
			"program": "${workspaceFolder}/node_modules/.bin/jest",
			"args": ["${relativeFile}"]
		},
		{
			"type": "pwa-node",
			"request": "launch",
			"name": "Test current file (Babel 8)",
			"program": "${workspaceFolder}/node_modules/.bin/jest",
			"args": ["${relativeFile}"],
			"env": { "BABEL_8_BREAKING": "true" }
		}
	]
}
```

**Pull request merged**
