### PR TITLE
Start version created by babel-plugin init @ 0.0.0

### PR DESCRIPTION
**Pull request by thejameskyle**
Re: https://github.com/UXtemple/babel-plugin-react-autoprefix/commit/8d16a530d2ec3d277613ecd6c51ab2de6482b465

### CODE REVIEW

**Comment by sebmck** [comment]
Why?

**Comment by thejameskyle** [comment]
So that when you run `babel-plugin push` you can set it to 1.0.0

**Comment by sebmck** [comment]
It should be 1.0.0 by default though?

**Comment by thejameskyle** [comment]
But then npm version can't set it to 1.0.0 and you have [commits like this](https://github.com/UXtemple/babel-plugin-react-autoprefix/commit/8d16a530d2ec3d277613ecd6c51ab2de6482b465)

**Comment by dariocravero** [comment]
:+1:

**Comment by sebmck** [comment]
@thejameskyle Huh? That commit isn't a result of anything. You can publish versions completely properly starting from 1.0.0.

**Pull request closed without merging**
