### PR TITLE
Compress output for optional chain with multiple `?.`

### PR DESCRIPTION
**Pull request by nicolo-ribaudo**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | `Fixes #1, Fixes #2` 
| Patch: Bug Fix?          |
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

- The first commit is shared with https://github.com/babel/babel/pull/15739.
- The second commit optimizes transforming `a?.b?.c` from `a == null ? void 0 : a.b == null ? void 0 : a.b.c` to `a == null || a.b == null ? void 0 : a.b.c`, to only emit `void 0` once.
- The third commit optimizes transforming `delete a?.b` from `a == null ? true : delete a.b` to `a == null || delete a.b`.
- The fourth commit optimizes transforming `a()?.b?.c` from `var _tmp1, _tmp2; (_tmp1 == a()) == null || (_tmp2 = _tmp1.b) == null ? void 0 : _tmp2.c` to `var _tmp1; (_tmp1 == a()) == null || (_tmp1 = _tmp1.b) == null ? void 0 : _tmp1.c`.

Terser doesn't do these optimization by itself, so this change also brings improvements to minified code.

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/15740"></a>

### CODE REVIEW

**Review by JLHwung — APPROVED** [review]
The output is much better, thank you!

**Review by liuxingbaoyu — APPROVED** [review]

**Comment by nicolo-ribaudo** [comment]
@SimenB Multiple PRs are failing with this (flaky) failure, but I fail to see how it can be Babel-related. However, it only fails for our "breaking" tests and not for the Babel 7 tests.
Do you have any idea of what might cause that unlinking error?

**Comment by SimenB** [comment]
Hmmm, no. The test uses `@babel/register` tho, so there might be something to it.

I can update the test to use `fs.rm` with `force` instead - that should in theory be more tolerant to errors such as these and bubble up a better result? Or just ignore the failure if it doesn't matter.

**Comment by SimenB** [comment]
See https://github.com/jestjs/jest/pull/14296

**Comment by SimenB** [comment]
> I can test that PR in our CI to see if it makes the problem go away.

That'd be great 👍 

> Is it possible that those failure are just hiding a real error?

That's what I was thinking

**Pull request merged**
