### PR TITLE
fix: Don't throw in `getTypeAnnotation` when using TS+inference

### LINKED ISSUE #15380: [Bug]: TypeScript compilation throws error on correct program (type inference on array spread syntax?)
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@babel/cli

### Input code

```ts
const foo = () => {
  const bar = 0 ? mkList() : [];

  return [...bar];
};

function mkList(): any[] {
  return [];
}

export default {};
```

[This REPL session](https://babeljs.io/repl#?browsers=&build=&builtIns=false&corejs=false&spec=false&loose=false&code_lz=MYewdgzgLgBAZiEMC8MAUBKFA-GBvAKBhlElgCMBDAJxRgAYYB-GAWwGsAZAS2kxgBcMANoBdANwEiMagFMoAV2pgRAOnVVqEggF9JBOArDAo3cGy68omIZTABPMfmlzFykdp1TZADwAOINSwACaycJQKADaweHoEQA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Ctypescript&prettier=false&targets=&version=7.20.14&externalPlugins=&assumptions=%7B%7D) also showcases the issue.

### Configuration file name

babel.config.json

### Configuration

```json
{
  "presets": [
    "@babel/preset-env",
    "@babel/preset-typescript"
  ]
}
```

### Current and expected behavior

Current behavior: compilation fails with the following log:
```
$ /tmp/babel/node_modules/.bin/babel src --extensions .ts -d build
TypeError: /tmp/babel/src/index.ts: Property types[1] of TSUnionType expected node to be of a type ["TSType"] but instead got "GenericTypeAnnotation"
    at validate (/tmp/babel/node_modules/@babel/types/lib/definitions/utils.js:112:11)
    at validator (/tmp/babel/node_modules/@babel/types/lib/definitions/utils.js:88:7)
    at Object.validate (/tmp/babel/node_modules/@babel/types/lib/definitions/utils.js:188:7)
    at validateField (/tmp/babel/node_modules/@babel/types/lib/validators/validate.js:21:9)
    at validate (/tmp/babel/node_modules/@babel/types/lib/validators/validate.js:15:3)
    at validateNode (/tmp/babel/node_modules/@babel/types/lib/builders/validateNode.js:12:27)
    at tsUnionType (/tmp/babel/node_modules/@babel/types/lib/builders/generated/index.js:1757:36)
    at createTSUnionType (/tmp/babel/node_modules/@babel/types/lib/builders/typescript/createTSUnionType.js:18:39)
    at createUnionType (/tmp/babel/node_modules/@babel/traverse/lib/path/inference/util.js:24:16)
    at NodePath.ConditionalExpression (/tmp/babel/node_modules/@babel/traverse/lib/path/inference/inferers.js:118:36) {
  code: 'BABEL_TRANSFORM_ERROR'
}
error Command failed with exit code 1.
```

Moving the function definition for `mkList` to the top of the file fixes the issue. So does adding a type assertion on line 4: `return [...(bar as typeof bar)];`.

Setting targets to "defaults" in the config also fixes the issue.

### Environment

```
  System:
    OS: macOS 12.5.1
  Binaries:
    Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.17.0/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.0/bin/npm
  npmPackages:
    @babel/cli: 7.20.7 => 7.20.7
    @babel/core: 7.20.12 => 7.20.12
    @babel/preset-env: 7.20.2 => 7.20.2
    @babel/preset-typescript: 7.18.6 => 7.18.6
```

### Possible solution

_No response_

### Additional context

This appears to be a regression between 7.17 and 7.18. See [this REPL session](https://babeljs.io/repl#?browsers=&build=&builtIns=false&corejs=false&spec=false&loose=false&code_lz=MYewdgzgLgBAZiEMC8MAUBKFA-GBvAKBhlElgCMBDAJxRgAYYB-GAWwGsAZAS2kxgBcMANoBdANwEiMagFMoAV2pgRAOnVVqEggF9JBOArDAo3cGy68omIZTABPMfmlzFykdp1TZADwAOINSwACaycJQKADaweHoEQA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Ctypescript&prettier=false&targets=&version=7.17.12&externalPlugins=&assumptions=%7B%7D), where I just changed the version to 7.17.

In the CLI, I can make the compilation succeed with the following package.json file for Yarn:
```json
{
  "devDependencies": {
    "@babel/cli": "~7.17.0",
    "@babel/core": "~7.17.0",
    "@babel/preset-env": "~7.17.0",
    "@babel/preset-typescript": "~7.17.0",
    "typescript": "4.9.4"
  },
  "resolutions": {
    "@babel/types": "~7.17.0",
    "@babel/generator": "~7.17.0",
    "@babel/traverse": "~7.17.0"
  }
}
```

### PR DESCRIPTION
**Pull request by liuxingbaoyu**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #15380 
| Patch: Bug Fix?          | √
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | √
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/15383"></a>

### CODE REVIEW

**Review by nicolo-ribaudo — COMMENTED** [review]
`createUnionType` could not return `undefined`, because the `if`/`else` checks are not exhaustive anymore. Could we either:
1. Update its type definition to `function createUnionType(types: Array<t.FlowType | t.TSType>) : t.FlowType | t.TSType | undefined`
2. Update its type definition to `funcion createUntionType<T extends Array<t.FlowType> | Array<t.TSType>>(types: T): T[number]`, and only call it if all the types are from the same type system

I slightly prefer (2), but (1) is also fine.

**Comment by liuxingbaoyu** [comment]
Makes sense!
I also like 2, but I find it is called multiple places.
I thought of two ways
1. Modify `createUnionType` to allow returning `undefined`
2. Add `maybeCreateUnionType` and put the check inside
These functions are not exported, so we can safely modify them.

**Comment by nicolo-ribaudo** [comment]
Thanks for rebasing, did you go with any of the suggestions in https://github.com/babel/babel/pull/15383#pullrequestreview-1275215586?

**Comment by liuxingbaoyu** [comment]
Yes, I chose the first one. :)

**Review by nicolo-ribaudo — APPROVED** [review]

**Pull request merged**
