### PR TITLE
Update to Rollup 3.2.3

### PR DESCRIPTION
**Pull request by nicolo-ribaudo**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            |
| Patch: Bug Fix?          |
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

There are a few peer deps warnings from the `rollup-*` plugins that expect Rollup 2, but everything seems to work locally. Let'ss see on CI.

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/15038"></a>

### CODE REVIEW

**Comment by liuxingbaoyu** [comment]
Failure on Windows I'm not sure if it's a regression.
https://github.com/babel/babel/pull/14003 The problem is back.

**Comment by liuxingbaoyu** [comment]
https://github.com/rollup/rollup/issues/4680
There is a bug similar to https://github.com/babel/babel/pull/15031 for rollup's treeshake.😄

**Review by liuxingbaoyu — APPROVED** [review]

**Comment by JLHwung** [comment]
@liuxingbaoyu I just did a rebase and it looks good to me, is this PR still blocked?

**Comment by liuxingbaoyu** [comment]
@JLHwung Thanks! Now it is no longer blocked, as long as CI is green again!

**Review by JLHwung — APPROVED** [review]

**Pull request merged**
