### PR TITLE
Add `onlyRemoveTypeImports` option to `transform-typescript`

### LINKED ISSUE #10981: `import type` in TypeScript
TypeScript 3.8 will support a new `import type` construct. While there's already some logic for similar stuff (Flow has its own `import type`), TypeScript's has a few extra restrictions.

* `import type` can only be used on imports with named imports or with a default import - but not both.

  ```ts
  import type FooDefault, { Bar, Baz } from "module"; // error!
  ```
* Even though `import type` creates no emit, an `import type` functionally shadows variables from the outer scope, and using these declarations in a value position that will be emitted causes an error.

  ```ts
  import type { RegExp } from "special-regexp-module";

  // Okay - RegExp won't be used at runtime here.
  declare class Foo extends RegExp { }

  // Okay - RegExp won't be used at runtime here.
  let r: typeof RegExp;

  // Error! RegExp is imported via import type and cannot be used as a value here.
  new RegExp()
  ```

See more at

* https://github.com/microsoft/TypeScript/pull/35200
* https://github.com/microsoft/TypeScript/pull/36092
* https://github.com/microsoft/TypeScript/issues/36138

### PR DESCRIPTION
**Pull request by kaicataldo**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #10981
| Patch: Bug Fix?          |
| Major: Breaking Change?  |
| Minor: New Feature?      | Yes
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

This is based on the [`feat-7.9.0/ts-import-type`](https://github.com/babel/babel/tree/feat-7.9.0/ts-import-type) branch, and I believed the test failures are from that branch.

With the addition of type-only imports and exports to TypeScript, we are now able to explicitly mark imports as types. This PR adds an `onlyExplicitTypeImports` option to `plugin-transform-typescript`, which allows the user to opt into only removing imports that are unambiguously types. We will probably want to make this the default behavior in the future.

Questions for reviewers:
1. Are there any missing test cases? 
1. Would it be worth adding a second test file that explicitly sets the new option to `false`?

### CODE REVIEW

**Comment by nicolo-ribaudo** [comment]
@kaicataldo I have rebased `feat-7.9.0/...` and your branch on master to make CI pass.

**Comment by kaicataldo** [comment]
`onlyRemoveTypeImports` seems like the clearest option name to me.

**Comment by nicolo-ribaudo** [comment]
Kai doesn't like using newly learned words! :stuck_out_tongue:

**Comment by kaicataldo** [comment]
Maybe I did know the word at some point and it was elided from my vocabulary.

**Comment by nicolo-ribaudo** [comment]
Could you also add tests for `import {} from "x"` and `import "x"`, since they are explicitly pointed out in a comment in the code?

**Comment by nicolo-ribaudo** [comment]
Merged into #11171

**Comment by JLHwung** [comment]
We also need
1) add this option to `preset-typescript`.
2) update docs on https://babeljs.io/docs/en/babel-preset-typescript#options and https://babeljs.io/docs/en/babel-plugin-transform-typescript#options

**Pull request merged**
