### PR TITLE
Disable parameter-destructuring in Edge 18

### PR DESCRIPTION
**Pull request by saschanaz**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | #9139
| Patch: Bug Fix?          | Yes
| Major: Breaking Change?  | No
| Minor: New Feature?      | No
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  | No
| License                  | MIT

### CODE REVIEW

**Comment by nicolo-ribaudo** [comment]
Could you open two separate PRs?

**Comment by saschanaz** [comment]
> Also, does `(param, {deep = {}}) => {}` work on Edge 18?

Yep:

image

**Comment by saschanaz** [comment]
Opened #9143.

**Comment by saschanaz** [comment]
@nicolo-ribaudo Would you restart the test? Thanks!

**Comment by saschanaz** [comment]
>Can you update the compat-table hash to the latest

Done! Regeneration didn't cause any diffs 👍

**Comment by existentialism** [comment]
@saschanaz thanks!

**Pull request merged**
