### PR TITLE
Use forked `semver@6` with backported security fixes

### LINKED ISSUE #15720: [Bug]: [Security][helper-compilation-targets] Dependency semver version has vulnerability
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Other (Next.js, Gatsby, vue-cli, ...)

### Input code

n/a

### Configuration file name

_No response_

### Configuration

n/a

### Current and expected behavior

Installing `@babel/helper-compilation-targets@7.22.5` requires `semver@6.3.0`
This now throws an error on npm audits with a vulnerability
```
┌─────────────────────┬────────────────────────────────────────────────────────┐
│ moderate            │ semver vulnerable to Regular Expression Denial of      │
│                     │ Service                                                │
├─────────────────────┼────────────────────────────────────────────────────────┤
│ Package             │ semver                                                 │
├─────────────────────┼────────────────────────────────────────────────────────┤
│ Vulnerable versions │ <7.5.2                                                 │
├─────────────────────┼────────────────────────────────────────────────────────┤
│ Patched versions    │ >=7.5.2                                                │
├─────────────────────┼────────────────────────────────────────────────────────┤
│ Paths               │ . > @pinia/nuxt@0.4.11 > @nuxt/kit@3.6.0 >             │
│                     │ @nuxt/schema@3.6.0 > untyped@1.3.2 >                   │
│                     │ @babel/core@7.22.5 >                                   │
│                     │ @babel/helper-compilation-targets@7.22.5 >             │
│                     │ semver@6.3.0                                           │
│                     │                                                        │
│                     │ . > @pinia/nuxt@0.4.11 > @nuxt/kit@3.6.0 >             │
│                     │ @nuxt/schema@3.6.0 > untyped@1.3.2 >                   │
│                     │ @babel/core@7.22.5 > semver@6.3.0                      │
│                     │                                                        │
│                     │ . > @pinia/nuxt@0.4.11 > @nuxt/kit@3.6.0 >             │
│                     │ untyped@1.3.2 > @babel/core@7.22.5 >                   │
│                     │ @babel/helper-compilation-targets@7.22.5 >             │
│                     │ semver@6.3.0                                           │
│                     │                                                        │
│                     │ ... Found 721 paths, run `pnpm why semver` for more    │
│                     │ information                                            │
├─────────────────────┼────────────────────────────────────────────────────────┤
│ More info           │ https://github.com/advisories/GHSA-c2qf-rxjj-qqgw      │
└─────────────────────┴────────────────────────────────────────────────────────┘

```

### Environment

  System:
    OS: macOS 12.6
  Binaries:
    Node: 18.16.0 - /usr/local/bin/node
    Yarn: 1.22.19 - ~/.npm-packages/bin/yarn
    npm: 9.5.1 - /usr/local/bin/npm
  npmPackages:
    eslint: ^8.43.0 => 8.43.0 

### Possible solution

Is this package compatible (or can it be compatible) with semver>=7.5.2 ?

package.json
```json
...
  "overrides": {
      "semver": ">=7.5.2"
  }
...
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by nicolo-ribaudo**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #15720
| Patch: Bug Fix?          |
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

I forked semver to backport https://github.com/npm/node-semver/pull/564 to v6. The fork is at https://github.com/nicolo-ribaudo/semver-v6 (lmk if you need write access at any point).

Our `conditions` system does not support having two different package names for the two options, and we cannot have `if` statements around static imports, so for now v8 also uses the forked package.

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/15742"></a>

### CODE REVIEW

**Review by liuxingbaoyu — APPROVED** [review]
👍

**Review by JLHwung — APPROVED** [review]

**Comment by nicolo-ribaudo** [comment]
I'll release tomorrow morning :)

**Comment by sshifty** [comment]
Hey! Does 7.22.6 contain this change? I cant see it in change log:/
Thanks in advance :)

**Comment by liuxingbaoyu** [comment]
Yes, it's included in v7.22.6!

**Comment by SphinxKnight** [comment]
Shouldn't https://github.com/nicolo-ribaudo/babel/blob/91c3c3827718ee0f7ebb3630794814afde1dabe1/packages/babel-helper-compilation-targets/package.json#L30 target the updated version of semver as well (`7.5.2`)? My understanding is that if the condition is true, then `^7.3.4` will be used.

**Comment by nicolo-ribaudo** [comment]
Well, `^7.3.4` will resolve to the latest v7 release. However, a PR to explicitly update it is welcome!

We use this yarn plugin btw: https://github.com/nicolo-ribaudo/yarn-plugin-conditions

**Comment by thienandangthanh** [comment]
[npm/node-semver](https://github.com/npm/node-semver) backported the fix.
Should we go back to use the original semver package?
https://github.com/npm/node-semver/releases/tag/v6.3.1

**Comment by nicolo-ribaudo** [comment]
Yes! Do you want to open a PR?

**Pull request merged**
