### PR TITLE
Fix lerna path

### PR DESCRIPTION
**Pull request by amasad**
call it from node_modules/.bin/lerna

### CODE REVIEW

**Comment by hzoo** [comment]
Thanks!

**Comment by thejameskyle** [comment]
I'm interested in why https://github.com/babel/babel/blob/master/Makefile#L5 doesn't fix that

**Comment by amasad** [comment]
Interesting, I hadn't seen that. But I don't  know why

**Comment by jmm** [comment]
@thejameskyle @amasad Me too -- that's strange. I added that line to account for this situation (originally for gulp, but it was supposed to take care of it for any other bins).

@amasad What OS was that not working on?

**Comment by amasad** [comment]
OS X

**Comment by jmm** [comment]
@amasad Thanks.

**Comment by jmm** [comment]
@amasad When you had that issue, was your CWD the root of the project?

**Comment by amasad** [comment]
Yeah. @hzoo saw the same issue I think

**Comment by jmm** [comment]
@amasad Ok, thanks. Hmm...weird. I'll have to see if I can repro locally, otherwise I don't know how to debug it.

**Comment by loganfsmyth** [comment]
Yeah, I've had path issues too. I had to install `gulp` globally for `watch` to work, even though `bootstrap` worked successfully.

**Comment by jmm** [comment]
@loganfsmyth @hzoo OS X? Hmm, found [this](http://stackoverflow.com/a/21709821/1034448) which may be relevant.

Possible solutions:

1. Add stuff (e.g. prepend `;`) to each relevant command to invoke the "slow path" (assuming that actually works). Kind of gross. (See above link.)

2. [Set `SHELL`](http://stackoverflow.com/a/26936855/1034448) (assuming that actually works). Is there a shell we can count on everyone having (Bash?)? (And would setting that affect Windows?)

3. Just explicitly prefix each Node bin with the path (`./node_modules/.bin` or `$(npm bin)`).

4. Set the path in a variable and explicitly prefix each Node bin with it. E.g.
  ```make
  NODE_BIN := $(npm bin)
  # ...
  $(NODE_BIN)lerna
  ```

  I would slightly prefer this to the previous option.
  
In any case, I think we should handle all instances the same way if possible.

**Pull request merged**
