### PR TITLE
No need for parens for new expressions without args

### PR DESCRIPTION
**Pull request by amasad**

### CODE REVIEW

**Comment by hzoo** [comment]
I would not of found those other edge cases - I wonder if there could be a tool that searches through codebases prints out the different types of AST to look for these. I guess you can also try to generate code from the spec but I would have even less idea about that?

**Comment by amasad** [comment]
One thing to do is to check how existing tools do this. I went through uglify's code and it seems like we're handling everything they're handling.

**Comment by hzoo** [comment]
Ah yeah I guess that works as a baseline - unless they are messing up something as well. I remember sebmck mentioning everything.js in an old issue which has some other forms - https://github.com/michaelficarra/everything.js/blob/9bdd8a0a9fd571ecca612d53d417890e5a9409d4/es5.js#L77-L80

**Comment by amasad** [comment]
Ah that's useful. I can do some more testing using that

**Comment by hzoo** [comment]
with
```js
new x();
new new x()();
new x[0]();
new x.a();
new x[0].a();
new x.a[0]();
new x;
new new x;
new new x();
new new x().a;
new new x()[0];
```
I get 

```js
new X;new Y()();new F().z;new x;new new x;new x[0];new x.a;new x[0].a;new x.a[0];new x;new new x;new new x;new new x().a;new new x()[0];
```

**Comment by amasad** [comment]
looks correct?

**Comment by hzoo** [comment]
Yeah looks good

**Comment by phantom10111** [comment]
@amasad Some test cases that produce incorrect results:
```JavaScript
new new x()(a);
new new x()()();
new new x()(a)();
new new x()()(a);
new new x()(a)(a);
```
Produces
```JavaScript
new new x(a);new new x()();new new x(a)();new new x()(a);new new x(a)(a);
```
All those have empty parens first so it's possible they are all the same edge case.

**Comment by hzoo** [comment]
Ok `&& !(t.isNewExpression(parent) && parent.arguments.length > 0)` seems to fix it

**Comment by hzoo** [comment]
```js
new new x()();
new new x()(a);
new new x(a)();
new new x(a)(a);

new new x;new new x()(a);new new x(a);new new x(a)(a);
```

**Comment by hzoo** [comment]
Added the other commit in https://github.com/babel/babel/commit/21f76655ad1c7ba76461460354864265ec85df87

**Comment by hzoo** [comment]
Actually I'm not sure how we would do this for multiple calls of new (my patch only works for `new new` but not `new new new`). I don't think we have a reference to the parent of the parent in this module - it's only `export function NewExpression(node: Object, parent: Object) {`.

Who would do even `new new` anyway?

Maybe it would be better to just not do anything for multiple nested `NewExpression`.

**Comment by hzoo** [comment]
Talked with @amasad - just going to `return` if the parent of the `NewExpression` is a `NewExpression`

**Pull request merged**
