### PR TITLE
Support existential operator

### LINKED ISSUE #855: Elvis/existential operator?
I know this is out of spec, but it would be very nice to add support for Elvis operator in playground. 

```js
object?.property // object && object.property
foo?() // foo && foo() 
```

### PR DESCRIPTION
**Pull request by naholyr**
This should fix #855 and #2628 by adding a new option ``existentialOperator`` (no ``es7.`` prefix as there is no proposal afaik).

If set to true, this non-standard syntax will be successfully recognized:

```js
o?.x
```

The result is the same as parsing ``o.x`` unless the left node will earn a new attribute ``existentialOperator: true``.

## Additional syntax

The third commit in this PR removes support for ``o?[x]`` and ``foo?()`` as it brings confusion with ternary operator (at this point, enabling the option would even raise SyntaxError if you try to use ternary with an array or parens).

Which is why I **discarded those changes** and limited support to the simple ``?.`` operator.

I'd propose following [Biju's proposal](https://mail.mozilla.org/pipermail/es-discuss/2014-May/037261.html) to support weird-but-not-confusing syntax ``o?.[x]`` and ``foo?.()``.

## Next steps

* Is there a chance it's merged as it's not part of any standard yet?
* Should I rename the option?
* Should I add the alternative syntaxes?

### CODE REVIEW

**Comment by sebmck** [comment]
This is not an active proposal being considered by the TC39 and so has no place in Babel. Please refer to discussion in #855 and #2628 on why this is not appropriate.

**Comment by jmm** [comment]
@sebmck I was about to hit the post button with pretty much the same thing when your comment appeared. I thought perhaps @naholyr was thrown off by [this outdated comment](https://github.com/babel/babel/issues/855#issuecomment-75400012).

**Comment by naholyr** [comment]
But then how can we move forward?

Making Babylon extensible will cost a lot more (and is supposedly not a priority) than merging those 4 LoC, and the argument sounds weird now that babel is admittedly **not** only an ES2015 transpiler (which it was already not, as soon as it supported JSX).

**Comment by sebmck** [comment]
Babel is not about to become an entirely new language. The only non-standard syntax that it supports is JSX and Flow and there's better justification for those because they're actual specifications.

**Comment by naholyr** [comment]
Well, it's far too much a structuring choice to be discussed here, and I understand your point, but you have to agree that this operator is [by far closer to a future standard](https://github.com/rwaldron/tc39-notes/blob/master/es6/2012-09/sept-20.md#existential-operator-strawman-discussion) than JSX or Flow ;)

**Comment by jmm** [comment]
@naholyr
> and the argument sounds weird now that babel is admittedly not only an ES2015 transpiler (which it was already not, as soon as it supported JSX).

As of v6 it's just a generalized JS transformation platform. It's specifically been architected so that Babel / Babylon doesn't know about ES2015 or JSX or {{whatever}}. Granted, the API may not be there yet for implementing this kind of thing in a plugin, but that's the way forward. Even if it would've made sense to implement this in Babylon in v5 (which I'm not saying) it wouldn't make sense to backtrack from extracting all specific transforms to plugins and add this to the parser.

**Comment by sylvainpolletvillard** [comment]
Null Propagation operator moved to stage 1

https://github.com/tc39/proposals/commit/cb447642290a55398d483f5b55fb7f973273c75d

**Comment by hzoo** [comment]
yep, would be first a parser change (in https://github.com/babel/babylon/ now)

**Comment by kristofdegrave** [comment]
Hi,

I have an old fork ready to implement this. I tried to add this some months ago, but it was to early (https://github.com/babel/babylon/issues/205)

my plugin: https://github.com/kristofdegrave/babel/tree/master/packages/babel-plugin-transform-conditional-member-access
Changes to babylon: 
https://github.com/kristofdegrave/babylon/commit/beb97e6e9b485938252d59c55432bd92cea694a1

I'll bring the branches up-to-date so they can hopefully be added.

**Pull request closed without merging**
