### PR TITLE
babel-plugin-constant-folding: evaluate only if resulting value is le…

### PR DESCRIPTION
**Pull request by hzoo**
…ss bytes than original

Not sure if this would be the right implementation - I guess it depends on if a minified file or more optimized one is wanted? Maybe it could be a plugin option value in the future?

```js
// Input 
1 / 3
// Output
0.333333333333333
// Output - check the output length
1 / 3
```

### CODE REVIEW

**Comment by sebmck** [comment]
But the goal of the constant folding plugin isn't to do this?

**Comment by hzoo** [comment]
Yeah I guess it's more for the minifier

**Comment by sebmck** [comment]
But `0.333333333333333` _might_ actually gzip better than `1 / 3`. I'm not sure if constant folding is a good thing for a minifier to be doing anyway.

**Comment by hzoo** [comment]
Yeah maybe because of the 3's - should probably look into that more - I'l close

**Pull request closed without merging**
