### PR TITLE
test: ensures standalone is built into ES5

### LINKED ISSUE #14112: [Bug]: Rogue 'let' statements in Babel package breaks ES5 support
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Other (Next.js, Gatsby, vue-cli, ...)

### Input code

<script src="https://unpkg.com/@babel/standalone@7.16.4/babel.min.js"></script>

### Configuration file name

_No response_

### Configuration

_No response_

### Current and expected behavior

Browsers which don't support ES6 (e.g. Gecko/20100101 Firefox/43.0) throw a syntax error due to instances of 'let' in the standalone package.

The expected behaviour is that 'let' would be 'var' in this package, allowing older browsers to use Babel.

### Environment

N/A

### Possible solution

There are 11 instances of 'let' in this package, here's one: `for(let e=1;e<t.length;e++)`  They are all grouped together right at the top of the file.  By contrast, there are 5,114 instances of 'var', so it's 99.8% ES5 compliant.

### Additional context

This is generating errors for Google's Blockly Games, where we attempt do a client-side transpile of user-created ES6 code to ES5.

Originally posted as #14008 as a discussion more than a month ago, but got no traction.

### PR DESCRIPTION
**Pull request by JLHwung**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #14112 
| Patch: Bug Fix?          | Y
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

This PR is built upon #14003, a test is added to ensure that `@babel/standalone` is ES5-compliant.

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/14124"></a>

### CODE REVIEW

**Comment by nicolo-ribaudo** [comment]
Rollup was pinned with `~` because of https://github.com/rollup/rollup/issues/4195, which will be solved by https://github.com/rollup/plugins/pull/1038. I have a PR to test that rollup fix: https://github.com/babel/babel/pull/14003.

**Comment by JLHwung** [comment]
I will update that PR and rebase this one upon that. The https://github.com/rollup/plugins/pull/1038 won't be merged soon due to watch mode support, but we don't need it anyway.

**Comment by nicolo-ribaudo** [comment]
Could you rebase this on `main`?

**Comment by JLHwung** [comment]
On the failing breaking Babel e2e test, did we decide that `@babel/standalone` 8 will drop IE11 support? If so we may bump the syntax standard of `@babel/standalone` to ES2015 or higher. Or I can disable that test for now.

**Comment by nicolo-ribaudo** [comment]
At least for `@babel/preset-env` it would probably be good to compile down to es5 rather than to something newer. I think that the change is because in Babel 8 we target Node.js 14, and that has also affected `@babel/standalone`.

**Review by liuxingbaoyu — APPROVED** [review]

**Pull request merged**
