### PR TITLE
Add strict option to es2015 preset

### PR DESCRIPTION
**Pull request by Tom910**
| Q                        | A 
| ------------------------ | ---
| Patch: Bug Fix?          | no
| Major: Breaking Change?  | no
| Minor: New Feature?      | yes
| Deprecations?            | no
| Spec Compliancy?         | yes
| Tests Added/Pass?        | yes
| License                  | MIT
| Dependency Changes       | no

I added the strict option for es2015 preset, which includes this setting for babel-plugin-transform-es2015-block-scoping and babel-plugin-transform-es2015-modules-commonjs. At this moment, there is no another way to enable this option for preset. I think it could be useful.

### CODE REVIEW

**Comment by loganfsmyth** [comment]
What is your definition of `strict`? It seems strange to relate it to throwIfClosureRequired. For the module `strict` flag, see https://github.com/babel/babel/pull/5362

**Comment by Tom910** [comment]
>It seems strange to relate it to throwIfClosureRequired.
What better name to choose to turn on the `throwIfClosureRequired`? For me this is also suitable for a strict mode. So it does not allow to do something that gives excessive code

**Comment by loganfsmyth** [comment]
We could certainly expose a `throwIfBlockScopingClosureRequired` on `es2015` but I don't think it should relate to `strict` on CommonJS.

**Comment by Tom910** [comment]
Yeah, maybe. I thought to make a likeness of loose option

**Comment by loganfsmyth** [comment]
Closing since this hasn't seen any activity. happy to revisit though.

**Pull request closed without merging**
