### PR TITLE
Promote trailing-function-commas to stage 3

### PR DESCRIPTION
**Pull request by jacobrask**
See https://github.com/tc39/proposals

### CODE REVIEW

**Comment by jacobrask** [comment]
When running locally I don't get the failing test for babel-plugin-transform-class-properties, only the failing Flow tests which failed for me on master as well.

Does this fail due to the package not being published or version bumped? Should I do that in this pull request?

**Comment by hzoo** [comment]
can you rebase/push again?

**Comment by thejameskyle** [comment]
Looks good, be sure to merge https://github.com/babel/babel.github.io/pull/849 when publishing

**Comment by hzoo** [comment]
So how are we doing this? We are still using lerna 1.x which has a fixed version and this is a breaking change for the preset.

A few options I can think of
- make a minor release (don't think we should do this)
- major release which means all packages will be a 7.x (don't think we should do this either)
- lerna 2.x update https://github.com/babel/babel/pull/3509 and then use independent mode (not sure about this since specifiying the version for each can be annoying unless especially if we update all packages)
  - if we can incorporate a semantic release type feature it would be nice (github label -> release)
- make the presets independently versioned by themselves
  - either in the repo itself (lerna probably needs an update to support both if that's possible)
  - separate repo (and making sure the tests are still in the main repo)

**Comment by loganfsmyth** [comment]
I don't follow on this, is this a breaking change? As far as I can tell, we're only adding a new feature to `stage-3` and all else should be the same.

**Comment by jacobrask** [comment]
Right, stage-2 users don't experience any change.

**Comment by hzoo** [comment]
@loganfsmyth we have to remove it from 1 stage and move it to another right? I must be confusing myself haha.

Right if a user is using stage-2, then it automatically requires stage-3 so it's ok

**Comment by chicoxyzzy** [comment]
when are you plan to release this?

**Comment by hzoo** [comment]
The next minor - I could do it now but probably will wait for some other things to get in so this week or so

**Pull request merged**
