### PR TITLE
Pass `dirname` as extra metadata to preset constructor.

### PR DESCRIPTION
**Pull request by izaakschroeder**
| Q                 | A
| ----------------- | ---
| Bug fix?          |no
| Breaking change?  |no
| New feature?      | yes
| Deprecations?     | no
| Spec compliancy?  | ??
| Tests added/pass? | yes
| Fixed tickets     | N/A
| License           | MIT
| Doc PR            | N/A

Sometimes a preset would like to know where it should resolve relative paths from (e.g. any preset that uses https://github.com/tleunen/babel-plugin-module-resolver) and this extra information makes that possible.

### CODE REVIEW

**Comment by izaakschroeder** [comment]
Let me know if you need anything from me @hzoo 😄

**Comment by loganfsmyth** [comment]
Should we add this to plugins too?

**Comment by izaakschroeder** [comment]
@loganfsmyth I wouldn't be opposed personally, some plugins might make use of it.

**Comment by motiz88** [comment]
I am strongly in favour of doing this for presets. It would enable https://github.com/babel/babel-preset-env/issues/26 to Just Work™️ (see https://github.com/babel/babel-preset-env/pull/161 for an alternative approach without this change to core, involving passing an explicit path in preset options)

Re: Doing the same for plugins - 
1. Plugins appear to be cached rather than re-constructed for every file, so to add this we might need to undo that and risk a perf regression.
2. Plugins can already get at this information via the traversal machinery, right?

With that in mind - @hzoo @loganfsmyth, what are your thoughts at the moment? I'm thinking this just needs a test case and is otherwise ready to go.

**Comment by motiz88** [comment]
I've added a minimal test for this (on the back of an existing test, which is not ideal but I think reasonable here). @izaakschroeder I hope you don't mind my fiddling with your branch 😅 

All done now as far as I'm concerned. @xtuc thanks for the review, want to merge this?

**Comment by izaakschroeder** [comment]
Oh no by all means, happy to have this making progress @motiz88 😄

**Comment by yavorsky** [comment]
Cool! Then I could make some changes to https://github.com/babel/babel-preset-env/pull/161 and use `path` from 3-rd argument instead of explicit specifying in config.

**Comment by izaakschroeder** [comment]
Let me know if you need anything else from me @loganfsmyth, @motiz88. 🎉

**Comment by izaakschroeder** [comment]
Awesome! @hzoo Can you let me know what version this lands in? Thanks so much!

**Comment by hzoo** [comment]
Sorry for the super long delay, next release so probably this week/next.

**Comment by izaakschroeder** [comment]
No worries, that sounds great! 👌

**Comment by izaakschroeder** [comment]
Sorry for the nag, but any further idea when this is going out? 😄 Thanks!

**Pull request merged**
