### PR TITLE
Add `declare type` and `declare interface` Flow syntax support to 5.x

### PR DESCRIPTION
**Pull request by samwgoldman**
Backport of #3230 to 5.x branch

### CODE REVIEW

**Comment by samwgoldman** [comment]
cc @hzoo @amasad

**Comment by amasad** [comment]
LGTM, but I have no idea how we manage releases for 5.x. Did @sebmck recently do one?

**Comment by samwgoldman** [comment]
I don't think it's been done before, but it's not too hard to backport this stuff, and I'd like to use it without waiting for people to update to 6.x. If it turns out pushing 5.x is too hard, no big deal.

**Comment by kittens** [comment]
@amasad We've never done one. I'll need to figure out how to do one without accidently setting the npm tag to `latest`.

**Pull request merged**
