### PR TITLE
Rest params with es6.arrowFunctions disabled throws

### PR DESCRIPTION
**Pull request by bradencanderson**
Addresses #2332.

Now when rest parameters are compiled down to the `arguments` object, check that `es6.arrowFunctions` is enabled. If it's not, throw an error.

### CODE REVIEW

**Comment by jmm** [comment]
I don't know if there's other instances like this currently, but my understanding is that transformers are generally supposed to operate in isolation without awareness of other transformers. If something like this is going to be implemented it also makes me wonder if there should be an abstraction for identifying what syntax a transformer handles in case someone wants to, say, disable `es6.arrowFunctions` and use a custom arrow transformer.

**Comment by jmm** [comment]
Also, welcome to the Babel community and thank you for contributing @bradencanderson :smiley:

**Comment by bradencanderson** [comment]
What do you think of splitting the rest transformer into two transformers, one for classic functions (`es6.parameters`) and one for arrow functions (`es6.arrow-parameters`)? The latter would have a dependency on `es6.arrowFunctions` and `es6.parameters`.

**Comment by sebmck** [comment]
Transformers should not throw errors and should support all available syntax. The `es6.parameters` transformer should be converting arrow functions to normal ones.

**Comment by bradencanderson** [comment]
> The es6.parameters transformer should be converting arrow functions to normal ones.

That feels a little weird -- if es6.arrowFunctions is explicitly disabled, shouldn't the compiler respect that? There must be some philosophy about the purpose of transformers that I'm not getting.

**Comment by sebmck** [comment]
@bradencanderson If an arrow function has a rest parameter and the only way to compile it is through getting `arguments` then it should be compiling the arrow function to a normal one. A transform needs to be independent and not depend on other transformers. Transformer dependencies lead to brittle transforms.

**Comment by jmm** [comment]
I guess that caveat should just be documented and then people can decide whether they want to do without rest in the input or arrows in the output in those cases.

**Comment by sebmck** [comment]
Why any caveat? Why does it matter what features require desugaring in order to compile rest parameters?

**Comment by bradencanderson** [comment]
Thanks folks, this all makes sense.

**Comment by bradencanderson** [comment]
@sebmck Aren't arrow functions faster in V8 now? If we're producing slower code when people have explicitly opted out of that slow code, they should know.

**Comment by jmm** [comment]
@sebmck Maybe it doesn't. I was just thinking it's not necessarily immediately obvious that enabling rest and explicitly disabling arrows will still result in arrows being transformed in the output.

**Comment by jmm** [comment]
As you said though, I guess the user's expection just has to be that any transformer may transform any syntax.

**Comment by sebmck** [comment]
@bradencanderson If you're measuring it in some crazy amount of operations a second then sure. The difference is not significant. Documenting all the steps a transform goes through is tedious and unnecessary though. There are many intermediate representations for transforms that you don't know about and shouldn't know about.

@jmm It'd only transform arrow functions with rest parameters.

**Comment by jmm** [comment]
@sebmck 
> It'd only transform arrow functions with rest parameters.

Yes, I didn't mean to imply otherwise.

**Comment by bradencanderson** [comment]
Passing tests locally with 3.3.0.

**Comment by sebmck** [comment]
This PR is no longer applicable since this bug has been fixed in 6.0

**Pull request closed without merging**
