### PR TITLE
Bump `home-or-tmp` for `babel-register`.

### PR DESCRIPTION
**Pull request by wtgtybhertgeghgtwtg**
| Q                        | A 
| ------------------------ | ---
| Patch: Bug Fix?          | No
| Major: Breaking Change?  | No (for `babel@7.0.0`)
| Minor: New Feature?      | No
| Deprecations?            | No
| Spec Compliancy?         | No
| Tests Added/Pass?        | No
| Fixed Tickets            | N/A
| License                  | MIT
| Doc PR                   | No
| Dependency Changes       | Yes

Bump `home-or-tmp` from `^2.0.0` to `^3.0.0`.  `3.0.0` drops the ponyfills for `os.homedir` and `os.tmpdir`.

### CODE REVIEW

**Comment by hzoo** [comment]
Since it's just `os.homedir() || os.tmpdir();` I kinda wanted us to just use https://github.com/avajs/find-cache-dir instead? We did this for babel-loader already with https://github.com/babel/babel-loader/blob/e9e37029e0c5905d8846f69d9a0c348f3d49fe50/src/fs-cache.js#L164-L174

`const FILENAME = process.env.BABEL_CACHE_PATH || path.join(homeOrTmp, ".babel.json");`

**Comment by wtgtybhertgeghgtwtg** [comment]
Understood.

**Comment by hzoo** [comment]
I think we can still land it - It depends if everyone else agrees we should move the cache directory to node_modules or not - have any thoughts on that?

**Comment by wtgtybhertgeghgtwtg** [comment]
I'll reopen while you decide that.  I would like to have `find-cache-dir` bump the minimum supported version to `node@4.0.0` so it can bump the `find-up` dependency, but that's besides the point.

**Comment by hzoo** [comment]
I think we can make https://github.com/babel/babel/issues/5198 and still fallback to home-or-tmp?

**Comment by hzoo** [comment]
And if you'd like to do an issue to investigate slimming deps feel free to do so. I'm tried before but didn't find anything other than https://github.com/babel/babel/issues/5118 which would be in 7.0

**Comment by wtgtybhertgeghgtwtg** [comment]
`babel` is pretty small and close-knit, so there isn't really much to be done in that area outside of dropping ponyfills (the most obvious already done with https://github.com/babel/babel/pull/5179) and bumping stuff (i.e. bumping `detect-indent` from `^4.0.0` to `^5.0.0` for `babel-generator` would remove `repeating`, `is-finite`, and `number-is-nan`) for `babel@7.0.0`.

**Comment by hzoo** [comment]
> bumping stuff (i.e. bumping detect-indent from ^4.0.0 to ^5.0.0 for babel-generator would remove repeating, is-finite, and number-is-nan) for babel@7.0.0.

Ok yeah if you would like to make PRs for those in 7.0 would be appreciated!

**Comment by hzoo** [comment]
Actually I don't see any of those deps (must of been removed already) https://github.com/babel/babel/blob/7.0/packages/babel-generator/package.json

**Comment by wtgtybhertgeghgtwtg** [comment]
`repeating` is a dependency of `detect-indent@4.0.0`, but not `detect-indent@5.0.0`, which uses `' '.repeat`.  `repeating` depends upon `is-finite`, which depends upon `number-is-nan`.
PR: #5226

**Pull request merged**
