### PR TITLE
Test main next merge

### PR DESCRIPTION
**Pull request by nicolo-ribaudo**
There were a lot of conflicts in CI config files, so I want to be sure that they still work

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/11963"></a>

### CODE REVIEW

**Comment by nicolo-ribaudo** [comment]
@arcanis Yarn is failing in the e2e test, and we are seeing the same failure in https://github.com/babel/babel/pull/11962.

Lerna bumps `@babel/core` to 7.11.4, and it updates the various dependencies on that package to `@babel/core@workspace:^7.11.4`. Then, during prepack, Yarn throws `Error: @babel/core@workspace:^7.11.4: No local workspace found for this range`. I tried to SSH into the CI, and I correctly see that package as existing:
```
cat packages/babel-core/package.json 
{
  "name": "@babel/core",
  "version": "7.11.1",

```

Do you have any idea of what could be happening?

**Comment by nicolo-ribaudo** [comment]
This also fails with yarn-2.0.0-rc.36, so the error has probably been introduced by something else.

**Comment by arcanis** [comment]
This error is only supposed to happen when you're using a `workspace:` dependency [that doesn't even point to a workspace](https://github.com/yarnpkg/berry/blob/06b380070d55e8b6311ebaad10c469ad18f98c64/packages/plugin-pack/sources/index.ts#L50). When you're logged in, does running `yarn workspaces list` shows `@babel/core`?

**Comment by nicolo-ribaudo** [comment]
Yes, but it doesn't specify the version:
```
 YN0000: .
➤ YN0000: codemods/babel-plugin-codemod-object-assign-to-object-spread
➤ YN0000: codemods/babel-plugin-codemod-optional-catch-binding
➤ YN0000: eslint/babel-eslint-config-internal
➤ YN0000: eslint/babel-eslint-parser
➤ YN0000: eslint/babel-eslint-plugin
➤ YN0000: eslint/babel-eslint-plugin-development
➤ YN0000: eslint/babel-eslint-plugin-development-internal
➤ YN0000: eslint/babel-eslint-shared-fixtures
➤ YN0000: eslint/babel-eslint-tests
➤ YN0000: packages/babel-cli
➤ YN0000: packages/babel-code-frame
➤ YN0000: packages/babel-compat-data
➤ YN0000: packages/babel-core
➤ YN0000: packages/babel-generator
➤ YN0000: packages/babel-helper-annotate-as-pure
➤ YN0000: packages/babel-helper-bindify-decorators
➤ YN0000: packages/babel-helper-builder-binary-assignment-operator-visitor
➤ YN0000: packages/babel-helper-builder-react-jsx
➤ YN0000: packages/babel-helper-builder-react-jsx-experimental
➤ YN0000: packages/babel-helper-call-delegate
➤ YN0000: packages/babel-helper-compilation-targets
➤ YN0000: packages/babel-helper-create-class-features-plugin
➤ YN0000: packages/babel-helper-create-regexp-features-plugin
➤ YN0000: packages/babel-helper-define-map
➤ YN0000: packages/babel-helper-explode-assignable-expression
➤ YN0000: packages/babel-helper-explode-class
➤ YN0000: packages/babel-helper-fixtures
➤ YN0000: packages/babel-helper-function-name
➤ YN0000: packages/babel-helper-get-function-arity
➤ YN0000: packages/babel-helper-hoist-variables
➤ YN0000: packages/babel-helper-member-expression-to-functions
➤ YN0000: packages/babel-helper-module-imports
➤ YN0000: packages/babel-helper-module-transforms
➤ YN0000: packages/babel-helper-optimise-call-expression
➤ YN0000: packages/babel-helper-plugin-test-runner
➤ YN0000: packages/babel-helper-plugin-utils
➤ YN0000: packages/babel-helper-regex
➤ YN0000: packages/babel-helper-remap-async-to-generator
➤ YN0000: packages/babel-helper-replace-supers
➤ YN0000: packages/babel-helper-simple-access
➤ YN0000: packages/babel-helper-skip-transparent-expression-wrappers
➤ YN0000: packages/babel-helper-split-export-declaration
➤ YN0000: packages/babel-helper-transform-fixture-test-runner
➤ YN0000: packages/babel-helper-validator-identifier
➤ YN0000: packages/babel-helper-wrap-function
➤ YN0000: packages/babel-helpers
➤ YN0000: packages/babel-highlight
➤ YN0000: packages/babel-node
➤ YN0000: packages/babel-parser
➤ YN0000: packages/babel-plugin-external-helpers
➤ YN0000: packages/babel-plugin-proposal-async-generator-functions
➤ YN0000: packages/babel-plugin-proposal-class-properties
➤ YN0000: packages/babel-plugin-proposal-decorators
➤ YN0000: packages/babel-plugin-proposal-do-expressions
➤ YN0000: packages/babel-plugin-proposal-dynamic-import
➤ YN0000: packages/babel-plugin-proposal-export-default-from
➤ YN0000: packages/babel-plugin-proposal-export-namespace-from
➤ YN0000: packages/babel-plugin-proposal-function-bind
➤ YN0000: packages/babel-plugin-proposal-function-sent
➤ YN0000: packages/babel-plugin-proposal-json-strings
➤ YN0000: packages/babel-plugin-proposal-logical-assignment-operators
➤ YN0000: packages/babel-plugin-proposal-nullish-coalescing-operator
➤ YN0000: packages/babel-plugin-proposal-numeric-separator
➤ YN0000: packages/babel-plugin-proposal-object-rest-spread
➤ YN0000: packages/babel-plugin-proposal-optional-catch-binding
➤ YN0000: packages/babel-plugin-proposal-optional-chaining
➤ YN0000: packages/babel-plugin-proposal-partial-application
➤ YN0000: packages/babel-plugin-proposal-pipeline-operator
➤ YN0000: packages/babel-plugin-proposal-private-methods
➤ YN0000: packages/babel-plugin-proposal-private-property-in-object
➤ YN0000: packages/babel-plugin-proposal-throw-expressions
➤ YN0000: packages/babel-plugin-proposal-unicode-property-regex
➤ YN0000: packages/babel-plugin-syntax-class-properties
➤ YN0000: packages/babel-plugin-syntax-decimal
➤ YN0000: packages/babel-plugin-syntax-decorators
➤ YN0000: packages/babel-plugin-syntax-do-expressions
➤ YN0000: packages/babel-plugin-syntax-export-default-from
➤ YN0000: packages/babel-plugin-syntax-flow
➤ YN0000: packages/babel-plugin-syntax-function-bind
➤ YN0000: packages/babel-plugin-syntax-function-sent
➤ YN0000: packages/babel-plugin-syntax-import-meta
➤ YN0000: packages/babel-plugin-syntax-jsx
➤ YN0000: packages/babel-plugin-syntax-logical-assignment-operators
➤ YN0000: packages/babel-plugin-syntax-module-attributes
➤ YN0000: packages/babel-plugin-syntax-numeric-separator
➤ YN0000: packages/babel-plugin-syntax-partial-application
➤ YN0000: packages/babel-plugin-syntax-pipeline-operator
➤ YN0000: packages/babel-plugin-syntax-record-and-tuple
➤ YN0000: packages/babel-plugin-syntax-throw-expressions
➤ YN0000: packages/babel-plugin-syntax-top-level-await
➤ YN0000: packages/babel-plugin-syntax-typescript
➤ YN0000: packages/babel-plugin-transform-arrow-functions
➤ YN0000: packages/babel-plugin-transform-async-to-generator
➤ YN0000: packages/babel-plugin-transform-block-scoped-functions
➤ YN0000: packages/babel-plugin-transform-block-scoping
➤ YN0000: packages/babel-plugin-transform-classes
➤ YN0000: packages/babel-plugin-transform-computed-properties
➤ YN0000: packages/babel-plugin-transform-destructuring
➤ YN0000: packages/babel-plugin-transform-dotall-regex
➤ YN0000: packages/babel-plugin-transform-duplicate-keys
➤ YN0000: packages/babel-plugin-transform-exponentiation-operator
➤ YN0000: packages/babel-plugin-transform-flow-comments
➤ YN0000: packages/babel-plugin-transform-flow-strip-types
➤ YN0000: packages/babel-plugin-transform-for-of
➤ YN0000: packages/babel-plugin-transform-function-name
➤ YN0000: packages/babel-plugin-transform-instanceof
➤ YN0000: packages/babel-plugin-transform-jscript
➤ YN0000: packages/babel-plugin-transform-literals
➤ YN0000: packages/babel-plugin-transform-member-expression-literals
➤ YN0000: packages/babel-plugin-transform-modules-amd
➤ YN0000: packages/babel-plugin-transform-modules-commonjs
➤ YN0000: packages/babel-plugin-transform-modules-systemjs
➤ YN0000: packages/babel-plugin-transform-modules-umd
➤ YN0000: packages/babel-plugin-transform-named-capturing-groups-regex
➤ YN0000: packages/babel-plugin-transform-new-target
➤ YN0000: packages/babel-plugin-transform-object-assign
➤ YN0000: packages/babel-plugin-transform-object-set-prototype-of-to-assign
➤ YN0000: packages/babel-plugin-transform-object-super
➤ YN0000: packages/babel-plugin-transform-parameters
➤ YN0000: packages/babel-plugin-transform-property-literals
➤ YN0000: packages/babel-plugin-transform-property-mutators
➤ YN0000: packages/babel-plugin-transform-proto-to-assign
➤ YN0000: packages/babel-plugin-transform-react-constant-elements
➤ YN0000: packages/babel-plugin-transform-react-display-name
➤ YN0000: packages/babel-plugin-transform-react-inline-elements
➤ YN0000: packages/babel-plugin-transform-react-jsx
➤ YN0000: packages/babel-plugin-transform-react-jsx-compat
➤ YN0000: packages/babel-plugin-transform-react-jsx-development
➤ YN0000: packages/babel-plugin-transform-react-jsx-self
➤ YN0000: packages/babel-plugin-transform-react-jsx-source
➤ YN0000: packages/babel-plugin-transform-react-pure-annotations
➤ YN0000: packages/babel-plugin-transform-regenerator
➤ YN0000: packages/babel-plugin-transform-reserved-words
➤ YN0000: packages/babel-plugin-transform-runtime
➤ YN0000: packages/babel-plugin-transform-shorthand-properties
➤ YN0000: packages/babel-plugin-transform-spread
➤ YN0000: packages/babel-plugin-transform-sticky-regex
➤ YN0000: packages/babel-plugin-transform-strict-mode
➤ YN0000: packages/babel-plugin-transform-template-literals
➤ YN0000: packages/babel-plugin-transform-typeof-symbol
➤ YN0000: packages/babel-plugin-transform-typescript
➤ YN0000: packages/babel-plugin-transform-unicode-escapes
➤ YN0000: packages/babel-plugin-transform-unicode-regex
➤ YN0000: packages/babel-polyfill
➤ YN0000: packages/babel-preset-env
➤ YN0000: packages/babel-preset-flow
➤ YN0000: packages/babel-preset-react
➤ YN0000: packages/babel-preset-typescript
➤ YN0000: packages/babel-register
➤ YN0000: packages/babel-runtime
➤ YN0000: packages/babel-runtime-corejs2
➤ YN0000: packages/babel-runtime-corejs3
➤ YN0000: packages/babel-standalone
➤ YN0000: packages/babel-template
➤ YN0000: packages/babel-traverse
➤ YN0000: packages/babel-types
➤ YN0000: Done in 0s
```

**Comment by nicolo-ribaudo** [comment]
@JLHwung The bug has _not_ been introduced by https://github.com/babel/babel/pull/11777 (I can reproduce it even if I revert that commit)

**Comment by nicolo-ribaudo** [comment]
I give up for today, I'll properly bisect.

**Comment by JLHwung** [comment]
I can still reproduce the e2e error if we replace `workspace:\^7\.\d+\.\d+` to `workspace:*`, which is also recommended in the docs.

**Comment by arcanis** [comment]
Found the problem! There's an accidental lockfile (I think?) in `eslint/babel-eslint-parser/yarn.lock` that throws off Yarn when running `yarn pack` inside this folder - preventing it from detecting other workspaces.

**Comment by JLHwung** [comment]
The e2e error has been fixed in #11962.

**Comment by nicolo-ribaudo** [comment]
Closing, I'll do this again after the yarn PRs are merged into main.

**Pull request closed without merging**
