### PR TITLE
chore: specify package type [skip-ci]

### PR DESCRIPTION
**Pull request by JLHwung**
| Q                        | A 
| ------------------------ | ---
| License                  | MIT

Per [Node.js ECMAScript Modules Docs](https://nodejs.org/api/esm.html#esm_code_package_json_code_code_type_code_field), package should include "type" field and be explicit about it.

### CODE REVIEW

**Comment by nicolo-ribaudo** [comment]
While this PR doesn't add any new feature, I would prefer to merge it in v7.8.0. Since it changes every package, it will cause every package of the monorepo to be published even if the code is the same.
I think that we should keep patch releases small.

**Comment by JLHwung** [comment]
@nicolo-ribaudo I am also going to add `exports: false` to every package (other than `@babel/runtime`). I can prepend `exports: false` to `"licence": "MIT"` so that we can avoid merge conflicts, though.

**Comment by nicolo-ribaudo** [comment]
Since this PR is quite simple, you push the `exports` changes here as a separate commit and then we'll use "Rebase and merge" instead of "Squash and merge" if you prefer.

**Comment by nicolo-ribaudo** [comment]
I have added the `Ready to be Merged` label even if there is a single review, since this PR is quite straightforward.

**Pull request merged**
