### PR TITLE
Fix "--help" distinguish optional transforms

### PR DESCRIPTION
**Pull request by zertosh**
I miss the square brackets around optional transforms.

### CODE REVIEW

**Comment by sebmck** [comment]
Whoops. The `obj[key].metadata` existence check isn't necessary though since it's guaranteed to always exist.

**Comment by zertosh** [comment]
Fixed!

**Comment by sebmck** [comment]
:tada: Thanks!

**Comment by zertosh** [comment]
Whoa wait!

**Comment by sebmck** [comment]
wot

**Comment by zertosh** [comment]
It is necessary! The module formatters don't have metadata

**Comment by sebmck** [comment]
Oh...

**Pull request merged**
