### PR TITLE
Fix to add missing dependencies

### PR DESCRIPTION
**Pull request by tricknotes**
Without cached `node_modules`, build script fails caused by missing dependency.
(Such as https://travis-ci.org/tricknotes/babel/jobs/71286171)
 .
To fix this issue, some missing modules should be described at `package.json`.

### CODE REVIEW

**Comment by jmm** [comment]
I've been having problems building and found that I had to install `babel-core@5.6.x`, to get `make bootstrap` to run anyway.

**Comment by hzoo** [comment]
I only had to update babel to `5.6.23` to get `make bootstrap` to work - probably since it would include all those other dependencies as well?

**Comment by sebmck** [comment]
I don't understand the issue. I'm not sure why your Travis build is failing when [babel/babel](https://travis-ci.org/babel/babel/builds) works fine.

**Comment by hzoo** [comment]
Yeah his particular issue is weird since the commits are the same.

I'm referring to cloning babel and then trying to run `make bootstrap` leading to `Error: Cannot find module 'babel-core/lib/babel/transformation/modules'` which I fixed by updating the package.json to the latest babel version - `"babel": "^5.6.23",`

**Comment by sebmck** [comment]
Ah right I understand now, thanks for the clarification @hzoo. Stupid me was a hypocrite and relied on a file inside of `babel-core` whose location changed between versions. I've pushed out a patch that adds in a dummy file.

**Comment by tricknotes** [comment]
Hmm, it seems this issue is not fixed yet.

When I run the following command:
``` sh
$ rm -rf node_modules
$ make bootstrap build-dist
```

I met the following error:
```
cd packages/babel; \
	scripts/build-dist.sh
cd packages/babel-runtime; \
	node scripts/build-dist.js
module.js:338
    throw err;
    ^
Error: Cannot find module 'lodash/collection/each'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/tricknotes/src/github.com/babel/babel/packages/babel-runtime/scripts/build-dist.js:3:18)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
make: *** [build-dist] Error 1
```

To fix this, some dependencies are required for me.
```
$ npm install --save-dev lodash regenerator babel-plugin-runtime
```

Could you confirm this ?

**Comment by sebmck** [comment]
Your `make bootstrap` likely didn't finish properly. All of those dependencies are only used by `babel` package and they're included in the [package.json](https://github.com/babel/babel/blob/master/packages/babel/package.json).

**Comment by tricknotes** [comment]
Thanks, https://github.com/babel/babel/commit/da60230801c6e2566acf1305c5c493c9d2cfb163 fixes this issue.

**Pull request closed without merging**
