### PR TITLE
fix: The test `variance-annotations-with-jsx` with BABEL_8_BREAKING

### PR DESCRIPTION
**Pull request by liuxingbaoyu**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            |  
| Patch: Bug Fix?          |
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

I'm investigating the CI exception in the main branch.
It looks like this test is not legal. (I'm sorry I don't understand ts and jsx, please point out if I'm wrong)

If this PR can be passed, I will open a PR in the prettier.

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/14585"></a>

### CODE REVIEW

**Comment by nicolo-ribaudo** [comment]
The old tests are correct, because they are testing disambiguation between JSX and arrow functions with type parameters. I'll work on a fix for the failure tomorrow.

**Comment by liuxingbaoyu** [comment]
Is there anything I can do? Or close this PR. (I may not be able to work about the parser)

**Comment by nicolo-ribaudo** [comment]
Feel free to close this. If you want to try looking at the parser internals feel free to do so, just keep in mind that I'll probably start investigating it in ~24 hours so ping me if you start working on a fix!

**Comment by liuxingbaoyu** [comment]
(I have a question if you have time😊)
Is this a jsx statement or a ts statement, is the behavior correct in babel7?

**Comment by nicolo-ribaudo** [comment]
You can test it at https://www.typescriptlang.org/play?ts=4.7.0-beta#code/G4QwTgBAZgdg3BAFLAlBAvNArjAxgFwEsB7GRFAbwF84g
- select version 4.7
- make sure that JSX is enabled in the options (maybe it's the source type drop-down, I don't remember)
- there is somewhere an AST view, but usually just seeing the generated output is ok to understand what's going on

**Comment by liuxingbaoyu** [comment]
Thanks!
I tested and found that this error also exists, but it is treated as a recoverable error.
Is all we need to do to make it recoverable?

**Comment by liuxingbaoyu** [comment]
Well, after making it recoverable a new problem arose and I chose to give up.

**Pull request closed without merging**
