### PR TITLE
WIP: stage 2018 preset

### PR DESCRIPTION
**Pull request by dnalborczyk**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | 
| Patch: Bug Fix?          |
| Major: Breaking Change?  | 👍 `-> we're removing object rest/spread and async generator functions from stage 3 preset`
| Minor: New Feature?      |
| Tests Added + Pass?      |
| Documentation PR         | 
| Any Dependency Changes?  |
| License                  | MIT

based on https://github.com/babel/babel/pull/7406 and https://github.com/babel/babel/pull/7408

### CODE REVIEW

**Comment by TrySound** [comment]
@dnalborczyk I thought this kind of modules are deprecated in favor of `babel-preset-env`. Do we need new deprecated package?

**Comment by dnalborczyk** [comment]
@TrySound  good point, if that is the case this can be closed.

**Comment by hzoo** [comment]
Thanks for the PR!

>  I suppose we would still need to rename both in the stage-3-package, or, better, remove them entirely. it would be quite confusing otherwise - as well as adjust the preset-env package.

I'm confused? Yeah we are planning on making any yearly presets as I have described in https://babeljs.io/blog/2017/12/27/nearing-the-7.0-release + deprecated yearly presets

**Comment by hzoo** [comment]
Going to close

**Comment by dnalborczyk** [comment]
@hzoo  as, you and @TrySound mentioned, yearly presets are deprecated.

I suppose we would still need to do any of the following to avoid confusion:

_(same applies to async generator functions)_

1. leave the v7 beta.40 in stage-3-preset package as is (proposal)
2. leave them in stage-3, but rename both (proposal -> transform)
3. remove both

**Pull request closed without merging**
