### PR TITLE
Extract config file resolution from OptionsManager 

### PR DESCRIPTION
**Pull request by jamestalmage**
Currently OptionsManager encompasses a number of tasks:

1. Climbing up the directory tree for the correct `.babelrc` / `.babelignore`
2. Following the `extends` option to find base configurations which are being extended.
3. Combining all applicable config files into a single set of options for use in the transform.

This PR separates `1` and `2` from `3`. 

`build-config-chain.js` now does all the file system searching, and builds a list of configs that should be merged.

`OptionsManager#mergeOptions` no longer calls itself recursively.

The entire operation is essentially reduced to:

```js
buildChain({filename}).forEach(config => optionManager.mergeOptions(config));
```

Great care was taken to ensure that `build-config-chain.js` builds the list of options in the same order as they would have been merged in `OptionsManager` previously.

`build-config-chain.js` - has a very minimal dependency list, and building the chain does not require loading up any of the rest of `babel-core`, or any plugins. I believe this could be used to greatly reduce performance hits caused by `require`-ing lots of modules that may never be used. Additional refactoring to `babel-register` could prevent loading up `babel-core` unless it is actually needed.

https://github.com/avajs/ava/pull/945 improves performance of AVA test suites some 30%-50% by precompiling in the main process, and avoiding `babel-register` for child processes. However, it does not work well for dynamic requires.

My eventual goal is to reduce the penalty for `babel-register` to near-zero when it isn't needed (because AVA successfully precompiled everything in the main process), but still have it in place in case of dynamic requires.

I think this has practical use outside of the AVA use cases described above. For one, I think it just provides a better separation of concerns. Secondly, I think it would be fairly easy to inspect the chain and determine if more aggressive caching was possible.

### CODE REVIEW

**Comment by jamestalmage** [comment]
Any feedback on this from the Babel team?

**Comment by hzoo** [comment]
So you're not just left here - Sorry, haven't been able to look at this (haven't really looked options in much detail anyway)

**Comment by loganfsmyth** [comment]
I'm totally for this as long as we're sure the config ordering will still be identical. The amount of state tracked inside the OptionsManager has been a little crazy to follow.

So I understand your long-term goal, you'd like to be confident in the options used for a file without having to load babel-core itself? Are you planning another step once this lands to expose an API to do that?

I'm all for all of this, I wish Babel had better logic for caching builds safely, but at least this is a step in a better direction.

**Comment by jamestalmage** [comment]
> So I understand your long-term goal, you'd like to be confident in the options used for a file without having to load babel-core itself? Are you planning another step once this lands to expose an API to do that?

Yes and Yes. I am happy to keep plugging away at that goal. I would prefer to do it in smaller PR's so the core team can comment on the progression and help steer the implementation details, but I can just continue to pile on to this PR if you want proven benefits before merging.

**Comment by jamestalmage** [comment]
> I'm totally for this as long as we're sure the config ordering will still be identical.

I spent a lot of time ensuring that, and I really do think I got it right. An added benefit of this change is that config ordering is now testable/tested.

**Comment by loganfsmyth** [comment]
Let's do this

**Comment by hzoo** [comment]
Thanks for all the work + tests @jamestalmage! 🎉

**Comment by loganfsmyth** [comment]
I think the benefits for overall readability and API clarity are worth it in their own right, but also happy to iterate on public APIs for config access too. Thanks for the help!

**Comment by jamestalmage** [comment]
Awesome! Thanks!

**Comment by montogeek** [comment]
"extended" plugin refers to which plugin?

**Comment by loganfsmyth** [comment]
@montogeek Not sure I understand? Babel lets you use `extends` in your config to do

```
{
  extends: "../otherDir/.babelrc",
}
```
to pull in config from a different config file.

**Comment by montogeek** [comment]
@loganfsmyth Thanks for the reply, I miss this option, I asked because found some errors when migrating tests to Jest

**Pull request merged**
