### PR TITLE
Add tests for IIFEs as default exports.

### PR DESCRIPTION
**Pull request by pygy**
This will hopefully help answer the question *["If a bug hatches in a tower and there's no one to watch it live and die, is it still a bug?"](https://github.com/babel/babel/issues/1755)*.

As a side note, there are four unrelated tests that are failing on my end, and seven left pending, should I report them?

### CODE REVIEW

**Comment by sebmck** [comment]
Thanks! :)

> As a side note, there are four unrelated tests that are failing on my end, and seven left pending, should I report them?

Pending tests are just test stubs and aren't an issue. Failing tests would be an issue with your environment as they're passing on [Travis](https://travis-ci.org/babel/babel/builds). Either that or you caught me in the middle of some refactoring which I've been doing for the past ~6 hours.

**Comment by pygy** [comment]
I've just pulled from the main repo then `make clean` and `make bootstrap` and I still get this:

https://gist.github.com/pygy/82a547961876570af685

**Comment by sebmck** [comment]
Yep, it's an environment issue. You're using an old Node version, probably 0.10.

**Comment by pygy** [comment]
Indeed, v0.10.33

All fine then (-:

**Comment by pygy** [comment]
Unrelated, but seeing how you're treating GH issues as a chat, are you using an interface on top of them?

**Comment by sebmck** [comment]
What do you mean, as a chat?

**Comment by pygy** [comment]
Sub-minute responsivity.

**Comment by sebmck** [comment]
Nope. I just check my emails and respond as they come in.

**Comment by pygy** [comment]
Thanks :-)

**Comment by jmm** [comment]
@pygy In case you don't know, there *is* a chat about babel though: https://babeljs.slack.com/

**Comment by pygy** [comment]
@jmm apparently I need an @tenpla.net email address to log in.

**Comment by jmm** [comment]
@pygy I'm not sure what you mean about that domain, but maybe I gave you a bad link in general. I thought it'd be possible to sign up via that URL, but maybe not. See the [README](https://github.com/babel/babel/blob/6386b60b9a6ce0c647048a629e6c8e3bcf3610ac/README.md) for the signup link.

**Pull request merged**
