### PR TITLE
Export type definition functions

### PR DESCRIPTION
**Pull request by rattrayalex**
| Q                 | A 
| ----------------- | ---
| Bug fix?          |  no
| Breaking change?  |  no
| New feature?      | yes
| Deprecations?     | no
| Spec compliancy?  | no
| Tests added/pass? | they pass, none added
| Fixed tickets     | https://discuss.babeljs.io/t/openning-up-definetype/771
| License           | MIT
| Doc PR            | The babel-handbook may need an update?
| Dependency Changes| 

I have a fork of babylon which parses a few novel bits of syntax into custom Nodes. I need to be able to define those types in Babel as well. Currently, I have a fork of babel which adds definitions in `babel-types`, but especially given the monorepo nature of the project that won't be feasible for production. 

In this PR, I simply expose the exports of `babel-types/definitions` from `babel-types`. I hope this change can be merged.

However, this alone is insufficient for an easily usable API, since important exports such as `TYPES` are defined at load time, and thus aren't updated when `defineType` is called outside of `babel-types/definitions/init`. Furthermore, `TYPES`, and possibly other such keys like `FLIPPED_ALIAS_KEYS`, are mutated by other babel packages (eg; [here](https://github.com/babel/babel/blob/master/packages/babel-traverse/src/path/index.js#L183)). 

For now, I intend to mutate `TYPES` in my code after calling `defineTypes`, but I'd also be happy to help implement a cleaner solution if possible. I played around with turning `TYPES` into a getter method (`Object.defineProperty(t, 'TYPES', { get() {...} }`), which worked, but seemed overly hacky. 

Thoughts?

Thanks so much!

### CODE REVIEW

**Comment by loganfsmyth** [comment]
This is a tough one. As you said, there are lots of ways Babel can fail due to unknown node types. I'm not sure we're ready to support that, and I'm a bit hesitant to allow partial support if we know it's not going to work all the way.

**Comment by rattrayalex** [comment]
I feel conflicted, personally. 
Currently, I use this function:

```
  function reallyDefineType(name, opts) {
    t.defineType(name, opts);

    t.TYPES.push(name);

    opts.aliases.forEach((alias) => {
      t.FLIPPED_ALIAS_KEYS[alias] = t.FLIPPED_ALIAS_KEYS[alias] || [];
      t.FLIPPED_ALIAS_KEYS[alias].push(name);

      if (!t.TYPES[alias]) t.TYPES.push(alias);
    });
  }
```

which does the job, but depends on my forked copy of Babel that contains this PR (that is, it simply exports `defineType`). I really don't want to have to ship a forked copy of Babel, and I also really don't want to have to copy/paste the contents of `defineType`, and I'm okay with continuing to use the function I wrote above.

That said, it would clearly be much better if `defineType` "just worked". 

To make that happen, all the scattered constant-construction happening at boot time in `index.js` needs to instead happen as a direct result of `defineType`. 

Now that I know the code a little better, I'd be willing to make a PR that does that, if you think it'd have a decent chance at being accepted @loganfsmyth ?

**Comment by rattrayalex** [comment]
After further evaluation, I'm pretty sure [my project](https://github.com/lightscript/lightscript) is dead in the water without this being merged... due to the monorepo nature of `babel`, I'm pretty sure I'd have to rename every single package in `packages` to something new and ship them all to NPM in order to be able to use this one change (happy to be proven wrong!). 

I'd be happy to do a refactor of `defineType` later to fully-support plugin-defined-types, but for now, my plugin can't live without these functions at least being exported 😅

@existentialism , I noticed you [commented](https://github.com/jlongster/prettier/pull/234#issuecomment-273384972) on my work over in `prettier` – any chance I could shamelessly parlay that into a consideration of this PR? 😉

**Comment by rattrayalex** [comment]
@loganfsmyth would you feel comfortable exporting only the assertion functions, and not `defineType`?

**Comment by loganfsmyth** [comment]
I'm triaging old PR on Babel. Since this has been sitting for ages, I'm going to close it. If it's a conversation you want to continue, feel free to re-open though. 

From my side, I just don't think this is a public API we'd want to maintain until we're ready to really explore custom parsing and AST handling.

**Pull request closed without merging**
