### PR TITLE
Expose parse (babylon) for plugins

### PR DESCRIPTION
**Pull request by xtuc**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | no (probably unused) 
| Patch: Bug Fix?          |
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR         | 
| Any Dependency Changes?  |
| License                  | MIT

See the `transform-eval` plugin for use case:

https://github.com/babel/babel/blob/master/packages/babel-plugin-transform-eval/src/index.js#L15

I like this idea because it tigh alone with traverse the parse with the current version of Babel.

### CODE REVIEW

**Comment by loganfsmyth** [comment]
We've talked about this a bit for https://github.com/babel/babel-eslint/issues/573#issuecomment-356352031 and https://github.com/babel/babel/pull/6332#issuecomment-333399009. Personally I think we should to expose a parsing function, but it should be more than just a pass-through to Babylon. We'd probably want it to essentially do the whole first phase of config loading and just skip transformation in favor of parsing and returning the AST.

**Comment by xtuc** [comment]
@loganfsmyth I agree, but i'm not sure to understand what do you mean with the config? Probably the Babylon configuration because right now it's not configured correctly, I will change it.

**Comment by kaicataldo** [comment]
@xtuc I believe this is to ensure that Babylon parses with the correct plugins given a user's .babelrc. This would be extremely useful for downstream projects like babel-eslint.

**Comment by xtuc** [comment]
@kaicataldo yes I understand, I will change it to take the current configuration into account.

**Comment by kaicataldo** [comment]
@xtuc Cool - I was going to work on this, but it looks like you've already got it!

**Comment by xtuc** [comment]
@kaicataldo this is a naive implementation, Babylon is not configured like Babel is (like the parser plugins).

**Comment by xtuc** [comment]
Closing this in favor of https://github.com/babel/babel/pull/7291

**Pull request closed without merging**
