### PR TITLE
Don't force chokidar@2 to be downloaded from registry.npmjs.org

### LINKED ISSUE #12181: Failed to install chokidar@2.1.8
## Bug Report

- [ ] I would like to work on a fix!

**Current behavior**

We have a bug installing `babel@7.12.0`.
The error we see is this one
```
error An unexpected error occurred: "https://registry.npmjs.org/chokidar/-/chokidar-2.1.8.tgz: ETIMEDOUT".
```
We are using a private repository, so we shouldn't access `registry.npmjs.org`.

**Expected behavior**

Install packages succesfully 

**Environment**

```
  System:
    OS: macOS 10.15.7
  Binaries:
    Node: 12.18.2 - ~/.nvm/versions/node/v12.18.2/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.5 - ~/.nvm/versions/node/v12.18.2/bin/npm
  Monorepos:
    Yarn Workspaces: 1.22.4

```
**Possible Solution**

Looks like it's related to this area of code
https://github.com/babel/babel/pull/12174/files#diff-51e4f558fae534656963876761c95b83b6ef5da5103c4adef6768219ed76c2deR13

**Additional context**

### PR DESCRIPTION
**Pull request by nicolo-ribaudo**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #12181
| Patch: Bug Fix?          | Yes
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  | https://github.com/nicolo-ribaudo/chokidar-2
| License                  | MIT

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/12182"></a>

### CODE REVIEW

**Review by JLHwung — APPROVED** [review]

**Comment by nstepien** [comment]
I think the following could have worked as well:
```json
    "chokidarAt2": "npm:chokidar@2.1.8"
```

**Comment by nicolo-ribaudo** [comment]
I think that it only works with yarn (https://docs.npmjs.com/files/package.json#dependencies does not mention it).

**Comment by nstepien** [comment]
Just did
```sh
npm i -D chokidarAt2@npm:chokidar@2.1.8
```
and it worked fine. I'm on npm 6.14.8.

And for extra confirmation, the package-lock.json ends up like this:
```json
    "chokidarAt2": {
      "version": "npm:chokidar@2.1.8",
      "resolved": "https://registry.npmjs.org/chokidar/-/chokidar-2.1.8.tgz",
      "integrity": "sha512-ZmZUazfOzf0Nve7duiCKD23PFSCs4JPoYyccjUFF3aQkQadqBhfzhjkwBH2mNOG9cTBwhamM37EIsIkZw3nRgg==",
      "dev": true,
      "requires": {
        "anymatch": "^2.0.0",
        "async-each": "^1.0.1",
        "braces": "^2.3.2",
        "fsevents": "^1.2.7",
        "glob-parent": "^3.1.0",
        "inherits": "^2.0.3",
        "is-binary-path": "^1.0.0",
        "is-glob": "^4.0.0",
        "normalize-path": "^3.0.0",
        "path-is-absolute": "^1.0.0",
        "readdirp": "^2.2.1",
        "upath": "^1.1.1"
      },
      "dependencies": {
        ...
```

**Comment by JLHwung** [comment]
@nstepien The `npm:` protocol, ironically, is not documented on npm docs: https://docs.npmjs.com/files/package.json#dependencies Can you verify that `npm:version-range` works for Node.js 6 (Npm 3)?

**Comment by nstepien** [comment]
It doesn't work with npm 3 unfortunately:
```
> npx npm@^3 i -D chokidarAt2@npm:chokidar@2.1.8
npx: installed 266 in 8.811s
npm ERR! Windows_NT 10.0.19041
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\xxx\\AppData\\Roaming\\npm-cache\\_npx\\11568\\node_modules\\npm\\bin\\npm-cli.js" "i" "-D" "chokidarAt2@npm:chokidar@2.1.8"npm ERR! node v6.17.1
npm ERR! npm  v3.10.10

npm ERR! Unsupported URL Type: npm:chokidar@2.1.8
```

**Pull request merged**
