### PR TITLE
Dependencies: Upgrade regexpu-core to ^4.0.2

### PR DESCRIPTION
**Pull request by ysangkok**
| Q                        | A 
| ------------------------ | ---
| Patch: Bug Fix?          | no
| Major: Breaking Change?  | no
| Minor: New Feature?      | no
| Deprecations?            | no
| Spec Compliancy?         | n/a
| Tests Added/Pass?        | no
| Fixed Tickets            | `Fixes #1, Fixes #2` 
| License                  | MIT
| Doc PR                   | 
| Dependency Changes       | yes

Updating this dependency two major releases allows for closer spec emulation.

### CODE REVIEW

**Comment by loganfsmyth** [comment]
Unfortunately this package only works on Node >= 4, while Babel 6 is stuck supporting 0.10 until we bump our major version next.

**Comment by ysangkok** [comment]
I understand. I am curious, how did you know that it won't work for Node < 4? I can't see any documentation about the compatibility.

**Comment by ysangkok** [comment]
Also, do you want me to close this?

**Comment by danez** [comment]
You can see this by looking at our testcases which are not failing on node 0.12. I close it for now and we can come back to this as soon as we drop node 0.12 support.

**Comment by loganfsmyth** [comment]
In this case I thought I remembered that being the case, so I looked in the `package.json` the `engine` line: https://github.com/mathiasbynens/regexpu-core/blob/855a27e43c4c3121d4a4ad70c6ad81d9f422f330/package.json#L8

**Comment by hzoo** [comment]
We can do this now

**Comment by hzoo** [comment]
shouldn't need to do anything else, @mathiasbynens?

**Comment by mathiasbynens** [comment]
Yeah, this is good to go. [All tests pass except in Node.js v0.12.](https://travis-ci.org/babel/babel/builds/192563564)

**Comment by hzoo** [comment]
Thanks @ysangkok (merged into 7.0)

**Pull request merged**
