### PR TITLE
ES7 trailing function commas

### PR DESCRIPTION
**Pull request by AluisioASG**
Implement stage 1 proposal as spec'ed at https://github.com/jeffmo/es-trailing-function-commas.

### CODE REVIEW

**Comment by sebmck** [comment]
Trailing commas in call expressions aren't in that proposal.

**Comment by AluisioASG** [comment]
The slides say otherwise.

**Comment by sebmck** [comment]
The proposal title of "Proposal to allow trailing commas in function parameter lists" is confusing then.

cc @jeffmo

**Comment by jeffmo** [comment]
Yea sorry, the title is misleading. The proposal is for both calling and definition param lists

**Comment by sebmck** [comment]
Thanks @AluisioASG!

**Comment by sebmck** [comment]
@AluisioASG Minding submitting a PR to [babel.github.io](https://github.com/babel/babel.github.io) adding docs?

**Comment by sebmck** [comment]
Released as of 5.1.0, thanks!

**Comment by AluisioASG** [comment]
Will do later today.

**Pull request merged**
