### PR TITLE
Handle typescript function overloading in a default export

### LINKED ISSUE #13594: [Bug]: babel/traverse cannot handle typescript function overloading in a default export
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@babel/cli

### Input code

The following code is valid TypeScript but crashes babel.

```typescript
export default function(choiceField: PDFDict, selectedIndex: number): void;
export default function(choiceField: PDFDict, selectedValue: string): void;
export default function(choiceField: PDFDict, selection: number | string) {
  // ...
}
```

### Configuration file name

babel.config.js

### Configuration

```
{
  presets: ['@babel/preset-typescript']
}
```

### Current and expected behavior

The expected behaviour is that it would transform properly. Instead, it crashes babel with the error stack that follows. 

> { TypeError: /home/thisissami/code/s2sBackend/s2sWebApi/src/libraries_v2/PDF/fillPDF/interactiveFields/choiceFields/fillChoiceField.ts: Cannot read property 'name' of null
>     at PluginPass.enter (/home/thisissami/code/s2sBackend/s2sWebApi/node_modules/@babel/plugin-transform-typescript/lib/index.js:263:59)
>     at newFn (/home/thisissami/code/s2sBackend/s2sWebApi/node_modules/@babel/core/node_modules/@babel/traverse/lib/visitors.js:171:21)
>     at NodePath._call (/home/thisissami/code/s2sBackend/s2sWebApi/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:53:20)
>     at NodePath.call (/home/thisissami/code/s2sBackend/s2sWebApi/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:40:17)
>     at NodePath.visit (/home/thisissami/code/s2sBackend/s2sWebApi/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:90:31)
>     at TraversalContext.visitQueue (/home/thisissami/code/s2sBackend/s2sWebApi/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:99:16)
>     at TraversalContext.visitSingle (/home/thisissami/code/s2sBackend/s2sWebApi/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:73:19)
>     at TraversalContext.visit (/home/thisissami/code/s2sBackend/s2sWebApi/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:127:19)
>     at Function.traverse.node (/home/thisissami/code/s2sBackend/s2sWebApi/node_modules/@babel/core/node_modules/@babel/traverse/lib/index.js:76:17)
>     at traverse (/home/thisissami/code/s2sBackend/s2sWebApi/node_modules/@babel/core/node_modules/@babel/traverse/lib/index.js:56:12) code: 'BABEL_TRANSFORM_ERROR' }

### Environment

- Babel Version: 7.14.8
- Node: 10.24.0
- OS: both windows 10 and Ubuntu 18.04

### Possible solution

This is not a fix, but it is a workaround. Avoiding overloading the `default` directly, but instead overloading the function elsewhere and then exporting that overloaded function as default works, as follows:

```ts
function fillChoiceField(choiceField: PDFDict, selectedIndex: number): void;
function fillChoiceField(choiceField: PDFDict, selectedValue: string): void;
function fillChoiceField(choiceField: PDFDict, selection: number | string) {
  // ...
}

export default fillChoiceField;
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by tony-go**
| Q                        | A
| ------------------------ | ---
| Fixed Issues?            | Fixes #13594 
| Patch: Bug Fix?          | 👍 
| Major: Breaking Change?  | ⛔ 
| Minor: New Feature?      | ⛔
| Tests Added + Pass?      | 👍 
| Documentation PR Link    | ⛔
| Any Dependency Changes?  | ⛔
| License                  | MIT

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/13605"></a>

### CODE REVIEW

**Comment by tony-go** [comment]
I always split my work, as following:
- Add the test case which fails
- Add the fix
- Tag the PR as `ready for review`

**Comment by nicolo-ribaudo** [comment]
Tip: in the PR description, don't just write the issue number but write "Fixes #13594": if you include the "Fixes" keyword, when this PR is merged the issue will be automatically closed.

**Comment by tony-go** [comment]
The CI seems to fail somewhere (`babel-old-version`). Anyway, I added a check for the `node.id` for the `isTSDeclareFunction` case. But I wonder if we shouldn't make a global check... 🤔 with `&&` ?

**Review by fedeci — APPROVED** [review]

**Comment by tony-go** [comment]
Friendly ping @JLHwung 🙌

**Review by JLHwung — APPROVED** [review]
Thanks!

**Review by nicolo-ribaudo — APPROVED** [review]

**Pull request merged**
