### PR TITLE
Flow: interface identifier should be declared in the scope

### LINKED ISSUE #10044: Export is not defined
## Bug Report

**Current Behavior**
SyntaxError: Export 'Foo' is not defined 

**Input Code**
```js
interface Foo {}

export type { Foo }
```

**Expected behavior/code**
no error

**Babel Configuration (.babelrc, package.json, cli command)**
flow plugin

**Environment**
- Babel version(s): 7.4.5
- Node/npm version: Node 11.13 / npm 6.7

**Possible Solution**
flowParseInterfaceish() should call checkLVal() or scope.declareName()

### PR DESCRIPTION
**Pull request by JLHwung**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #10044
| Patch: Bug Fix?          | Yes
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

A follow up to #9493: Declare interface identifier in the scope so that it would not be an undefined export. Thanks @jj-choi for suggestions to the solution.

As I didn't find any specification for Flow, I have developed several [test cases] on Flow REPL. We revise the `flowParseInterfaceish` according to the following observations:

| Declarations | Identifier Binding Type | Facts |
| --- | --- | --- |
| Interface<sub>[Declare]</sub> | `LEXICAL` | `interface I {}; interface I {}; ` will throw |
| Type<sub>[Declare]</sub> | `LEXICAL` | `type A = string; type A = string;` will throw |
| OpaqueType | `LEXICAL` | `opaque type A = string; opaque type A = string'` will throw |
| Class<sub>[+Declare]</sub> | `VAR` | `declare class A {}; declare class A{};` does _not_ throw<br> but `declare class A {}; class A{};` will throw |
| Variable<sub>[+Declare]</sub> | ??? | `declare var A; declare var A;` does _not_ throw<br> `declare var A; declare var A; var A` does _not_ throw |
| Function<sub>[+Declare]</sub> | ??? | `declare function A(): void; declare function A(): void; function A() {}` does not throw |

Since Class<sub>[+Declare]</sub> implies a `VAR` type binding identifier, I have changed the scope type of `DeclareModule` to `SCOPE_VAR`, otherwise the following snippet will throw:

```js
declare module M {
  declare class C{}
}
declare class C{}
```

## Known issues
We haven't applied `declareName` for Variable<sub>[+Declare]</sub> and Function<sub>[+Declare]</sub> since they can share the identifier name with `VariableDeclaration` and `FunctionDeclaration`, which means the following snippet would fail

```js
declare var A;
declare function B(): void;
export { A, B };
```

We may solve this issue by introducing `flowVars` to `Scope` and record them in an array other than `scope.vars`. However, I suggest we submit another PR to solve it before this one gets too big to review.

[test cases]: https://flow.org/try/#0EQVwzgpgBGAuBOBLAxrYBuAUJgJhZANgIbzSFFhhQDCAjFAN4C+We5pU5lNtAPACoA+Ri1z5iHRADtYEeADMiyaHRGtxJaLACeABxX0AvDATSA5li5VVzSwHspcHlGMAmLGPbQAtnZwgCaABZegZMKCg2CWhpWQUlAxFMUU9oqF9-QKgQxnDIjQ4dfWdjOCQpC2SPK2zQlKjNKFi5RWUoAEk69S8mmRaEjq7MGs6k1MaANxIoADUAMW60qfhZhcxl1Y8Gwr1ofiMoKRBvACM5RcaivYOj0-PMK6h9l0Pjs-gPO10iAEcQLV2T1cL1u7ywX1+-ygj34wOMoPu2G20HkICkqEQDlWAAoAJQALigEzsiBwFw4qPRsExUhxBKJJLJmEpGKx8zxSSAA

### CODE REVIEW

**Comment by tanhauhau** [comment]
I've a similar PR https://github.com/babel/babel/pull/10100, but I've no time to work on it now. Just FYI.

**Comment by JLHwung** [comment]
@tanhauhau Thank you. I should have found from the original issue that you are working on it. As our approaches are pretty similar, Nicolò will try to merge my test case to your implementation.

**Comment by JLHwung** [comment]
Update: I have merged #10100 add disabled some test related to Variable<sub>[+Declare]</sub> and Function<sub>[+Declare]</sub>

@tanhauhau This PR is almost same with #10100 except https://github.com/babel/babel/pull/10220/commits/a61fa147bbd4a6c67c3fefd8cdaab9d82111c795#diff-c3d4a6608f6a39a6a14b0c4f474c922cL197

**Comment by fisker** [comment]
/cc @JLHwung status? 

need this for prettier `@babel/parser` upgrade

**Comment by existentialism** [comment]
@fisker we've been waiting for someone on the Flow team to chime in

**Comment by fisker** [comment]
@fisker that's OK, just checking. 

FYI, this failure test is copy from flow project, and it has been broken since @bable/parser@7.4.0

**Comment by RReverser** [comment]
@existentialism Do you know who on the Flow team should be pinged to move this forward? This is currently the only issue/PR that is blocking Babel upgrade in Prettier.

**Comment by evilebottnawi** [comment]
Yep, it is blocker for us (prettier)

/cc @nmote maybe you can help?

**Comment by nmote** [comment]
At its face this all sounds reasonable. I'm not an expert on the parser; if you need an in-depth review I'd try to get in touch with @gabelevi or @mroch. What sort of feedback are you looking for from the Flow team?

**Comment by nicolo-ribaudo** [comment]
Mostly if it is being declared in the scope correctly, or if it should follow some other rules (for example regarding to shadowing/redeclaration)

**Comment by nmote** [comment]
Unfortunately I'm not really familiar with that area of the parser. My process would basically be to look at how it behaves in practice, which @JLHwung has already done.

**Comment by nicolo-ribaudo** [comment]
Well, let's merge this!

**Comment by evilebottnawi** [comment]
@nicolo-ribaudo any ETA for patch release?

**Pull request merged**
