### PR TITLE
Update micromatch to latest version

### PR DESCRIPTION
**Pull request by danez**
| Q                        | A 
| ------------------------ | ---
| Patch: Bug Fix?          | n
| Major: Breaking Change?  | n
| Minor: New Feature?      | n
| Deprecations?            | n
| Spec Compliancy?         | n
| Tests Added/Pass?        | n
| Fixed Tickets            | 
| License                  | MIT
| Doc PR                   | 
| Dependency Changes       | 

This throws currently in some tests.

### CODE REVIEW

**Comment by danez** [comment]
The babel-standalone tests fail @Daniel15 Do you have any idea? I guess that one of the new dependencies of micromatch does not work in a browser environment.

**Comment by Daniel15** [comment]
You might need to shim it in the Webpack config. Anything that uses the
file system needs to be shimmed. Usually just shimming the fs module is
sufficient though (the config already does that).

**Comment by loganfsmyth** [comment]
Hmm, personally I'd love to not have anything that Webpack can't process in our dependencies, we're so close right now to being able to build babel-standalone without any custom Webpack plugins. Would you be up for looking at the dep graph to see what is pulling those in? Maybe we can PR micromatch to drop that dependency.

**Comment by Daniel15** [comment]
We're always going to have to have some customized Webpack config though,
since filesystem access always needs to be shimmed.

Sent from my phone.

On Sep 15, 2017 7:04 PM, "Logan Smyth" <notifications@github.com> wrote:

Hmm, personally I'd love to not have anything that Webpack can't process in
our dependencies, we're so close right now to being able to build
babel-standalone without any custom Webpack plugins. Would you be up for
looking at the dep graph to see what is pulling those in? Maybe we can PR
micromatch to drop that dependency.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/babel/babel/pull/5992#issuecomment-329725174>, or mute
the thread

**Comment by loganfsmyth** [comment]
@Daniel15 In a perfect world, code that uses `fs` would be split off into files that swapped with stubs using the `browser` field in `package.json`. We've really close to that with `babel-core`, it's just that our dependencies don't all do that. I personally think if a module can function with an `fs` stub, it should proactively stub it and make the error messages useful. Like in `babel-core` I have https://github.com/babel/babel/blob/master/packages/babel-core/src/config/loading/files/index-browser.js

**Pull request closed without merging**
