### PR TITLE
Optimizations for asyncToGenerator

### PR DESCRIPTION
**Pull request by nooks**
Never use a bind!
Never use arguments as an array!

### CODE REVIEW

**Comment by zloirock** [comment]
Agree about `bind`, but why do you think usage `arguments` bad here? :) Engines optimize `apply` case.

**Comment by nooks** [comment]
Sorry http://jsperf.com/apply-null-arguments-vs-apply-null-args, but it is not necessary to use a bind

**Comment by nooks** [comment]
Могли бы и по русски поговорить :)

**Comment by zloirock** [comment]
Могли бы, но с этим лучше в личку - здесь не все поймут :)

**Comment by jdalton** [comment]
I think this depends on whether the `.apply` itself is inlined. If it is inlined then it won't trigger the perf hit of materializing the `arguments` object otherwise it will.

**Pull request merged**
