### PR TITLE
Bug fix for printing minified literals

### PR DESCRIPTION
**Pull request by shinew**
| Q                 | A
| ----------------- | ---
| Bug fix?          | yes
| Breaking change?  | no
| New feature?      | no
| Deprecations?     | no
| Spec compliancy?  | yes
| Tests added/pass? | yes
| Fixed tickets     | -
| License           | MIT
| Doc PR            | -

Now, when in minified mode, this prints the shorter of the literal's `raw` and `value`, rather than only the `value`. This is useful when the `raw` is shorter than the `value` ('5e4' vs '50000'), or vice versa ('5e1' vs '50').

### CODE REVIEW

**Comment by kangax** [comment]
Looks reasonable. /cc @hzoo @loganfsmyth

**Comment by hzoo** [comment]
Ugh need to look into the `babel-code-frame opts.highlightCode:` failing test - flaky

**Comment by shinew** [comment]
Would it make sense to integrate the literal minification logic from babili into this? This behavior is confusing in that it shortens to the literal, not the "global best" representation. (e.g. `1e1` -> `10`, but not `1000` -> `1e3`).

Oh, I guess that test must've passed on my machine ;)

**Comment by shinew** [comment]
I guess I'll wait until the flaky test has been resolved upstream?

**Comment by hzoo** [comment]
No it's cool, we can merge if it's good. babel-code-frame is part of this monorepo

**Pull request merged**
