### PR TITLE
[es6.tailCall] Move '<arg> = undefined' to the place in front of Continue statement. 

### LINKED ISSUE #2401: blacklist 'es6.blockScoping' error
Hi, I use `node@4.0.0`, so I add `es6.blockScoping` to babel blacklist, but an error occurred.

The code:
```js
function getFetchData(component = {}) {
  if (component.WrappedComponent) {
    return getFetchData(component.WrappedComponent);
  }
  return component.fetchData;
}
```

Compile:
```js
function getFetchData() {
  var _arguments = arguments;
  var _again = true;

  _function: while (_again) {
    component = undefined;
    _again = false;
    let component = _arguments.length <= 0 || _arguments[0] === undefined ? {} : _arguments[0];

    if (component.WrappedComponent) {
      _arguments = [component.WrappedComponent];
      _again = true;
      continue _function;
    }
    return component.fetchData;
  }
}
```

Error:
```
ReferenceError: component is not defined
```
Because `let component` only define once.

I think ES6 Default value should be to `var` rather than `let`.

### PR DESCRIPTION
**Pull request by jhen0409**
Fixed #2401.

### CODE REVIEW

**Comment by thejameskyle** [comment]
This seems okay, @sebmck good to merge?

**Comment by thejameskyle** [comment]
Actually @jhen0409 can you add a test case?

**Comment by jhen0409** [comment]
@thejameskyle I added a test case, but I don't know if ideal.

**Comment by sebmck** [comment]
cc @RReverser was there any reason it was done this way?

**Comment by RReverser** [comment]
There was something about values on the first pass, but can't find any case that would be broken so far. Maybe no more a problem with latest transformations.

**Pull request merged**
