### PR TITLE
Fixing T6644 with global __babel_native__

### PR DESCRIPTION
**Pull request by timdp**
Probably not the most elegant solution. See [T6644](https://phabricator.babeljs.io/T6644).

### CODE REVIEW

**Comment by timdp** [comment]
I'll gladly squash these into more decent commits once the proposed syntax gets approved.

**Comment by sebmck** [comment]
I'm not convinced this is the right solution as it just adds a whole lot more complexity. The `typeof` transform should just ignore children of nodes it's responsible for creating.

**Comment by timdp** [comment]
I'm cool with that. Just trying to help. There's already a discussion going
on under T6644.

**Comment by hzoo** [comment]
Goina close this one since we merged https://github.com/babel/babel/pull/3142 to fix the issue

**Pull request closed without merging**
