### PR TITLE
Babel-cli update dependencie chokidar

### PR DESCRIPTION
**Pull request by karlAlnebratt**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | 
| Patch: Bug Fix?          |
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR         | 
| Any Dependency Changes?  | chokidar: update to the latest version
| License                  | MIT

Update the `@bable/cli` watch dependency that used an outdated version.
The old version of `chokidar` is dependent och an old version of `fsevents`  that is dependent on an old version of `node-pre-gyp` that uses an old version of `hawk`. 

`hawk` in it case is using an old version of `hoek` that throws git dependencies scan warning 

screen shot 2018-05-02 at 10 19 08

screen shot 2018-05-02 at 10 20 09

### CODE REVIEW

**Comment by nicolo-ribaudo** [comment]
I don't think, since we don't expose that package.

**Comment by hal869** [comment]
I run
```
	yarn -v
		1.9.2
```

on linux/64.

I've got the @babel/*@7.0.0-beta.55 branches installed, e.g.
```
	├─ @babel/cli@7.0.0-beta.55
```

I see this was merged on May 13.  Fair to assume those changes *have* made it into 

atm, *every* time I exec any yarn install/upgrade, I still get the warning
```
	info fsevents@1.2.4: The platform "linux" is incompatible with this module.
	info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
```

checking
```
	yarn why fsevents
		yarn why v1.9.2
		[1/4] Why do we have the module "fsevents"...?
		[2/4] Initialising dependency graph...
		[3/4] Finding dependency...
		[4/4] Calculating file sizes...
		=> Found "fsevents@1.2.4"
		info Reasons this module exists
		   - "@babel#cli#chokidar" depends on it
		   - Hoisted from "@babel#cli#chokidar#fsevents"
		Done in 1.58s.

	yarn why chokidar
		yarn why v1.9.2
		[1/4] Why do we have the module "chokidar"...?
		[2/4] Initialising dependency graph...
		[3/4] Finding dependency...
		[4/4] Calculating file sizes...
		=> Found "chokidar@2.0.4"
		info Reasons this module exists
		   - "@babel#cli" depends on it
		   - Hoisted from "@babel#cli#chokidar"
		   - Hoisted from "webpack#watchpack#chokidar"
		info Disk size without dependencies: "144KB"
		info Disk size with unique dependencies: "608KB"
		info Disk size with transitive dependencies: "5.24MB"
		info Number of shared dependencies: 58
		Done in 1.61s.

	yarn why @babel/cli
		yarn why v1.9.2
		[1/4] Why do we have the module "@babel/cli"...?
		[2/4] Initialising dependency graph...
		[3/4] Finding dependency...
		[4/4] Calculating file sizes...
		=> Found "@babel/cli@7.0.0-beta.55"
		info Has been hoisted to "@babel/cli"
		info This module exists because it's specified in "devDependencies".
		info Disk size without dependencies: "88KB"
		info Disk size with unique dependencies: "6.12MB"
		info Disk size with transitive dependencies: "6.52MB"
		info Number of shared dependencies: 18
		Done in 1.66s.
```

**Comment by loganfsmyth** [comment]
Nope. It's specifically labeled "info" because it's not an error or a warning, just a notification.

**Comment by hal869** [comment]
> because it's not an error or a warning, just a notification.

Well, I guess that settles it?

Incessant, useless noise that's labelled "info" is ok?

Good thing every OTHER package doesn't feel the same ...

**Comment by loganfsmyth** [comment]
> Incessant, useless noise that's labelled "info" is ok?

Aggressively complaining to people with no control over what you're complaining about is not good use of your time. If your goal is not productive discussion, then you are not welcome here.

**Pull request merged**
