### PR TITLE
Fixes T7436: prevent extra newlines when 'retainLines' option is enabled

### PR DESCRIPTION
**Pull request by georgiy-abbasov**
https://phabricator.babeljs.io/T7436
Hi. I've suddenly stumbled upon this problem and it interrupted my work. I've tried to write a workaround to just go ahead and it looks like it works.
Anyway, i just wanted to draw your attention to the task above.

### CODE REVIEW

**Comment by loganfsmyth** [comment]
Totally open to exploring fixes for this, but this doesn't seem like the right approach to this issue. The core of the problem appears to be that the declaration is moved out of the generator but the position is preserved, causing it to jump lines earlier than it would otherwise have. That's what we should fix.

**Comment by georgiy-abbasov** [comment]
@loganfsmyth, thank you for attention. I've changed the code, so take a look please.

**Comment by georgiy-abbasov** [comment]
ping @loganfsmyth

**Comment by loganfsmyth** [comment]
Closing in favor of https://github.com/babel/babel/pull/3586

**Comment by georgiy-abbasov** [comment]
@loganfsmyth, thanks a lot.

**Pull request closed without merging**
