### PR TITLE
Simplify `helper-function-name` logic

### PR DESCRIPTION
**Pull request by nicolo-ribaudo**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | `Fixes #1, Fixes #2` 
| Patch: Bug Fix?          |
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

- We had some logic to avoid variable renames when injecting a new ID with the same name that in practice refers to the same variable. Remove that logic, as
  1. it's not actually necessary
  2. it's based on specific knowledge of our arrow functions transform, and might not apply to other callers of the helper
- We were assigning a `newId[NOT_LOCAL_BINDING] = true`, but that's not needed anymore

### CODE REVIEW

**Review by JLHwung — APPROVED** [review]

**Comment by nicolo-ribaudo** [comment]
@JLHwung I pushed a new commit, since I noticed that we have a custom wrapper for generators that we don't actually need (we can just return the generator object without `yield*`ing it, similarly to how we don't `await` promises).

**Review by JLHwung — APPROVED** [review]
Nice catch.

**Review by liuxingbaoyu — APPROVED** [review]
> We were assigning a newId[NOT_LOCAL_BINDING] = true, but that's not needed anymore

This is awesome, and this is the only plugin that sets it.

> I pushed a new commit, since I noticed that we have a custom wrapper for generators that we don't actually need (we can just return the generator object without yield*ing it, similarly to how we don't await promises).

I suspect this is to keep `FUNCTION_ID.prototype` unchanged, but I think the new behavior is fine.

**Comment by nicolo-ribaudo** [comment]
> This is awesome, and this is the only plugin that sets it.

We can then remove from wherever it's used, I'm not sure whether it should be considered a breaking change (for old versions of this plugin) or not.

> I suspect this is to keep FUNCTION_ID.prototype unchanged, but I think the new behavior is fine.

Yeah we already loose the prototype in many other wrapping cases

**Pull request merged**
