### PR TITLE
Yarn

### PR DESCRIPTION
**Pull request by hzoo**
Just adding the lock file? `yarn.lock`

I guess we should update https://github.com/babel/babel/blob/yarn/Makefile#L64 to be `yarn` instead of `npm install` + contributing.md if it's good

@kittens?

### CODE REVIEW

**Comment by danez** [comment]
But we also don't have shrinkwrap commited, does it make sense to commit lock files for libraries?

**Comment by hzoo** [comment]
This is just the devDependencies though?

**Comment by pi0** [comment]
**Good news!** I have made a wrapper package for `npm` which globally converts and wraps all `npm` commands to `yarn`, which fallback comp-ability to features like scoped packages :) 
Please check out [YarNPM](https://github.com/pi0/yarnpm)

**Comment by hzoo** [comment]
closing (not for libraries), also can just do a gitignore for the lock file

**Pull request closed without merging**
