### PR TITLE
fix: babel-traverse: handle removal of first element of ArrayPattern …

### PR DESCRIPTION
**Pull request by coderaiser**
…(#15523)

| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | https://github.com/babel/babel/issues/15523  
| Patch: Bug Fix?          | Yes
| Major: Breaking Change?  | No
| Minor: New Feature?      | No
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/15524"></a>

### CODE REVIEW

**Review by JLHwung — CHANGES_REQUESTED** [review]
This PR changes the expectation of `NodePath#remove`. Previously `NodePath#remove` removes `this.node` from the AST if the NodePath is within an array container, e.g. elements of ArrayPattern, bodies of BlockStatement, etc. Currently `NodePath#remove` _replaces_ the first such element with `null`.

There are two consequences:

1. When the container allows `null` as an element, namely the `ArrayExpression` and `ArrayPattern`. The first element will be replaced with `null`, this is still a breaking change:

    ```js
    NodePath("const [a, b] = c").get("...path of a").remove()
    // before:
    const [ b ] = c
    // after:
    const [ , b ] = c
    ```
    but the behaviour of other elements, when removed, are not changed.
    ```js
    NodePath("const [a, b] = c").get("...path of b").remove()
    // outputs
    const [ a ] = c
    ```

1. When the container does not allow `null`, we are generating invalid AST by replacing the first element with `null`, the CI fails due to unexpected AST shape.

I suggest we loose the constraint here:

https://github.com/babel/babel/blob/fe7c9a07cf4cd5ccaa1ee090715919d76f839991/packages/babel-traverse/src/path/replacement.ts#L121-L125

We can allow `null` if the parent is `ArrayExpression` / `ArrayPattern`, since in the AST `null` represents a hole in the array. So the new behaviour will be

```js
NodePath("const [a, b] = c").get("...path of a").replaceWith(null)
// outputs
const [, b] = c

NodePath("const [a, b] = c").get("...path of b").replaceWith(null)
// outputs
const [a, ] = c
```

In this way we can offer transform utility for both non-hole and hole output without breaking change.

**Comment by liuxingbaoyu** [comment]
I agree with that.
Because both behaviors make sense, and `const [b] = c;` will be consistent with the behavior of other nodes, which is more in line with human intuition.
At the same time, we manually modify it to `const [,b] = c;`just needs `path.node=null`, which is much simpler than manually modifying `const [,b] = c;`.

> I suggest we loose the constraint here:

I'm concerned that this will cause confusion in many cases of user error, and I'm inclined to add documentation advising users to temporarily use `path.node=null` or add a method `replaceWithNull`.

**Comment by liuxingbaoyu** [comment]
Or we can specifically detect the parent node type when `replaceWith(null)`.

**Comment by coderaiser** [comment]
I can explain why it’s useful.
If you have array of `items`, and you want to iterate it:

```js
for (const [i, item] of items.entries() {
    log(item);
}
```

But `i` isn’t used, you can find the node and remove it and you will have broken code:

```js
for (const [item] of items.entries() {
    log(item);
}
```

For other cases `path.remove()` works as expected: it removes the node. But for `ArrayPattern` things a little bit different, since it initializes variables with same value according to it’s position.

**Comment by JLHwung** [comment]
> But i isn’t used, you can find the node and remove it and you will have broken code:

Yes, this is exactly the reason why `path.node = null` should be used or `path.replaceWith(null)` should be introduced. In your case, the output AST should be `ArrayPattern [ null, identifier ]` rather than `ArrayPattern [ identifier ]`. To achieve this one should replace the first element with `null` rather than removing it.

It will be confusing if `NodePath#remove` sometimes removes element in an array and sometimes replaces it with `null`. Even in the `ArrayPattern` case, we can not dictate that removing the first element must result to an array hole. For example, suppose we are developing a codemod to migrate the usage from
```ts
function readFromProtocolV1(): [string, string, string]
const [magic, header, content] = readFromProtocolV1();
```
to
```ts
function readFromProtocolV2(): [string, string]
const [header, content] = readFromProtocolV2();
```
Now `NodePath(ArrayPattern).get(...first element).remove()` does the job. But if we change the behaviour, this codemod will be broken.

**Comment by coderaiser** [comment]
OK, that’s already handled by [`@putout/operate`](https://github.com/coderaiser/putout/tree/master/packages/operate#removepath), so for such low level operation as `path.remove()` better to keep smallest possible scope of responsibility.

Thank you guys for fast reply :)!

**Pull request closed without merging**
