### PR TITLE
Fixed link to @babel/parser's issues in README

### PR DESCRIPTION
**Pull request by naffiq**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            |  Fixed README link
| Patch: Bug Fix?          |
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | skip ci
| Documentation PR Link    | readme update
| Any Dependency Changes?  |
| License                  | MIT

Fixed link to issues in `@babel/parser` package's README

### CODE REVIEW

**Comment by existentialism** [comment]
We should update `https://github.com/babel/babel/blob/master/scripts/generators/readmes.js`, so this doesn't get overridden!

**Comment by naffiq** [comment]
@existentialism Thanks for pointing that out!
 Updated the generator script as well, should be all good now 👌

**Comment by naffiq** [comment]
@existentialism @kaicataldo 
Oops, should I do something about travis-ci?

**Comment by nicolo-ribaudo** [comment]
The travis error is fixed in https://github.com/babel/babel/commit/4c4c22a31675038cc10e9329e8b478f17156b337

**Comment by existentialism** [comment]
@naffiq thanks!

**Pull request merged**
