### PR TITLE
Install `psmisc` in Vue e2e tests on CircleCI

### PR DESCRIPTION
**Pull request by nicolo-ribaudo**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | 
| Patch: Bug Fix?          |
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

This is unrelated to the e2e vue fix we just merged.

Vue e2e tests on CircleCI recently started failing because the `fuser` command is not installed:
- https://app.circleci.com/pipelines/github/babel/babel/6546/workflows/e2c240b0-3e42-4c4e-84d1-d57459f5b249/jobs/45261
- https://app.circleci.com/pipelines/github/babel/babel/6545/workflows/4cd1899b-21c9-4b77-9650-a720f8d68f0b/jobs/45253
- https://app.circleci.com/pipelines/github/babel/babel/6545/workflows/90a641c1-be46-46bf-bfc7-5c0507d4f809/jobs/45252

I don't know why it stopped working, but maybe this PR fixes it :shrug:

### CODE REVIEW

**Review by JLHwung — DISMISSED** [review]

**Comment by nicolo-ribaudo** [comment]
Ok now `psmisc` is correctly installed, but there is another error because the Babel 8 patch has some conflicts

**Review by hzoo — APPROVED** [review]
do we want still want to pin the commit somehow since it's a dev branch?

**Comment by nicolo-ribaudo** [comment]
Even if it's a dev branch it's always green, so it isn't a big problem. Specifically, this PR was caused by some change in CircleCI and not in vue.

**Comment by nicolo-ribaudo** [comment]
It passed! https://app.circleci.com/pipelines/github/babel/babel/6551/workflows/2f298539-2417-42d9-8c88-c62ec42fde3e/jobs/45283

**Pull request merged**
