### PR TITLE
add guard for cannot find decorator of undefined

### PR DESCRIPTION
**Pull request by ajaymathur**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | N/A 
| Patch: Bug Fix?          | No
| Major: Breaking Change?  | No
| Minor: New Feature?      | No
| Tests Added + Pass?      | N/A
| Documentation PR         | 
| Any Dependency Changes?  |
| License                  | MIT

could get error `cannot find decorators of undefined` in case node is undefined. Could happen if node is deleted, therefore added guard for that.

### CODE REVIEW

**Comment by Andarist** [comment]
Why would it be deleted? Could you paste in example code and babel config which has resulted in an unexpected error being thrown?

**Comment by ajaymathur** [comment]
this case comes in this scenario, https://github.com/babel/babel/pull/7038

**Comment by nicolo-ribaudo** [comment]
I suspect that it is either a bug with that PR or with babel-traverse, since a NodePath should always have a node.

**Comment by ajaymathur** [comment]
So, In that PR. I am trying to running a loop over all the container nodes transforming them and then removing them from container. Like I don't want to transform the next nodes in container.

**Comment by loganfsmyth** [comment]
I'm triaging old PR on Babel. Since this has been inactive for ages, I'm going to close it. 

As mentioned, the node should be there, so if it is missing, It would be better to file a new bug with reproduction steps for that behavior so we can fix whatever is causing the node to be missing.

**Pull request closed without merging**
