### PR TITLE
fix(babel‑helpers/interopRequireWildcard): Avoid double nullish check

### PR DESCRIPTION
**Pull request by ExE-Boss**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Probably none
| Patch: Bug Fix?          | Yes
| Major: Breaking Change?  | No
| Minor: New Feature?      | No
| Tests Added + Pass?      | Not yet
| Documentation PR Link    | No
| Any Dependency Changes?  | No
| License                  | MIT

This avoids the double‑nullish check in `interopRequireWildcard`, since `undefined` and `null` are already covered by babel#10574.

### CODE REVIEW

**Comment by JLHwung** [comment]
Could you run `OVERWRITE=true make test-only` to overwrite the test fixtures?

**Comment by ExE-Boss** [comment]
I’m unable to do that for whatever reason, even with **WSL**.

Probably because I’m on **Windows** and I have a weird setup or something.

**Comment by nicolo-ribaudo** [comment]
@ExE-Boss Could you enable the "Allow edits from maintainers." at the bottom of the left sidebar here on GitHub? Then I can push the fixtures updates.

**Comment by ExE-Boss** [comment]
I&nbsp;have it&nbsp;enabled, but&nbsp;**GitHub** has&nbsp;bugs with&nbsp;forks on&nbsp;organisations.

**Comment by JLHwung** [comment]
@ExE-Boss I have updated the test fixtures. Could you run
```
git remote add JLHwung https://github.com/JLHwung/babel
git fetch JLHwung
git reset --hard JLHwung/fix/babel-helpers/interop-require-wildcard/avoid-double-nullish-check
git push origin fix/babel-helpers/interop-require-wildcard/avoid-double-nullish-check
git remote rm JLHwung
```
on your working branch?

**Comment by nicolo-ribaudo** [comment]
Thanks!

**Pull request merged**
