### PR TITLE
fix: wrong node name when add LabeledStatement to Program scope.globals.

### PR DESCRIPTION
**Pull request by lovetingyuan**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            |  No
| Patch: Bug Fix?          | Yes
| Major: Breaking Change?  | No
| Minor: New Feature?      | No
| Tests Added + Pass?      | Not added
| Documentation PR Link    | 
| Any Dependency Changes?  | No
| License                  | MIT

### CODE REVIEW

**Comment by nicolo-ribaudo** [comment]
What are the old and new behaviours?

**Comment by lovetingyuan** [comment]
input
```
test()
foo: bar.name
```
### old
visitor
```javascript
{
  Program(path) {
   assert.equal(Object.keys(path.scope.globals), ['test', 'undefined', 'bar'])
 }
}
```
### new
```javascript
{
  Program(path) {
   assert.equal(Object.keys(path.scope.globals), ['test', 'foo', 'bar'])
 }
}
```

**Comment by nicolo-ribaudo** [comment]
I think that the correct result should be `['test', 'bar']`: labels aren't global variables.

**Comment by lovetingyuan** [comment]
Yes, I think almost nobody still use label statement.
However, babel call `addGlobal` in `LabeledStatement`, I am not clear the reason to do that.
Thanks.

**Comment by JLHwung** [comment]
@lovetingyuan This code has been here since babel 6.0. Since it is always `undefined`, I don't think removing this would break anyone practically.

**Comment by lovetingyuan** [comment]
Yes, I think it does not matter, feel free to close this PR.
Thanks.

**Comment by nicolo-ribaudo** [comment]
@lovetingyuan I would still accept a PR which produces the output at https://github.com/babel/babel/pull/10776#issuecomment-559779436

**Pull request closed without merging**
