### PR TITLE
Remove check constants plugin

### LINKED ISSUE #5967: Remove the `check-es2015-constants` plugin and move code
Continuing from the fix for https://github.com/babel/babel/issues/5728 done in https://github.com/babel/babel/pull/5930, we should move that logic out into the two places it actually needs to be used.

* ~~`transform-es2015-modules-*` - `import`ed variables are constant, so assignments to them should throw~~ (This is now handled in `babel-helper-modules`)
* `transform-block-scoping` - `const` variables are constants, so assignments to them should throw

We currently have a plugin that doesn't really correspond to one specific part of the spec, meaning someone looking in `block-scoping` would probably expect it the handling to be in there, but it is not currently.

### PR DESCRIPTION
**Pull request by maurobringolf**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #5967   
| Patch: Bug Fix?          | No
| Major: Breaking Change?  | No 
| Minor: New Feature?      | No
| Tests Added + Pass?      | Not yet
| Documentation PR         | 
| Any Dependency Changes?  | No

It took me quite some time to figure out where to put the code inside `block-scoping`. I am not 100% sure if it is correct now, but according to the tests it should behave the same as before. But overall tests still fail and I dont understand why yet. As a first step it would be awesome if someone could confirm the placement of the check-constants logic or guide me on how to place it correctly.

### CODE REVIEW

**Comment by hzoo** [comment]
This can be removed in preset-env too then

**Comment by xtuc** [comment]
Shouldn't we rather move into the archive repo?

> We'll miss you babel-plugin-check-constants

**Comment by maurobringolf** [comment]
I was wondering this as well, since I saw some other things being archived.

**Comment by maurobringolf** [comment]
I got everything working, let me know if I should do anything regarding archives or other changes.

**Comment by rzr** [comment]
I observed that online doc:
http://babeljs.io/docs/en/plugins/#transform-plugins

still point to:
http://babeljs.io/docs/en/plugins/babel-plugin-check-es2015-constants

which is gone

Relate-to: https://github.com/babel/babel/issues/5967

**Comment by existentialism** [comment]
@rzr this plugin was removed in v7, http://babeljs.io/docs/en/next/plugins#transform-plugins

**Pull request closed without merging**
