### PR TITLE
Trailing commas in methods

### PR DESCRIPTION
**Pull request by amasad**
They're allowed

### CODE REVIEW

**Comment by amasad** [comment]
new release soon?

**Comment by sebmck** [comment]
Possibly, just a little worried that the perf work that's been done will break a lot of stuff that the tests didn't cover. I guess the only way is to release and get reports.

**Comment by amasad** [comment]
FWIW I finally ran our app end-to-end with babel. It's ~10mb of compiled JS. That's not bad of a signal :)

**Comment by sebmck** [comment]
True. Will push out a new release in <1 hour. Need to fix a couple more issues.

**Comment by sebmck** [comment]
Just published 5.3.0

**Comment by amasad** [comment]
thanks boss! :balloon: :balloon: :balloon:

**Pull request merged**
