### PR TITLE
chore: use npm install in babel-test262-runner setup

### PR DESCRIPTION
**Pull request by JLHwung**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes recent test262 error: https://app.circleci.com/jobs/github/babel/babel/16405
| License                  | MIT

Test262 is breaking recently with error message
```
30993) test/language/statements/class/subclass/builtin-objects/WeakSet/super-must-be-called.js strict mode # (expected success, got runtime error):
     Error: test/language/statements/class/subclass/builtin-objects/WeakSet/super-must-be-called.js strict mode # (expected success, got runtime error)
      at ReferenceError: $262 is not defined
      at lib/run-tests/index.js:65:11
      at undefined:314:2
      at Function.vm.runInESHostContext (/tmp/A6ROkEYz45yUtYvhXw7I/f-1581006044714-1819-xbyfk6.b0ok.js:15:13)
      at Object.<anonymous> (/tmp/A6ROkEYz45yUtYvhXw7I/f-1581006044714-1819-xbyfk6.b0ok.js:26:4)
```

A recent release of `eshost` (https://github.com/bterlson/eshost/commit/d7c39a1907108fa2fe535f36ce15efaa76465edd) breaks `babel-test262-runner` where we hardcoded the context variable `$`.

https://github.com/babel/babel-test262-runner/blob/63bad42d7f10210a2498a1725356d4a28f1777e5/lib/run-tests/babel-agent-runtime.js#L23

`babel-test262-runner` uses a npm lock file where `eshost` is pin to 6.4, so this is the minimum fix that should keep things working, otherwise we keep installing latest 6.x of `eshost`.

I will update `babel-test262-runner` later with latest `eshost` support.

### CODE REVIEW

**Comment by nicolo-ribaudo** [comment]
I think that `npm i` ignores the lockfile; we need `npm ci`.

**Comment by nicolo-ribaudo** [comment]
I have opened https://github.com/babel/babel/pull/11116 to check if we can fix the error directly in the runner, but I think that this PR should still be merged.

**Comment by nicolo-ribaudo** [comment]
This PR doesn't fix the problem.
It's CircleCI that shipped a breaking change in the artifacts paths: https://circleci.com/api/v1.1/project/github/babel/babel/15688/artifacts vs https://circleci.com/api/v1.1/project/github/babel/babel/16573/artifacts

**Comment by kaicataldo** [comment]
`npm i` doesn't ignore lockfiles (assuming it's a fairly recent version). That being said, `npm ci` should be much faster since it doesn't verify the lockfile against the constraints listed in `package.json`.

**Pull request merged**
