### PR TITLE
LiteralPropertyName should allow BigIntLiteral

### PR DESCRIPTION
**Pull request by JLHwung**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | LiteralPropertyName does not allow BigIntLiteral
| Patch: Bug Fix?          | Yes
| Tests Added + Pass?      | Yes
| License                  | MIT

Tracing through the spec:

```
LiteralPropertyName => NumericLiteral => DecimalBigIntegerLiteral
LiteralPropertyName => NumericLiteral => NonDecimalIntegerLiteral BigIntLiteralSuffix
```
Related: 
https://github.com/tc39/test262/pull/2457
https://bugs.chromium.org/p/v8/issues/detail?id=10083

CI is red due to
- [ ] https://github.com/microsoft/TypeScript/issues/35982

### CODE REVIEW

**Comment by nicolo-ribaudo** [comment]
You can run `make test-typescript-update-whitelist`

**Comment by JLHwung** [comment]
Yeah we can always revert the whitelist when TypeScript fixed this issue.

**Comment by nicolo-ribaudo** [comment]
Oh, I meant the fact that JS allows bigints as property names 😂

**Comment by JLHwung** [comment]
@nicolo-ribaudo Well it has been staged 4, so 🤷‍♂️

**Pull request merged**
