### PR TITLE
update debug dep because of security issue

### PR DESCRIPTION
**Pull request by modosc**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues             | `Fixes #1, Fixes #2` 
| Patch: Bug Fix?          | 
| Major: Breaking Change?  | 
| Minor: New Feature?      | 
| Tests Added/Pass?        | 
| Spec Compliancy?         | 
| License                  | MIT
| Doc PR                   | 
| Any Dependency Changes?  | 

https://nodesecurity.io/advisories/534

### CODE REVIEW

**Comment by xtuc** [comment]
Good catch, thanks.

The build failed on circleci but it seems unrelated. I don't know who is using `husky`.

**Comment by existentialism** [comment]
@xtuc husky is used by our precommit hook.

**Comment by existentialism** [comment]
@modosc thanks!

**Comment by yuliaHope** [comment]
@existentialism Could you update sources in npm repository, please? Now they're not relevant.

**Pull request merged**
