### PR TITLE
Add importKind to spec

### PR DESCRIPTION
**Pull request by danez**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Refs #9485 
| Patch: Bug Fix?          |
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

Adds importKind to spec.md

### CODE REVIEW

**Comment by nicolo-ribaudo** [comment]
Isn't that file generated? Even if it isn't, also the definition needs to be updated:
https://github.com/babel/babel/blob/3a9743fce43a9b8a87548ad6997d4b34fe8d5e93/packages/babel-types/src/definitions/es2015.js#L306-L327

**Comment by danez** [comment]
No that file isn't generated afaik. I can add it to the definition, although it would only be for the validation.

**Comment by nicolo-ribaudo** [comment]
I thought that it was generated because of https://github.com/babel/babel/pull/9343/files#r249301395

**Comment by danez** [comment]
I don't see any code that generates this file. It might have been a ide plugin that generated the toc for this person. That is weird.

**Comment by nicolo-ribaudo** [comment]
@danez I have updated @babel/types so that it is also included in packages/babel-types/lib/index.d.ts and packages/babel-types/lib/index.js.flow

**Comment by danez** [comment]
thanks 👍

**Pull request merged**
