### PR TITLE
test(plugin-proposal-class-properties): add failing test for decorator interop

### PR DESCRIPTION
**Pull request by buschtoens**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | 
| Patch: Bug Fix?          |
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes, No
| Documentation PR         | 
| Any Dependency Changes?  |
| License                  | MIT

This PR adds a failing test for the `proposal-class-properties` plugin, that shows an incompatibility with decorators in the TDZ check.

Specifically, there seems to be a problem with the scope. `classRef` is `undefined` here

https://github.com/babel/babel/blob/a07f96ce3f28ed053c7e5e061dae3627ff451bc5/packages/babel-plugin-proposal-class-properties/src/index.js#L123

and `path.scope.getBinding(path.node.name)` is `undefined` here

https://github.com/babel/babel/blob/a07f96ce3f28ed053c7e5e061dae3627ff451bc5/packages/babel-plugin-proposal-class-properties/src/index.js#L36

Therefore the above `if` condition evaluates to `true` and errorneously adds the `classNameTDZError`.

### CODE REVIEW

**Comment by buschtoens** [comment]
Referencing https://github.com/babel/babel/pull/6855, pinging @maurobringolf :smile:

**Comment by buschtoens** [comment]
There may be an edge case without the decorators transform that triggers this as well, but I could not come up with one.

**Comment by maurobringolf** [comment]
Thank you for providing the test case. I'm looking into it but I am not familiar with the decorators plugin yet.

**Comment by nicolo-ribaudo** [comment]
Merged in #8463. Thank you!

**Pull request closed without merging**
