### PR TITLE
optimisations.react.inline: don't pass empty array.

### PR DESCRIPTION
**Pull request by STRML**
This fixes incompatibilities with code that check for the existence of children when multiline elements are created.

The bug is that there is a difference between:

```
<Baz></Baz>
```

and

```
<Baz>
</Baz>
```

The second example contains a newline, which causes the optimization to pass an empty array when it should not pass the `children` prop at all.

Added a test case, which fails on `master`:

```
1) transformation/optimisation.react.inline elements multiline:

    /git/forks/babel/packages/babel/test/fixtures/transformation/optimisation.react.inline-elements/multiline/actual.js !== /git/forks/babel/packages/babel/test/fixtures/transformation/optimisation.react.inline-elements/multiline/expected.js
    + expected - actual

       $$typeof: babelHelpers.typeofReactElement,
       type: Baz,
       key: null,
       ref: null,
    +  props: babelHelpers.defaultProps(Baz.defaultProps, {}),
    -  props: babelHelpers.defaultProps(Baz.defaultProps, {
    -    children: []
    -  }),
       _owner: null
     });
```

### CODE REVIEW

**Comment by STRML** [comment]
Hmm does this need a rebase?

**Comment by STRML** [comment]
I've rebased - I can't seem to get the tests to run but they are identical to those from before, and they passed then. Not sure if this is 6.0 related. I wiped the project entirely and did a `make bootstrap`, `make build`, and `make test`:

```
~/g/f/babel (master|✔) $ env TEST_GREP=transformation make test
node node_modules/.bin/eslint packages/*/src
#flow check
./scripts/test.sh
module.js:339
    throw err;
    ^

Error: Cannot find module 'babel-runtime/helpers/interop-require-default'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/samuelreed/git/forks/babel/packages/babylon/lib/index.js:5:30)
```

**Comment by STRML** [comment]
Thanks!

**Comment by sebmck** [comment]
Sorry for the extreme delay!

**Comment by STRML** [comment]
No worries - this gets me closer to using these optimizations in production, which is a big win.

**Pull request merged**
