### PR TITLE
fix: Correctly generate `TSMappedType`

### LINKED ISSUE #16393: [Bug]: Typescript mapped type with implicit any results in faulty TS
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```ts
type Bar = { [key in Foo] };
```

### Configuration file name

_No response_

### Configuration

options passed to @babel/parser:
```js
{
    sourceType: 'module',
    plugins: ['typescript'],
}
```

### Current and expected behavior

When just parsed using @babel/parser and generated back using @babel/generator, with nothing else being done to AST, the mentioned code becomes:
```ts
type Bar = { [key in Foo]: };
```
which is an ivalid typescript, raises "Type expected" error because indeed, there is no type after `:`.

Expected behavior:
It should be generated back into
```ts
type Bar = { [key in Foo] };
```

### Environment

- Babel: 7.24.3
- @babel/plugin-syntax-typescript: 7.24.1
- Node: 18.19.0
- npm: 10.2.3

### Possible solution

If the `MappedType` node has its `type` field set to `undefined`, there should be no `:` printed out after the `[key in Foo]`.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by liuxingbaoyu**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #16393 
| Patch: Bug Fix?          | √
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | √
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

### CODE REVIEW

**Review by nicolo-ribaudo — APPROVED** [review]

**Review by JLHwung — APPROVED** [review]

**Comment by aczekajski** [comment]
@liuxingbaoyu Thank you for the swift fix!
I looked briefly at the PR and I have a feeling that it won't generate the same TS code in these cases:
```
type Foo2 = { [key in Bar]? };
type Foo3= { [key in keyof Bar]-? };
type Foo4 = { [key in keyof Bar]+? };
```

**Comment by liuxingbaoyu** [comment]
You are right, thank you! I will open a new PR.

**Comment by nicolo-ribaudo** [comment]
Ugh, til that's valid TS :grimacing:

**Comment by aczekajski** [comment]
[Suprisingly it is 😂](https://www.typescriptlang.org/play?noImplicitAny=false#code/C4TwDgpgBAQghgJygXinAdiA3AWAFCiRQBiA9qSlAN5QDaA1hCFAJbqyIC6UAvrgeGhlSAJko0GTVu3gJOAfl79CQ8gGZUExszZRtpAGYc5AWkV98KkuQAs4utul6mh45wDU5rEA)

**Pull request merged**
