### PR TITLE
fix: `preset-env` throws exception for `export * as x`

### LINKED ISSUE #16155: [Bug]: @babel/transform-export-namespace-from is not included after v7.23.3
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

Babel v7.23.2 - [Link](https://babeljs.io/repl#?browsers=node%2014&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=KYDwDg9gTgLgBAKjgQwM5wAoEszLgMyggFs4ByAOgHowdkyBuIA&debug=false&forceAllTransforms=false&modules=commonjs&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env&prettier=false&targets=&version=7.23.2&externalPlugins=%40babel%2Fplugin-transform-class-properties%407.23.3&assumptions=%7B%7D)
Babel v7.23.5 - [Link](https://babeljs.io/repl#?browsers=node%2014&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=KYDwDg9gTgLgBAKjgQwM5wAoEszLgMyggFs4ByAOgHowdkyBuIA&debug=false&forceAllTransforms=false&modules=commonjs&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env&prettier=false&targets=&version=7.23.5&externalPlugins=%40babel%2Fplugin-transform-class-properties%407.23.3&assumptions=%7B%7D)

### Configuration file name

_No response_

### Configuration

_No response_

### Current and expected behavior

After `7.23.3` version plugin `transform-export-namespace-from` is not included in config, provided by `@babel/preset-env`.

I belive it's because of changes in https://github.com/babel/babel/pull/15988/
Explicitly this [line](https://github.com/babel/babel/pull/15988/files#diff-bb38565ade744da31005fed35f391279a176bb8cbc960bc43b316ba10714cf37R399)
before that plugin included if `module !== "auto"`, but now it require `module === "auto"` to be included. Looks like a typo, since other part of that condition are changes properly (`api.caller?.(supportsExportNamespaceFrom)` into `!api.caller(supportsExportNamespaceFrom)` )

### Environment

Babel REPL

### Possible solution

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by liuxingbaoyu**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #16155 
| Patch: Bug Fix?          |
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

### CODE REVIEW

**Comment by liuxingbaoyu** [comment]
Because of its existence, it did not cause a more serious regression.
But I'm not sure if this PR is the best fix.
https://github.com/babel/babel/blob/328489729b3d39a1497bfe22b6be15507e0df640/packages/babel-preset-env/src/index.ts#L407-L418

**Review by nicolo-ribaudo — APPROVED** [review]
The old error makes sense when one feature was standard and one a proposal. Now nobody even knows that `export * as` was not introduced together with ESM.

**Comment by JLHwung** [comment]
This would be not consistent with how we treat dynamic `import()` in the module transforms, the `dynamic-import` plugin is required if `import()` is seen in module transforms

https://github.com/babel/babel/blob/665078b059e260275de7fcc74c50a3f0a50ec90a/packages/babel-plugin-transform-modules-amd/src/index.ts#L92

I think the expected behaviour should be: let `preset-env` add module related transform plugins when `modules` is not `false`, and respect the compat-data only when `module` is `false`.

**Comment by liuxingbaoyu** [comment]
https://github.com/actions/download-artifact/issues/249
I'm surprised it's been two weeks and it still hasn't been fixed.

**Review by nicolo-ribaudo — APPROVED** [review]

**Comment by nicolo-ribaudo** [comment]
I'd like to release a patch once this is merged.

**Review by JLHwung — APPROVED** [review]

**Comment by preservance717** [comment]
Hi @liuxingbaoyu @JLHwung @nicolo-ribaudo 
Could you help take a look the question when u are free,thx?

After the babel related dependencies in our project were upgraded from `7.23.7` to `7.23.8,` the page could not work normally and the page prompted the error `ES Modules may not assign module.exports or exports.*, Use ESM export syntax, instead: ./*/index.js`.
Related babel configuration:
```
 presets: [
      [
        '@babel/preset-env',
        {
          useBuiltIns: 'usage',
          corejs: 3,
        },
      ],
      [
        '@babel/preset-react'
      ],
      ['@babel/preset-typescript'],
    ],
plugins: [***]
```


If I want the page to work fine, I  need to use one of two following ways: 

- add configuration: `sourceType: "unambiguous"`, and the page will work normally. 
- Or change the ` '@babel/preset-env'` preset to
```
[
  '@babel/preset-env',
  {
    "targets": "defaults"
  },
]

```

What I'm curious about now is why 7.23.7 version doesn't need to add/update  configurations, but 7.23.8 version needs to change these configurations. I feel that it is related to the three latest PR changes (https://github.com/babel/babel/pull/16181 https://github.com/babel/babel/pull/16201 https://github.com/babel/babel/pull/16199), but I can't find the specific point. Can you help me check it out? will appreciate it.

**Comment by liuxingbaoyu** [comment]
Only this PR is relevant between 7.23.7 and 7.23.8, but I don't know how it breaks your build.
Can you provide a repository to reproduce?

**Comment by preservance717** [comment]
Thanks for your quick reply, I can't reproduce it on the practice demo, but I will try it on serval times, if reproduced successfully, I will provide it.

**Pull request merged**
