### PR TITLE
bump chokidar version due to security issue

### LINKED ISSUE #8034: Dependency on braces, which suffers from security vulnerabilities
Vulnerability report: https://snyk.io/vuln/npm:braces:20180219

To reproduce this error: run 
```
snyk test babel-cli

Testing babel-cli...
✗ Low severity vulnerability found on braces@1.8.5
- desc: Regular Expression Denial of Service (ReDoS)
- info: https://snyk.io/vuln/npm:braces:20180219
- from: babel-cli@6.26.0 > chokidar@1.7.0 > anymatch@1.3.2 > micromatch@2.3.11 > braces@1.8.5
Upgrade direct dependency chokidar@1.7.0 to chokidar@2.0.0 (triggers upgrades to anymatch@2.0.0 > micromatch@3.1.4 > braces@2.3.1)
```
Solution: update chokidar@1.7.0 to chokidar@2.0.0.
Can PR if needed.

### PR DESCRIPTION
**Pull request by annyhe**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #8034 
| Patch: Bug Fix?          |
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      |
| Documentation PR         | 
| Any Dependency Changes?  | Yes
| License                  | MIT

Bumped the version of chokidar so snyk doesn't complain

### CODE REVIEW

**Comment by annyhe** [comment]
@nicolo-ribaudo when would the changes be merged, and the npm package updated with the changes?

**Comment by xtuc** [comment]
Since we release Babel 7 is this still needed?

**Comment by xtuc** [comment]
Closing this for now. Please free feel to open a new issue.

**Comment by Anaphase** [comment]
It appears the `chokidar@^1.6.1` dependency is throwing `npm audit` errors again since it (indirectly) relies on braces@1.8.5:

```
└─┬ babel-cli@6.26.0
  └─┬ chokidar@1.7.0
    ├─┬ anymatch@1.3.2
    │ └─┬ micromatch@2.3.11
    │   └── braces@1.8.5
    └─┬ readdirp@2.2.1
      └─┬ micromatch@3.1.10
        └── braces@2.3.2
```

[Here's a link to the NPM advisory](https://www.npmjs.com/advisories/786) on the vulnerability. I can't really upgrade to Babel 7 at the moment, so a backport would be nice.

**Pull request closed without merging**
