### PR TITLE
Switch to pirates for babel-register.

### PR DESCRIPTION
**Pull request by danez**
This is the follow up for #3139 and #3609 

This uses pirates for registering the module extension and adds basic tests

https://github.com/ariporad/pirates/pull/27

### CODE REVIEW

**Comment by ariporad** [comment]
@danez: I'm so sorry I haven't had a chance to submit this PR yet! It really was on my todo list, I swear! Regardless, thanks so much anyway!

I commented on your pirates PR. And I'm more than happy to add you to a contributor to pirates as well. (Hopefully life will calm down soon and I'll actually have some time to work on it properly.)

**Comment by bcoe** [comment]
@danez @ariporad this is awesome; will be cool to try this out with `nyc` after, I think we had some longstanding issues around babel-register + nyc.

**Comment by danez** [comment]
Waiting for https://github.com/ariporad/pirates/pull/28

**Comment by danez** [comment]
Are we okay with merging this now? @hzoo @loganfsmyth

**Pull request merged**
