### PR TITLE
Bumping source-map-support in babel-register

### PR DESCRIPTION
**Pull request by TheSavior**

### CODE REVIEW

**Comment by hzoo** [comment]
Hm how can we know nothing breaks (other than manually testing), since we don't have tests for this yet

**Comment by TheSavior** [comment]
Without tests, I wouldn't feel confident updating this. I don't believe I have the time or am the best person here to write tests for this part of babel, thus closing out this PR.

**Comment by jamestalmage** [comment]
See https://github.com/avajs/ava/issues/974

@hzoo - what sort of test do you want?

**Comment by cody-greene** [comment]
Tests for breaking changes in a dependency should be the responsibility of the dependency itself. Unfortunately, this [doesn't seem to have a changelog](https://github.com/evanw/node-source-map-support/issues/99) so you can't easily browse through each release like you normally would, when upgrading. Scrolling through each commit would be the best best thing, and surprisingly there aren't that many.

**Comment by simonbuchan** [comment]
Doesn't tag back to 0.2.10, but here's the comparison: https://github.com/evanw/node-source-map-support/compare/e1a092fe79a1abf1a6d7b59b7878ced3fa9e793d...v0.4.1

Major bullet points seem to be:
- Added option to explicitly specify environment.
- Handles error reporting changes in node 4 (at least in tests)
- Handles being registered multiple times.
- Adds `source-map-support/register`

Don't seem to be any existing API changes.

**Pull request closed without merging**
