### PR TITLE
Add support for the F# pipeline operator

### PR DESCRIPTION
**Pull request by nicolo-ribaudo**
This PR includes #9450 and #9984, which were not merged to master but to a separate branch. They have already been approved.

:warning::warning::warning: Note to myself (or whoever will merge this PR)
**Do not** use "Squash and merge", to keep both @thiagoarrais and @mAAdhaTTah as the authors.

### CODE REVIEW

**Comment by Sceat** [comment]
@nicolo-ribaudo any ETA ? 🚀

**Comment by mAAdhaTTah** [comment]
@Sceat F# is targeted for babel v7.5.0. I don't know as there is a specific timeline for that, but it'll go in when the team has decided they're ready to cut the next minor release.

**Comment by benjamn** [comment]
Does this need to be blocking v7.5.0? Or is it close to getting reviewed/approved? I would offer to review, but I don't have a very deep understanding of the pipeline operator proposal.

**Comment by mAAdhaTTah** [comment]
@benjamn This is done–reviewed and approved already. It's just waiting for the timing of v7.5.0, which should be sometime within the next week or two.

**Comment by thiagoarrais** [comment]
Related: https://github.com/babel/website/pull/2049

**Pull request merged**
