### PR TITLE
Support shadowing super() and super.* - fixes T6895

### PR DESCRIPTION
**Pull request by loganfsmyth**
This'll conflict with https://github.com/babel/babel/pull/3422 but posting for review since it'll be an easy conflict to fix.

### CODE REVIEW

**Comment by loganfsmyth** [comment]
Ah hmm, not sure how I missed that test. `es2015-object-super` is a pain :(

**Comment by loganfsmyth** [comment]
Closing for now, will think on more approaches to this.

**Comment by kjanoudi** [comment]
@loganfsmyth why did you choose to close this? I'm running into the issue of super with generators and wondering if you had a workaround or  a fix in mind

**Comment by loganfsmyth** [comment]
This unfortunately ended up not being the easy fix I thought it was, this PR was not quite the right fix.

**Comment by samdj** [comment]
I'm running into the same issue as @kjanoudi 
Temp solution is to use the full `es2015` preset till something more clear comes along.

**Comment by kjanoudi** [comment]
@samdj so the full es2015 as opposed to es2015-node5 will solve issues with
super?


On Sun, Apr 17, 2016 at 8:14 PM samdj <notifications@github.com> wrote:

> I'm running into the same issue as @kjanoudi <https://github.com/kjanoudi>
> Temp solution is to use the full es2015 preset till something more clear
> comes along.
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly or view it on GitHub
> <https://github.com/babel/babel/pull/3423#issuecomment-211137137>
>
-- 
Kareem

**Comment by samdj** [comment]
@kjanoudi yes, because the fully transpiled generators have seemingly proper support for `super` in this context. I haven't looked into the minimum subset of plugins to make it work with node5 yet, so if you are tired of your builds taking 3 times longer I'd like to see that. Last I tried I hit a `unknown Expression of type "ArrowFunctionExpression"` error and gave up.

**Comment by alexey2baranov** [comment]
try to use "fast-async" babel plugin. It works perfect with super.*

**Pull request closed without merging**
