### PR TITLE
Enable test `variance-annotations-with-jsx` with babel8

### PR DESCRIPTION
**Pull request by liuxingbaoyu**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | `Fixes #1, Fixes #2` 
| Patch: Bug Fix?          |
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/14626"></a>

### CODE REVIEW

**Review by nicolo-ribaudo — APPROVED** [review]

**Comment by liuxingbaoyu** [comment]
I'm having a weird problem here.
In parser tests, this file has a lot of redefinition errors.
But in the generator test, there is only one `<` error when parsing.

**Comment by nicolo-ribaudo** [comment]
The generator test ignores all the recoverable errors when `errorRecovery` is enabled! I'm merging this, since it only touches tests.

**Comment by liuxingbaoyu** [comment]
```
  "errors": [
    "SyntaxError: Unexpected token `>`. Did you mean `&gt;` or `{'>'}`? (2:10)",
    "SyntaxError: 'public' modifier cannot appear on a type parameter. (98:9)",
    "SyntaxError: Duplicate modifier: 'in'. (99:16)",
    "SyntaxError: 'in' modifier must precede 'out' modifier. (99:16)",
```
Strangely, when I debug, only the first error is included in the parsing result.

**Comment by nicolo-ribaudo** [comment]
Let me try cloning this PR locally :thinking:

**Comment by nicolo-ribaudo** [comment]
Is it in the Babel 7 or Babel 8 test?

**Comment by liuxingbaoyu** [comment]
Thanks!

These bugs such as redefinition errors should exist in both babel 7 and 8.
https://github.com/babel/babel/blob/edd8d01bf26143ad648b61dda183f7986b8c5383/packages/babel-parser/test/fixtures/typescript/types/variance-annotations-with-jsx-babel-7/output.json
But `errorRecovery` is not needed in babel 7's generator tests.
Also only contains `>` symbol errors in babel 8's generator tests.
it's weird...

**Comment by nicolo-ribaudo** [comment]
Uh well, you see different errors because the generator test and the parser tests have different inputs! The parser tests is londer and contain many invalid statements, so we test that we can still parse them.

For the generator we only care about printing them, and we only test valid inputs because invalid inputs are not 100% represented in the AST. For example, `in in T` has the same AST as `in T` so we only test the second one.

**Comment by liuxingbaoyu** [comment]
Oh, thanks! I see, sorry for not noticing.

**Pull request merged**
