### PR TITLE
rename flow-comments plugin

### PR DESCRIPTION
**Pull request by hzoo**
`flow-comments` -> `transform-flow-comments`

### CODE REVIEW

**Comment by thejameskyle** [comment]
How do we want to handle releasing this?

**Comment by hzoo** [comment]
I'm not sure - have we had to rename other plugins before? I don't think we did anything in particular after splitting the `check-es2015-constants` plugin

**Comment by amasad** [comment]
meh. But if you insist merge and release at your convenience :no_pedestrians:

**Comment by hzoo** [comment]
@sebmck wanted to

**Pull request merged**
