### PR TITLE
v6.16.0 changelog [skip ci]

### PR DESCRIPTION
**Pull request by hzoo**

### CODE REVIEW

**Comment by deepsweet** [comment]
I have just noticed that blockquote should be closed right after this:

```
{
  presets: ["@org/babel-preset-name"], // actual package
  presets: ["@org/name"] // shorthand name
}
```

**Comment by danez** [comment]
Love the emojis. 😍

**Comment by hzoo** [comment]
So many ideas - we should add these to contributing for commits!

- :boom: :broken_heart: :sob:   [Breaking Change]
 - :cop: :eyeglasses:   [Spec Compliancy]
 - :rocket: :tada: :gift: :shipit: :new: :bulb: :star:[New Feature]
 - :bug: :wrench: :hammer: :beetle: :bee: :space_invader:    [Bug Fix]
 - :memo: :bookmark_tabs: :book: :blue_book: :books: :ledger:  [Documentation]
 - :house:     [Internal]
 - :nail_care: :gem: :lipstick: :art: [Polish]

- :skull: :fire:  :scissors: Deprecate/Removal
- :package: New Package
- :arrow_up: Update
- :arrow_down: Downgrade
- :racehorse: Perf
- :lock: Security
- :shirt: Linting
- :checkered_flag: :bookmark: Release

**Comment by deepsweet** [comment]
have been using this list for a while:

* :hatching_chick: — initial commit
* :sparkles: — new version
* :recycle: — update dependencies
* :heavy_check_mark: — bug fixed
* :see_no_evil: — stupid bug fixed
* :boom: — breaking changes
* :heavy_plus_sign: — new feature
* :heavy_minus_sign: — remove feature/file/etc.
* :wrench: — refactoring
* :lipstick: — cosmetic refactoring
* :space_invader: — tests
* :no_pedestrians: — lint
* :microscope: — experiment
* :pencil: — readme/docs update

**Comment by danez** [comment]
Why are the tests running when we only change *.md 🤔

**Comment by deepsweet** [comment]
@danez `[skip ci]` appended to your commit message will do the trick.

**Comment by danez** [comment]
We have a Check that should do this automatically, but it doesn't seem to work. The skip ci trick sadly breaks greenkeeper so I always avoid it

**Comment by deepsweet** [comment]
woah, nice `before_install` hook, hadn't noticed it before 👍

**Pull request merged**
