### PR TITLE
Remove flow

### PR DESCRIPTION
**Pull request by samwgoldman**
Same as #3378, but there were a lot of files that had annotations, but no `@flow` or `@noflow` pragma.

### CODE REVIEW

**Comment by samwgoldman** [comment]
Geez, how am I reducing coverage despite being net negative 250+ LoC?

**Comment by hzoo** [comment]
It's cool, don't think we can do anything about that

**Comment by danez** [comment]
Not 100% related but currently there are still files with `@flow` present in (at least) babel-core@6.6.0. Seems these are the inlined babel-register files.

**Comment by hzoo** [comment]
Yeah good find - don't know if I posted it anywhere but it's because my `lib/` (compiled source files) wasn't cleaned when I published before (it still has old/removed files). When I publish again it shouldn't be there.

**Comment by amasad** [comment]
hmm, was there any harm in keeping them? Even if they just acted as hints for humans?

Also, I vaguely remember that we compiled for-of loops to traditional for-loops if the `Array` annotation was there. I might be wrong though.

**Comment by hzoo** [comment]
The "harm" was only that we only partially used it and doing simple stuff like `Object` - @samwgoldman explained in the original issue since you don't have the context. https://github.com/babel/babel/pull/3378#issue-137110310

Also flow users that included babel had errors (although that was partially due to the fact I didn't clean the `lib` folder so files that were deleted in src were still there and published.

**Comment by amasad** [comment]
I meant just keeping the hints not the pragmas

**Comment by samwgoldman** [comment]
These annotations were actually innocuous to Flow users, since these files didn't have the `@flow` comment. Still, the relatively weak types (`Object`, `Function`) and fact that they were totally unchecked made me want to just strip them out.

I am a big supporter of adding types, but I think the effort should be rebooted with a clearer mission to provide safety, even if it means reorganizing the code to make Flow better able to check it.

**Comment by hzoo** [comment]
Oh ok yeah definetely, and we can also just remove the flow-comments plugin if there's still issues with that?

**Comment by amasad** [comment]
Well, I hope someone would take this up -- should be a fun project

**Comment by samwgoldman** [comment]
There are definitely still issues with it, but it would be cool to see them resolved. Maybe the README could be updated to indicate that it's experimental and has known bugs? I mean, I'm not going to work on it, and the maintenance burden doesn't fall on me by default, so your call.

**Comment by amasad** [comment]
I've personally found value in them as comments of sorts. Gives me a shortcut to understand the original author's intent. Traditionally, you'd have to include a JSDoc block above every function to indicate the types and some documentation. This seems like a lightweight way of doing that.

Unless people find them harmful or have caused bugs in the past then I vote for keeping them

**Comment by samwgoldman** [comment]
I don't like the idea of Flow type annotations as unchecked comments. It's just the wrong tool for the job. If you want JSDoc, use JSDoc. If you want Flow type annotations, check them with Flow. Using them as comments will complicate any effort to add checked types in the future.

**Comment by amasad** [comment]
I'm saying I don't want JSDoc :) This gives us 80% of the value with 20% of the effort.

>Using them as comments will complicate any effort to add checked types in the future

Is it really? If removing them is a simple as this commit then the barrier to someone embarking on this project in the future is to scan the repo and remove them (just like you did here). If anything, they'll probably be useful for primitives and for optionality (because most likely these are correct).

**Comment by samwgoldman** [comment]
Why not add the types and also check them? I fully support that.

**Comment by amasad** [comment]
Me too, but I don't see them as exclusive. Unfortunately, none of us are working full time on Babel so this needs to be done piecemeal. And maybe existing annotations can provide some shortcuts at least in understanding.

**Comment by samwgoldman** [comment]
While I don't agree with using Flow annotations as comments, I'm just some guy. Feel free to put up a PR adding them back in. If it gets enough support to merge, I'll hold my tongue.

**Comment by amasad** [comment]
If it makes you feel any better about abusing Flow we can just call them Blow annotations :stuck_out_tongue_winking_eye:

**Comment by jmm** [comment]
This project needs *more* (and better) documentation in the source code (including of function parameters and return types), not less. The last time I made an effort to add some I included JSDoc-style comments documenting parameters and types and @kittens told me to use Flow annotations instead. I assume that's what's happened with everything, so that the only documentation of parameters, types, etc. was in the form of Flow annotations (correct?). Then they were all just nuked. This makes no sense. This stuff needs to be documented in the source. I'm not especially enthusiastic about Flow at this point, but I don't care that much what the format is as long as it'll be sufficiently expressive and human readable / writable.

If the source code docs need to serve some other purpose we need to consider that too. I was under the impression that @thejameskyle wanted to setup Documentationjs to generate API docs (which I presume would require JSDoc-style comments?).

In other words, if it meets all of the needs the docs need to fulfill (first and foremost, documentation for human consumption), I'm open to either of these outcomes:

> I don't like the idea of Flow type annotations as unchecked comments. It's just the wrong tool for the job. If you want JSDoc, use JSDoc.



> I'm saying I don't want JSDoc :)

If [this](https://github.com/babel/babel/pull/3378#issuecomment-190443030) is the case:

> FYI most of the types were wrong so their validity for code documentation is extremely questionable.

First of all, how did that happen? More importantly, that's a reason to fix what's wrong, not nuke everything and leave the project without even a *format* for adding docs.

If it's the case that:

> Many of the existing annotations have low value [and] are quite weak in practice.

Again, that's a reason to improve those, not nuke everything. Also I don't understand how documenting a type as `object` or `function` is weaker and lower value than not documenting it *at all*?

Most importantly, this:

> Me too, but I don't see them as exclusive. Unfortunately, none of us are working full time on Babel so this needs to be done piecemeal. And maybe existing annotations can provide some shortcuts at least in understanding.

If these were removed because of a philosophical objection and not some important, active problem, and these PRs just wiped out a bunch of docs like I'm under the impression they did, I think they should be reverted. How to proceed from there depends what format source docs (at least the ones for type, parameter optionality, etc.) are going to be authored in here. As I said, my understanding was that it was Flow annotations. As @amasad said any changes should likely be piecemeal: if something is going to be removed it should be replaced by something of equal or greater value, whatever the format is.

**Pull request merged**
