### PR TITLE
Improved UMD global exports

### PR DESCRIPTION
**Pull request by lincolndbryant**
When using UMD modules, I'm not a fan of how each individual module name is made into a camelCased identifier based on the module name.  I want my module to be collected into an object, with the module names as keys.  This PR introduces a `globalModuleRoot` boolean option to accomplish this.

An object is created on `window.{moduleRoot}` and each module is added as a key.  `moduleIds` must be true for this feature to work.

Here is an example of how [a project of mine](https://github.com/lincolndbryant/waitsfor) would look with this change merged https://gist.github.com/lincolndbryant/644a01bc060e3d5e58ca  The global object ends up looking like this

screen shot 2015-08-21 at 7 55 20 pm

I'm glad to add more tests, but want to get some feedback first.  Thanks for the great product!

### CODE REVIEW

**Comment by jmm** [comment]
Hello @lincolndbryant. Thanks for your interest in Babel. I see this is your first time here on the issue tracker, welcome!

I haven't looked at the substance of this too closely, but in case you're not aware I wanted to let you know that there's [a feature freeze in place for `v5`](https://github.com/babel/babel/issues/2168#issuecomment-128134192). Also (and maybe you've done this), it's encouraged to discuss ideas like this (e.g. on slack) before putting in the work.

**Comment by sebmck** [comment]
I'm not convinced that this is a common enough use-case to be covered by core. Is there something here that can't be covered through the use of a userland plugin?

**Comment by muzuiget** [comment]
Oh, I am looking for this feature. I thing this is a must-have feature. because current exported code will polluting the global native object.

For examle

Babel option

```javascript
var babelOption = {
    modules: 'umd',
};
```

User create a filename `screen.js`

```javascript
// import a third-party library name "navigator"
import {foo} from 'navigator';
console.log(foo);
```

the code babeljs export is

```javascript
(function (global, factory) {
  if (typeof define === 'function' && define.amd) {
    define(['exports', 'navigator'], factory);
  } else if (typeof exports !== 'undefined') {
    factory(exports, require('navigator'));
  } else {
    var mod = {
      exports: {}
    };
    // Polluting 1: the native object window.navigator, not the third-party library ones;
    factory(mod.exports, global.navigator);
    // Polluting 2:  the native object window.screen is replace by user one;
    global.screen = mod.exports;
  }
})(this, function (exports, _navigator) {
  'use strict';

  console.log(_navigator.userAgent);
});
//# sourceMappingURL=../scripts/screen.js.map
```

So, I think `moduleRoot` is a good solulcation;

**Comment by sebmck** [comment]
> I think this is a must-have feature. because current exported code will polluting the global native object.

Then you obviously don't want UMD. The entire point of UMD is that it falls back to globals if there's no module system in use.

**Comment by muzuiget** [comment]
@sebmck Sorry, I don't understand this. my point is this "global object polluting". For example, the `screen.js` is a reusable code(e.g a Math library), write with standard ES6 module, the code itself should not care about how to run (AMD/CommonJS/UMD), but the filename and the `import` name will polluting the browser `window` object property.

**Comment by muzuiget** [comment]
Find a similar use case https://github.com/babel/babel/issues/2288

**Comment by lincolndbryant** [comment]
@sebmck choosing UMD is about making sure everyone can use your project, so that others can use AMD or choose not to.  Yes it should fall back to globals but the current manner is unusable if your project has more than 1 module, @muzuiget gets what i mean.

Right now, each module in your project is exported as a separate global, which are `camelCased` and look very unlike the module names for amd/commonjs.  Top-level generic names like `utils` would end up being defined as `window.utils`, which is not an acceptable way to release a module.  My change to attach modules to an object named by the `moduleRoot` config fixes this pollution, users get one global that contains all modules.  This is achieving #2288 and utilizing the existing `moduleRoot` config to allow you to pick the global variable name (obviously not all babel users can use `umdRoot

The second change I made to use string indexes of this object in the assignment (eg `global['moduleName']` instead of `global.moduleName`) gives us way more flexibility to use module names with characters not allowed in identifies like `/` and '.'  If you could accept just this part, we are way better off.  My project that used to be
```
window.fooOne = {module}
window.fooTwo = {module}
window.fooThree = {module}.
```
could now be
```
window.foo = {
  "one": {module}
  "two": {module}
  "three": {module}
}
```
importing modules from the project not looks much more similar
```
var one = require("foo/one") // commonjs
var one = window.foo["one"] // globals
```

**Comment by jmeas** [comment]
Interesting idea, @lincolndbryant ! I wonder if this is too specific an algorithm. We can get the same functionality of this in a more general, and more familiar way, by implementing https://github.com/babel/babel/issues/1681.

There's no reason for Babel to "construct" an Object for a developer, I think. A developer can do this same thing with good old JavaScript. All that Babel needs to do is add `n -> 1` file compilation.

Some bonuses to doing it this way instead are:

1. it's conceptually simpler (Babel just worries about the modules, and not the Objects within the modules)
2. more similar to how RequireJS, Browserify, Webpack, Esperanto, and Rollup works, so pretty much every developer will know how to use it
3. smaller file size!

**Comment by sebmck** [comment]
The more I think about the more entrenched I am with my original view of:

> I'm not convinced that this is a common enough use-case to be covered by core. Is there something here that can't be covered through the use of a userland plugin?

With 6.0.0 nothing is enabled by default so feel free to fork the UMD module transformer and implement this yourself in userland.

Thanks! :blush:

**Comment by jmeas** [comment]
> With 6.0.0 nothing is enabled by default so feel free to fork the UMD module transformer and implement this yourself in userland.

This makes sense to me – :+1:

**Pull request closed without merging**
