### PR TITLE
Rename `index.mjs` to `_index.mjs` in `@babel/runtime`

### LINKED ISSUE #12853: Error with latest @babel/helper-create-class-features-plugin (v7.13.0)
Received message:   "_typeof is not a function"
      at _possibleConstructorReturn (node_modules/@babel/runtime/helpers/possibleConstructorReturn/index.js:6:16)

### LINKED ISSUE #12854: 7.13 "_interopRequireDefault is not a function"
In addition to https://github.com/babel/babel/issues/12851

If you set `resolutions` for `@babel/core` to `~7.12.0` you then get this error:

```
   8 | exports.navigateTo = exports.replace = exports.push = exports.navigate = exports.default = void 0;
   9 |
> 10 | var _objectWithoutPropertiesLoose2 = _interopRequireDefault(require("@babel/runtime/helpers/objectWithoutPropertiesLoose"));
     | ^
  11 |
  12 | var _assertThisInitialized2 = _interopRequireDefault(require("@babel/runtime/helpers/assertThisInitialized"));
  13 |


  WebpackError: TypeError: _interopRequireDefault is not a function

  - index.js:10
    node_modules/gatsby-link/index.js:10:1

  - utils.js:136
    node_modules/@reach/router/lib/utils.js:136:1
```

`gatsby-link` requires `babel/runtime/helpers/interopRequireDefault` which seems to no longer exist in `@babel/runtime@7.13`

### PR DESCRIPTION
**Pull request by nicolo-ribaudo**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | fix #12854, fix #12853
| Patch: Bug Fix?          |
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

~This should fix #12854, but for some reason webpack still loads the `.mjs` version when using `require()` :thinking:~
~Maybe it's a caching problem, but what I see locally is that even uses the `.mjs` version even if I remove every mention of `.mjs` in `@babel/runtime`'s `package.json`~

The problem is that Webpack 4 _always_ loads `index.mjs` if there are both `index.js` and `index.mjs`, and there is no way (unless you update the webpack config) to tell it to load `index.js`.

### CODE REVIEW

**Comment by nicolo-ribaudo** [comment]
I can confirm that this works in my local gatsby project.

**Review by JLHwung — APPROVED** [review]

**Review by hzoo — APPROVED** [review]

**Comment by KyleAMathews** [comment]
Thanks 🙏

**Comment by nicolo-ribaudo** [comment]
@KyleAMathews We are releasing (https://github.com/babel/babel/actions/runs/591028231)

**Comment by KyleAMathews** [comment]
@nicolo-ribaudo thanks so much! Confirmed Gatsby is back in business with 7.13.1 🎉

**Comment by nicolo-ribaudo** [comment]
I'm going to sleep now, but tomorrow I'll DM you to see how we can add Gatsby as an e2e test 😬

**Comment by KyleAMathews** [comment]
Excellent!

**Comment by DSchau** [comment]
@nicolo-ribaudo thank you truly for the quick turnaround on this.

We at Gatsby appreciate this, and so too do our users. We'd love to chat about e2e test, so let us know how we can help ensure we can automate and track this case for the future 👍

**Comment by AndriusBil** [comment]
Hey! I think this produces a bug.
Check out this example repo: https://github.com/AndriusBil/babel-require-example
If you lock @babel/runtime to 7.13.1 it works like a charm not like 7.13.2

**Pull request merged**
