### PR TITLE
upgrade: ESLint v7

### PR DESCRIPTION
**Pull request by kaicataldo**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | 
| Patch: Bug Fix?          | :+1:
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

This updates all of our packages to have a peer dependency on ESLint v7 (the current release line), as well as to use v7 to lint the repo. The biggest difference is some stricter validation in the RuleTester (which is why I needed to update tests).

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/11778"></a>

### CODE REVIEW

**Comment by JLHwung** [comment]
Can we skip testing babel-eslint on node < 10?

**Comment by kaicataldo** [comment]
Opened #11857 to replace this PR.

**Comment by JLHwung** [comment]
@kaicataldo You could force-push `update-eslint-7` to `update-eslint` so this PR stays open. It helps PR `#` autocomplete a bit.

**Comment by kaicataldo** [comment]
I felt like it would be best to just start fresh, but I can def so that if you prefer.

**Pull request closed without merging**
