### PR TITLE
chore: Attempt to fix test262 failed

### PR DESCRIPTION
**Pull request by liuxingbaoyu**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | `Fixes #1, Fixes #2` 
| Patch: Bug Fix?          |
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/15438"></a>

### CODE REVIEW

**Comment by nicolo-ribaudo** [comment]
:crossed_fingers:

**Comment by liuxingbaoyu** [comment]
The problem seems to be no longer reproducible. :)

**Comment by nicolo-ribaudo** [comment]
Ohh thanks :)

**Review by nicolo-ribaudo — APPROVED** [review]

**Comment by liuxingbaoyu** [comment]
Ah, I mean even without this PR issue doesn't appear anymore.🤦‍♂️

**Comment by nicolo-ribaudo** [comment]
For context: the root cause of the problem was that, before cloning, `actions/checkout` makes an API call to get the name of the default branch. Hard-coding its name avoids that API call, that was failing due to rate limiting.

**Comment by nicolo-ribaudo** [comment]
> Ah, I mean even without this PR issue doesn't appear anymore.man_facepalming

Oh, I didn't notice it :sweat_smile:

**Comment by nicolo-ribaudo** [comment]
Well, if it happens again I'll restart the CI jobs on this PR.

**Comment by nicolo-ribaudo** [comment]
This is still avoiding an unnecessary API call (`Determining the default branch`), it might be worth to merge it anyway.

**Comment by nicolo-ribaudo** [comment]
Rate limited again: https://github.com/babel/babel/actions/runs/4212001194/jobs/7310741029

**Review by JLHwung — APPROVED** [review]

**Pull request merged**
