### PR TITLE
Downgrade semver for compatibility with Node 6

### LINKED ISSUE #10990: Latest version breaks on node<10
## Bug Report

**Current Behavior**
semver is included as "^7.1.1" in following:
https://github.com/babel/babel/pull/10899/files#diff-ef7266ff2423fa596fa449062b0b725fR23
https://github.com/babel/babel/pull/10899/files#diff-284fef7c611cebc1a424f6a765782a30R28

Newly created packages `babel-compat-data` and `babel-helper-compilation-targets` seems to be using v7.1.1 of semver which breaks on node<10

Ref: https://github.com/npm/node-semver/commit/d61f828e64260a0a097f26210f5500#r36469180

**Expected behavior/code**
Just like the rest of the packages of babel - semver should be less than v7.1.1 possibly in 5 or 6 range

- Babel version(s): [e.g. v6.0.0, v7.0.0-beta.34]
- Node/npm version: Node 8.15.0
- OS: OSX 10.13.6
- Monorepo: Yes (Lerna workspace)
- How you are using Babel: [e.g. `cli`, `register`, `loader`]

**Possible Solution**
Please don't depend on v7.1.1 of semver package

**Additional context/Screenshots**
```error semver@7.1.1: The engine "node" is incompatible with this module. Expected version ">=10". Got "8.15.0" error Found incompatible module.```

Please let me know if I'm looking it in an incorrect way

### PR DESCRIPTION
**Pull request by nicolo-ribaudo**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #10990
| Patch: Bug Fix?          | Yes
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

### CODE REVIEW

**Comment by ljharb** [comment]
@nicolo-ribaudo semver v6 also works down to node 0.8; i think that's the lowest you really need to go (and compared to v5, has better handling of prereleases)

**Comment by zloirock** [comment]
Pinned `semver@7.0` works fine even with Node 6 and will be deduplicated with `core-js-compat`.

**Comment by nicolo-ribaudo** [comment]
I used v5 because we are already using it in other Babel packages.
We can surely upgrade to a higher version now (or wait for Babel 8 soon and use ^7.0.0`), but I wanted to release a quick patch with a lower risk of breaking other things.

**Comment by eilon-shai** [comment]
when this version will be published?

**Comment by nicolo-ribaudo** [comment]
It has already been published a few minutes after this PR has been merged. Only the updated packages have been released.

**Comment by eilon-shai** [comment]
our build is failing (node 6), and I think it relates to this fix, getting
npm ERR! typeerror Error: Missing required argument #1
it fail on babel installation, for example:
npm i @babel/code-frame@7.8.0
but when trying @babel/code-frame@7.8.1 it says that this version does not exists

**Comment by ljharb** [comment]
That's an npm bug on windows, i believe (possibly a new, registry-caused one)

**Comment by eilon-shai** [comment]
this is happening both on jenkins (linux) and reproduced locally (mac os)
node 6.1.0 npm 3.8.9 
npm  i @babel/highlight@7.8.0 and others fail

**Comment by nicolo-ribaudo** [comment]
They have been published: https://www.npmjs.com/package/@babel/highlight
Please report the bug to npm.

**Comment by eilon-shai** [comment]
ok, thanks

**Pull request merged**
