### PR TITLE
removed unused alias in babel-runtime

### PR DESCRIPTION
**Pull request by JulianJason**
| Q                        | A 
| ------------------------ | ---
| Patch: Bug Fix?          | No
| Major: Breaking Change?  | No 
| Minor: New Feature?      | No
| Deprecations?            | No
| Spec Compliancy?         | No
| Tests Added/Pass?        | Pass
| Fixed Tickets            | [#5472](https://github.com/babel/babel/issues/5472) 
| License                  | MIT
| Doc PR                   | 
| Dependency Changes       | 

Removed unused alias from babel runtime. Used to be built for compability but it is safe to remove.

### CODE REVIEW

**Comment by JulianJason** [comment]
Hey this is my first PR, please be harsh and criticize me so I can learn. Thank you.

**Comment by hzoo** [comment]
Awesome 👍

**Comment by hzoo** [comment]
Only thing is that you should add `Fixes #number` so that the issue closes when merged (assuming it does actually fix it and you don't want to just reference it)

**Comment by JulianJason** [comment]
Thank you so much @hzoo

**Pull request merged**
