### PR TITLE
Doc changes for https://github.com/babel/babel/issues/7063

### LINKED ISSUE #7063: Test fixtures: rename actual/expected to input/output
Ref https://github.com/babel/babel/pull/7059#issuecomment-352766948

`actual.js` and `expected.js` isn't as intuitive as `input.js` and `output.js`. If someone wants to change this, that would be great.

Going to have to change the references (more than just what I linked) in at least these 2 packages:

https://github.com/babel/babel/blob/68476b6dddfdfc0941142cc45687c5b33c0cfe37/packages/babel-helper-fixtures/src/index.js#L87-L88

https://github.com/babel/babel/blob/68476b6dddfdfc0941142cc45687c5b33c0cfe37/packages/babel-helper-transform-fixture-test-runner/src/index.js#L134

Then all the tests need to be renamed. So this is a lot of work but relatively simple.

---

We might want to consider making https://github.com/babel-utils/babel-plugin-tester the official package or something, or merging that with our current setup eventually. Then we can move toward recommendation + standardization of quality of plugins via tests + use it as a way to upgrade plugins better. I should probably make a separate issue for this @kentcdodds

### PR DESCRIPTION
**Pull request by rajzshkr**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #7063
| Patch: Bug Fix?          |
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | 
| Documentation PR         | Yes [skip ci]
| Any Dependency Changes?  |
| License                  | MIT

### CODE REVIEW

**Comment by rajzshkr** [comment]
@xtuc Its in my check list, somehow I missed.

**Comment by xtuc** [comment]
> In an actual/expected test

You didn't change it but it's ok to me, it wouldn't make sense otherwise.

**Comment by existentialism** [comment]
Some other places:
https://github.com/babel/babel/blob/master/packages/babel-helper-plugin-test-runner/README.md
https://github.com/babel/babel/blob/master/packages/babel-helper-fixtures/README.md


(sidenote, your commit message needs [skip ci], not the pr title!)

**Comment by rajzshkr** [comment]
@existentialism I didn't make changes in https://github.com/babel/babel/blob/master/packages/babel-helper-fixtures/src/index.js#L29. 

Upated the other one.

**Pull request merged**
