### PR TITLE
Remove "class-constructor-call" syntax and transform plugins

### LINKED ISSUE #5112: [7.0] Removal of "class-constructor-call" from the repo
Remove it from the repo (meaning delete the folder/files)! super fun 😄 

Proposal dropped in [2016-01-28 tc39 meeting](https://github.com/rwaldron/tc39-notes/blob/master/es7/2016-01/2016-01-28.md#progress-review-callable-class-constructors-allen) a while back so we should get rid of it.

I guess that removing the pkgs from the repo technically doesn't even have to be 7.0, only removing it from the stage-x preset (which is already up for removal too).

In detail:
- [ ] [babel-plugin-transform-class-constructor-call](https://github.com/babel/babel/tree/master/packages/babel-plugin-transform-class-constructor-call). (remove this folder)
- [ ] [babel-plugin-syntax-class-constructor-call](https://github.com/babel/babel/tree/master/packages/babel-plugin-syntax-class-constructor-call). (remove this folder)
- [ ] remove this plugin from the [stage-1 preset](https://github.com/babel/babel/tree/master/packages/babel-preset-stage-1) (the package.json + main file)
- [ ] other references to constructor call (main readme? I would just grep the codebase)
- [ ] Reword the website pages to say its been removed in babel 7
  - [ ] https://github.com/babel/babel.github.io/blob/master/docs/plugins/syntax-class-constructor-call.md
  - [ ] https://github.com/babel/babel.github.io/blob/master/docs/plugins/transform-class-constructor-call.md
  - [ ] https://github.com/babel/babel.github.io/blob/master/docs/plugins/preset-stage-1.md

---

- [ ] use `npm deprecate` on the 2 transform/syntax pkgs (from @hzoo to do)

### PR DESCRIPTION
**Pull request by ColinRTaylor**
| Q                        | A 
| ------------------------ | ---
| Patch: Bug Fix?          | no
| Major: Breaking Change?  | no 
| Minor: New Feature?      | no
| Deprecations?            | yes
| Spec Compliancy?         | yes
| Tests Added/Pass?        | yes
| Fixed Tickets            | #5112
| License                  | MIT
| Doc PR                   | 
| Dependency Changes       | no

As described in #5112 this removes the class-constructor-call syntax and transform plugins and all references to them. It has been dropped by TC39.
I:
 

1.  Removed `packages/babel-plugin-transform-class-constructor-call`
2. Removed  `packages/babel-plugin-syntax-class-constructor-call`
3. Remove the plugin from the stage-1 preset in both the package.json + main file

### CODE REVIEW

**Comment by hzoo** [comment]
This is awesome! (can you also check/grep for "constructor call" in the codebase) there shouldn't be any maybe in the readme

**Comment by ColinRTaylor** [comment]
@hzoo the only other place that I am finding 'constructor call' is in the CHANGELOG.md

**Comment by hzoo** [comment]
Cool must of removed it already then - will wait for another approval but thanks.

Hopefully we can get this all out soon

**Comment by existentialism** [comment]
I think we can also safely remove:
https://github.com/babel/babel/blob/7bb430aeea28edafd7c923b14836101aed2accdf/packages/babel-generator/src/generators/classes.js#L84

**Comment by hzoo** [comment]
cool haha yeah grep for the non space version to due using camelCase in js. `constructor-call`, `constructorCall`, `constructor call`

**Comment by ColinRTaylor** [comment]
Thanks. I found one using camelCase it was in the file that @existentialism mentioned. It has been removed.

**Pull request merged**
