### PR TITLE
advance es7.trailingFunctionCommas to stage 2

### PR DESCRIPTION
**Pull request by michaelficarra**
Waiting on https://github.com/tc39/ecma262/pull/70.

### CODE REVIEW

**Comment by hzoo** [comment]
https://github.com/tc39/ecma262/pull/70 is merged

**Comment by sebmck** [comment]
@michaelficarra Is this the last of the latest stage updates? I can push out a new release.

**Comment by michaelficarra** [comment]
Nope. Wait until tomorrow after the meeting is over.

**Comment by stefanpenner** [comment]
@sebmck some remaining discussions/proposals still happening today.

**Comment by sebmck** [comment]
Thanks! Thought it finished yesterday.

**Comment by stefanpenner** [comment]
You can sorta follow along on the agenda: https://github.com/tc39/agendas/blob/master/2015/09.md Agenda items with `✓` are completed, and without are still pending.

**Comment by kangax** [comment]
I wish TC39 would keep an authoritative source of metadata related to stages so that both Babel and us (es-compat-table) and whoever else could just pull from there... 

@bterlson @domenic @wycats any plans for something like that?

**Comment by domenic** [comment]
It already exists. See the OP of this thread.

**Comment by kangax** [comment]
So README in ecma262 is the source of truth?

**Comment by michaelficarra** [comment]
@kangax It is.

**Comment by kangax** [comment]
I see. Any chance to give proposals some kind of identifiers? Something that's not subject to change (unlike titles or urls)?

**Comment by michaelficarra** [comment]
It could probably be converted to a more easily programmatically consumed format, as well. @kangax You should send a PR with your ideal format. I would suggest CSV, since GitHub [has special support for them](https://github.com/blog/1601-see-your-csvs).

**Comment by bterlson** [comment]
I still want this info in the readme as it's the biggest reason people look at this repo. Any way to embed a CSV? Or do we want it two places?

**Comment by kangax** [comment]
If we just add unique identifier to an additional cell for each entry in
README, it should be easy to parse (it's basically |-separated values)

**Comment by domenic** [comment]
I think it should be the responsibility of people who need unique ids to maintain that list, not the responsibility of TC39.

**Comment by bterlson** [comment]
There kind of is a unique ID already for stage 1 and above (or should be, going forward) - the tc39 repository name.

**Comment by michaelficarra** [comment]
The GitHub CSV UI *is* really nice though. @bterlson Would you be okay just linking to it from the readme?

**Comment by bterlson** [comment]
Sorry for the delay. @michaelficarra Yeah I'd be fine with that personally. Someone can feel free to send me a PR for that :)

**Comment by michaelficarra** [comment]
@bterlson Done: https://github.com/tc39/ecma262/pull/235

**Pull request merged**
