### PR TITLE
Switch to nyc, babel-plugin-istanbul & codecov-node for code coverage

### PR DESCRIPTION
**Pull request by motiz88**
| Q | A |
| --- | --- |
| Bug fix? | no |
| Breaking change? | no |
| New feature? | no |
| Deprecations? | no |
| Spec compliancy? | no |
| Tests added/pass? | no (well they pass) |
| License | MIT |

The key benefit of this setup, apart from using the newer tools (same as Babylon has used for a while) is that coverage is now referenced to [`src/`](https://codecov.io/gh/motiz88/babel/tree/ff3433b74f26206cfc8fbe0fb16d9267f84d0d69/packages) rather than [`lib/`](https://codecov.io/gh/babel/babel/tree/6271530d4a3c9139688ef3fc8168a187b3606b76/packages), so the correct source shows up on Codecov, hopefully getting us to #1851 faster 😉 

Thanks @bcoe for releasing istanbuljs/istanbul-lib-instrument#26 so quickly!

---

[As I've mentioned on Slack](https://babeljs.slack.com/archives/development/p1476686636000868) - this currently causes a double build on CI, once during `make bootstrap` and once during `make test-cov`. This is not ideal and I'm hoping someone can weigh in on whether we need to build in `make bootstrap` at all.

### CODE REVIEW

**Comment by danez** [comment]
The only big problem that we have then and we currently also have in babylon is that not all files show up in the reports. Only the files that are required at least once.
https://github.com/istanbuljs/babel-plugin-istanbul/issues/4
So it could be that we reach 100% but still have uncovered files.

**Comment by motiz88** [comment]
@danez Oh. I think I knew about that problem and then forgot about it. Gonna have a look.

**Comment by motiz88** [comment]
Just a quick update - I'm doing some work on `nyc` and `istanbul-lib-instrument` (also been back full-circle to Babel with #4746 :smile:) to fix the problem @danez mentioned above. My test repo [motiz88/nyc-all-demo](https://github.com/motiz88/nyc-all-demo) ties everything together and has links to the gory details.

**Comment by bcoe** [comment]
@motiz88 @danez @hzoo, we've landed changes to `istanbul-lib-instrument` and `nyc`, such that `--all` should now work for `babel-plugin-istanbul` 👍 

This is currently published to the `next` branch on npm, and I would love the extra help testing:

`npm cache clear; npm i nyc@next babel-plugin-istanbul@latest`

My configuration and test-script look like this, in the testing project I've been using:

`cross-env NODE_ENV=test nyc --all --show-process-tree --silent mocha test/*.js`

```json
  {"babel": {
    "presets": [
      "es2015"
    ],
    "env": {
      "test": {
        "plugins": [
          "istanbul"
        ]
      }
    }
  },
  "nyc": {
    "include": [
      "src/**/*.js"
    ],
    "exclude": [
      "node_modules"
    ],
    "require": [
      "babel-register"
    ],
    "sourceMap": false,
    "instrument": false
  }}
```

Thanks for everyone's help and feedback regarding this feature; it will be awesome to babel using `nyc`, which I think will in turn help make `nyc` significantly better.

**Comment by bcoe** [comment]
@motiz88 @danez everything necessary to land this with `--all` support should now be landed; 

You might find yourself wanting to fiddle with cache settings for a large codebase like this though.

**Comment by hzoo** [comment]
Merged this via https://github.com/babel/babel/pull/4885

**Pull request closed without merging**
