### PR TITLE
Avoid adding unnecessary closure for block scoping

### PR DESCRIPTION
**Pull request by spicyj**
When you write

```js
for (const x of l) {
  setTimeout(() => x);
}
```

we need to add a closure because the variable is meant to be block-scoped and recreated each time the block runs. We do this.

However, we also add the closure when a block is present but no loop is:

```js
function foo() {
  {
    const x;
    setTimeout(() => x);
  }
}
```

This isn't necessary, because if no loop is present then each piece of code runs at most once. I changed the transform to only add a closure if a variable is referenced from within a loop.

(Builds on #5236.)

### CODE REVIEW

**Comment by spicyj** [comment]
cc @gaearon @hzoo @extentialism – Any thoughts on this?

**Comment by loganfsmyth** [comment]
This will land in 6, I'm investigating one last issue before we publish the next 6.x minor, so next few days probably.

7.x likely won't be for a few more weeks as a minimum, we've still got things we want to address for that.

**Comment by hzoo** [comment]
Thanks again @spicyj 👌

**Comment by spicyj** [comment]
Thank you all!!

**Pull request merged**
