### PR TITLE
Fix bug with paren printing in compact + line retained mode

### PR DESCRIPTION
**Pull request by amasad**

### CODE REVIEW

**Comment by amasad** [comment]
Any feedback?

**Comment by sebmck** [comment]
Somehow missed this. Looks good :+1: Thanks!

**Comment by amasad** [comment]
you're allowed to miss something every once in a while :stuck_out_tongue_winking_eye: 
lmk when you publish plz

**Comment by sebmck** [comment]
ETA after I fix #1545 and #1544 so maybe <1 hour.

**Comment by sebmck** [comment]
Released as of 5.4.3.

**Pull request merged**
