### PR TITLE
[babel 8] Require Node.js `^16.20.0 || ^18.16.0 || >=20.0.0`

### PR DESCRIPTION
**Pull request by nicolo-ribaudo**
| Q                        | A 
| ------------------------ | ---
| License                  | MIT

Node.js 14 EOL is on April 30th.

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/15585"></a>

### CODE REVIEW

**Comment by liuxingbaoyu** [comment]
Does this mean we don't support node17 and node19? I personally tend to favor them.

**Comment by nicolo-ribaudo** [comment]
Node.js 17 is not maintained anymore. We could still support Node.js 19, but it will stop being maintained on June 1st.

It's _likely_ that supporting Node.js 16 means that Babel will work on those, but since they are not maintained anymore users should migrate to a different Node.js version.

**Comment by liuxingbaoyu** [comment]
I'm concerned that some downstream projects need their support.
And some users use babel to use the new syntax in lower versions, so maybe babel will have a lot of usage in nodejs versions that are no longer maintained.

FYI: https://github.com/prettier/prettier/issues/13142#issuecomment-1483862766
I'd rather we're not actively fixing bugs specific to no longer maintained nodejs versions than we don't explicitly require newer versions, since theoretically most of our packages are not affected by nodejs versions, and only a few we want to use new features.

**Comment by nicolo-ribaudo** [comment]
I would be ok with having `>=16.20` in `engines.node`, but still only document ^16.20 || ^18.16.0 || >=20.0.0` as supported (and only test those).

**Comment by JLHwung** [comment]
I like `^16.20 || ^18.16.0 || >=20.0.0`. The LTS releases have feature access so `^16.20` could contain features that Node.js 17 does not have. For example, Node.js 16.20 supports externally shared js builtins while 17.7.1 does not support it. Therefore 
`^16.20 || ^18.16.0 || >=20.0.0` does not equal to `>=16.20` because of this LTS release strategy.

For downstream projects using unsupported Node versions, they can stay with Babel 7 anyway.

**Review by liuxingbaoyu — APPROVED** [review]
Actually I think >=14 is fine. Because most of our packages are not version affected, and we don't need new features.
At the same time, babel is often used to use new features on lower versions of nodejs. Although those users can stay in babel7, I am worried that this will bring more negative effects even to us, especially when babel8 becomes esm .

I won't block this PR merge though.

**Comment by nicolo-ribaudo** [comment]
Actually, there are features between v14.21 and v16.20 that would be nice to use:
- `String.prototype.replaceAll`
- `??=` & co
- `Object.hasOwn`
- Error cause (we currently just join stack traces, but we should use this)

**Comment by zloirock** [comment]
EOL of NodeJS 16 in less than a half year. Will Babel 8 be published before that?

**Comment by nicolo-ribaudo** [comment]
The standard for all those projects is to support the Node.js version that were still maintained when the new major version has been released:
- ESLint 8 was released in October 2021, and Node.js 12 EOL was April 2022
- Prettier 3 bumped the required Node.js version to 16 because Node.js 14 is EOL and Node.js 16 has all the nice utilities I mentioned above (https://github.com/prettier/prettier/issues/13142#issuecomment-1483829516)
- typescript-eslint just matches ESLint
- Jest 29 was released in August 2022, and Node.js 14 EOL is in April 2023 (while Node.js 12 EOL was before, hence it's not supported)

Tbh, if users are stuck on a Node.js version that doesn't receive security fixes anymore they have much bigger problems than not being able to update Babel 😅

**Comment by liuxingbaoyu** [comment]
You're right!
But I still think it's good to make it easier for more users to upgrade to babel8 when we have less burden. 😕

**Comment by nicolo-ribaudo** [comment]
I'll investigate in our code how much we would actually use those new utility functions.

**Comment by liuxingbaoyu** [comment]
Thanks!

In addition, prettier seems to have not yet reached an agreement on the point of view.
https://github.com/prettier/prettier/issues/13142#issuecomment-1483882351
https://github.com/prettier/prettier/issues/13142#issuecomment-1517844522

**Comment by nicolo-ribaudo** [comment]
TS will keep supporting Node.js 14 for a while: https://github.com/wooorm/import-meta-resolve/pull/15#issuecomment-1520726323

**Comment by fisker** [comment]
Prettier v3 will support Node.js 14. Development version requires Node.js 16.

**Comment by nicolo-ribaudo** [comment]
I have been thinking about this for a while, and I lean towards still supporting Node.js 14. The only significant advantage we would get by dropping it is that `.replaceAll` is incredibly nice when working with paths:
```js
output = output.replace(new RegExp(escapeRegExp(path), "g"), "<CWD>");
// vs
output = output.replaceAll(path, "<CWD>");
```

Except for that, all the other changes from Node.js 14 to 16 are insignificant for us (yes, writing `Object.hasOwn` is shorted than `Object.hasOwnProperty.call`, but it doesn't justify the cost).

If the stable release of Babel 8 will be in more than, lets say, 6 months, we could revisit this decision.

**Comment by zloirock** [comment]
@nicolo-ribaudo I think that in this case the required Node version is almost not related to supported ES features - the main reason is dependencies.

After Node 16 EOL, many dependencies that Babel uses will bump the minimal required Node version to 18 - and Babel will not be able to update them.

How many years Babel 8 will be supported? 3? 4? 5? For this time, it will affect the most of dependencies.

**Comment by JLHwung** [comment]
I agree with @zloirock. Unless we match the Node release cycle, releasing major every 6 months, it won't be long when one of our dependencies are pinned because of Node.js 14, but we need a patch for a CVE, which is only supported in higher versions that supports maintained Node.js versions only. We have seen such situation for `chalk@2` in Babel 7 era.

A solution will be to "drop dead Node.js versions" after it is dead by X years in minor version bumps. We can start specifying `~` dependencies for packages in monorepo, release all packages every minor bump (to update their `~` version spec), so we can come up with a table for users using a dead Node.js versions, e.g.

(The examples here are imaginative)

| Node.js | Install |
| --- | --- |
| 14 | npm i @babel/core@~8.2 |
| 16 | npm i @babel/core@~8.8 |
| 18 | npm i @babel/core |

Other than dropping dead node.js versions, we will not ship any breaking changes in minor updates.

**Comment by nicolo-ribaudo** [comment]
Another data point: Node.js 16 EOL is on [2023-09-11](https://nodejs.org/en/blog/announcements/nodejs16-eol/), just in a few months.

**Comment by ehoogeveen-medweb** [comment]
FWIW, Node.js 16 is the last version to run on CentOS 7 because Node.js 18 requires a newer version of glibc (which is tied to the OS): Compare https://github.com/nodejs/node/blob/v16.x/BUILDING.md#platform-list and https://github.com/nodejs/node/blob/v18.x/BUILDING.md#platform-list (I'm not sure they document it anywhere else).

**Comment by nicolo-ribaudo** [comment]
It looks like both Vite and Rollup are waiting until September for their next major, dropping support for Node.js 14 and 16: https://github.com/vitejs/vite/discussions/12466#discussioncomment-5349558

Webpack is also planning to drop Node.js 14 in its next major: https://twitter.com/TheLarkInn/status/1664255352987340805

**Comment by nicolo-ribaudo** [comment]
I'm going to update this PR with ^16.20.0, but until the stable Babel 8 release we can decide to make it ^14.... or ^18....

**Comment by nicolo-ribaudo** [comment]
Also, today is Node.js 19 EOL.

**Pull request merged**
