### PR TITLE
Fix turning division operator into line comment in compact mode

### LINKED ISSUE #7071: Babel generator 6 turns division + comment into just comment in compact mode
Bug: When a division in the input is followed by a line or block comment, no space is output between them in comact mode, thus turning the whole thing into a line comment.

### Input Code

```js
var a = 1 / /*c*/ v;
var a = 1 / //bar
  v;
```

### Babel/Babylon Configuration (.babelrc, package.json, cli command)
Initially happened when running `nyc` but reproduced with a test case in the babel-generator package

### Expected Behavior

Space between the division and the comment in the output, even in compact mode.

### Current Behavior

No space:

```js
var a=1//*c*/v;
var a=1///bar
v;
```

### Possible Solution

Ensure that when comments are output and the preceding character is a slash, a space is always emitted as well

### Context

Was trying to instrument our code but the code is invalid after the transformation

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  6.26.0
| Babylon          | n/a
| node             | 8.9.3
| npm              | 5.6.0
| Operating System | Ubuntu 17.04

### PR DESCRIPTION
**Pull request by karottenreibe**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #7071 
| Patch: Bug Fix?          | yes
| Major: Breaking Change?  | no
| Minor: New Feature?      | no
| Tests Added + Pass?      | Yes
| Documentation PR         | no
| Any Dependency Changes?  | no
| License                  | MIT

After emitting a division operator, the code generator MUST output a space if a comment is output right afterwards, otherwise, the division slash and the comment's starting slash will be merged to produce a line comment. See #7071

### CODE REVIEW

**Comment by karottenreibe** [comment]
The circlci build is failing with

```
/home/ubuntu/babel/node_modules/husky/bin/install.js:4
const path = require('path')
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:945:3
```

in the `npm install` stage. I'm not sure how my changes could have caused this but I'm happy to try and fix it, if someone can give me a pointer in the right direction! :-)

**Comment by karottenreibe** [comment]
No they don't. Wrote a test for that and will attempt a fix. Thanks for thinking about that :-)

**Comment by karottenreibe** [comment]
Done :-) Added a test + the fix

**Comment by nicolo-ribaudo** [comment]
Can you modify this PR to target the `master` branch?

**Comment by karottenreibe** [comment]
Had to cherrypick those changes to the master branch due to conflicts. created #7131 instead. closing this pull request

**Pull request closed without merging**
