### PR TITLE
Add es2015 loose mode back

### PR DESCRIPTION
**Pull request by hzoo**
- Revert again to use es2015 loose mode

### CODE REVIEW

**Comment by danez** [comment]
I've seen the test failure before when I tried to write tests for babel-register. I think it was the cli tests which registered babel-register and then all tests are registered afterwards. Although not sure why it comes up with your changes.

**Comment by danez** [comment]
After merging this, babylon might need to be adapted, so it can correctly replace itself when running babel tests.

**Comment by hzoo** [comment]
Yeah it probably has to do with babel-register so maybe something is run at the top level now?

**Comment by hzoo** [comment]
Ok had another error with babel-polyfill being imported multiple times, so not sure

**Comment by danez** [comment]
👍

**Pull request merged**
