### PR TITLE
fix plugin-transform-react-constant-elements transform JSXFrament but not add JSXExpressionContainer

### LINKED ISSUE #16449: [Bug]:  Fragment child elements are not transformed correctly when using @babel/plugin-transform-react-constant-elements
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```js
const a = () => <><div>a</div></>
```

### Configuration file name

babel.config.json

### Configuration

```json
{
  "parserOpts": {
    "plugins": ["jsx"]
  },
  "presets": [],
  "plugins": ["@babel/plugin-transform-react-constant-elements"]
}
```

### Current and expected behavior

Expected:
```js
var _div;
const a = () => <>{_div || (_div = <div>a</div>)}</>;
```
or
```js
var _Fragment;;
const a = () => _Fragment || (_Fragment = <><div>a</div></>);
```

Received:
```js
var _div;
const a = () => <>_div || (_div = <div>a</div>)</>;
```

### Environment

-  System:
    OS: macOS 14.4.1
-  Binaries:
    Node: 20.11.1 - ~/.proto/shims/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.18.2/bin/yarn
    npm: 10.2.4 - ~/.proto/shims/npm
    bun: 1.0.29 - ~/.proto/shims/bun
-  npmPackages:
    @babel/plugin-transform-react-constant-elements: ^7.24.1 => 7.24.1 
    @babel/preset-typescript: ^7.24.1 => 7.24.1 

### Possible solution

https://github.com/babel/babel/blob/e779cad081d47bd6a91302e274dbb93f08bd1d51/packages/babel-plugin-transform-react-constant-elements/src/index.ts#L245-L250

Although the entire fragment cannot be made constant, the transformation of child elements works fine using the code below.
```js
if (
  path.parentPath.isJSXFragment() ||
  path.parentPath.isJSXElement() ||
  path.parentPath.isJSXAttribute()
) {
  replacement = t.jsxExpressionContainer(replacement);
}
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by keiseiTi**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #16449 
| Patch: Bug Fix?          |
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

fix #16449，the specific repair content is shown in the following figure

image

### CODE REVIEW

**Review by nicolo-ribaudo — COMMENTED** [review]
Thank you! Would you like to update the PR to get to the other possible expected output (the one where the fragment itself is hoisted), since it seems to be better?

And if yes, then also add a test where only one element can be hoisted and not the whole fragment:
```js
function Component({ x }) {
   return <>
     <a>{x}</a>
     <b />
   </>;
}
```

**Comment by keiseiTi** [comment]
> Thank you! Would you like to update the PR to get to the other possible expected output (the one where the fragment itself is hoisted), since it seems to be better?
> 
> And if yes, then also add a test where only one element can be hoisted and not the whole fragment:
> 
> ```js
> function Component({ x }) {
>    return <>
>      <a>{x}</a>
>      <b />
>    </>;
> }
> ```

sorry , I can't seem to understand what you mean . or  want to add a test case ? or tell me your expected conversion result , then I will do that .

**Comment by JLHwung** [comment]
@keiseiTi Sorry for the late reply.

For the test case
```jsx
function F() {
  return <><div>f</div></>;
}
```

The current output is PR is
```js
var _div;
function F() {
  return <>{_div || (_div = <div>f</div>)}</>;
}
```
This is already working but not optimal, since we still create a new JSX fragment `<>{_div...}</>` whenever `F` is invoked. Can you try to further optimize it to
```js
var _frag;
function F() {
  return _frag || _frag = <><div>f</div></>;
}
```


And when you have done the optimization part, can you also add the following test case?

- `jsx-dynamic-children-in-fragment`
```jsx
function Component({ x }) {
   return <>
     <a>{x}</a>
     <b />
   </>;
}
```
The expected output should be
```js
var _b;
function Component({
  x
}) {
  return <>
    <a>{x}</a>
    {_b || (_b = <b />)}
  </>;
}
```
This test is to verify that Babel can still hoist constant elements, e.g. `<b />` within the fragment, when the fragment as a whole, should not be hoisted as `x` is dynamic.

**Comment by JLHwung** [comment]
Pushed changes from #16220.

**Review by liuxingbaoyu — APPROVED** [review]
Thanks!

**Review by nicolo-ribaudo — APPROVED** [review]
Thanks to both!

**Pull request merged**
