### PR TITLE
temporary disable feature which can break

### PR DESCRIPTION
**Pull request by jbruni**
Bug fix for https://github.com/jbruni/babel-issue

### CODE REVIEW

**Comment by jbruni** [comment]
Just reported the issue here: https://phabricator.babeljs.io/T7127

**Comment by jbruni** [comment]
I am just taking the same approach taken by @zloirock in a commit from 4 days ago: https://github.com/babel/babel/commit/e6e0171db39f04e8c81f33a76a7e9e5afded4ad3

I actually can't build my app front-end due to this bug, and this simple change, despite temporary, just allows the build to complete successfully.

Thank you.

**Comment by zloirock** [comment]
`Object.defineProperty` definition was available in `6.0`, features in the mentioned commit was disabled for preventing the conflict old `runtime` with new `transform-runtime`, it's definitely should not be disabled because it will create problems with `Symbol` polyfill and future `runtime` verions. The problem in the transform, not in the definitions.

**Comment by jbruni** [comment]
Ok. Thanks a lot for the feedback.

By now, in order to keep the current ES6 exports code as they are in the affected application, I temporarily removed `transform-runtime` plugin from my `.babelrc` settings. I wish to bring the plugin it back as soon as the issue is properly fixed.

Thank you.

**Pull request closed without merging**
