### PR TITLE
Fix the transform of `super.foo--`/`super[foo]--` (and prefix)

### LINKED ISSUE #14161: [Bug]: get wrong result after transform `Update assignment expression` in async method
### 💻

- [X] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

[REPL](https://babeljs.io/repl#?browsers=chrome%2050&build=&builtIns=false&corejs=false&spec=false&loose=false&code_lz=MYGwhgzhAECC0FMAeAXBA7AJjAQtA3gFDTSQCe6w0AZgPa0AUAlAcSdBAK4AOCATgDo6taAGpRAbjYkAtDI49-AgEZg-U9gt58A2gCJhegLpjJ06HK399qvsY3QAvoUdA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=script&lineWrap=true&presets=env&prettier=true&targets=&version=7.16.9&externalPlugins=&assumptions=%7B%22noClassCalls%22%3Atrue%2C%22noDocumentAll%22%3Atrue%2C%22mutableTemplateObject%22%3Atrue%2C%22iterableIsArray%22%3Atrue%2C%22ignoreToPrimitiveHint%22%3Atrue%2C%22ignoreFunctionLength%22%3Atrue%2C%22enumerableModuleMeta%22%3Atrue%2C%22noNewArrows%22%3Atrue%2C%22objectRestNoSymbols%22%3Atrue%2C%22privateFieldsAsProperties%22%3Atrue%2C%22pureGetters%22%3Atrue%2C%22setClassMethods%22%3Atrue%2C%22setComputedProperties%22%3Atrue%2C%22setPublicClassFields%22%3Atrue%2C%22setSpreadProperties%22%3Atrue%2C%22skipForOfIteratorClosing%22%3Atrue%2C%22superIsCallableConstructor%22%3Atrue%7D)

```javascript
class A extends B {
  async foo() {
    super.foo ++;
    -- super.bar;
    super["foo"] ++;
    -- super["bar"];
  }
}
```

### Configuration file name

_No response_

### Configuration

Targets: chrome 50

### Current and expected behavior

```javascript
class A extends B {
  foo() {
    var _superprop_getFoo = () => super.foo,
      _superprop_setFoo = (_value) => (super.foo = _value),
      _superprop_getBar = () => super.bar,
      _superprop_setBar = (_value2) => (super.bar = _value2),
      _superprop_get = (_prop3) => super[_prop3],
      _superprop_set = (_prop4, _value3) => (super[_prop4] = _value3);

    return _asyncToGenerator(function* () {
      var _tmp, _tmp2, _tmp3, _prop, _tmp4, _prop2;

      (_tmp = _superprop_getFoo()), _superprop_setFoo(_tmp + 1), _tmp;
      (_tmp2 = _superprop_getBar()), _superprop_setBar(_tmp2 + 1);          // <- wrong result
      (_tmp3 = _superprop_get((_prop = "foo"))),
        _superprop_set(_prop, _tmp3 + 1),
        _tmp3;
      (_tmp4 = _superprop_get((_prop2 = "bar"))),
        _superprop_set(_prop2, _tmp4 + 1);                                  // <- wrong result
    })();
  }
}
```

### Environment

- System:
  - OS: macOS 12.1
- Binaries:
  - Node: 16.13.1 - /opt/homebrew/Cellar/node@16/16.13.1/bin/node
  - Yarn: 1.22.15 - /opt/homebrew/bin/yarn
  - npm: 8.1.2 - /opt/homebrew/Cellar/node@16/16.13.1/bin/npm
- npmPackages:
  - @babel/cli: ^7.16.8 => 7.16.8 
  - @babel/core: ^7.16.7 => 7.16.7 
  - @babel/preset-env: ^7.16.8 => 7.16.8 

### Possible solution

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by magic-akari**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #14161
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/14162"></a>

### CODE REVIEW

**Review by nicolo-ribaudo — APPROVED** [review]
Thanks!

**Review by JLHwung — APPROVED** [review]
Thanks.

Not related to this PR, but we need to add logical assignment support to super property transforms (they should have been extracted to a new helper):

```js
class A extends B {
  async foo() {
    super.foo ??= 1;
  }
}
```

[currently throws](https://babeljs.io/repl#?browsers=chrome%2050&build=&builtIns=false&corejs=false&spec=false&loose=false&code_lz=MYGwhgzhAECC0FMAeAXBA7AJjAQtA3gFDTSQCe6w0AZgPa0AUAlAcSdBAK4AOCATgDo6taAH5RAXmgBGANxsAvoQVA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=script&lineWrap=true&presets=env&prettier=true&targets=&version=7.16.9&externalPlugins=&assumptions=%7B%22noClassCalls%22%3Atrue%2C%22noDocumentAll%22%3Atrue%2C%22mutableTemplateObject%22%3Atrue%2C%22iterableIsArray%22%3Atrue%2C%22ignoreToPrimitiveHint%22%3Atrue%2C%22ignoreFunctionLength%22%3Atrue%2C%22enumerableModuleMeta%22%3Atrue%2C%22noNewArrows%22%3Atrue%2C%22objectRestNoSymbols%22%3Atrue%2C%22privateFieldsAsProperties%22%3Atrue%2C%22pureGetters%22%3Atrue%2C%22setClassMethods%22%3Atrue%2C%22setComputedProperties%22%3Atrue%2C%22setPublicClassFields%22%3Atrue%2C%22setSpreadProperties%22%3Atrue%2C%22skipForOfIteratorClosing%22%3Atrue%2C%22superIsCallableConstructor%22%3Atrue%7D)

**Comment by nicolo-ribaudo** [comment]
I slightly reworded the PR title to fit in a commit message

**Comment by magic-akari** [comment]
> Thanks.
> 
> Not related to this PR, but we need to add logical assignment support to super property transforms (they should have been extracted to a new helper):
> 
> ```js
> class A extends B {
>   async foo() {
>     super.foo ??= 1;
>   }
> }
> ```
> 
> [currently throws](https://babeljs.io/repl#?browsers=chrome%2050&build=&builtIns=false&corejs=false&spec=false&loose=false&code_lz=MYGwhgzhAECC0FMAeAXBA7AJjAQtA3gFDTSQCe6w0AZgPa0AUAlAcSdBAK4AOCATgDo6taAH5RAXmgBGANxsAvoQVA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=script&lineWrap=true&presets=env&prettier=true&targets=&version=7.16.9&externalPlugins=&assumptions=%7B%22noClassCalls%22%3Atrue%2C%22noDocumentAll%22%3Atrue%2C%22mutableTemplateObject%22%3Atrue%2C%22iterableIsArray%22%3Atrue%2C%22ignoreToPrimitiveHint%22%3Atrue%2C%22ignoreFunctionLength%22%3Atrue%2C%22enumerableModuleMeta%22%3Atrue%2C%22noNewArrows%22%3Atrue%2C%22objectRestNoSymbols%22%3Atrue%2C%22privateFieldsAsProperties%22%3Atrue%2C%22pureGetters%22%3Atrue%2C%22setClassMethods%22%3Atrue%2C%22setComputedProperties%22%3Atrue%2C%22setPublicClassFields%22%3Atrue%2C%22setSpreadProperties%22%3Atrue%2C%22skipForOfIteratorClosing%22%3Atrue%2C%22superIsCallableConstructor%22%3Atrue%7D)

I am willing to fix it .Should I open a new issue?

**Pull request merged**
