### PR TITLE
[WIP]Feature/pattern matching statement

### PR DESCRIPTION
**Pull request by vincentdchan**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            |
| Patch: Bug Fix?          |
| Major: Breaking Change?  | No
| Minor: New Feature?      | Yes
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

This is an implementation of [tc39/pattern-matching](https://github.com/tc39/proposal-pattern-matching). Next to #7633 , which is an implementation that pattern matching was still an expression. Now, pattern matching becomes a statement.

Example:
```javascript
case (input) {
  when {x} -> console.log('object: ', x);
  when { name: { firstName },  age: x} -> console.log('nested object ', firstName, x);
  when [1, a, b] -> console.log('array: ', a, b);
  when [1, { type: 3 }, b] -> console.log('array', b);
  when undefined -> console.log('everything');
  when y -> console.log('equal to input: ', input, y);
}
```
It's awesome when you want to write something like a reducer in redux:
```javascript
function todoApp (state = initialState, action) {
  case (action) {
    when {type: 'set-visibility-filter', filter: visFilter} ->
      return {...state, visFilter}
    when {type: 'add-todo', text} ->
      return {...state, todos: [...state.todos, {text}]}
    when {type: 'toggle-todo', index} -> {
      return {
        ...state,
        todos: state.todos.map((todo, idx) => idx === index
          ? {...todo, done: !todo.done}
          : todo
        )
      }
    }
    when {} -> {} // ignore unknown actions
  }
}
```

Although it can work now, I am sorry to tell this implementation is currently **incomplete**. Features below are still working in progress:
- [ ] Initializers
- [ ] RestElement of Object Pattern

I will be happy if somebody want to help. Because there is still a large amount of work to do for this pattern matching feature. It's really cool! 💐💐💐

### CODE REVIEW

**Comment by luxueyan** [comment]
mark

**Comment by JuanCaicedo** [comment]
@vincentdchan I can take a look over the next couple days and will have some more free time to help after Dec 2nd 😀

**Comment by vincentdchan** [comment]
@JuanCaicedo That's great! Thank you!

**Comment by benjamine** [comment]
would the case expression return a value depending on the match? eg. if would be great to be able to write:
``` js
const guessKind = input => case (input) {
  when {x} -> 'an object';
  when { name: { firstName },  age: x} -> `nested object ${firstName} ${x}`;
  when [1, a, b] -> 'array: ' + a + b;
  when undefined -> 'not defined';
};
```

**Comment by np42** [comment]
Since pattern matching become an expression, I think you will have to write your exemple like this:

```
const guessKind = input => case (input) {
  when {x} -> return 'an object';
  when { name: { firstName },  age: x} -> return `nested object ${firstName} ${x}`;
  when [1, a, b] -> return 'array: ' + a + b;
  when undefined -> return 'not defined';
};
```

**Comment by benjamine** [comment]
I see, if it's a statement is that example still possible or it also mean you can't use it as an arrow function body? like `switch`? (which requires using a code block `{ }` around it)

**Comment by np42** [comment]
You're right, as a statement it should requires a code block around it

**Comment by quarryman** [comment]
What is the right way to try it in own project?

**Comment by vincentdchan** [comment]
@quarryman You can checkout my branch and compile yourself to use it in your project. But it's not recommended because it's not finished currently

**Comment by JuanCaicedo** [comment]
@sciencemanx I don't think there has been much change at the TC-39 level, but it's in progress 😀https://github.com/tc39/proposal-pattern-matching

**Comment by vincentdchan** [comment]
Guys, #9318 is a continuation of this PR, Greg is making his efforts to complete this feature. So I will close this PR.

**Pull request closed without merging**
