### PR TITLE
Fix path.remove() leading & trailing comments sharing

### LINKED ISSUE #5503: path.remove() is reversing leading & trailing comments
Hello dear maintainers,

### Input Code
```javascript
// hello world
import './file.js'; 
console.log('foo');
```

### Expected Behavior
```javascript
// hello world
console.log('foo');
```

### Current Behavior
```javascript
console.log('foo'); // hello world
```

### Possible Solution
Pull request #5504 fix the provided example.

### Context
Writing a custom babel plugin to selectively remove import statement so that they get ignored by plugins running after it.

### Your Environment

| software         | version
| ---------------- | -------
| Babel            |  6.23.1
| node             | 4.7.2
| npm              | 2.15.11
| Operating System | Windows 10.0.14393

### PR DESCRIPTION
**Pull request by dmail**
| Q                        | A 
| ------------------------ | ---
| Patch: Bug Fix?          | yes
| Major: Breaking Change?  | no
| Minor: New Feature?      | no
| Deprecations?            | no
| Spec Compliancy?         | 
| Tests Added/Pass?        | yes/yes
| Fixed Tickets            | Fixes #5503
| License                  | MIT
| Doc PR                   | no
| Dependency Changes       | no

### CODE REVIEW

**Comment by dmail** [comment]
Sorry for the commits noise. This pull request is still missing specific tests.

**Comment by dmail** [comment]
I won't commit more now all checks are passing.

At the moment, this pull request prevents comments order being messed up when using `path.remove()`.
However, as tests demonstrates, `path.remove()` still have a negative impact on comment outputs.

I cannot fix this with my current knowledge of babel.

Let me know if this pull request helps you,
Cheers.

**Comment by hzoo** [comment]
Yeah we may have to redo comments based on how eslint/prettier are handling them

**Comment by dmail** [comment]
**Warning** : Travis says tests are passing but `TEST_ONLY=babel-traverse make test` is currently failing.

I'm noticing that your [comments/attachment/expected.js](https://github.com/babel/babel/blob/3852746d875b45135e943c7e2e372872ac7ccf77/packages/babel-traverse/test/fixtures/comments/attachment/expected.js) are expecting correct comment outputs.

For instance you're expecting 
```js
hasPrev;
/* top */
/* left */willRemove;/* right */
/* bottom */
```
To become
```js
hasPrev;
/* top */
/* left */ /* right */
/* bottom */
```
However the current output is 
```js
hasPrev; /* top */ /* left */ /* right */ /* bottom */
```

**Comment by hzoo** [comment]
@dmail it works locally for me (both make test-only and TEST_ONLY)

**Comment by hzoo** [comment]
Truly awesome work @dmail! thanks 👏

**Pull request merged**
