### PR TITLE
fix: preserve function params type if possible

### LINKED ISSUE #14691: [Bug]: Destructurisation transformation loses typescript types
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@babel/cli

### Input code

```ts
type Point = {
  x: number;
  y: number;
}

export function test({x, y}: Point) {
  return x * y;
}
```

### Configuration file name

.babelrc.json

### Configuration

```json
{
  "plugins": [
    "@babel/plugin-transform-parameters",
    ["@babel/plugin-transform-destructuring", {
      "loose": true
    }],
    "@babel/plugin-syntax-typescript"
  ]
}
```

### Current and expected behavior

Current output:
```ts
type Point = {
  x: number;
  y: number;
};
export function test(_ref) {
  let x = _ref.x,
      y = _ref.y;
  return x * y;
}
```
Expected output:
```ts
type Point = {
  x: number;
  y: number;
};
export function test(_ref: Point) {
  let x = _ref.x,
      y = _ref.y;
  return x * y;
}
```

### Environment

  System:
    OS: macOS 12.2
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 3.2.1 - /usr/local/bin/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
  npmPackages:
    @babel/cli: ^7.17.10 => 7.17.10
    @babel/core: ^7.18.5 => 7.18.5
    @babel/plugin-syntax-typescript: ^7.17.12 => 7.17.12
    @babel/plugin-transform-destructuring: ^7.18.0 => 7.18.0

### Possible solution

_No response_

### Additional context

[Reproduction repo](https://github.com/cainrus/test-babel-ts-to-ts-transform)

### PR DESCRIPTION
**Pull request by magic-akari**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #14691 
| Patch: Bug Fix?          | 👍
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/14694"></a>

### CODE REVIEW

**Review by liuxingbaoyu — APPROVED** [review]

**Review by nicolo-ribaudo — COMMENTED** [review]
I dislike hard-coding TS/Flow AST info in "plain JS" plugins, but until we have something like https://github.com/babel/babel/issues/9545 this is the best we can do.

**Comment by nicolo-ribaudo** [comment]
Can you also add a test for `function point({ x, y }: Point = {})`?

**Comment by magic-akari** [comment]
> Can you also add a test for `function point({ x, y }: Point = {})`?

Sure. I dont' think there is anything to do if the function parameter doesn't exist.
Or should we add a param placeholder? not a good idea.

**Comment by magic-akari** [comment]
Since the function param with default value does not count in function length, we should never add param placeholder for it.

**Comment by nicolo-ribaudo** [comment]
Oh right, I don't know what I was thinking

**Review by nicolo-ribaudo — APPROVED** [review]

**Pull request merged**
