### PR TITLE
Ghost copy of #11167

### PR DESCRIPTION
**Pull request by arcanis**
This PR isn't for merge - I'd just like to run the repo tests on #11167 🙂

### CODE REVIEW

**Comment by nicolo-ribaudo** [comment]
Thanks! :grin:

**Comment by arcanis** [comment]
So it turns out that Node 13.10.1, just released, has a regression that breaks Node 🙃

https://github.com/sindresorhus/got/issues/1107

**Comment by arcanis** [comment]
@nicolo-ribaudo Does the e2e failure reminds you something? It seems Lerna is trying to publish the same package twice:

```
lerna http fetch PUT 409 http://localhost:4873/@babel%2fparser 748ms
...
lerna http fetch GET 200 http://localhost:4873/@babel%2fparser?write=true 121ms
lerna ERR! EPUBLISHCONFLICT Cannot publish @babel/parser@undefined over existing version.
```

**Comment by nicolo-ribaudo** [comment]
It should be fixed by rebasing on master. I can rebase my branch after dinner and then you can cherry-pick your commits, so that you won't have to resolve all the `workspace:^7.8.3` conflicts manually :stuck_out_tongue:

**Comment by nicolo-ribaudo** [comment]
@arcanis The e2e failure might not be related (I think I have seen it failing also in another PR targeting the `next-8-dev` branch)

**Comment by arcanis** [comment]
@nicolo-ribaudo does this error ring a bell? I'm not entirely sure what this test does.

image

**Comment by nicolo-ribaudo** [comment]
It happens when using `@babel/core@7.0.0` in our build script; I'll investigate why it is failing here and not on mastre.

**Pull request closed without merging**
