### PR TITLE
Revert to standard ASI behavior for class properties

### PR DESCRIPTION
**Pull request by loganfsmyth**
@jeffmo We'd like your final sign-off before merging this.

### CODE REVIEW

**Comment by jeffmo** [comment]
Thanks. And just for clarity, would you mind adding a few more tests?

```
class Foo {
  x
  y // works
}
```


```
class Foo {
  p
  [m] () {} // works
}
```


```
class Foo {
  p = x
  [m] () {} // parse error
}
```


```
class Foo {
  [p1]
  [p2] // works
}
```


```
class Foo {
  [p1] = x
  [p2] // parses as a '[p1] = x[p2];'
}
```

**Comment by jeffmo** [comment]
By the way: My apologizes to everyone for the thrash. I should've paid closer attention to the ASI stuff

**Comment by loganfsmyth** [comment]
@jeffmo Sure, I'll add those test cases. I don't think
```
class Foo {
  [p1]
  [p2] // works
}
```

would work though.

**Comment by loganfsmyth** [comment]
Actually nevermind. Currently Babel just does not handle parsing assignments to computed properties though.

**Comment by loganfsmyth** [comment]
I added the 3 of the 5 that don't involve computed properties.

**Comment by jeffmo** [comment]
Thanks, this looks correct

**Comment by amasad** [comment]
:+1:

**Comment by hzoo** [comment]
> Currently Babel just does not handle parsing assignments to computed properties though.
@loganfsmyth Do we already have an issue for that one?

Otherwise we can merge as a bug fix/spec

**Comment by loganfsmyth** [comment]
@hzoo I don't think we do. I didn't realize it was actually supposed to be supported :p

**Comment by ChrisCinelli** [comment]
Awesome! I look forward to the release!

**Comment by einarlove** [comment]
Which version will this be released in?

**Comment by hzoo** [comment]
I added a 6.5.x milestone, so in the next patch release - planning sunday/monday.

**Comment by michaelficarra** [comment]
A test involving a generator method would be great:

```js
class Foo {
  p = x
  *m () {} // parse error
}
```

**Comment by hzoo** [comment]
@michaelficarra k I'l do a PR

**Pull request merged**
