### PR TITLE
Switch to nyc, babel-plugin-istanbul & codecov-node for code coverage

### PR DESCRIPTION
**Pull request by bcoe**
This sees @motiz88's work over the finish line; I released a couple more changes to nyc for babel's benefit (caching on by default, configurable debug output) and tested thoroughly:

| Q                 | A 
| ----------------- | ---
| Bug fix?          |  No
| Breaking change?  | No
| New feature?      |  No
| Deprecations?     |  No
| Spec compliancy?  |  No
| Tests added/pass? |  No (they pass though, woo!)
| Fixed tickets     | `See #4740`
| License           | MIT
| Doc PR            |  Nope
| Dependency Changes| 

Just a couple tweaks to @motiz88's work, and a rebase with master; would love to see this over the finish line:

_Note: we do now add empty reports for files that aren't accessed._

CC: @danez, @hzoo

### CODE REVIEW

**Comment by motiz88** [comment]
Oh lovely. @bcoe I really appreciate you picking this up.

**Comment by bcoe** [comment]
@hzoo 👍

**Comment by hzoo** [comment]
Dono if it's worth adding make/npm command for us to open the coverage locally (if it works online then great, since it always seemed to be weird for me)

**Comment by bcoe** [comment]
@hzoo you can run:

`./node_modules/.bin/nyc --reporter=html`

And view an html report in the `/coverage` folder; would you like to add a shortcut for that to package.json?

**Comment by bcoe** [comment]
@hzoo perhaps we can land this, and in a separate issue if you describe to me the types of reports you'd like output I'd be happy to add a few more npm-scripts for you post-hoc.

**Comment by hzoo** [comment]
Ah yeah that was just a comment not a review or anything (I wasn't doing much oss last week)

**Pull request merged**
