### PR TITLE
Fixes #6726 ignore config option

### PR DESCRIPTION
**Pull request by subtleGradient**
https://phabricator.babeljs.io/T6726

### CODE REVIEW

**Comment by STRML** [comment]
This is a really annoying bug and contradicts the docs. Could someone please review and merge it ASAP?

**Comment by yaycmyk** [comment]
@hzoo ?

**Comment by hzoo** [comment]
So sorry for the delay, I'm not particularly familiar with this of the codebase but @kittens says it was probably an artifact of some older code at the time. https://github.com/babel/babel/commit/67201e969880e0435d7b20200d1e0d2695b5f863

**Comment by gcedo** [comment]
I am continuing to experience this bug, `babel-cli@6.14.0`. Now the `ignore` option is supported, but files are not ignored recursively.

E.g., declaring:
```
"ignore": [
        "node_modules"
]
```

Will cause the build to fail anyway because, as babel will try to transpile files deep down in the `node_modules` hierarchy:

```
69% 1206/1215 build modulesnode_modules/babel-plugin-react-transform/lib/index.js -> dist/node_modules/babel-plugin-react-transform/lib/index.js
```

**Comment by danez** [comment]
Does it work if you specify the option on the command line?
```
babel --ignore 'node_modules' ... 
```

**Comment by gcedo** [comment]
Yes, it does. As I have seen the bug fix I have moved the options in `.babelrc`, but now it fails 😢

**Comment by danez** [comment]
Can you please open a new issue, so we do not forget about it. Thanks

**Comment by pdillon** [comment]
@danez Opened #4707 and corresponding PR #4708

**Comment by cula** [comment]
Happen again on babel 6.24.0

**Comment by sabeurthabti** [comment]
happens on `6.26.0`

**Pull request merged**
