### PR TITLE
Fix potential failure for AMD loaders with lazy load

### PR DESCRIPTION
**Pull request by Justineo**
Package: babel-plugin-transform-es2015-modules-amd
Related issue: https://phabricator.babeljs.io/T7382

``` js
import 'foo';
```

Currently the code above is transformed into:

``` js
define(['foo'], function () {});
```

For AMD implemetations, it is explicitly allowed to _not_ execute the module factory of `foo` in this kind of situation (https://github.com/amdjs/amdjs-api/wiki/AMD#dependencies-):

> The dependencies argument is optional. If omitted, it should default to ["require", "exports", "module"]. However, if the factory function's arity (length property) is less than 3, then the loader **may choose to only call the factory with the number of arguments corresponding to the function's arity or length**.

So `foo`'s factory may never have chance to be called in certain AMD-compatible loaders.

I've added an `addBareSourceParams` option for `babel-plugin-transform-es2015-modules-amd`, which will append params corresponding to those bare imports to the module's param list.

The output looks like this with this option set to `true`:

``` js
define(['foo'], function (_temp) {});
```

### CODE REVIEW

**Comment by hzoo** [comment]
Hmm ok, so would doing this by default be non-backwards compatible?

**Comment by Justineo** [comment]
This is backward compatible but for those who use RequireJS or other certain AMD loaders, the extra params are useless so people may not want to have them in the results. So make it optional should be fine I think.

**Comment by danez** [comment]
As far as I understand the amd specs it says something like: 

> If there are no dependencies, it should default to ["require", "exports", "module"] and if there are less than 3 params in the factory it might only supply `["require"]` (1) or `["require", "exports"]` (2).

This all applies when there are no dependencies afaics, but we always set dependencies. Imho it would be fatal if the loader would not resolve dependencies if they are explicitly in the dependencies array, even if not used.

**Comment by Justineo** [comment]
@danez whether to strip "useless" params seem to differ among different minifiers. I can't find how to let Google Closure Compiler keep unused function params, while UglifyJS has an option for this (which keeps them by default). But as unused function params seem to be always "strppable" for minifiers, I think it's OK for us to keep them by default in Babel. I'll update the PR to make it a default behavior today.

**Comment by Justineo** [comment]
Hi guys, how can I get this PR merged?

**Pull request closed without merging**
