### PR TITLE
Update variableDeclaration documentation [skip ci]

### PR DESCRIPTION
**Pull request by jamime**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | :x: 
| Patch: Bug Fix?          |:x:
| Major: Breaking Change?  |:x:
| Minor: New Feature?      |:x:
| Tests Added + Pass?      | :x:
| Documentation PR         | :heavy_check_mark:
| Any Dependency Changes?  |:x:
| License                  | MIT

The **babel-types** documentation incorrectly stated that the `variableDeclaration` function accepts a `declare` argument. I have removed this.

### CODE REVIEW

**Comment by existentialism** [comment]
@jamime thanks for the PR! The babel-types documentation is actually [generated automatically](https://github.com/babel/babel/blob/master/scripts/generators/docs.js).

The reason this shows up is that `declarations` is in the `builder`:
https://github.com/babel/babel/blob/master/packages/babel-types/src/definitions/core.js#L810

**Comment by jamime** [comment]
@existentialism I did not realise this, although it is the `declare` param which is not in the `builder`.

**Comment by existentialism** [comment]
@jamime sorry, that's what I get for not having coffee this morning :)

`declare` needs to be in the `builder` array for it to work.

The README represents the current state of `master`, while babeljs.io represents 6.x since v7 is still in beta. (we definitely agree this is causing confusion, and are actively working on getting versioned docs up asap)

**Comment by jamime** [comment]
@existentialism Thanks for the explanation!

**Pull request closed without merging**
