### PR TITLE
Adds note about two approval policy to PR template

### PR DESCRIPTION
**Pull request by thiagoarrais**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | None
| Patch: Bug Fix?          | No
| Major: Breaking Change?  | No
| Minor: New Feature?      | No
| Tests Added + Pass?      | N/A
| Documentation PR Link    | 
| Any Dependency Changes?  | No
| License                  | MIT

I've sometimes noticed some folks getting confused about Babel's two approval policy. From the Contributor point of view, the PR seems stale after getting the first approval.

This adds a comment to the PR template with the goal of surfacing the policy and avoiding confusion.

### CODE REVIEW

**Comment by thiagoarrais** [comment]
Shoot! Should've added `[skip ci]` to the commit.

**Comment by hzoo** [comment]
I think I wrote some stuff before around this https://github.com/babel/babel/wiki/Maintaining-Babel#merging but yeah the general case is 2, unless it's more of a typo thing (mostly for the website),

I guess master is failing due to test fixtures (I assume related to data from compat type stuff)

**Comment by thiagoarrais** [comment]
I wasn't aware of that documentation. Just added a qualifier to the proposal in light of that

**Comment by hzoo** [comment]
Should be fine to merge if master is ok

**Pull request merged**
