### PR TITLE
Added support for disabling babel-node for a given Node version range

### PR DESCRIPTION
**Pull request by kripod**

### CODE REVIEW

**Comment by loganfsmyth** [comment]
I'm confused, why would you be running `babel-node` to begin with if it's a node version that you don't want to run on?

**Comment by hzoo** [comment]
Right otherwise you could just use `node`. Seems like it's for using babel-node to run tests on CI to have less configuration?

**Comment by kripod** [comment]
For packages which support legacy Node versions, it is important to provide consistency with babel-node. As Node v6 has come out, the need for babel-node's transpilation is not only redundant, but also has an impact on performance.

If you have an ES6 codebase only with features which Node v6 supports natively, then babel-node should not transpile your code if you're using Node v6. But if someone downloads your package and uses a Node v5 runtime, then babel-node transformations will occur.

To reproduce the case described above, just run `babel-node index.js --no-transpile >=6`

**Comment by hzoo** [comment]
When you use people's packages you usually consume them as ES5 though? Also regarding performance, transpiling can actually be faster in some cases since node hasn't had time to optimize.

**Comment by kripod** [comment]
Yeah, I consume every package as ES5.

**Pull request closed without merging**
