### PR TITLE
Expose wether a module has TLA or not as `.extra.async`

### PR DESCRIPTION
**Pull request by nicolo-ribaudo**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes https://github.com/babel/babel/issues/16471
| Patch: Bug Fix?          |
| Major: Breaking Change?  |
| Minor: New Feature?      | Yes
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

The parser already has this info, and having to detect it by yourself is error prone (due to computed keys and decorators).

We can also use this to warn in the CJS transform when there is top-level await (in a follow-up).

### CODE REVIEW

**Comment by liuxingbaoyu** [comment]
Would it be better to just use `topLevelAwait` as the name?
Can we put `hasTopLevelAwait` in `BaseParser` together with `sawUnambiguousESM`, which would save a place, since `1 << 11` is already there :)

**Comment by nicolo-ribaudo** [comment]
Renamed to `topLevelAwait`. I prefer to keep this in `.state.flags`, because currently we have still 20 bits of space that are being "wasted" there :) If anything, I would move `sawUnambiguousESM` to there.

**Comment by liuxingbaoyu** [comment]
You are right! If we just want to avoid traversing `Program`, that works too. Because other plugins run after that.
Of course, I personally prefer to avoid it by plugin order.

**Review by JLHwung — APPROVED** [review]
Can you add a test case for module expressions if there aren't such test? The current implementation should already work.

**Review by liuxingbaoyu — APPROVED** [review]

**Pull request merged**
