### PR TITLE
Restore es5 compatibility in `@babel/runtime/regenerator`

### PR DESCRIPTION
**Pull request by jlowcs**
This aims to fix https://github.com/babel/babel/issues/14586.

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/14588"></a>

### CODE REVIEW

**Comment by nicolo-ribaudo** [comment]
Whoops sorry, I'll release as soon as CI is green.

**Review by nicolo-ribaudo — APPROVED** [review]

**Review by liuxingbaoyu — APPROVED** [review]

**Comment by nicolo-ribaudo** [comment]
Released

**Comment by pecliu** [comment]
> Released

pls publish it on NPM

**Comment by liuxingbaoyu** [comment]
> > Released
> 
> pls publish it on NPM

https://www.npmjs.com/package/@babel/runtime

**Pull request merged**
