### PR TITLE
Build before running tests

### LINKED ISSUE #5910: `make test-ci-coverage` & `make test-only` seem to install deps differently
Was trying to look at the failing tests on https://github.com/babel/babel/pull/5735, and encountered strange (_at least I find it so_) behaviour in the process:

While on the [currently last commit](https://github.com/babel/babel/pull/5735/commits/3e27d174ee85f24919aed0d78227ba2015dc6117) of https://github.com/babel/babel/pull/5735, if I locally ran `make test-ci-coverage`, I see `dag-map` is present in the `node_modules` within `packages/babel-core`. If I locally ran `make test-only`, it isn't. Needless to say, the test results vary based on this fact.

Haven't investigated anything, just thought to report this in case somebody had pointers, else I'll come back to it.

Node 8 / npm 5

### PR DESCRIPTION
**Pull request by sarupbanskota**
| Q                        | A 
| ------------------------ | ---
| Patch: Bug Fix?          | 
| Major: Breaking Change?  | 
| Minor: New Feature?      | 
| Deprecations?            | 
| Spec Compliancy?         | 
| Tests Added/Pass?        | 
| Fixed Tickets            | Fixes #5910
| License                  | MIT
| Doc PR                   | 
| Dependency Changes       | 

Didn't get a response on https://github.com/babel/babel/issues/5910#issuecomment-314375177, so decided to PR anyway. Feel free to ignore if it's unnecessary

### CODE REVIEW

**Comment by jridgewell** [comment]
This'll seriously slow down development. Now that I read the issue fully, Travis never calls `make test-only` directly, it calls `make test-ci` (which bootstraps)

**Comment by sarupbanskota** [comment]
@jridgewell that's right, Travis doesn't

I could have understood wrong, but while developing, let's say I make a bunch of changes to a file, and only want to check if the tests are good, without linting checks. I'll need to build it anyway before I test, right? (otherwise all the files within `lib` are basically unchanged, only the source has changed) ...

as a side note, on my computer `make build` takes `~2s`. (`make bootstrap` takes `~30s`)

**Comment by hzoo** [comment]
normally I run `make watch` so it's already building and then run make test manually. There is a case for doing both I guess and running tests on change too

**Comment by danez** [comment]
`make test-only` is meant to be run together with `make watch` or just do `make build && make test-only`

**Pull request closed without merging**
