### PR TITLE
Fixes #7516 jsx single attribute spread

### PR DESCRIPTION
**Pull request by jfschwarz**
https://phabricator.babeljs.io/T7516

EDIT by hzoo: #4416

### CODE REVIEW

**Comment by hzoo** [comment]
Looks like you'll need to fixup the existing test (or just use that one as the test)

**Comment by jfschwarz** [comment]
whoops, seems like i forgot to run the full test suite... thank you.

**Comment by hzoo** [comment]
Although now that I think about it, why are you passing in a function anyway (and adding props to it)? This works when you pass an object, so I'm just wondering the benefit of doing that?

**Comment by jfschwarz** [comment]
Well, my use case might seem a bit obscure, but let me try to explain: I'm authoring a utility function for making react components themeable ([substyle](https://github.com/jfschwarz/substyle)), which has a chaining API. Example:

```jsx
// derive a new instance of the substyle function, which is preconfigured to 
// merge styles passed as arg with `defaultStyle`
const substyleForMyComp = substyle({ style: defaultStyle }) 

// `props.style` will be merged with `defaultStyle`, the result will be `Object.assign`ed 
// to the return function value  
const MyComp = (props) => <div {... substyleForMyComp(props)} />
```

In any case, I'd expect JSX spread to have the same semantics as regular object spreading. Since `const obj = { ...myFunction }` works, for consistency reasons also `<div {...myFunction} />` should work.

**Comment by hzoo** [comment]
I see, cc @zpao @spicyj for thoughts?

**Comment by spicyj** [comment]
A little related discussion: https://github.com/facebook/react/pull/6134.

@jfschwarz Can you explain why the current compilation doesn't work for your needs? I agree that your change makes it a little "more correct" but I think the difference should be basically unobservable with React unless you hit that warning (since createElement always copies the props object when extracting key/ref).

**Comment by jfschwarz** [comment]
@spicyj I think React behaves fine and that warning makes perfect sense. Indeed, passing in a function as second arg to `createElement` doesn't seem to break anything. (I was probably misled by another problem in my code initially.)

However, I would not expect to hit that warning when using JSX spread, which I would assume to behave the same as regular object spreading. It's especially weird, that I only get the warning if I do not pass any additional props.

The proposed change in the compilation would fix this inconsistency.

**Comment by afc163** [comment]
:+1:

**Comment by spicyj** [comment]
Just talked about this with @gaearon and @sebmarkbage – we don't really see a valuable semantic difference here and it would be unfortunate to introduce an extra copy for all of these cases so let's leave it as-is.

**Comment by jfschwarz** [comment]
@spicyj In that case, should we maybe consider removing the warning from React altogether? It actually makes sense to warn when using `createElement`. It doesn't when using JSX, though. 

I'd think a large majority of people is using JSX over `createElement`. So for many cases this warning is misplaced. Imho, it's better to just remove a warning if we can't prevent false positives.

Another thought: JSX might be compiled to a call of a wrapped version of `createElement` for which the warning would be disabled.

**Comment by spicyj** [comment]
We're removing it in https://github.com/facebook/react/pull/7724.

**Comment by hzoo** [comment]
Ok so this can be closed?

**Comment by jfschwarz** [comment]
Great to hear! Yes, then this can be closed.

**Comment by hzoo** [comment]
Cool, thanks for the PR anyways!

**Pull request closed without merging**
