### PR TITLE
incorrect handling of returns nested in switch cases

### LINKED ISSUE #1051: Aren't in a loop and we're trying to reassign breaks and continues
I'm seeing this error with Babel 4.7.13 when processing a pretty long script (which is actually still ES5 at this point):

```
Error: [filename]: Aren't in a loop and we're trying to reassign breaks and continues, something is going wrong here.
    at BlockScoping.buildHas (node_modules\babel-core\lib\babel\transformation\transformers\es6\block-scoping.js:548:15)
    at BlockScoping.build (node_modules\babel-core\lib\babel\transformation\transformers\es6\block-scoping.js:519:12)
    at BlockScoping.wrapClosure (node_modules\babel-core\lib\babel\transformation\transformers\es6\block-scoping.js:400:10)
    at BlockScoping.run (node_modules\babel-core\lib\babel\transformation\transformers\es6\block-scoping.js:283:12)
    at TraversalPath.BlockStatement (node_modules\babel-core\lib\babel\transformation\transformers\es6\block-scoping.js:99:18)
    at TraversalPath.call (node_modules\babel-core\lib\babel\traversal\path.js:127:26)
    at TraversalPath.visit (node_modules\babel-core\lib\babel\traversal\path.js:142:10)
    at TraversalContext.visitNode (node_modules\babel-core\lib\babel\traversal\context.js:34:22)
    at TraversalContext.visit (node_modules\babel-core\lib\babel\traversal\context.js:42:19)
    at Function.traverse.node (node_modules\babel-core\lib\babel\traversal\index.js:44:17)
    at TraversalPath.visit (node_modules\babel-core\lib\babel\traversal\path.js:159:18)
    at TraversalContext.visitNode (node_modules\babel-core\lib\babel\traversal\context.js:34:22)
    at TraversalContext.visit (node_modules\babel-core\lib\babel\traversal\context.js:51:28)
```

I was only passing `blacklist: ['strict']` originally, but it also happens from the command line, without any options.

I'd be happy to provide a minimal script that triggers the error, but how would I go about debugging this? From the looks of it, it's walking the AST, so I should probably be able to find the tree node it's choking on and map that back to the source?

### PR DESCRIPTION
**Pull request by ahl**
Without this fix the test included below crashes in the following way:
```
  1) babel-plugin-transform-es2015-block-scoping/general superswitch:
     TypeError: /Users/ahl/src/babel/packages/babel-plugin-transform-es2015-block-scoping/test/fixtures/general/superswitch/actual.js: Property body of LabeledStatement expected node to be of a type ["Statement"] but instead got null
      at Object.validate (packages/babel-types/lib/definitions/index.js:110:13)
      at validate (packages/babel-types/lib/index.js:541:9)
      at Object.builder (packages/babel-types/lib/index.js:494:7)
      at BlockScoping.run (packages/babel-plugin-transform-es2015-block-scoping/lib/index.js:384:16)
      at PluginPass.BlockStatementSwitchStatementProgram (packages/babel-plugin-transform-es2015-block-scoping/lib/index.js:65:24)
      at newFn (packages/babel-traverse/lib/visitors.js:301:19)
      at NodePath._call (packages/babel-traverse/lib/path/context.js:76:18)
      at NodePath.call (packages/babel-traverse/lib/path/context.js:48:17)
      at NodePath.visit (packages/babel-traverse/lib/path/context.js:106:12)
      at TraversalContext.visitQueue (packages/babel-traverse/lib/context.js:168:16)
      at TraversalContext.visitMultiple (packages/babel-traverse/lib/context.js:114:17)
      at TraversalContext.visit (packages/babel-traverse/lib/context.js:210:19)
      at Function.traverse.node (packages/babel-traverse/lib/index.js:161:17)
      at NodePath.visit (packages/babel-traverse/lib/path/context.js:116:43)
      at TraversalContext.visitQueue (packages/babel-traverse/lib/context.js:168:16)
      at TraversalContext.visitMultiple (packages/babel-traverse/lib/context.js:114:17)
      at TraversalContext.visit (packages/babel-traverse/lib/context.js:210:19)
      at Function.traverse.node (packages/babel-traverse/lib/index.js:161:17)
      at NodePath.visit (packages/babel-traverse/lib/path/context.js:116:43)
      at TraversalContext.visitQueue (packages/babel-traverse/lib/context.js:168:16)
      at TraversalContext.visitMultiple (packages/babel-traverse/lib/context.js:114:17)
      at TraversalContext.visit (packages/babel-traverse/lib/context.js:210:19)
      at Function.traverse.node (packages/babel-traverse/lib/index.js:161:17)
      at NodePath.visit (packages/babel-traverse/lib/path/context.js:116:43)
      at TraversalContext.visitQueue (packages/babel-traverse/lib/context.js:168:16)
      at TraversalContext.visitSingle (packages/babel-traverse/lib/context.js:119:19)
      at TraversalContext.visit (packages/babel-traverse/lib/context.js:212:19)
      at Function.traverse.node (packages/babel-traverse/lib/index.js:161:17)
      at NodePath.visit (packages/babel-traverse/lib/path/context.js:116:43)
      at TraversalContext.visitQueue (packages/babel-traverse/lib/context.js:168:16)
      at TraversalContext.visitMultiple (packages/babel-traverse/lib/context.js:114:17)
      at TraversalContext.visit (packages/babel-traverse/lib/context.js:210:19)
      at Function.traverse.node (packages/babel-traverse/lib/index.js:161:17)
      at NodePath.visit (packages/babel-traverse/lib/path/context.js:116:43)
      at TraversalContext.visitQueue (packages/babel-traverse/lib/context.js:168:16)
      at TraversalContext.visitSingle (packages/babel-traverse/lib/context.js:119:19)
      at TraversalContext.visit (packages/babel-traverse/lib/context.js:212:19)
      at Function.traverse.node (packages/babel-traverse/lib/index.js:161:17)
      at traverse (packages/babel-traverse/lib/index.js:83:12)
      at File.transform (packages/babel-core/lib/transformation/file/index.js:549:59)
      at packages/babel-core/lib/transformation/pipeline.js:50:19
      at File.wrap (packages/babel-core/lib/transformation/file/index.js:564:16)
      at Pipeline.transform (packages/babel-core/lib/transformation/pipeline.js:47:17)
      at run (packages/babel-helper-transform-fixture-test-runner/lib/index.js:223:20)
      at runTask (packages/babel-helper-transform-fixture-test-runner/lib/index.js:61:13)
      at Context.<anonymous> (packages/babel-helper-transform-fixture-test-runner/lib/index.js:87:13)
```

With the fix `make test` is clean.

This seems to be a consequence of the following commit:
```
commit 660d764390a65a3ff54d6e93fd801d4f9138c7da
Author: Sebastian McKenzie <sebmck@gmail.com>
Date:   Wed Mar 18 23:31:11 2015 +1100

    remove loop check when aliasing breaks, continues etc - fixes #1051
```

Note that this was found in the course of development and the test is a pruned down version of the actual code. A workaround was to replace the nested `return` with a `break` and some additional logic outside of the `switch`.

### CODE REVIEW

**Comment by lukeapage** [comment]
it looks like the same problem I reported yesterday:

https://phabricator.babeljs.io/T7528

**Comment by ahl** [comment]
What can I do to get this accepted?

**Comment by danez** [comment]
lgtm

**Comment by ahl** [comment]
@danez anything I can do to nudge this along?

**Comment by hzoo** [comment]
sorry, thanks!

**Pull request merged**
