### PR TITLE
Yarn 2.3.3

### PR DESCRIPTION
**Pull request by nicolo-ribaudo**
| Q                        | A 
| ------------------------ | ---
| License                  | MIT

This is needed for https://github.com/babel/babel/pull/12138 (they added a new feature in 2.3.2 that I need for the plugin)

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/12172"></a>

### CODE REVIEW

**Review by existentialism — APPROVED** [review]

**Comment by nicolo-ribaudo** [comment]
Ok it looks like their updated package wasn't released (even if it was merged before the last version). For now I copy-pasted their code in the yarn plugin, so this is not urgent.

**Comment by merceyz** [comment]
> Ok it looks like their updated package wasn't released (even if it was merged before the last version).

Yeah, it was a small patch release to fix a hoisting bug, sorry.

**Comment by nicolo-ribaudo** [comment]
Yeah, it's not a problem!

**Comment by nicolo-ribaudo** [comment]
Closing until yarn 2.4.0 is released

**Comment by merceyz** [comment]
2.4.0 has been released with the changes you needed :)

**Comment by nicolo-ribaudo** [comment]
Oh thanks, I'll prepare a PR!

**Pull request closed without merging**
