### PR TITLE
Do not include babel-register in test helper

### PR DESCRIPTION
**Pull request by danez**
Seems this is not needed for the internal tests? Not sure if this might be used outside of babel and break stuff there?

I discovered that while debugging the pirates integration and was curious why we do this, although not needed. Anybody knows?

### CODE REVIEW

**Comment by hzoo** [comment]
Yeah I was getting this issue before, but I thought this was transpiling the required tests? Not sure @kittens

**Comment by danez** [comment]
By looking more at it it seems to ignore anyway everything (node_modules and ./packages/)
```js
{
  ignore: [
    path.resolve(__dirname + "/../.."),
    "node_modules",
  ]
}
```

And we don't have code or tests outside of that.

I'm going to merge these and will keep an eye on this after the release, I tested with some external projects that use this module, but couldn't find anything.

**Comment by hzoo** [comment]
This means we can remove the babel-register dep?

**Comment by danez** [comment]
Oh ups, forgot that

**Pull request merged**
