### PR TITLE
7.0.patch

### PR DESCRIPTION
**Pull request by szb512**
| ------------------------ | ---
| Fixed Issues?            |Fixes a lot of issues
| Patch: Bug Fix?          |Yes
| Major: Breaking Change?  |Maybe
| Minor: New Feature?      |Maybe
| Tests Added + Pass?      | Yes
| Documentation PR Link    | Maybe
| Any Dependency Changes?  |Maybe
| License                  | MIT
This will fix a lot of bugs.

### CODE REVIEW

**Comment by nicolo-ribaudo** [comment]
What is this PR for?

**Comment by szb512** [comment]
It will fix a lot of bugs, and improve babel.

**Comment by nicolo-ribaudo** [comment]
I don't see how. Did you forget to push some commits?

**Comment by szb512** [comment]
No I didn't

**Comment by nicolo-ribaudo** [comment]
Both these commits have already been released different months ago.

**Comment by szb512** [comment]
Okay.

**Pull request closed without merging**
