### PR TITLE
Remove old optional chain features

### PR DESCRIPTION
**Pull request by jridgewell**
- Optional New is removed
- Put operations on an optional chain are removed
- Deletes on optional chain are removed

### CODE REVIEW

**Comment by littledan** [comment]
For the deleted paths, what is the behaviour? Is there a syntax error triggered at some point?

Another recent change was to change the scope of short circuiting. For example, `(null?.x).y` used to return undefined and now it throws a TypeError. Do you have any tests that distinguish these cases?

**Comment by jridgewell** [comment]
These removals have to be updated in Babylon so tbey’re no longer valid.

**Comment by claudepache** [comment]
> Deletes on optional chain are removed

They are *not* removed in the official proposal, and I don’t expect them to be removed.

**Comment by jridgewell** [comment]
I didn’t see it in the spec, where is it handled at?

**Comment by claudepache** [comment]
> I didn’t see it in the spec, where is it handled at?

There is no change needed in the [current spec around delete](https://tc39.github.io/ecma262/#sec-delete-operator) in order to make it work.

**Comment by claudepache** [comment]
Also, some invalid constructs that should be checked:

The new operator and tagged template literals can no longer be used after optional chaining, e.g.:  `new a?.b()` or `` a?.b`${x}` `` : they are not supported by the grammar.

Attempt  to assign to an optional chain (e.g. `a?.b = 2` or `(a?.b)++`) is an early Reference Error, in line with what happens with other statically detectable invalid assignment targets. (In the spec text, this is handled by the `IsValidSimpleAssignmentTarget` static semantics rule returning `false`.)

**Comment by claudepache** [comment]
> As things are now, I'd guess that `delete x?.y` might just consistently evaluate to true without deleting anything

`delete x?.y` evaluates to `true` if `x` evaluates to null/undefined; otherwise, it evaluates to the same value as `delete x.y` (with the same side-effect).

**Comment by littledan** [comment]
> that delete x?.y might just 

Thanks for clarifying what the specified behavior is.  My comment was referring to the Babel source.

**Comment by jridgewell** [comment]
This has been rebased. To answer a few of @littledan's points:

> Seems like this expands to == null, but the specified semantics are === undefined || === null.

This was fixed on master, and is in the rebase.

> I see a bunch of tests deleted; I'd prefer to see them test for the newly intended behavior
> When finding ?. used in places which are disallowed, such as x?.y = z, this should be a SyntaxError

This would require a large redo of the babylon code to accomplish. I've added checks for `AssignmentExpression` and `UpdateExpression` to throw, but they still parse.

> As long as the spec has optional chaining delete in it, IMO Babel should continue to support it.

Can someone walk me through how this is handled by the spec? Without it being explicitly called out, I don't see how the current text allows it.

**Comment by hzoo** [comment]
I think we should land with what's here and make a new PR for new fixes then?

**Comment by littledan** [comment]
> This would require a large redo of the babylon code to accomplish. I've added checks for AssignmentExpression and UpdateExpression to throw, but they still parse.

Sounds like some good follow-on work.

> Can someone walk me through how this is handled by the spec? Without it being explicitly called out, I don't see how the current text allows it.

See https://github.com/tc39/proposal-optional-chaining/issues/40#issuecomment-345483067

**Pull request merged**
