### PR TITLE
Archive syntax plugins enabled by default

### PR DESCRIPTION
**Pull request by nicolo-ribaudo**
| Q                        | A 
| ------------------------ | ---
| License                  | MIT

Moved to babel-archive: babel/babel-archive@8f23ddce037a6eead85c012e07e618c01f33bfaa

- `@babel/plugin-syntax-async-generators`
- `@babel/plugin-syntax-bigint`
- `@babel/plugin-syntax-dynamic-import`
- `@babel/plugin-syntax-json-strings`
- `@babel/plugin-syntax-nullish-coalescing-operator`
- `@babel/plugin-syntax-object-rest-spread`
- `@babel/plugin-syntax-optional-catch-binding`
- `@babel/plugin-syntax-optional-chaining`

### CODE REVIEW

**Comment by nicolo-ribaudo** [comment]
This PR depends on all the PRs that are enabling some syntax by default in the parser

**Comment by Alonski** [comment]
Hmm wondering why this wasn't a breaking change. 🤔 
Had to install all of these one by one until build passed

**Comment by nicolo-ribaudo** [comment]
With Babel 7.8 you don't need to install them. Maybe you were accidentally using an older Babel version, which required them.

**Comment by Alonski** [comment]
Hmm it is on a private app that I can't share. I just upgraded from 7.8.0 to 7.8.3 and started seeing compile time errors. Weird I know :)

**Comment by nicolo-ribaudo** [comment]
Also, this PR only changes tests and moves some packages to a different repository. It doesn't change the contents of any published package :thinking:

**Comment by Alonski** [comment]
Hmm maybe it's not this PR then. 😅 I'll check again tomorrow and jump minors one by one

**Pull request merged**
