### PR TITLE
Remove strict toggling wildcard interop

### PR DESCRIPTION
**Pull request by loganfsmyth**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues             | Fixes #5429 
| Patch: Bug Fix?          | 
| Major: Breaking Change?  | 
| Minor: New Feature?      | 
| Tests Added/Pass?        | 
| Spec Compliancy?         | 
| License                  | MIT
| Doc PR                   | 
| Any Dependency Changes?  | 

Ported #5429 over to the new reimplementation of the module transform, with some extra.

* Added one other small change, which was to remove the the `strict` flag's trigger for removing `use strict` since that now recommended to be done with `strictMode: false` if you want it.
* Deleted some useless code from `transform-strict-mode` that is left over from before my refactor.

### CODE REVIEW

**Comment by benjamn** [comment]
Thanks for flagging this as a breaking change! It was indeed, though easily fixed.

**Comment by loganfsmyth** [comment]
@benjamn There will probably be more stuff like this in the coming weeks. I'd really recommend that if you're using the Beta, you should lock to a specific version rather than a range.

**Comment by benjamn** [comment]
Everything in Meteor is locked to exact versions. I was deliberately trying to upgrade to the latest beta, so no surprise there.

**Comment by loganfsmyth** [comment]
Perfect :D

**Pull request merged**
