### PR TITLE
TypeScript 4.0: Allow spread in the middle of tuples

### PR DESCRIPTION
**Pull request by nicolo-ribaudo**
| Q                        | A 
| ------------------------ | ---
| Patch: Bug Fix?          |
| Major: Breaking Change?  |
| Minor: New Feature?      | Yes
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

https://devblogs.microsoft.com/typescript/announcing-typescript-4-0-beta/#variadic-tuple-types

Example:
```js
type Strings = [string, string];
type Numbers = [number, number];

// [string, string, number, number]
type StrStrNumNum = [...Strings, ...Numbers];
```

Note: currently the node is called `TSRestType` and not `TSSpreadType`. I _think_ we should rename it in the future.

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/11753"></a>

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
@weswigham @ahejlsberg anything special here? Looks reasonable to me

**Comment by weswigham** [comment]
Only question I'd have is if this plays well with the labeled tuple member support.

**Comment by nicolo-ribaudo** [comment]
> Only question I'd have is if this plays well with the labeled tuple member support.

There is a disable test in the other PR to test the integration between these :+1:

**Comment by nicolo-ribaudo** [comment]
I'm merging this to a `feat-7.11.0/ts-4.0` branch so that we can test the PRs together before merging them to `main`.

**Pull request merged**
