### PR TITLE
Update babel-core options

### PR DESCRIPTION
**Pull request by xtuc**
| Q                        | A 
| ------------------------ | ---
| Patch: Bug Fix?          | 
| Major: Breaking Change?  | 
| Minor: New Feature?      | 
| Deprecations?            | 
| Spec Compliancy?         | 
| Tests Added/Pass?        | 
| Fixed Tickets            |
| License                  | MIT
| Doc PR                   | yes 
| Dependency Changes       | 

PassPerPreset options is missing in the documentation.

### CODE REVIEW

**Comment by hzoo** [comment]
At the time, we wanted to keep it not documented since we wanted to change it anyway. it should of been a option per preset itself to say if it should have it's own pass rather than making all presets per pass

**Comment by xtuc** [comment]
Ok, I see. I saw it after a discussion on Slack.

I think this would help people with ordering issues. I can mark it as beta or tell that the usage may change in the future. What do you think?

**Comment by hzoo** [comment]
dono if you saw the original discussion on this https://github.com/babel/babel/pull/3281 and then https://github.com/babel/babel/commit/851ed6e6a5d4a5e26ab2959fda614fc6716435d2 lol

**Comment by hzoo** [comment]
Let's not do this since it will prob be deprecated (and has bugs atm)

**Pull request closed without merging**
