### PR TITLE
Babylon understands CSS

### PR DESCRIPTION
**Pull request by krasimir**
Hello everyone,

This PR introduces a new plugin to [babylon](https://github.com/babel/babel/tree/master/packages/babylon) called CSSX. It helps us writing vanilla CSS in JavaScript similarly like we do with HTML and JSX. There were couple of design decisions that I had to take to make this possible. Here is a quick example:

```
cssx(
  .selector > p {
    margin: 10px
  }
)
```

Is translated to the following AST:

```json
{
  "type": "Program",
  "sourceType": "script",
  "body": [
    {
      "type": "CSSXDefinition",
      "body": [
        {
          "type": "CSSXElement",
          "selector": {
            "type": "CSSXSelector",
            "value": ".selector > p"
          },
          "body": {
            "type": "CSSXRules",
            "body": [
              {
                "type": "CSSXRule",
                "label": {
                  "type": "CSSXProperty",
                  "name": "margin"
                },
                "body": {
                  "type": "CSSXValue",
                  "name": "10px\n "
                }
              }
            ]
          }
        }
      ]
    }
  ]
}
```
I skipped pasting some meta information like the location of the nodes and the tokens but that's how roughly the AST looks like.

One of the biggest issues that I had doing that plugin was the entry point. With JSX this is kinda clear because HTML is really different compared to JavaScript. However, we have some similarities between CSS and JSON. For example:

```css
var style = {
  margin: 0;
  padding: 0;
}
```

While reading tokens it is not clear what we have till we parse the whole block, which I think will be an overkill. Especially if we have a big chunk of CSS. We have to look so many tokens in the *future*. So I decided to wrap the css in `cssx(...)` expression. Everything inside is considered a CSSX syntax.

Another interesting bit was the *dynamic* expressions. In JSX we have `{...}` where we place a valid JavaScript. In CSSX this is problematic because we have lots of curly brackets around the styles. It was difficult keeping this syntax as an option so I came up with ``...``. Example:

```
cssx(
  `a+b`-top {
    margin: 10px;
  }
)
```
Which is then transpiled to:
```js
(function () {
  var _2 = {};
  _2['margin'] = '10px';
  var _1 = cssx('_1');
  _1.add(a + b + "-top", _2);
  return _1;
}.apply(this))
```

I'm currently using CSSX supported version of babylon in this project [https://github.com/krasimir/cssx](https://github.com/krasimir/cssx) where we have a transpiler of code containing CSSX expressions. A quick demo of how it works in browsers may be seen [here](http://krasimir.github.io/cssx/). Or there is a repl available at this address [http://krasimir.github.io/cssx/playground/try-it-out/](http://krasimir.github.io/cssx/playground/try-it-out/) where you could see the produced AST, JavaScript and the CSS.

The plugin is developed strictly following the TDD approach. There are ~50 tests that cover different scenarios which could be run with `TEST_ONLY=babylon make test-only`. They pretty much show the exact syntax and all problematic cases which I hit during development.

Let me know if you need more information. I know that it's a really fat PR and it's difficult to review all the changes. Sorry about that, I just wanted to have a working prototype.

### CODE REVIEW

**Comment by eventualbuddha** [comment]
Interesting. I wonder about the choice to use what appears, at first, to be a valid binding identifier as the caller of a function call as the entry point. Might it be better to use something that would not otherwise be syntactically valid?

**Comment by hzoo** [comment]
Wow ya that's interesting. Have you checked out some of the css parsers in http://astexplorer.net/ as well?

**Comment by krasimir** [comment]
@eventualbuddha 
Well, I was thinking a lot about that. Syntactically invalid entry point looks strange. I didn't find anything which made sense to me and at the same time is not in a conflict with some existing syntax/feature. A good example for that is how I'm handling the dynamic parts of the CSS. For example:

```
var bodyColor = '#FFF';
var sheet = cssx(
  body {
    color: `bodyColor`;
  }
);
```
I'm definitely not happy with this syntax and I'm considering moving to `{{...}}`.

--- 
@hzoo I think I landed on this site at some point. The thing is that I had some specific ideas about syntax and usage. I was also interested to see how babel works. Babylon is indeed one of the few ast generators that allow extending.

**Comment by kittens** [comment]
This is really really cool but I don't think it's something we'll want to have in Babel core. I have some free time next week so I might work on prototyping an extensible parser. Once that happens we can move the Flow and JSX plugins into userland and this can exist with them (whether in the monorepo or separately).  I'll ping a few people to get some feedback before we make a decision. Thanks for putting this together @krasimir, it's definently super interesting. Would love your feedback on how to make the parser more pluggable if that's the direction we decide to move in too.

**Comment by kittens** [comment]
One thing that's concerning is the amount of syntax ambiguity. This would also be very difficult to syntax highlight with traditional lexers that code editors use. Have you thought about prefixing CSSX with a contextual keyword? Something like

```javascript
cssx {
  .foo {
    color: red;
  }
}
```

Although the semantics of that seem confusing, does `cssx` refer to a local binding? How do you change it to reference a different one? etc.

**Comment by iamstarkov** [comment]
maybe this pull-request can benefit from [PostCSS](http://postcss.org/) — pretty impressive css parser

**Comment by kittens** [comment]
I think CSSX also begs the question, why not just used a tagged template literal and compile it away in a Babel plugin?

**Comment by jmm** [comment]
> Have you thought about prefixing CSSX with a contextual keyword? Something like

Maybe you could hijack labeled statements in a situation like this. But more importantly: 

> I think CSSX also begs the question, why not just use a tagged template literal and compile it away in a Babel plugin?

That's what I was thinking too. Seems like a much cleaner way to embed a new arbitrary syntax within JS and doesn't require any support by the parser.

**Comment by kittens** [comment]
I guess if you use template literals you don't have a CSSX AST so you can't write transforms for it.

**Comment by krasimir** [comment]
I'll prepare a proper response of the comments above tomorrow morning but Sebastian is right. Using a template literal doesn't provide ast. And having ast we may do all kind of stuff.

**Comment by lukeapage** [comment]
What about instead extending jsx to pick out style tags and treat them specially?

**Comment by krasimir** [comment]
I think we should start from the very beginning. Before actually jumping to the transpiler step I was prototyping CSSX and wanted to clarify what exactly I want from it. 

* It's not only having CSS string in JavaScript and be able to replace bits with variables. That's I think doable with template literals and it's already done [here](https://github.com/rtsao/csjs).
* I didn't want an inline styling. We already have that in React and there are couple of issues around it. We are targeting only one element. There are things which can not be applied with inline styling like media queries and pseudo classes.

So, the truth is that we need a complete access to CSS stylesheet. We need an API that allows us creating one and manipulate the styles inside. I started from there. That's how [CSSX client-side library](https://github.com/krasimir/cssx/tree/master/packages/cssx) was born. It's something like React's `cx` utility but with broader view. Really short example:

```js
var sheet = cssx();
var fontSize = 20;

var body = sheet.add('body', {
  'font-size': fontSize + 'px',
  'line-height': fontSize * 1.2 + 'px'
});
body.d('p', { // d = descendant
  'color': '#BADA55'
});
```
Produces the following CSS:
```css
body {
  font-size: 20px;
  line-height: 24px;
}
body p {
  color: #BADA55;
}
```

This is again not something new. There are plenty of modules that are converting valid JavaScript to CSS. The question is what we are going to do with this CSS. CSSX library is automatically creating a `<style>` tag and injecting the generated CSS. So if we change something in our JavaScript stylesheet we get this applied to the page immediately (well, not immediately but in the next tick). That's how I imagine the CSS in JavaScript. I don't want to deal with CSS strings and inlineing them to my DOM elements or manually injecting the same string to the page.

Once I implemented my css-in-javascript ideas I was able to write *living* stylesheets. Stylesheets that change based on JavaScript logic:

```js
var sheet = cssx();
var form = sheet.add('form');
var btn = form.d('input[type="submit"]', { opacity: 1 });

var disableButton = function () {
  btn.update({ opacity: 0.4 });
};
var enableButton = function () {
  btn.update({ opacity: 1 });
}
```

The CSS is updated at runtime and it's not statically loaded file. I'm saying that because there are other modules that indeed provide CSS in JavaScript but they act more like preprocessors. Which is not what I wanted.

And here is where Babylon comes handy. As you can see writing selectors and CSS rules in a JavaScript-ish way is frustrating. It takes time and it is not as simple as vanilla CSS. Having the library I started thinking about the syntax. That's why @kittens I decided to use `cssx( ... vanilla css here ...)` and not `cssx { ... vanilla css here ... }`. Mainly because it's easy to think "Oh, that's a function that accepts my styles" and not "I have to annotate this object expression with `cssx` in front". Or at least that was my feeling.

Of course I thought that using ES6 string templates will be a good idea.

```
var sheet = cssx(`
  body {
    margin-top: 1px;
  }
`);
```

Fine, that's working but I'm missing the *units*. I don't have rules, properties and values anymore. Just one string. One of the characteristics of CSSX is granularity. It gives us access to every CSS actor - selector, rules set, property and value. So it was clear, I needed AST and transpilation process. The CSSX client library was still working though. But it wasn't nice using it.

I did the basic CSS-in-JavaScript parsing. The next move was to generate valid JavaScript from the AST. And now it gets interesting. To make the things working I had to keep the current scope so if we place CSSX expression in a function it gets an access to the proper variables. Here is where I started treating the CSSX expression differently. A couple of examples:

```
var font = 'Helvetica';
var styles = cssx({
  font-family: `font`;
});

// it's transpiled to

var font = 'Helvetica';
var styles = (function () {
  var _2 = {};
  _2['font-family'] = font;
  return _2;
}.apply(this));

// or in other words it's producing 
// a simple object literal
```

```
var font = 'Helvetica';
cssx(
  body {
    font-family: Helvetica;
  }
);

// it's translated to

var font = 'Helvetica';
(function () {
  var _4 = {};
  _4['font-family'] = 'Helvetica';

  var _3 = cssx('_3');

  _3.add('body', _4);

  return _3;
}.apply(this))

// it's producing a cssx stylesheet
// and returns the stylesheet
```

```
var styles = {
  font: 'Helvetica',
  applyStyles: cssx(
    body {
      font-family: `this.font`;
    }
  )
}

// it's translated to

var styles = {
  font: 'Helvetica',
  applyStyles: function () {
    var _5 = {};
    _5['font-family'] = this.font;

    var _4 = cssx('_4');

    _4.add('body', _5);

    return _4;
  }
};

// It's not creating the stylesheet immediately
```

```
sheet().add(cssx(
  body {
    font-size: 20px;
    margin: 0;
  }
));

// is translated to

sheet().add((function () {
  var _5 = {};
  _5['margin'] = '0';
  _5['font-size'] = '20px';
  return [['body', _5]];
}.apply(this)));

// this was needed because we don't want
// to create a new stylesheet every time
// but still use vanilla CSS
// while registering multiple rules
```

(There is a [repl](http://krasimir.github.io/cssx/playground/try-it-out/) where you can try all these stuff and see the produced JavaScript)

I barely scratched the possibilities here. Having an access to every piece of CSS means that we are able to transform it in a really smart way. One of the first things that I did was defining custom CSS properties:

```
var sheet = cssx();

sheet.define('look', function (type) {
  switch (type) {
    case 'button':
      return cssx({
        display: block;
        font-size: 20px;
        color: #F00;
      });
    break;
    case 'link':
      return cssx({
        display: inline;
        font-size: 18px;
        color: #000;
      });
  }
});

sheet.add(cssx(
  form .btn {
    look: button;
  }
  form > a {
    look: link;
  }
));
```

If we run this code we'll get:

```
form .btn {
  color: #F00;
  font-size: 20px;
  display: block;
}
form > a {
  color: #000;
  font-size: 18px;
  display: inline;
}
```

Imagine how nice will be to define your own CSS properties made specifically for your project. As far as I know it is not really possible with string template literal.

---

Sorry for the looooong comment @kittens @hzoo @eventualbuddha @iamstarkov @jmm @lukeapage but I think I had to bring more light on the subject and clarify what were my initial ideas and what really stands behind CSSX in my head. 

What's next? Well, I'm trying to get rid of the weird syntax around the dynamic parts. I mean

```
cssx(
  font-`size` {
    font-size: `size`px;
  }
)
```

And maybe use double curly brackets

```
cssx(
  font-{{size}} {
    font-size: {{size}}px;
  }
)
```

Yes, I know that there are way many brackets but it's close to JSX and some popular template engines.

**Comment by jmm** [comment]
@krasimir I'm just skimming this, so I might not totally "get" it (and TBH I find the code examples pretty confusing). Even if Babylon supported extension, I'm not sure I understand the purpose of shoehorning CSS parsing into a JS parser, unless you just didn't think there was a better way. (I know that JSX doesn't set a good example here.)

> Fine, that's working but I'm missing the units. I don't have rules, properties and values anymore. Just one string. One of the characteristics of CSSX is granularity. It gives us access to every CSS actor - selector, rules set, property and value. So it was clear, I needed AST and transpilation process.

I think this is going to make more sense as 2 separate pieces:

1. Be able to embed CSS (or some variation on it) within the JS to get it past the parser. This is where the template literals come in.

2. Manipulate the CSS however you want -- e.g. parse and transform it, ultimately to JS AST that is inserted into the original script's AST.

Wouldn't something like this be a lot simpler (this is just a quick outline)?:

```js
// A Babel plugin
function cssx () {
  var visitor = {};
  var plugin = {visitor: visitor};

  visitor.TaggedTemplateExpression = function (path, state) {
    if (path.node.tag.name !== "cssx") return;
    path.replaceWith(/*
      Do whatever. Utilize the AST or raw source here in whatever fashion --
      parse the source to an AST with a CSS or bespoke parser if you want and
      manipulate it. In the end replace the template literal node with JS AST
      representing whatever you want.
    */);
  };

  return plugin;
}
```

```js
// Sample input
var sheet = cssx();

sheet.define('look', function (type) {
  switch (type) {
    case 'button':
      return cssx`
        display: block;
        font-size: 20px;
        color: #F00;
      `;
    break;
    case 'link':
      return cssx`
        display: inline;
        font-size: 18px;
        color: #000;
      `;
  }
});

sheet.add(cssx`
  form .btn {
    look: button;
  }
  form > a {
    look: link;
  }
`);
```

I think pursuing an approach like this probably makes far more sense than trying to make the JS parser be able to recognize CSS -- even if Bablyon was extendable.

With this it might make sense to use the native template literal interpolation syntax for your variables:

```js
var bodyColor = '#FFF';
var sheet = cssx`
  body {
    color: ${bodyColor};
  }
`;
```

**Comment by krasimir** [comment]
@jmm I'm not 100% sure that I can achieve the same thing with template literals. I see your points and they seem valid though. But let's see.

1. We pass the following to Babel:
```
var sheet = cssx`
  body {
    font-size: ${size}px;
  }
`
```
2. In the plugin I have an access to the string 
```
body {
  color: ${size}px;
}
```
I can't send this to a CSS parser because it has no idea about `${size}`. In my Babel plugin I do know about the expressions but I have no idea about the CSS AST nodes. And I can't replace `size` with the actual value because I want this to be a runtime executable logic. For sure I can think about the expressions as placeholders and once I get the CSS AST I traverse it and do the proper transformation. Maybe it will be a little bit tricky but it's possible. 

I may be wrong but your approach involves babylon too. Today I anyway need to use it for understanding the template literals. So I guess I didn't see your solution and it I didn't want to miss the fun learning how Babylon works in details.

**Comment by jmm** [comment]
@krasimir 

> I can't send this to a CSS parser because it has no idea about ${size}

I understand, but I think it'd probably be a lot easier to start from the perspective of parsing CSS and figure out a way to deal with expression placeholders than to start from the perspective of parsing JS. If you're going to parse the CSS to an AST to transform it to a JS AST then you can just use any placeholder that'll parse as CSS and then substitute it in the JS AST I'd think.

> In my Babel plugin I do know about the expressions but I have no idea about the CSS AST nodes. And I can't replace size with the actual value because I want this to be a runtime executable logic. For sure I can think about the expressions as placeholders and once I get the CSS AST I traverse it and do the proper transformation. Maybe it will be a little bit tricky but it's possible.

Yeah, you can basically do whatever you want here. One way or another there are going to be expression placeholders, right? In the Babel plugin you have access to the raw source and AST for the template string. If you use the native interpolation syntax (`${x}`) then Babel will have already separated the static content from expression placeholders for you. Or you can use whatever placeholder format you want and deal with it however you like. I think this gives you a lot to work with.

> I may be wrong but your approach involves babylon too. Today I anyway need to use it for understanding the template literals.

I'm not positive I know what you mean. Yes, this relies on Babylon under the hood to parse the template literals, but it requires no changes to Babylon -- at the top level the code is just JS. Then the rest can be done independently.

> I didn't want to miss the fun learning how Babylon works in details.

No doubt! I'm sure it's a great exercise if that's your goal. But as noted here it's very unlikely to actually be merged.

**Comment by krasimir** [comment]
@jmm I'm completely fine to not merge this PR. I understand that the CSS plugin here is strongly opinionated. It's a syntax that works for me and will probably not fit everywhere. It was important to me to get some feedback though which already happened :) I'll probably continue basing my CSSX project on babylon working with the fork in my account. Of course if babylon becomes *more* plugable I'll be happy to extract my plugin to a separate repo.

**Comment by krasimir** [comment]
Just to mention that I amended the plugin so it supports `<% ... %>` and `{{ ... }}` of the expressions inside CSSX. For example:

```
var sheet = cssx(
  .hero {
    font-size: <% heroFontSize %>em;
  }
);
```

**Comment by davidtheclark** [comment]
All the justifications above for having access to an AST of the CSS (e.g. transformation possibilities are limitless) are the reasons that PostCSS exists and is thriving. I think it would be a mistake to try to introduce into Babel a new, Babel-specific CSS parser that won't be as capable as PostCSS, won't be able to use PostCSS plugins, etc.

**Comment by krasimir** [comment]
@davidtheclark I really like the idea of PostCSS. I'm even using it in production. However, the purpose of this PR (of CSSX) is to write CSS inside JavaScript. This CSS is transformed to a JavaScript that's executed at runtime. It's not about postproduction. CSSX is also meant to be used for styling dynamic parts of the page. All the initial CSS that is needed for the first render should be delivered as a static file and not part of the JavaScript bundle.

**Comment by krasimir** [comment]
Closing this PR since Babylon is now moved out to its own [repo](https://github.com/babel/babylon). There is a CSSX plugin for the parser [here](https://github.com/krasimir/babylon-plugin-cssx) however the API of Babylon (as it is right now) does not allow registration of an external plugin. There is a dedicated [PR](https://github.com/babel/babylon/pull/5) for that.

**Pull request closed without merging**
