### PR TITLE
Remove charcodes from package as it is already in root

### PR DESCRIPTION
**Pull request by danez**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | 
| Patch: Bug Fix?          | n
| Major: Breaking Change?  | n
| Minor: New Feature?      | n
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

### CODE REVIEW

**Comment by danez** [comment]
I guess flow just simply does the same that node does and traverses up the hierarchy until it finds the package.

**Comment by loganfsmyth** [comment]
Perhaps it would be better to move that plugin into `babel-parser` itself and load it via a `.babelrc`?

**Comment by nicolo-ribaudo** [comment]
> Perhaps it would be better to move that plugin into babel-parser itself and load it via a .babelrc?

I find it easier to have all the config in one file. Is it such a big deal if this package is added both at the top-level and in `@babel/parser`? It is a devDep anyway, and probably it will be hoisted by lerna.

**Comment by danez** [comment]
The main problem what I did this was that the version in the root package.json was updated, but not the one in the package. So we were installing two different versions.

**Comment by nicolo-ribaudo** [comment]
Oh ok. I'm ok with both with removing the top-level dep or the one in babel/parser then.

**Comment by loganfsmyth** [comment]
I think, since the parser references it, it should be in the parser. I don't really care where the plugin lives. If it's in the root, I'd code to load `charcodes` from the parser package maybe by doing `require("./packages/babel-parser/node_modules/charcodes")` or using the npm `resolve` package with `basedir: "packages/babel-parser"`.

**Pull request closed without merging**
