### PR TITLE
Add support for the "Hack" pipeline proposal (#13191)

### PR DESCRIPTION
**Pull request by nicolo-ribaudo**
- [x] Add support for the "Hack" pipeline proposal (#13191)
- [x] Implement `topicToken: "%"` for Hack pipes (#13416)
- [x] Fix `%==` parsing in hack pipes (#13536)
- [x] Support hack pipeline in `@babel/standalone` (#13555)

## :warning: Use "Rebase and Merge"!

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/13413"></a>

### CODE REVIEW

**Comment by nicolo-ribaudo** [comment]
@js-choi I rebased this branch to fix the CI failure.

Could you rebase https://github.com/babel/babel/pull/13416 on top of this? You might need to do an interactive rebase to make sure not to duplicate the two commits already in this branch.

**Comment by js-choi** [comment]
I made a merge in 91d28f91e6ec7ecd7688fc88c8c19cb369da556c; is that okay?

**Comment by js-choi** [comment]
@nicolo-ribaudo: I have squashed and rebased #13416 onto this branch. 

After #13416, there will need to be one more pull request to apply `BABEL_8_BREAKING` to the deprecated smart-mix pipes.

**Comment by js-choi** [comment]
The feat-7.15.0/hack-pipes branch now has conflicts with the main branch. Should I make another pull request (based on #13488, which in turn is based on #13416) that resolves the conflicts?

**Comment by nicolo-ribaudo** [comment]
@js-choi I just merged your second PR and I'll rebase this to solve the conflicts. It's unlikely that your next PR will be merged before Babel 7.15.0, so unless you need to rebase it for some reason you could wait until this is merged to `main`.

The next PR (the one that disables the smart proposal for Babel 8) can even be merged in a patch anyway.

**Comment by js-choi** [comment]
@nicolo-ribaudo: Sounds good; thank you for reviewing and rebasing. As you say, the smart-mix deprecation PR can be put in v7.15.1 or whatever, but is this PR still on track for 7.15.0?

**Comment by nicolo-ribaudo** [comment]
Yes exactly. Smart mix will be removed behind a build-time flag that we'll toggle in Babel 8, so it doesn't matter when we merge it.

**Pull request merged**
