### PR TITLE
Only include necessary files in npm package [babel-core]

### PR DESCRIPTION
**Pull request by locks**
Motivation: https://github.com/babel/broccoli-babel-transpiler/issues/90

### CODE REVIEW

**Comment by hzoo** [comment]
We already have an npmignore file and I don't think we would want to include src because we transpile to lib which is what is already there?

**Comment by locks** [comment]
Hm, my bad then. I wonder where the 3257 count comes from in that case.

**Comment by hzoo** [comment]
babel-core has a lot of dependencies itself if you mean everything in node_modules

**Comment by hzoo** [comment]
Yeah we would have to check all of our own deps as well

**Pull request closed without merging**
