### PR TITLE
Fix default export with arrows and function naming

### PR DESCRIPTION
**Pull request by danharper**
| Q                 | A
| ----------------- | ---
| Bug fix?          | yes
| Breaking change?  | no
| New feature?      | no
| Deprecations?     | no
| Spec compliancy?  | no
| Tests added/pass? | yes
| Fixed tickets     | #4377, #4182, #4430
| License           | MIT
| Doc PR            | -

Default arrow function exports, with `transform-es2015-arrow-functions` and `transform-es2015-function-name` (or, just the `es2015` preset) results in loss of the default export.

* `function-name` [renames existing clashing identifiers](https://github.com/babel/babel/blob/5b89849f432cfc034860f495b5001039123e7754/packages/babel-helper-function-name/src/index.js#L54-L54) when adding a function name.
* When renaming, it attempts to [separate export declarations](https://github.com/babel/babel/blob/c3ccddaaaf5c1d752c31ec652b174f6661c9a47e/packages/babel-traverse/src/scope/lib/renamer.js#L110).
* In doing so, as the transpiled arrow function has no name, the default export node gets [changed to a named export which has no name](https://github.com/babel/babel/blob/c3ccddaaaf5c1d752c31ec652b174f6661c9a47e/packages/babel-traverse/src/scope/lib/renamer.js#L52-L68).

In the tests, I've only added ones for the CJS output as that's what I was originally trying to solve. This actually affects all module formats. I can follow up with duplicate tests for each module system if you'd like.

---

Minimal reproduction of the issue:

```json
{
  "plugins": [
  	"transform-es2015-function-name",
  	"transform-es2015-shorthand-properties",
  	"transform-es2015-arrow-functions"
  ]
}
```

```js
export default (a) => {
  return { a() { return a } };
}
```

```js
(function (_a) {
  return {
    a: function a() {
      return _a;
    }
  };
};

export {}
```

### CODE REVIEW

**Comment by danez** [comment]
Thank you. If you can easily reproduce this bug with amd and umd, then it would be nice to have a simple test for each of the module-systems.
I had a look at the code, but haven't had a look before at renamer, so going to debug a little bit, so I understand what it is doing.

**Comment by danharper** [comment]
👍 will do, just wanted to check this is the correct approach first.

An alternative approach is to transpile arrow functions whose parent is an `ExportDefaultDeclaration` into a `FunctionDeclaration` instead of a `FunctionExpression`. At which point, the renamer will ensure it [has a name of `_default`](https://github.com/babel/babel/blob/e64d86c1eb991a5b71c8ac0b70b5806d46eb83c9/packages/babel-traverse/src/scope/lib/renamer.js#L46-L48). Then we don't need to check for `specifiers.length`, as the arrow _will_ have a name.

```js
function _default(_a) {
  return {
    a: function a() {
      return _a;
    }
  };
}
exports.default = _default;
```

**Comment by danharper** [comment]
**However**, looking into it more, the code giving default exports a name was introduced here: https://github.com/babel/babel/pull/3134, which seems to be the same issue this is resolving

> it was inserting a standalone `export {}`

If I remove [that code](https://github.com/babel/babel/blob/e64d86c1eb991a5b71c8ac0b70b5806d46eb83c9/packages/babel-traverse/src/scope/lib/renamer.js#L46-L48), everything continues to work with my changes, just the associated test case changes to not be a separate statement:

```diff
 "use strict";
 
 Object.defineProperty(exports, "__esModule", {
   value: true
 });
+ exports.default = function () {
- function _default() {
   return function () {
     function Select() {
       babelHelpers.classCallCheck(this, Select);
     }
 
     babelHelpers.createClass(Select, [{
       key: "query",
       value: function query(_query) {}
     }]);
     return Select;
   }();
 }
-
- exports.default = _default;
```

(I'll check tonight how that works with class declarations, too.)

**Comment by hzoo** [comment]
The regression was https://github.com/babel/babel/issues/4228 with example code: `export const state = (state) => state.a`

**Comment by danharper** [comment]
Yeah, that was a regression from a previous attempted fix for exported arrows, which got reverted.

**Comment by hzoo** [comment]
This is great thanks!!

**Pull request merged**
