### PR TITLE
Fix TypeError with babel-register's cache

### PR DESCRIPTION
**Pull request by xtuc**
| Q                        | A 
| ------------------------ | ---
| Patch: Bug Fix?          | yes
| Major: Breaking Change?  | 
| Minor: New Feature?      | 
| Deprecations?            | 
| Spec Compliancy?         | 
| Tests Added/Pass?        | 
| Fixed Tickets            | #5259  
| License                  | MIT
| Doc PR                   | 
| Dependency Changes       | 

Follow up from #5259.

### CODE REVIEW

**Comment by xtuc** [comment]
I took this opportunity to add some tests to babel-register's cache. It is quite difficult to do.

Could you tell me what do you think about this test suite. Should we modify the code to make it more testable?

**Comment by existentialism** [comment]
Funny enough, the reason the tests fail during the coverage run is because `nyc` sets [`BABEL_DISABLE_CACHE=1`](https://github.com/istanbuljs/nyc/blob/1022b1607eca9cf8a1b4f4d805744113badd8764/bin/nyc.js#L4) 😆

**Comment by xtuc** [comment]
Oh, you're right :+1: Thanks for pointing out this to me.

**Comment by hzoo** [comment]
Nice work both of you!

**Pull request merged**
