### PR TITLE
Fix issue to allow module block in member expression

### LINKED ISSUE #13533: [Bug]: Module block should be allowed in member expression
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```js
module {}.foo
```

[AST Explorer](https://astexplorer.net/#/gist/db4b1a51b7645517f2a3c2f9690fbd6b/447c886c9745c468c1774b4e3dbe126d188e3520)

### Configuration file name

_No response_

### Configuration

_No response_

### Current and expected behavior

Current: Parsing fails
Expected: Parsing succeeds

According to the [spec](https://github.com/tc39/proposal-js-module-blocks#syntax-details), InlineModuleExpression (`module {}`) is a primary expression, so it should be allowed before the `.` in a member expression.

### Environment

- Babel versions: 7.14.5

### Possible solution

The module block is parsed in `Parser#parseMaybeUnary`

https://github.com/babel/babel/blob/bc1b9537b00499f462aa3ac0d49e30314a66f413/packages/babel-parser/src/parser/expression.js#L511-L517

which aligns to the [UnaryExpression](https://tc39.es/ecma262/#prod-UnaryExpression) in the spec. It should be moved to `Parser#parseExprAtom`, which handles PrimaryExpression.

https://github.com/babel/babel/blob/bc1b9537b00499f462aa3ac0d49e30314a66f413/packages/babel-parser/src/parser/expression.js#L971

Specifically we can extend the current logic for `tt.name` token and handle the `module {}` checks here: https://github.com/babel/babel/blob/bc1b9537b00499f462aa3ac0d49e30314a66f413/packages/babel-parser/src/parser/expression.js#L995 

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by nme077**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #13533 
| Patch: Bug Fix?          | 👍
| Major: Breaking Change?  | No
| Minor: New Feature?      | No
| Tests Added + Pass?      | 👍
| Documentation PR Link    | 
| Any Dependency Changes?  | No
| License                  | MIT

Moved the logic to check for `module {} ` in babel-parser from `Parser#parseMaybeUnary` to `Parser#parseExprAtom` within the  `tt.name` token.

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/13573"></a>

### CODE REVIEW

**Review by JLHwung — APPROVED** [review]
Not a blocker: After this PR, we can further remove the `module` lookahead. Like how we are handling `async function` and `async x =>`, we can parse the `module` as an `id` and when we see a left curly brace, we can reuse the `id` node and then finished as a `ModuleExpression`.

**Comment by nicolo-ribaudo** [comment]
Can you delete the `package.tgz` file? I think you added it by accident.

**Comment by nme077** [comment]
@nicolo-ribaudo done. I removed the `package.tgz` file.

**Review by nicolo-ribaudo — APPROVED** [review]
Thanks!

**Comment by JLHwung** [comment]
The CI error is unrelated and has been fixed in #13567.

**Pull request merged**
