### PR TITLE
Remove babel-standalone

### PR DESCRIPTION
**Pull request by jridgewell**
This reverts #6029 due to issues in #6120.

We need to first move `babel-loader` into the monorepo (and update its
dependencies on `babel-core`). Afterwards, we can re-add
`babel-standalone`.

### CODE REVIEW

**Comment by Daniel15** [comment]
Ahh, this is unfortunate :( Can we just comment out the build for now rather than completely deleting it? Just have it sit there until fixed. Would it be easy to move babel-loader into the monorepo?

**Comment by jridgewell** [comment]
> Can we just comment out the build for now rather than completely deleting it? 

We could do it that way, but is there a reason? It should be as simple as `git revert #6135` to put this back in after we get `babel-loader`.

> Would it be easy to move babel-loader into the monorepo?

That'd be a question for @danez.

**Comment by Daniel15** [comment]
> is there a reason?

Mainly thrash, and the fact that we want to move babili-standalone (now babel-minify-standalone) into the minify repo, and it'll reuse the shared Gulp tasks. There's also some tooling that relies on the babel-standalone builds now (like the REPL previews) so if possible I'd rather roll forwards instead of back.

Is the issue just that babel-loader's Babel reference is not lenient enough? If so, can I simply make my own fork of babel-loader to fix it?

**Comment by Daniel15** [comment]
I have some ideas for potentially fixing this. If the issue is with the
wrong version of Babel-core being bundled, we can use a custom Webpack
resolver plugin that *always* prefers the monorepo version. I'll play with
some ideas today.

**Comment by jridgewell** [comment]
> we can use a custom Webpack resolver plugin that *always* prefers the monorepo version

If you can get that to work, then perfect.

**Comment by danez** [comment]
Couldn't you simply set a `resolve.alias` in the webpack config to point to the correct babel-core instance? https://webpack.js.org/configuration/resolve/#resolve-alias

**Comment by Daniel15** [comment]
That sounds promising. I'll see if we can alias the Babel packages. I'm
still not 100% sure exactly what is broken so I'm going to try to replicate
the issue.

**Comment by Daniel15** [comment]
Hmm, this is super tricky. It's not actually a Webpack issue, it's a Node.js module resolution problem. Here's the stack trace I'm seeing:
```
Module build failed: Error: [BABEL] C:\src\babel\packages\babel-standalone\src\index.js: You gave us a visitor for the node type "PrivateName" but it's not a valid type
    at verify (C:\src\babel\node_modules\babel-core\node_modules\babel-traverse\lib\visitors.js:156:13)
    at Function.explode (C:\src\babel\node_modules\babel-core\node_modules\babel-traverse\lib\visitors.js:59:3)
    at instantiatePlugin (C:\src\babel\node_modules\babel-core\lib\config\option-manager.js:304:27)
    at loadPluginDescriptor (C:\src\babel\node_modules\babel-core\lib\config\option-manager.js:280:14)
    at C:\src\babel\node_modules\babel-core\lib\config\option-manager.js:73:14
    at Array.map (native)
    at OptionManager.mergeOptions (C:\src\babel\node_modules\babel-core\lib\config\option-manager.js:72:34)
    at C:\src\babel\node_modules\babel-core\lib\config\option-manager.js:100:15
    at Array.forEach (native)
    at OptionManager.mergeOptions (C:\src\babel\node_modules\babel-core\lib\config\option-manager.js:99:15)
    at C:\src\babel\node_modules\babel-core\lib\config\option-manager.js:100:15
    at Array.forEach (native)
    at OptionManager.mergeOptions (C:\src\babel\node_modules\babel-core\lib\config\option-manager.js:99:15)
    at C:\src\babel\node_modules\babel-core\lib\config\option-manager.js:100:15
    at Array.forEach (native)
    at OptionManager.mergeOptions (C:\src\babel\node_modules\babel-core\lib\config\option-manager.js:99:15)
    at C:\src\babel\node_modules\babel-core\lib\config\option-manager.js:100:15
    at Array.forEach (native)
    at OptionManager.mergeOptions (C:\src\babel\node_modules\babel-core\lib\config\option-manager.js:99:15)
    at OptionManager.init (C:\src\babel\node_modules\babel-core\lib\config\option-manager.js:131:14)
    at manageOptions (C:\src\babel\node_modules\babel-core\lib\config\option-manager.js:59:30)
    at loadConfig (C:\src\babel\node_modules\babel-core\lib\config\index.js:20:38)
    at Object.transform (C:\src\babel\node_modules\babel-core\lib\transformation\pipeline.js:48:37)
    at transpile (C:\src\babel\node_modules\babel-loader\lib\index.js:49:20)
    at Object.module.exports (C:\src\babel\node_modules\babel-loader\lib\index.js:174:20)
```

`node_modules\babel-core` is version `7.0.0-alpha.18` from npm (as that's what the root `package.json` references), whereas the version in the repo is `7.0.0-alpha.19`. 

I think you were on the right track in #6132, with some refinement. If we can install `babel-loader` into the `babel-standalone` directory rather than the root, it will use **babel-standalone**'s version of `babel-core` rather than the root version of babel-core, which should fix it (as babel-standalone references the monorepo's version of babel-core)

The other option is to override the Node.js module resolution algorithm (eg. by overriding `Module._load`) and force it to load the right `babel-core` version.

I'll try the easiest approach first and see how I go.

**Comment by Daniel15** [comment]
#6137 should fix this. Thank you so much for the initial investigation, @jridgewell!

**Pull request closed without merging**
