### PR TITLE
Fix printer for explicitly inexact Flow types

### LINKED ISSUE #10040: Flow: losing info about explicitly inexact objects
## Bug Report

**Current Behavior**
Babel is currently losing info about explicitly inexact objects when using Flow parser plugin. It should return the code as is. Thanks for checking it! :)

**Input Code**
This is not possible to reproduce in REPL. Input code:

```js
// @flow strict
  
export type ExplicitlyInexact = { foo: number, ... };
```

Package.json:

```json
{
  "dependencies": {
    "@babel/cli": "^7.4.4",
    "@babel/core": "^7.4.5"
  }
}
```

Command:

```text
yarn babel input.js
```

Output:

```js
// @flow strict
export type ExplicitlyInexact = {
  foo: number
};
```

As you can see, information about the inexact object (` ... `)  is lost.

**Expected behavior/code**
It should return the code as is:

```js
// @flow strict
export type ExplicitlyInexact = {
  foo: number,
  ...
};
```

**Babel Configuration (.babelrc)**

```json
{
  "parserOpts": {
    "plugins": ["flow"]
  }
}
```

**Additional context/Screenshots**
https://medium.com/flow-type/on-the-roadmap-exact-objects-by-default-16b72933c5cf

### PR DESCRIPTION
**Pull request by mrtnzlml**
Closes: https://github.com/babel/babel/issues/10040 🎉 

| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #10040 
| Patch: Bug Fix?          | Yes
| Major: Breaking Change?  | No
| Minor: New Feature?      | No
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  | No
| License                  | MIT

### CODE REVIEW

**Comment by mrtnzlml** [comment]
@nicolo-ribaudo Added. Is this the right way how to do it?

**Comment by mrtnzlml** [comment]
Also, CI failed but doesn't seem to be related (?). It's green when I run locally. Travis seems to be happy as well.

**Comment by existentialism** [comment]
@mrtnzlml restarted it

**Comment by nicolo-ribaudo** [comment]
Yes :+1: I asked for that test because when printing objects we indent, dedent, indent and dedent again.

**Comment by mrtnzlml** [comment]
> I asked for that test because when printing objects we indent, dedent, indent and dedent again.

🤔 I see, is there a way how to avoid my manual indent/dedent?

**Comment by nicolo-ribaudo** [comment]
It is possible to pass an option to `printJoin` to avoid indenting there, and only indent ad the start and at the end of ObjectTypeAnnotation. Anyway, since `.indent()` only does something like `this.indentLevel++`, it's fine as-is.

I'm merging this PR, thank you :smile:

**Comment by mrtnzlml** [comment]
@nicolo-ribaudo Hi, when can we expect this to be released? Seems like it's still not and I just faced this bug again today.

**Pull request merged**
