### PR TITLE
[hotfix][T2765#72428] Wrong  'this'  for nested arrow in arrow function

### PR DESCRIPTION
**Pull request by horpto**

### CODE REVIEW

**Comment by horpto** [comment]
Fix for https://phabricator.babeljs.io/T2765#72428

**Comment by djanowski** [comment]
When will this make it to a release?

**Comment by hzoo** [comment]
Soon, we're thinking of doing a pre-release first (although figuring out how that will work)

**Comment by horpto** [comment]
@hzoo 
Maybe over tags? But each subpackage should be tagged by 'next' tag.

https://medium.com/greenkeeper-blog/one-simple-trick-for-javascript-package-maintainers-to-avoid-breaking-their-user-s-software-and-to-6edf06dc5617#.xlfg6arz0

**Comment by hzoo** [comment]
Yeah definitely with tags just trying to figure out how it works with our monorepo and our publish setup with kittens/lerna.

We should be able to publish all the changed packages as well next tag but how would the dependencies update as well?

**Pull request merged**
