### PR TITLE
Add another con 😞

### PR DESCRIPTION
**Pull request by mischah**
| Q                 | A 
| ----------------- | ---
| Bug fix?          | no
| Breaking change?  | no
| New feature?      | no
| Deprecations?     | no
| Spec compliancy?  | N/A
| Tests added/pass? | N/A
| Fixed tickets     | N/A
| License           | MIT
| Doc PR            | yes
| Dependency Changes| no

Add another con against the usage of monorepos:
Lower ranking in [npms](https://npms.io/) results. At least until [npms-io/npms-analyzer#83](https://github.com/npms-io/npms-analyzer/issues/83) is fixed.

Monorepos aren’t indexed equally because the API Responses from monorepos differs to the response from »normal« repos.

Compare the following two responses.

+ »normal« repo
  + https://api.npms.io/v2/package/generator-http-fake-backend
+ Monorepo
  + https://api.npms.io/v2/package/generator-react-server

The `github` object is missing in case of monorepos.
This object contains properties like `starsCount`, `forksCount`, `contributors`, `statuses` and `issues` which influence all aspects of the npms ranking algorithm. See https://npms.io/about.

### CODE REVIEW

**Comment by hzoo** [comment]
Do we want to leave the ??? haha

**Comment by mischah** [comment]
Oops. I just brought them back.

Let me know if you want me to squash commits.

**Comment by hzoo** [comment]
Can just squash when merging

**Comment by Daniel15** [comment]
I'm surprised npms doesn't properly handle monorepos... I guess they're not as common in the JS world yet, compared to other environments.

**Pull request merged**
