### PR TITLE
WIP - Better error message for duplicated params in arrow functions

### PR DESCRIPTION
**Pull request by rajzshkr**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | https://github.com/babel/babel/issues/6690
| Patch: Bug Fix?          |
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR         | 
| Any Dependency Changes?  |
| License                  | MIT

### CODE REVIEW

**Comment by rajzshkr** [comment]
If Argument name clash is not allowed only in strict mode then we can show a explicit message like `Argument name clash in strict mode`. But it is not allowed in both strict or normal. So I think, it is better to have a generic message for both strict or normal.

**Comment by nicolo-ribaudo** [comment]
Two parameters can't have the same name if they are in strict mode or they are in an arrow function (even if it isn't strict).

**Comment by xtuc** [comment]
It's just me or this is now an empty PR?

Also I like the error message Chrome is throwing: `Duplicate parameter name not allowed in this context`.

**Comment by rajzshkr** [comment]
@xtuc I revert the files. Will update shortly.

**Comment by rajzshkr** [comment]
The main aim of this PR is to show relevant error for arrow function and function declaration if it has argument clash

```
"use strict"; var x = (y, y) => y; // SyntaxError: duplicate argument names not allowed in this context
var x = (y, y) => y; // SyntaxError: duplicate argument names not allowed in this context
"use strict"; function test(x,x){} // // SyntaxError: duplicate argument names not allowed in this context
function test(x,x){} // should not throw any error

// Error message copied from V8
```
So, trying to find a function is arrow is difficult and using this.state.potentialArrowAt is not a reliable flag.

So I'm closing this PR now and work on it later.

**Pull request closed without merging**
