### PR TITLE
Add option to define output directory relative to the input

### PR DESCRIPTION
**Pull request by lgeiger**
**Motivation:**

Monorepos using lerna have the following structure:
```
my-lerna-repo/
  packages/
    package-1/
      src/
        bar/
      lib/
        bar/
    package-2/
      src/
      lib/
```
A lot of repositories using lerna (including this one and [jest](https://github.com/facebook/jest)) have to maintain one big script which compiles the packages.

**Changes in this PR:**

This PR adds a `--relative` option  to `babel-cli` to allow users to define the output directory relative to the input directory:
```bash
> babel packages/**/src --out-dir ../lib --relative
package-1/src/bar/bar1.js -> package-1/lib/bar/bar1.js
package-1/src/foo1.js -> package-1/lib/foo1.js
package-2/src/foo2.js -> package-2/lib/foo2.js
```

This PR includes ~~3~~ 5 commits:
1. Fixes a bug where `babel src/foo.js --out-dir lib` transpiled to `lib/src/foo.js` instead of `lib/foo.js`
2. Adds test cases describing the new behavior (this commit will fail CI)
3. Implements desired behavior
4. and 5. More tests to make Codecov happy 💚 

---

| Q                        | A 
| ------------------------ | ---
| Patch: Bug Fix?          |  yes
| Major: Breaking Change?  | no
| Minor: New Feature?      | yes
| Deprecations?            | no
| Spec Compliancy?         | yes
| Tests Added/Pass?        | yes
| Fixed Tickets            | -
| License                  | MIT
| Doc PR                   | no
| Dependency Changes       | no

### CODE REVIEW

**Comment by rgbkrk** [comment]
How does this work with nested paths like:

```
packages/something/src/components/index.js
```

**Comment by lgeiger** [comment]
> How does this work with nested paths like:

@rgbkrk Good point!
I updated the PR description with the output of the [relevant test case](https://github.com/babel/babel/pull/5421/files#diff-33242e33ef3691a4cac2a5da9c87342b).

**Comment by loganfsmyth** [comment]
I'm a little concerned about

> Fixes a bug where `babel src/foo.js --out-dir lib` transpiled to `lib/src/foo.js` instead of `lib/foo.js`

Could you elaborate more on the current behavior for comparing passing directories vs passing in files, with a directory as the output? I see what you're saying about it being weird, and it would be good for the directory vs file inputs to be consistent, but we'll also want to document this as a clear breaking change in 7.x if we go through with it, and clear examples will be important.

**Comment by lgeiger** [comment]
@loganfsmyth Thanks for taking a look the PR. You're right, I did a terrible job at explaining this 😄

This may be a edge case since most of the people who transpile single files also use `--out-file`. I discovered this behavior only while writing tests for this PR.


Consider the following package structure:
```
src/
  foo.js
lib/
  foo.js <-- transpiled
```

Using a input directory and a output directory one would do:
```bash
> babel src --out-dir lib
src/foo.js -> lib/foo.js
```

This PR changes behavior if a input file and a output directory is used.

**Current behavior:**
```bash
> babel src/foo.js --out-dir lib
src/foo.js -> lib/src/foo.js
```

**This PR:**
```bash
> babel src/foo.js --out-dir lib
src/foo.js -> lib/foo.js
```

This PR adds also a new `--relative` option for the use case described above:
```bash
> babel src/foo.js --out-dir lib --relative
src/foo.js -> src/lib/foo.js

> babel src --out-dir lib --relative
src/foo.js -> src/lib/foo.js
```
To get the desired package structure with the `--relative` option one would need to use `../lib` as the output directory, since the path is relative to the defined input directory or filename:
```bash
> babel src/foo.js --out-dir ../lib --relative
src/foo.js -> lib/foo.js

> babel src --out-dir ../lib --relative
src/foo.js -> lib/foo.js
```
I added test cases for all behaviors, I hope this makes the change clearer.

**Comment by lgeiger** [comment]
Just rebased this PR. Any updates on this?

**Comment by lgeiger** [comment]
Thanks a lot for approving the change! Since it's been a while I rebase the commits onto `7.0` to make sure this PR doesn't break anything.

**Comment by keyanzhang** [comment]
Would love to see this merged! :)

**Comment by lgeiger** [comment]
Thanks for merging! Looking forward too Babel 7.0.

**Pull request merged**
