### PR TITLE
Add --out-file-extension option to babel-cli

### LINKED ISSUE #6222: Ability to output mjs extension when -d is specified
Feature request:

[Recommendation](https://twitter.com/bradleymeck/status/906572163519578112) from Node core is to output mjs alongside js files so that the package.json `main` field can be ambiguous. Since babel only outputs `.js` files when used with the `-d` directory flag, it becomes complicated to make this work. I'd like to see an option available to specify the extension the same as with parsing/consuming mjs.

### Current Behavior

This is the most elegant solution I've found so far, which involves building all files into a temporary directory, renaming all the files to mjs, copying them into the `dist/node` destination, and then removing the temp directory.

``` sh
"build-node-esm": "babel lib -d dist/node-es && rename -v .js .mjs dist/node-es/*.js && rename -v .js .mjs dist/node-es/**/*.js && cp -R dist/node-es/* dist/node && rm -rf dist/node-es",
```

### Possible Solution

My suggestion would be to add a new CLI flag option to specify the output extension. This will allow developers to easily support both Node-based ESM/CJS.

``` sh
babel lib -d dist/node --ext ".mjs"
```

### Context

I'm trying to figure out how to build a library that will be ready to take advantage of the new Node ESM semantics.

### Your Environment

| software         | version(s)
| ---------------- | -------
| node             | v9.0.0-pre

### PR DESCRIPTION
**Pull request by eps1lon**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #6222
| Patch: Bug Fix?          | No
| Major: Breaking Change?  | No
| Minor: New Feature?      | Yes
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

Webpack 4 automatically [prioritizes `foo.mjs` over `foo.js`](https://webpack.js.org/configuration/resolve/#resolve-extensions) when resolving `import foo from './foo'`.  With this change we can publish a flat package with esmodules and commonjs side by side that allows imports such as `import foo from package/bar` that webpack can easily tree shake with help of esmodules.

Settled on `out-file-extension` to be consistent with other flags (`out-dir`, `out-file` etc.)

Alternatives for flag name:
- `--output-file-extension`
- `--with-file-extension`

Should I add a warning if both `--keep-file-extension` and `--use-file-extension` are used?
> Yeah, it should throw.

It throws now

### CODE REVIEW

**Comment by eps1lon** [comment]
@ljharb I think so too so that you could use a single cli command and change the output extension based on some environment variable. 

I think this is a better starting point though since `--keep-file-extension` is also a cli flag.

**Comment by karlhorky** [comment]
Small nit in the PR description:

> Webpack 4 automatically prioritizes `foo.mjs` over `foo.js` when resolving `import foo from './bar'`

Shouldn't the filenames be `bar.mjs` and `bar.js` (because of the path `./bar` in the import example)?

**Comment by nicolo-ribaudo** [comment]
> Should I add a warning if both `--keep-file-extension` and `--use-file-extension` are used?

Yeah, it should throw.

WDYT about naming it `--out-file-extension`, for consistency with `--out-file` and `--out-dir`?

**Comment by eps1lon** [comment]
@nicolo-ribaudo 
- refactored file extension logic (looked very brittle to me, `path` module already has everything we need: 680cab64a415059c7873d53d7fab6700659012c1
- renamed `use-file-extension` -> `--out-file-extension`: 003d6588411ef9e5fb914d104b489f550af614a9
- added error if both flags are used (do test these?): e12d5e59fedd3fdf0f68e5dfe6e44cd44ea55696

**Comment by nicolo-ribaudo** [comment]
You can test them like https://github.com/babel/babel/tree/master/packages/babel-cli/test/fixtures/babel/error%20--out-dir%20--out-file

**Comment by eps1lon** [comment]
@nicolo-ribaudo Done d5dc562fc5fd95a9edcdb381e1d867ed77351872. Initially forgot to add a trailing newline to `stderr.txt` and `options.json`. Added them later and squashed but github doesn't pick it up.

**Comment by IvanGoncharov** [comment]
I would love to see this PR merged since it will allow us to remove ugly shell scripts from our `package.json`:
https://github.com/graphql/graphql-js/blob/0b5e95556ef8334416a1dcb97084c1cc0a21ff5e/package.json#L41-L42
and make our project more Windows-friendly.

We have a choice of either waiting until this feature gets merged or drop `babel-cli` and write our build scripts using `babel-core`.
Can someone from Babel team please clarify the status of this PR?

**Comment by jaydenseric** [comment]
Is there something blocking a merge?

Really looking forward to this shipping; so we can output separate `.mjs` and `.cjs` files with package scripts like this:

```json
{
  "prepare:mjs": "BABEL_ESM=1 babel src -d . --out-file-extension .mjs",
  "prepare:js": "babel src -d . --out-file-extension .cjs"
}
```

**Comment by eps1lon** [comment]
> Thanks! Docs is needed anyway.

See https://github.com/babel/website/pull/2128

**Comment by manuelbieh** [comment]
Any rough estimation on when this will be merged? Is there anything left to be done I could help with? I would really love to see this feature merged because I'm currently trying to get native ESModules working with Node and Node requires `.mjs` as file extension for ESModules.

**Comment by eps1lon** [comment]
I think this is just waiting for the next minor babel release. 

Looking at the [7.8 milestone](https://github.com/babel/babel/milestone/32) and what is ready to be shipped it seems close enough.

On the bright side: This PR could celebrate its 1 year anniversary :smile:

**Comment by tbranyen** [comment]
Thanks for landing this, much appreciated!

**Comment by FezVrasta** [comment]
How can a plugin read the `--out-file-extension` value? I'm trying to add support for it on the `babel-plugin-add-import-extension` plugin.

**Comment by nicolo-ribaudo** [comment]
@FezVrasta It's not currently possible. The options of the tool used to call Babel (i.e. `@babel/cli`, `babel-loader`, `rollup-plugin-babel`, etc) are unrelated to the options passed to Babel itself and to the plugins.

**Pull request merged**
