### PR TITLE
Use preferred property syntax in polyfill

### PR DESCRIPTION
**Pull request by zachmullen**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | 
| Patch: Bug Fix?          | 
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | 
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

### CODE REVIEW

**Comment by xtuc** [comment]
May I ask why this is needed?

**Comment by zachmullen** [comment]
Was there a reason it was written as `["return"]` instead of the way properties are referenced in the rest of the file? If not, there is value in consistency.

**Comment by hzoo** [comment]
It's probably since `return` is a reserved word, and the helpers themselves are not compiled against what browsers you support so it's matched against the lowest common denominator which is ES3.

**Comment by zachmullen** [comment]
If you look around the same file I edited, you'll notice the property named `return` is referenced with dot notation elsewhere, so that doesn't seem like the explanation.

**Comment by xtuc** [comment]
I would actually prefer to use array access because of ES3 compat (which already caused an issue on one of my projects).

**Comment by zachmullen** [comment]
Ok, in that case I'll close this.

**Pull request closed without merging**
