### PR TITLE
Remove unnecessary object accesses for legibility

### PR DESCRIPTION
**Pull request by conartist6**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?   |     No
| Patch: Bug Fix?          | No
| Major: Breaking Change?   | No
| Minor: New Feature?    | No
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  | No
| License                  | MIT

Minor stylistic cleanup for readability.

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/14446"></a>

### CODE REVIEW

**Comment by nicolo-ribaudo** [comment]
It looks like your fork is very old, could you try rebasing?

**Comment by conartist6** [comment]
Rebased. I just used github's "edit this file" feature to make the PR, but it seems to have targeted `master` as the base to make the change against instead of `main`. I don't think that was something I chose on purpose, but I could be wrong.

**Comment by nicolo-ribaudo** [comment]
Changed it :+1: (it can be done by clicking on "Edit" near the PR title)

**Comment by conartist6** [comment]
I made a [second PR}(https://github.com/babel/babel/pull/14448) as a test -- it seems the problem was caused by my fork being old and having the wrong default branch (`master`).

**Pull request merged**
