### PR TITLE
normalize line endings

### PR DESCRIPTION
**Pull request by chocolateboy**
convert repo line endings to LF and add a note to CONTRIBUTORS.md about setting up a dev environment to correctly consume and produce cross-platform line endings

### CODE REVIEW

**Comment by sebmck** [comment]
This is unnecessary and is going to destroy the git history for these files.

**Comment by chocolateboy** [comment]
IMO, it's necessary to prevent further pain/conflicts down the line. The vast majority of files are already valid, and this PR only changes a few lines in a few files. It also adds a note to reduce the chance of this being an issue in the future.

**Comment by sebmck** [comment]
I already added `end_of_line = lf` to `.editorconfig` to prevent issues like this in the future (a49f74670030d5fe0b122ca31e0191f00f5d135d). jscs picks up on line endings anyway, the `test` folder is just ignored because there are obviously a lot of issues with the fixtures. I'd rather just get @RReverser to fix it (he uses Windows and authored those files with his TCO PRs) than to erase his history.

**Comment by sebmck** [comment]
Related: discussion on 002be9a05cf88cea1102f6d3861dc2f4739c3773.

**Comment by chocolateboy** [comment]
> This is unnecessary and is going to destroy the git history for these files.

Most of these files (8/10) are less than five lines and have no history to speak of.

**Comment by chocolateboy** [comment]
> I'd rather just get @RReverser to fix it (he uses Windows and authored those files with his TCO PRs) than to erase his history.

Fair enough, though I don't see the problem with a one-off fix, and it *is* [recommended by GitHub](https://help.github.com/articles/dealing-with-line-endings/).

**Comment by chocolateboy** [comment]
Re-opening this since, IMO, the linked discussion confuses two issues 1) editor preferences and 2) the standard way to fix and prevent broken line endings. This PR only addresses the latter.

**Comment by meandmycode** [comment]
One thing I would add is that on Windows the JSCS rule:

```json
"validateLineBreaks": "LF"
```

Causes linting to be very unhappy, although I know building on Windows isn't a goal (and doing so would realistically require replacing make with grunt/gulp/shelljs/similar), it would certainly help there to at least standardize.

**Comment by sebmck** [comment]
@chocolateboy This will be mitigated in the future already via two things:

 - jscs is always setup to warn on non-LF line endings, this doesn't apply to the tests for obvious reasons.
 - The editorconfig specifies LF line endings so anyone who uses that plugin (everyone should be) will automatically have their editor setup.

**Comment by chocolateboy** [comment]
> anyone who uses that plugin (everyone should be)

I can't see a reference to it in CONTRIBUTING.md.

I still don't understand the reason for *not* fixing this in the [standard way](https://github.com/babel/babel/commit/002be9a05cf88cea1102f6d3861dc2f4739c3773#commitcomment-9860263) (i.e. as well as the editor options). The sticking point seems to be a belief that this "[destroys](https://github.com/babel/babel/pull/865#issuecomment-75437854)" or "[erases](https://github.com/babel/babel/pull/865#issuecomment-75438186)" history in some way. Could you clarify what you mean by this?

**Comment by sebmck** [comment]
> I still don't understand the reason for not fixing this in the standard way (i.e. as well as the editor/linter options).

Because this is a waste of my time.

> The sticking point seems to be a belief that this "destroys" or "erases" history in some way. Could you clarify what you mean by this?

**Comment by sebmck** [comment]
> I still don't understand the reason for not fixing this in the standard way (i.e. as well as the editor/linter options).

Because this is a waste of my time.

> The sticking point seems to be a belief that this "destroys" or "erases" history in some way. Could you clarify what you mean by this?

See commit 002be9a05cf88cea1102f6d3861dc2f4739c3773, my editor inadvertently replaced all the newlines causing all the author attribution of @RReverser to be stripped.

**Comment by chocolateboy** [comment]
> See commit 002be9a, my editor inadvertently replaced all the newlines causing all the author attribution of @RReverser to be stripped.

FYI: Unless you copy and paste a PR rather than merging/modifying it, the authorship is not lost from the history, and the author's contributions are not lost. This appears to be a misunderstanding.

> Because this is a waste of my time.

Understood (though I suspect not fixing this will waste [more](https://code.google.com/p/ps3mediaserver/issues/detail?id=856) [time](https://code.google.com/p/ps3mediaserver/source/detail?r=476) down the line).

**Pull request closed without merging**
