### PR TITLE
Force displayName plugin to run before all other transforms

### PR DESCRIPTION
**Pull request by thejameskyle**
Fixes https://github.com/gaearon/babel-plugin-react-transform/issues/67

cc @gaearon

### CODE REVIEW

**Comment by thejameskyle** [comment]
Better diff: https://github.com/babel/babel/pull/3209/files?w=0

**Comment by gaearon** [comment]
[What if two transforms did this?](https://blogs.msdn.microsoft.com/oldnewthing/20050607-00/?p=35413/)
(Not trolling, just want to understand this a little better.)

**Comment by thejameskyle** [comment]
@gaearon What is actually happening here is we're forcing this plugin to run in isolation.

Babel's transform pipeline optimizes the traversal process by [merging visitors](https://github.com/babel/babel/blob/master/packages/babel-traverse/src/visitors.js#L149-L170) together. Basically making every visitor run at the same time. This is why order is (mostly) insignificant in Babel 6.

This sometimes causes issues with one transform "beating" another by hitting a node first and mutating nodes that another plugin wants to touch. What I've done here is hit the top-most node and forced an isolated traversal of the entire tree.

So to answer your question of "what if two transforms did this", it would just mean that the order is significant just like Babel 5. Since this transform is not really destructive in any kind of way it doesn't matter that much that it's running before other things.

**Comment by gaearon** [comment]
Thanks for explaining. :+1: 
Does this mean this would introduce a perf regression?

**Comment by thejameskyle** [comment]
> Does this mean this would introduce a perf regression?

Yes

**Comment by amasad** [comment]
Another option is for `babel-plugin-react-transform` to take on this plugin as a dependency and manually run the visitors before doing it's work.

**Comment by gaearon** [comment]
Wouldn't this result in duplicated work? Or can Babel detect that this happened?

**Comment by amasad** [comment]
I thought this plugin bails when it sees a dsiplayName? But anyways it's a
trade off. IMHO it's better than everyone paying the cost whether or not
they use both plugins.

**Comment by gaearon** [comment]
>IMHO it's better than everyone paying the cost 

Yep, I agree.

**Comment by thejameskyle** [comment]
>I thought this plugin bails when it sees a displayName?

I mean technically it's going to revisit the nodes again, but thats pretty insignificant in comparison. I never thought to pull in the actual visitor in another plugin.

**Comment by sebmck** [comment]
This is bad, we shouldn't be encouraging plugins to be written like this. The gaearon/babel-plugin-react-transform issue doesn't actually explain why this is happening:

> Basically since in Babel 6 plugin visitors get merged, this plugin will always run before `babel-plugin-transform-react-display-name`, meaning that `displayName` will never get added because we've already changed the AST.

What is causing this plugin to not be ran and why is this the only possible fix?

**Comment by sebmck** [comment]
Okay we can fix this by just crawling up the ancestry looking for appropriate parent nodes, breaking on statements so we don't go too high up. Alternate PR incoming.

**Comment by sebmck** [comment]
#3216

**Pull request closed without merging**
