### PR TITLE
standalone: update `preset-stage-*`

### PR DESCRIPTION
**Pull request by sosukesuzuki**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | N/A
| Major: Breaking Change?  | Y?
| Minor: New Feature?      | Y?
| Tests Added + Pass?      | Yes
| License                  | MIT

I'm not sure that how we should treat this PR for semantic versioning.

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/13476"></a>

### CODE REVIEW

**Comment by hzoo** [comment]
Yeah it's weird, we should mention we don't support stages https://babeljs.io/blog/2018/07/27/removing-babels-stage-presets since a few years ago it just happens to still be used as the api..

It's mostly for our own REPL, we should try to remove the feature entirely (just turn on all plugins or make it opt in like most people have to use it)

**Review by nicolo-ribaudo — APPROVED** [review]
Let's merge this as a minor.

For Babel 8, since everything will be ESM-based we might just consider dropping `@babel/standalone` support and relying on `"exports"` to differentiate between Node.js and browser code.

**Review by existentialism — APPROVED** [review]
:+1: for minor

**Review by JLHwung — CHANGES_REQUESTED** [review]
Removing stage 3 plugins is a breaking change. Because 'stage-3' no long enables the plugins that were enabled before Babel 7.15. We have to defer deletion to Babel 8. Otherwise this PR looks good to me.

**Review by JLHwung — APPROVED** [review]

**Pull request merged**
