### PR TITLE
Prevent transform-es2015-function-name from altering MethodDefinition's Re: T6779

### PR DESCRIPTION
**Pull request by jmm**
See https://phabricator.babeljs.io/T6779. Looking for feedback on whether this is:

1. The correct outcome.

1. A sensible way to get there. With the current implementation, I guess it was more efficient to visit the `ObjectExpression`'s and loop all the props / methods, but if just the props are being considered it seems like visiting `ObjectProperty`'s makes sense.

1. An object literal (`ObjectExpression`) is the only context where an `ObjectProperty` can appear.

My understanding is that transforming an ES2015 object literal method definition (e.g. `{x () {}}`) to ES5 has at least one important semantic limitation (regarding `super` -- see the issue). (Someone please confirm.) So it seems to me it ought to be possible to do this:

`input.js`

```js
// ES2015 that should not be transformed.
var x = {x () { super.x(); }};

// ES5 that should get transformed to have a name.
var y = {y: function () {}};
```

```js
babel.transform(input, {
  plugins: ["babel-plugin-transform-es2015-function-name"]
});
```

My understanding is that `babel-plugin-transform-es2015-shorthand-properties` is the one that should transform ES2015 like in this example and it seems to me that the user should opt-in to that if they want to transform the method definition syntax and accept the limitations. It should be possible to use both transforms together if you want the outcome that `babel-plugin-transform-es2015-function-name` on its own is delivering currently with this input, correct? (Actually, now that I think about it, should `shorthand-properties` not automatically name the function when transforming `MethodDefinition`'s?)

Existing tests pass with this change, so if this is not the correct behavior the `actual` fixture ought to be adopted along with a different `expected`.

### CODE REVIEW

**Comment by hzoo** [comment]
Ok forgot about super in object literals - right it does look like that has to be in a ObjectMethod.

And `babel-plugin-transform-es2015-shorthand-properties` already converts both objectproperty/objectmethod so it looks like a good idea to split the two and not have overlapping functionality. :+1:

**Comment by jmm** [comment]
@hzoo Cool, thanks for reviewing.

> And `babel-plugin-transform-es2015-shorthand-properties` already converts both objectproperty/objectmethod so it looks like a good idea to split the two and not have overlapping functionality.

Ironically, since I started this it occurred to me that maybe `shorthand-properties` *should* be doing the naming on `ObjectMethod`'s itself. I'll probably bring that up in slack or another issue.

**Comment by amasad** [comment]
I don't understand the issue with regards to `super`? What is the expected output? To not transform to function at all?

**Comment by jmm** [comment]
@amasad Thanks for reviewing.

> I don't understand the issue with regards to super?

Sorry, that's my fault. The `super` part is actually misstated in the bug report and in my followups. Thanks for your comment -- it prompted me to think the situation through more and take a closer look. The bug report misstates the problem by saying it's:

> not valid code due to `super` out of method.
 
But the real problem there is that it's `super` in ES5, right? I think the problem the bug report raises is solved by adding `babel-plugin-transform-es2015-object-super`.

However, the report brought this other issue to my attention and I still think the outcome of this PR is correct.

> What is the expected output? To not transform to function at all?

Correct, that's what I'm proposing. As in the fixtures here, `MethodDefinition` syntax input and output. Forget `super` completely. The subject of this PR is: should it be possible to simultaneously use `transform-es2015-function-name` to mock ES2015 function name inference for anonymous functions (ES5), while not transforming `MethodDefinition`'s? I think yes.

Those seem like separate concerns to me and my understanding is that `transform-es2015-shorthand-properties` is the one that should be concerned with `MethodDefinition`. (I'm also going to submit a PR proposing that that always transform them to named functions since I think that more closely approximates the real ES2015 semantics.)

The hypothetical is enough, but recent versions of V8 (Chrome 45 / Node 5) are a perfect example of why I think this behavior makes sense:

```js
var x = {
  y: function () {},
  z () {},
};

console.log(x.y.name); // ""
console.log(x.z.name); // "z"
```

**Comment by amasad** [comment]
Cool, can you cite the ES2015 to make sure we're doing the right thing? Browsers often don't fully implement the spec.

**Comment by jmm** [comment]
@amasad I'm sorry, I muddled this by talking about `super`, which really isn't relevant here, and other stuff outside the scope of this PR. Rather than heavily edit the description here I started over with a new PR with a focused description: https://github.com/babel/babel/pull/3176. In a nutshell, there's no spec-correctness question involved in this PR. The PR only addresses this question: should you be able to opt-in to naming anonymous functions and *not* transform method definitions at the same time.

**Pull request closed without merging**
