### PR TITLE
fix: replace backslashes with forward slashes from resolved path for …

### LINKED ISSUE #11357: Broken resolved paths in Windows inside a monorepo
## Bug Report

- [ ] I would like to work on a fix!

**Current Behavior**
I'm using `rollup` to bundle a package inside a `yarn` monorepo. As soon as `@babel/plugin-transform-runtime` is used, the built package breaks because of broken resolved paths to runtime helpers such as `_typeof`. This results in warnings like this:

```
(!) Unresolved dependencies

C:UsersjohanneszProjectsMyproject
untime/helpers/typeof (imported by ..\..\..\node_modules\regenerator-runtime\runtime.js,  C:UsersjohanneszProjectsMyproject
untime/helpers/typeof?commonjs-external
```

As you can see, the Backslashes are missing from the paths, causing a broken build.

See https://github.com/rollup/plugins/issues/290 and https://github.com/yarnpkg/yarn/issues/8031

**Input Code**

Here is a repro: https://github.com/johannes-z/rollup-yarn-path-error

**Expected behavior/code**
The paths should be correctly resolved on Windows

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `babel.config.js`

```js
module.exports = {
  presets: [
    [
      '@vue/cli-plugin-babel/preset',
      {
        corejs: 3,
        useBuiltIns: 'usage',
      },
    ],
  ],
}
```

**Environment**

```
  System:
    OS: Windows 10 10.0.18363
  Binaries:
    Node: 11.13.0 - C:\Users\johannesz\scoop\apps\nvm\current\nodejs\nodejs\node.EXE
    Yarn: 1.22.0 - C:\Users\johannesz\scoop\apps\yarn\current\Yarn\bin\yarn.CMD    
    npm: 6.7.0 - C:\Users\johannesz\scoop\apps\nvm\current\nodejs\nodejs\npm.CMD   
  Monorepos:
    Yarn Workspaces: 1.22.0
  npmPackages:
    eslint: ^5.16.0 => 5.16.0
    rollup-plugin-babel: ^4.4.0 => 4.4.0
```

- How you are using Babel: loader/rollup-plugin-babel

**Possible Solution**
I was able to *fix* this problem by fixing the backslashes:
https://github.com/babel/babel/blob/master/packages/babel-plugin-transform-runtime/src/index.js#L237

This is the line where the error ultimately occurs (I don't know where it comes from though).

Changing this line to fixed it for me:

```js
return this.addDefaultImport(
  `${modulePath.replace(/\\/g, '\\\\')}/${helpersDir}/${name}`,
  name,
  blockHoist
);
```

Of course, this is not a *permanent* fix; especially since it seems to work on UNIX systems. I think `resolveAbsoluteRuntime` should consider Windows as an environment and generate a correct path.

Changing it to the following would probably be a better solution to fix this issue:

```js
`${modulePath.replace(/\\/g, '/')}/${helpersDir}/${name}`
```

**EDIT:** I investigated a little further. In fact the `resolveAbsoluteRuntime` function causes inconsistent paths between OS: https://github.com/babel/babel/blob/master/packages/babel-plugin-transform-runtime/src/index.js#L13-L15

`path.dirname` creates forward slashes for unix systems, but on windows it only creates single backslashes: `C:\Users\Johannes\...`. Backslashes returned from `dirname` should be replaced with forward slashes - I haven't found a node.js way of doing this automatically.

### PR DESCRIPTION
**Pull request by johannes-z**
…windows environments

| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #11357
| Patch: Bug Fix?          | Yes
| Major: Breaking Change?  | No
| Minor: New Feature?      | No
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  | No
| License                  | MIT

See #11357

### CODE REVIEW

**Comment by nicolo-ribaudo** [comment]
@johannes-z Could you add a test for this change?

Since the test should only run on windows, you can specify it like it has been done in `packages/babel-plugin-transform-react-jsx-development/test/fixtures/windows/classic-runtime-with-source-self-plugins-windows/options.json`.

**Comment by johannes-z** [comment]
@nicolo-ribaudo Sure, I can try. I have no experience with the test suite. Are there docs for it? I also would need to know how to run it 😓

**Comment by existentialism** [comment]
@johannes-z check out https://github.com/babel/babel/blob/master/CONTRIBUTING.md#running-lintingtests, and let us know if you run into any problems so we can improve the docs!

**Comment by johannes-z** [comment]
I'm on Windows here and unable to run the test suite:

```
$ make test
BABEL_ENV=test yarn --silent eslint scripts packages codemods eslint '*.js' --format=codeframe
'BABEL_ENV' is not recognized as an internal or external command,
operable program or batch file.
mingw32-make: *** [Makefile:112: lint-js] Error 1
```

**Comment by nicolo-ribaudo** [comment]
Try running `yarn jest` directly.

**Comment by johannes-z** [comment]
It worked executing, but I'm getting errors:

```
 FAIL  packages/babel-plugin-transform-typescript/test/index.js
  ● Test suite failed to run

    Configuration error:

    Could not locate module @babel/code-frame mapped as:
    ......\babel\packages\babel-code-frame.

    Please check your configuration for these entries:
    {
      "moduleNameMapper": {
        "/^@babel\/(?!eslint-)(?!plugin-syntax-async-generators|plugin-syntax-bigint|plugin-syntax-dynamic-import|plugin-syntax-json-strings|plugin-syntax-nullish-coalescing-operator|plugin-syntax-object-rest-spread|plugin-syntax-optional-catch-binding|plugin-syntax-optional-chaining|plugin-syntax-export-namespace-from)([a-zA-Z0-9_-]+)$/": "......\babel\packages\babel-$1"
      },
      "resolver": null
    }

      at createNoMappedModuleFoundError (node_modules/jest-resolve/build/index.js:501:17)
```

**Comment by nicolo-ribaudo** [comment]
@johannes-z We are thinking about migrating away from `make` to make it easier for windows users.

**Pull request merged**
