### PR TITLE
docs(babel-standalone): remove bower mention

### PR DESCRIPTION
**Pull request by Haroenv**
Since the package won't be downloadable as `@babel/standalone` it's best to just remove it, since it's pretty much deprecated as is. I left the other mention of babel-standalone-bower since I guess that's just the name and still useful in other cases

cc @daniel15 

reported in https://github.com/babel/babel/pull/6495#pullrequestreview-70980926

| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | none really
| Patch: Bug Fix?          | no
| Major: Breaking Change?  | no
| Minor: New Feature?      | no
| Tests Added + Pass?      | -
| Documentation PR         | oops, I can't change the commit message now - on GitHub 😢
| Any Dependency Changes?  | no

### CODE REVIEW

**Comment by xtuc** [comment]
Do we consider this as a breaking change since bowser user won't be able to download it. @Daniel15 do you have any stats about this?

**Comment by Haroenv** [comment]
I guess the real breaking change was in #6495 🤔

**Comment by nicolo-ribaudo** [comment]
We could keep the `babel-standalone` bower package with the old name if it is not too confusing.

**Comment by Daniel15** [comment]
I don't have any stats, unfortunately. 

Installing babel-standalone via Bower pulls it from https://github.com/babel/babel-standalone-bower, which hasn't been updated in a long time (last updated for 6.19.0). I automated it but the automation broke at some point and I never fixed it. Nobody's complained, so I wonder if anyone actually uses it 😛

**Comment by Haroenv** [comment]
Exactly. I think that’s why we should remove the mentions of it here!

**Pull request merged**
