### PR TITLE
Fix typescript side effects

### LINKED ISSUE #8634: [TypeScript] typescript plugin removes parameter decorators imports
It seems like typescript plugin has some side effects while working with decorators - it removes parameter decorators imports.

Source file:
```ts
// test.ts
import { NgModule, Optional, SkipSelf } from '@angular/core';

@NgModule({})
export class CoreModule {
  constructor(@Optional() @SkipSelf() parentModule) {}
}
```
Babel config:
```json
// .babelrc
{
  "plugins": [
    [ "@babel/plugin-proposal-decorators", { "legacy": true }],
    "babel-plugin-transform-function-parameter-decorators",
    "@babel/plugin-transform-typescript"
  ]
}
```
Result (note that there are no `Optional` and `SkipSelf` imports):
```js
var _dec, _class;

import { NgModule } from '@angular/core';
export let CoreModule = (_dec = NgModule({}), _dec(_class = class CoreModule {
  constructor(_parentModule) {
    var _parentModule2 = Optional()(SkipSelf()(_parentModule));
  }

}) || _class);
```
Expected result (can be obtained by removing typescript plugin):
```js
var _dec, _class;

import { NgModule, Optional, SkipSelf } from '@angular/core';
export let CoreModule = (_dec = NgModule({}), _dec(_class = class CoreModule {
  constructor(_parentModule) {
    var _parentModule2 = Optional()(SkipSelf()(_parentModule));
  }

}) || _class);
```

Environment:
```
node: v10.9.0
npm: 6.2.0
@babel/cli@7.0.0
@babel/core@7.0.0
@babel/plugin-proposal-decorators@7.0.0
babel-plugin-transform-function-parameter-decorators@1.2.0
@babel/plugin-transform-typescript@7.0.0
macOS: 10.13.6 
```

### PR DESCRIPTION
**Pull request by yuri-karadzhov**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | `Fixes #8634
| Patch: Bug Fix?          | Yes
| Major: Breaking Change?  | No
| Minor: New Feature?      | No
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  | No
| License                  | MIT

### CODE REVIEW

**Comment by danez** [comment]
Thank you very much for this, could you please add a test?

If you need help with the tests fell free to join our slack chat and ask there, but basically all the tests for the transforms have a file with the input code (`input.mjs`) and a file with the expected output (`output.mjs`). To enable certain plugins you can also create a file called `options.json`. For example look at this test: https://github.com/babel/babel/tree/master/packages/babel-plugin-transform-typescript/test/fixtures/imports/elide-react-no-2

**Comment by yuri-karadzhov** [comment]
Sure will do that this week. Thanks for detailed explanation.

**Comment by yuri-karadzhov** [comment]
Strange, it works in application, but not in test. I will investigate.

**Comment by danez** [comment]
The underlying problem was that babel-traverse was not visiting decorators which are added to params. I changed the PR to reflect this. Now the test works.

**Comment by yuri-karadzhov** [comment]
Any updates on this PR?

**Comment by pixelmeister** [comment]
Any ETA when this will be released?  Are there nightly builds of Babel available that I could use in the interim?

**Pull request merged**
