### PR TITLE
Providing File.has method for core/transformation package

### PR DESCRIPTION
**Pull request by Borales**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | No ticket
| Patch: Bug Fix?          | No
| Major: Breaking Change?  | No
| Minor: New Feature?      | Could be (mostly - providing BC for https://github.com/yahoo/babel-plugin-react-intl/issues/122)
| Tests Added + Pass?      | No new tests, Pass - Yes
| Documentation PR         | No
| Any Dependency Changes?  | No

Simply provides `.has(key)` method for [File](packages/babel-core/src/transformation/file/file.js) class.

### CODE REVIEW

**Comment by Borales** [comment]
@xtuc Hi, I'm not really sure who should I assign this task to, but could you please tell me what's missing here, so this PR got reviewed? Thanks

**Comment by xtuc** [comment]
I'm wondering why this methods doesn't exists in 7 anymore.

**Comment by Borales** [comment]
@xtuc I have no idea :)

**Comment by Borales** [comment]
@xtuc @nicolo-ribaudo thank you for the review. Could you please tell me what are my further steps? Do I need to do anything else?

**Comment by xtuc** [comment]
I'll go ahead and merge this.

I don't know when we're planning to make the next beta release.

**Pull request merged**
