### PR TITLE
fix unexpected token issue for regex after block case

### PR DESCRIPTION
**Pull request by hzoo**
- Ex: `if (1) {} /foo/`

Fixes babel/babel-eslint#161
Ref marijnh/acorn#289

### CODE REVIEW

**Comment by sebmck** [comment]
Thanks @hzoo!

**Comment by hzoo** [comment]
Ok test fail - it wasn't erroring for me before..

**Comment by hzoo** [comment]
It didn't fail when it generated the `expected.json` but after running `make test` again it did

**Comment by sebmck** [comment]
Ah, it failed to serialise the regex, feel free to delete the reggae `value` field from expected.json

**Pull request merged**
