### PR TITLE
Pipelines as flattened expressions (support for async/await)

### PR DESCRIPTION
**Pull request by thiagoarrais**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Related to babel/proposals#29
| Patch: Bug Fix?          | Yes
| Major: Breaking Change?  | No
| Minor: New Feature?      | No
| Tests Added + Pass?      | Yes
| Documentation PR Link    |
| Any Dependency Changes?  | No
| License                  | MIT

This adds support for async/await in pipeline expressions by flattening them. Await and yield expressions will be transpiled from

```javascript
const r = a |> b |> await # |> c
```
to something like

```javascript
const $0 = a;
const $1 = b($0);
const $2 = await $1;
const r = c($2)
```

Most of the work here was inspired by js-choi's [description of statement flattening](https://gist.github.com/js-choi/446f79ea2b4a1cfac8a8cf594ca269a9) (thanks for that, @js-choi!).

Relates to https://github.com/babel/babel/projects/9#card-15461738

### CODE REVIEW

**Comment by nicolo-ribaudo** [comment]
This statement flattening has an ordering problem:

```js
(alert(1), alert)([alert(2), 3][1] |> #);
```

This should alert 1, 2, 3 but alerts 2, 1, 3. I think that it can be solved by using expressions instead of statements:
```js
var _pipe;
(alert(1), alert)(_pipe = [alert(2), 3][1], _pipe);
```
(you can create the `var _pipe` using `path.scope.push`)

**Comment by nicolo-ribaudo** [comment]
This statement flattening has an ordering problem:

```js
(alert(1), alert)([alert(2), 3][1] |> #);
```

This should alert 1, 2, 3 but alerts 2, 1, 3.
```js
// Current output
const _pipe = [alert(2), 3][1];
(alert(1), alert)(_pipe);
```

I think that we can support `await` without needing different statements:
```js
// input
async function f() {
  const r = Promise.resolve(2) |> await # |> # + 1;
}

// outpu
async function f() {
  var _ref1, _ref2;
  const r = (_ref1 = Promise.resolve(2), _ref2 = await _ref1, _ref2 + 1);
}

**Comment by thiagoarrais** [comment]
> ```javascript
>  const r = (_ref1 = Promise.resolve(2), _ref2 = await _ref1, _ref2 + 1);
> ```

That approach has the potential to be a lot simpler. It warrants a separate PR.

@js-choi, let me summon you here: do you see any potential limitations?

**Comment by thiagoarrais** [comment]
If we manage to avoid "statementizing" the pipeline expressions, 

>```javascript
>(alert(1), alert)([alert(2), 3][1] |> #);
>```

**Comment by thiagoarrais** [comment]
Just opened a new PR for this. Please see #9401.

**Pull request closed without merging**
