### PR TITLE
Replace `chalk` with `picocolors`

### LINKED ISSUE #14213: Reduce bundle size of `@babel/codeframe`
### 💻

- [X] Would you like to work on this feature?

### What problem are you trying to solve?

Reduce the bundle size of projects that depend on `@babel/codeframe`

### Describe the solution you'd like

We are working on reducing the bundle size of Prettier, tracked in https://github.com/prettier/prettier/issues/12144

In https://github.com/prettier/prettier/issues/12144#issuecomment-1024994274 @dakmor suggested to switch Chalk in `@babel/codeframe` to [colorette](https://github.com/jorgebucaran/colorette), which should reduce the size of the package by 19kB (as Chalk pulls in 20kB and colorette is 1kB)

Can we remove large dependencies from `@babel/codeframe` and reduce its disk footprint?

### Describe alternatives you've considered

Keep Chalk and keep a large bundle

### Documentation, Adoption, Migration Strategy

_No response_

### PR DESCRIPTION
**Pull request by nicolo-ribaudo**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Closes #14213
| Patch: Bug Fix?          |
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

I was checking https://npmgraph.js.org/?q=%40babel%2Fcore#hide= and I noticed that we have both `chalk` and `picocolors` (through `browserslist`) in our dependency tree.

This PR replaces `chalk` with `picocolors`, to avoid two libraries that do the same thing. `picocolors` supports Node.js 6+, so we can start using it also in Babel 7, but it's much smaller:
- 5kb smaller than the latest chalk version (https://bundlephobia.com/package/picocolors@1.0.0 vs https://bundlephobia.com/package/chalk@5.3.0)
- 20kb smaller than chalk 2 (vs https://bundlephobia.com/package/chalk@2.4.2)

This reduces our `@babel/standalone` unminified size from 5128kB to 5072kB.

There is just a footnote to all of this: we cannot _actually_ drop chalk in Babel 7, because `@babel/highlight` exports a `getChalk` function that just returns it. However, given that:
- `picocolors` it's likely in the dependencies tree
- when it's not (e.g. a package directly using `@babel/highlight`), `picocolor` only adds 2% to chalk's size
- if the `getChalk` function is not used, it's dead code and bundlers can hopefully eliminate it

I decided to go ahead and also use picocolors for Babel 7, rather than branching everywhere on `process.env.BABEL_8_BREAKING`.

cc @fisker @sosukesuzuki I know that Prettier does some magic to remove `chalk` from Babel when bundling, this might affect it.

### CODE REVIEW

**Review by liuxingbaoyu — APPROVED** [review]

**Review by fisker — APPROVED** [review]

**Comment by nicolo-ribaudo** [comment]
Some snapshot tests in Jest are failing:
```diff
-     </><red><bold>></intensity></color><gray> 1 |</color> <cyan>throw</color> <cyan>new</color> <yellow>Error</color>(<green>"Whoops!"</color>)<yellow>;</color></>
-     </> <gray>   |</color>       <red><bold>^</intensity></color></>
+     </><red><bold>></intensity></color><gray> 1 |</color> <cyan>throw</color> <cyan>new</color> <yellow>Error</color>(<green>"Whoops!"</color>)<yellow>;</color>
+      <gray>   |</color>       <red><bold>^</intensity></color></>
```

(wow, serializing ANSI escapes like this is super helpful)

I think this difference (the missing `</>` "terminate all styles" at the end of the first line and beginning of the second) is ok, because both `<color>` styles and `<intensity>` (`<bold>`) are explicitly terminated already.

**Review by JLHwung — APPROVED** [review]

**Comment by nicolo-ribaudo** [comment]
I'll merge with CI red, release and then open a PR to Jest -- it's much easier than working it around her :grimacing:

**Comment by nicolo-ribaudo** [comment]
https://github.com/jestjs/jest/pull/14976

**Comment by SimenB** [comment]
>(wow, serializing ANSI escapes like this is super helpful)

https://www.npmjs.com/package/jest-serializer-ansi-escapes fwiw 🙂

**Pull request merged**
