### PR TITLE
You Should probably close this

### PR DESCRIPTION
**Pull request by TheAlphaNerd**
mostly opening this as a way to make a joke to continue the twitter thread found at https://twitter.com/thejameskyle/status/626289868419805184

### CODE REVIEW

**Comment by thejameskyle** [comment]
http://youtu.be/YoDh_gHDvkk

**Comment by TheAlphaNerd** [comment]
Did you know that I have been listening to Bowie on youtube for the last 30 minutes.

Space oddity on repeat ftw!

**Comment by TheAlphaNerd** [comment]
We are also doing this at karaoke some time soon... MAH FUCKING JAM

**Comment by forivall** [comment]
The funniest thing is that the error wouldn't even get thrown during transpilation.

**Comment by sebmck** [comment]
wtf lol

**Comment by TheAlphaNerd** [comment]
LOLOLOLOL MORNING @sebmck

**Pull request closed without merging**
