### PR TITLE
fix: tsSatisfiesExpression check with different duplicated @babel/typ…

### PR DESCRIPTION
**Pull request by nanianlisao**
…es versions

| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | `Fixes #1, Fixes #2` 
| Patch: Bug Fix?          |
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/15147"></a>

### CODE REVIEW

**Comment by liuxingbaoyu** [comment]
Are you having problems with `tsSatisfiesExpression`? This plugin doesn't seem to detect `t.tsSatisfiesExpression`.

**Comment by ityuany** [comment]
@liuxingbaoyu 
This is a logical error, and although it does not lead to a real error, it is politically correct to correct it.
If you are willing to merge, we will organize human assistance to fix such problems in all plugins in a large area.

**Comment by ityuany** [comment]
If @babel/core is imported directly from the header, it may actually cause that the @babel/core that the plugin depends on is not the same as the real one in the future, which will inevitably lead to other failures. We think that since there is already a type in the parameter api , then it will be the most stable and reliable to get it directly from here

**Comment by liuxingbaoyu** [comment]
Thanks for your work, but I personally don't think it's necessary to change everything to use `@babel/core`.
Using the newer version of `@babel/types` is fine in most cases, there are even some special cases where we explicitly want to use the newer `@babel/types`. And the modification will take a lot of time, we need to always use `@babel/types` as a parameter, especially in complex plugins. And overall, we may not get much benefit.
But for only this one PR I look good.

**Review by liuxingbaoyu — APPROVED** [review]

**Pull request closed without merging**
