### PR TITLE
Add options.allowAwaitOutsideFunction.

### PR DESCRIPTION
**Pull request by jdalton**
This PR addresses #7634.

~~It's missing tests as the moment. *(I'll rebase them in soon)*~~

**Update:**

✅ Added tests.

### CODE REVIEW

**Comment by nicolo-ribaudo** [comment]
WDYT of naming it `allowTopLevelAwait`, since it is how it's usually referred to?

**Comment by jdalton** [comment]
Fixed lint errors, added tests, and ensured an error is thrown for the case raised by @nicolo-ribaudo.
I kept the name as `allowAwaitOutsideFunction` since it's technically more correct and aligns with existing and similar options *(feel free to tweak to taste however)*.

**Comment by jdalton** [comment]
> Could we maybe rename the tests?

I wasn't sure about that but noticed a large collection of tests incremented as numbers. Is there a particular place or naming scheme you had in mind?

**Comment by nicolo-ribaudo** [comment]
You could put it in `fixtures/es2017/async-functions/allowAwaitOutsideFunction`.

> I kept the name as allowAwaitOutsideFunction since it's technically more correct and aligns with existing and similar options

I still prefer the `allowTopLevelAwait` name, but I'm ok with this since it is how `allowReturnOutsideFunction` is named.

**Comment by nicolo-ribaudo** [comment]
I just learned that this is actually a new proposal (https://github.com/MylesBorins/proposal-top-level-await). Can you define this feture it using a new Babylon plugin (`topLevelAwait`) instead of an option?

**Comment by jdalton** [comment]
I rather not since the proposals are much more involved. I think later, if someone wants to add a plugin to support those proposals more in-depth then they could build on top of `allowAwaitOutsideFunction`

**Comment by jdalton** [comment]
Moved tests to a more readable place.

**Comment by hzoo** [comment]
>  I think later, if someone wants to add a plugin to support the proposal (and variations) more in-depth, then they could build on top of allowAwaitOutsideFunction

that's true

**Pull request merged**
