### PR TITLE
Suggest using `BABEL_SHOW_CONFIG_FOR` for config problems

### PR DESCRIPTION
**Pull request by nicolo-ribaudo**
| Q                        | A 
| ------------------------ | ---
| Patch: Bug Fix?          |
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

In some errors we report that there is a problem with the user's config. However, configuration problems can be hard to debug. This PR mentions `BABEL_SHOW_CONFIG_FOR` in the error messages, so that users have a starting point to find the problem where "just fix your config" doesn't work.

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/12428"></a>

### CODE REVIEW

**Review by JLHwung — COMMENTED** [review]
I think we could link to our docs
```
// e.g.
babel.dev/diagnostics/?show-config-for=(base58 path)
```

So it can be more convenient for verbose help messages. In this cases, PowerShell users have `$Env:BABEL_SHOW_CONFIG_FOR = [some path]` and CMD has `SETX BABEL_SHOW_CONFIG_FOR [some paht]` -- We could not cover all of them in the published sources. There is a reason why [`cross-env`](https://www.npmjs.com/package/cross-env) is handy. 😄

**Comment by nicolo-ribaudo** [comment]
Rebased, and updated the error message to use `cross-env` so that a single command works in every platform :) I also added a link to the docs.

**Comment by liuxingbaoyu** [comment]
Let's unify path separators in error messages to `/`?
That way we can use same tests on different platforms.

**Comment by nicolo-ribaudo** [comment]
We are just logging the filename exactly as it is passed to the `filename` option, without further modifying it. I think we currently treat is as an opaque string everywhere.

Maybe in our tests we could pass it using `/` even on Windows? Do you know how other tools (webpack, rollup & co) pass the filename to Babel on Windows? I'm worried that we would not be testing what our users actually see.

**Comment by liuxingbaoyu** [comment]
I'm not sure about this, but it seems like they will use the original path.
You are right, maybe let's add an option to replace `\` with `/` in `output.js`.

**Review by liuxingbaoyu — APPROVED** [review]

**Pull request merged**
