### PR TITLE
Remove lodash sortBy use

### PR DESCRIPTION
**Pull request by jridgewell**
This one `require` increases startup time by ~100ms (coming from `loadOptions`).

Screen Shot 2021-03-18 at 3 33 56 PM

Re: https://github.com/babel/babel/issues/11726

### CODE REVIEW

**Review by JLHwung — COMMENTED** [review]
`lodash/sort` is stable. However, `Array#sort` is not stable util V8 7.0. We can polyfill it by lodash sortBy on Node.js < 11 like we did for other features:

https://github.com/babel/babel/blob/21e8e59f7d807ce4683e3c31bbf4935bc9d8c9d2/babel.config.js#L259-L270

Hopefully we can switch to `Array#sort` in Babel 8.

**Comment by jridgewell** [comment]
> We can polyfill it by lodash sortBy on Node.js < 11 like we did for other features

I added a simple bucket sorter. And it's faster! https://jsbench.github.io/#f32d70e88170ab4e165ac1f7f30df163

**Comment by JLHwung** [comment]
Good catch. We should add logical assignment to shippedProposals.

**Comment by nicolo-ribaudo** [comment]
Does this change the behavior when `_blockHoist` is `Infinity`?

**Comment by jridgewell** [comment]
> Does this change the behavior when _blockHoist is Infinity?

You're right. I've updated to not use an array.

**Review by nicolo-ribaudo — APPROVED** [review]
Thanks!

**Review by xtuc — APPROVED** [review]

**Review by JLHwung — APPROVED** [review]

**Pull request merged**
