### PR TITLE
[babel 8] Materialize ESTree's `classFeatures` option

### PR DESCRIPTION
**Pull request by nicolo-ribaudo**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | `Fixes #1, Fixes #2` 
| Patch: Bug Fix?          |
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/13752"></a>

### CODE REVIEW

**Comment by nicolo-ribaudo** [comment]
There is a bug in the ESTree plugin; I'll open a new PR to fix it.

**Review by JLHwung — COMMENTED** [review]
If it's for Babel 8, I think we can actually remove this feature. The Babel eslint will also be bumped to support Babel 8 only.

**Comment by nicolo-ribaudo** [comment]
Yeah, with "enable by default" actually meant "always enable, without checking for the flag".

**Review by JLHwung — APPROVED** [review]
Maybe change the PR title to "Materialize ESTree `classFeatures` option"? Since you can't disable it in Babel 8.

**Review by hzoo — APPROVED** [review]

**Pull request merged**
