### PR TITLE
test: add tests about behaviour of replaceWithMultiple

### PR DESCRIPTION
**Pull request by JLHwung**
| Q                        | A 
| ------------------------ | ---
| Tests Added + Pass?      | Yes
| License                  | MIT

Add a test on the `NodePath#replaceWithMultiple` behaviour when one of node is the replaced node. This tests is required by #12302, I feel it should be landed separately.

This behaviour is not intuitive to me. It is _not_ visited because in https://github.com/babel/babel/blob/12c6db6fae54ea7ffe6481ffe7e610b8cf4146ae/packages/babel-traverse/src/path/replacement.js#L46-L52, 

when we clear `this.node` (we denote `this.node` by `n`, w.l.o.g. we assume `nodes[0] === n`), we don't update the `pathCache` of its parent. 

https://github.com/babel/babel/blob/12c6db6fae54ea7ffe6481ffe7e610b8cf4146ae/packages/babel-traverse/src/path/index.js#L70

Since the `pathCache` holds a NodePath which has a reference to the `n`, it implicitly copy `n` to a new memory address. Now when the `n` is queried against `pathCache`

https://github.com/babel/babel/blob/12c6db6fae54ea7ffe6481ffe7e610b8cf4146ae/packages/babel-traverse/src/path/index.js#L79

The `pathCache` is missed because the NodePath is referencing a shallow copy of `n`, so a new NodePath instance is created for `n` and `this.node` is always `null` during

https://github.com/babel/babel/blob/12c6db6fae54ea7ffe6481ffe7e610b8cf4146ae/packages/babel-traverse/src/path/replacement.js#L53-L59

then it is removed instead of `requeue` so this node is never visited after replaced.

I think intuitively all nodes in the argument of `replaceWithMultiple` should be revisited. But the suggested behaviour is a breaking change, e.g. breaking TDZ implementation.

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/12309"></a>

### CODE REVIEW

**Review by nicolo-ribaudo — APPROVED** [review]

**Review by existentialism — APPROVED** [review]
💯

**Comment by nicolo-ribaudo** [comment]
What happens if `path.node` is not the first element in `replaceWithMultiple`?

**Comment by nicolo-ribaudo** [comment]
> I think intuitively all nodes in the argument of replaceWithMultiple should be revisited. But the suggested behaviour is a breaking change, e.g. breaking TDZ implementation.

I'm not sure that I would expect that behavior. However, I think it should match whatever `path.replaceWith(path.node)` does. My intuition is that neither should requeue the node, unless someone does `path.requeue()` explicitly.

**Comment by JLHwung** [comment]
> What happens if path.node is not the first element in replaceWithMultiple?

The order does not matters since they are created in a loop 
https://github.com/babel/babel/blob/12c6db6fae54ea7ffe6481ffe7e610b8cf4146ae/packages/babel-traverse/src/path/modification.js#L57-L65
but I have added another tests.

> However, I think it should match whatever path.replaceWith(path.node) does. My intuition is that neither should requeue the node, unless someone does path.requeue() explicitly.

Yeah `NodePath#replaceWith` does not requeue when `this.node` equals to the replacement, https://github.com/babel/babel/blob/12c6db6fae54ea7ffe6481ffe7e610b8cf4146ae/packages/babel-traverse/src/path/replacement.js#L119-L121

but it does requeue for other cases. https://github.com/babel/babel/blob/12c6db6fae54ea7ffe6481ffe7e610b8cf4146ae/packages/babel-traverse/src/path/replacement.js#L178-L179

**Pull request merged**
