### PR TITLE
Add isScriptContext for babel-generator

### PR DESCRIPTION
**Pull request by boopathi**
| Q                        | A 
| ------------------------ | ---
| Patch: Bug Fix?          | n
| Major: Breaking Change?  | y
| Minor: New Feature?      | y
| Deprecations?            | n
| Spec Compliancy?         | 
| Tests Added/Pass?        | 
| Fixed Tickets            | 
| License                  | MIT
| Doc PR                   | 
| Dependency Changes       |

### CODE REVIEW

**Comment by boopathi** [comment]
Which would be a better API ?

```js
transform(input, {
  isScriptContext: true
});
```

or

```js
transform(input, {
  generatorOpts: { 
    isScriptContext: true
  }
});
```

or 

```js
transform(input, {
  generatorOpts: {
    jsesc: {
      isScriptContext: true
    }
  }
});
```

also, 

```js
transform(input, {
   jsesc: { isScriptContext: true }
});
```

**Comment by vigneshshanmugam** [comment]
I would vote for the last one since its clear the options are meant for jsesc

**Comment by loganfsmyth** [comment]
I'm not sure how I feel about this. It seems like Babili should be making sure the AST is structured such that this serialization happens based on the AST content, rather than as another generator options. Thoughts?

**Comment by boopathi** [comment]
Summary: 
The problem this solves is to escape things like `</script` in String to transform to `<\/script`. Where including `jsesc` in babili will run twice on a String Literal and all the quotes will be escaped again and causes problems like - https://github.com/babel/babili/issues/440.

Not sure if I understood your comment properly.

The only thing that detects that something needs to be escaped in a ScriptContext is `jsesc`. Babel or Babili doesn't have information to tag a StringLiteral whether something needs to be escaped. And this option `isScriptContext` is decided by the user and not by Babel or Babili. Even if the option is provided by babili, it should be passed to babel-generator as it runs `jsesc`.

/cc @mathiasbynens

**Comment by mathiasbynens** [comment]
Shouldn’t `isScriptContext` be `true` by default? This is the safest, least surprising default.

**Comment by boopathi** [comment]
Yes. That sounds good. I'll add `isScriptContext` default to be `true`.

Regarding passing the option `isScriptContext` (as discussed above - https://github.com/babel/babel/pull/5581#issuecomment-291482828), which one is better ?

**Comment by jridgewell** [comment]
Can you rebase?

**Comment by nicolo-ribaudo** [comment]
In Babel 7, you can do 
```js
const out = babel.transformSync(input, {
  generatorOpts: {
    minified: true,
    jsescOption: {
      isScriptContext: true,
    },
  },
});
```

(https://github.com/babel/babel/pull/8143)

**Pull request closed without merging**
